// 帳戶詳情（zh-HK）
export default {
  capeUnequipped: '披風已卸下',
  capeEquipped: '披風已裝備',
  capeSwitchFailed: '披風切換失敗，請重新登入後重試',
  skinUploaded: '皮膚上載成功',
  skinUploadFailed: '皮膚上載失敗',
  resetSkinConfirm: '確定要重設為預設皮膚嗎？',
  skinReset: '皮膚已重設',
  skinResetFailed: '皮膚重設失敗',
  skinSavedTo: '皮膚已儲存到 {dest}',
  skinDownloaded: '皮膚已下載',
  skinDownloadFailed: '皮膚下載失敗',
  deleteAccountConfirm: '確定要刪除此帳戶嗎？',
  loading: '載入中...',
  showNameTag: '顯示名稱標籤',
  showCape: '顯示披風',
  downloadSkin: '下載皮膚',
  accountInfo: '帳戶資訊',
  name: '名稱',
  type: '類型',
  authServer: '驗證伺服器',
  skinModel: '皮膚模型',
  slim: '纖幼 (Slim)',
  classic: '經典 (Classic)',
  cape: '披風',
  none: '無',
  hasSkin: '有',
  refreshSkin: '重新整理皮膚',
  switchCape: '切換披風',
  uploadSkin: '上載皮膚',
  chooseArmModel: '選擇手臂模型',
  skinPreview: '皮膚預覽',
  classicArm: '經典手臂',
  slimArm: '纖幼手臂',
  resetSkin: '重設皮膚',
  goToSkinSite: '前往皮膚站',
  deleteAccount: '刪除帳戶',
} as const
