// 通用高頻文案（zh-HK）
export default {
  ok: '確定',
  cancel: '取消',
  close: '關閉',
  save: '儲存',
  create: '建立',
  delete: '刪除',
  edit: '編輯',
  confirm: '確認',
  loading: '載入中...',
  noData: '暫無數據',
  comingSoon: '即將上線',
  retry: '重試',
  refresh: '重新整理',
  copy: '複製',
  copied: '已複製',
  search: '搜尋',
  select: '選擇',
  back: '返回',
  next: '下一步',
  prev: '上一個',
  unknown: '未知',
  all: '全部',
  none: '無',
  enabled: '已啟用',
  disabled: '已停用',
  error: '錯誤',
  warning: '警告',
  success: '成功',
  failed: '失敗',
  info: '提示',
  input: '輸入',
  inputPlaceholder: '請輸入...',
  batchSelected: '已選 {count} 個',
  selectAll: '全選',
  deselect: '取消選擇',
  noMatch: '無匹配',
  pendingTasksCloseConfirm: '還有未完成的任務，關閉後將刪除所有任務。\n\n確定要關閉嗎？',
  language: '介面語言',
  theme: '主題',
  dark: '深色',
  light: '亮色',
  externalLink: '外部連結',
  seeMore: '查看更多',
  goto: '前往',
  name: '名稱',
  version: '版本',
  status: '狀態',
  action: '操作',
  detail: '詳情',
  optional: '可選',
  javaRuntimeRequired: '啟動 Minecraft 需要 Java 執行環境。\n\n你可以使用「設定 → Java → 下載 Java」功能快速安裝，或手動加入已安裝的 Java 路徑。',
  javaRuntimeRequiredTitle: '未偵測到 Java 執行環境',
} as const
