// 下載中心（zh-HK）
export default {
  status: {
    queued: '排隊中',
    downloading: '下載中',
    paused: '已暫停',
    completed: '已完成',
    failed: '失敗',
    cancelled: '已取消',
  },
  stage: {
    queued: '排隊中',
    'fetching-json': '取得版本清單',
    'downloading-installer': '下載載入器安裝器',
    downloading: '下載遊戲檔案',
    'scanning-base': '掃描遊戲檔案',
    'downloading-base': '下載遊戲資源檔案',
    'scanning-loader-libs': '掃描載入器依賴庫',
    'downloading-loader-libs': '下載載入器庫',
    'installing-optifine': '安裝 OptiFine',
    'downloading-addons': '下載附加內容',
    'downloading-additional-files': '下載附加檔案',
    'installing-loader': '安裝載入器',
    'verifying-jar': '校驗主程式',
    finishing: '完成收尾',
    'downloading-json': '下載版本 JSON',
    'downloading-libraries': '下載支援庫',
    'downloading-assets': '下載資源檔案',
    'downloading-mainjar': '下載主檔',
    'downloading-loader': '下載載入器',
    'downloading-modpack': '下載整合包',
    'parsing-modpack': '解析整合包',
    'modpack-files': '下載整合包檔案',
    'modpack-overrides': '解壓覆蓋檔案',
    'installing-game': '安裝遊戲與載入器',
    'building-version': '合併元件修補程式',
    'downloading-game': '下載遊戲檔案',
    'copying-files': '複製實例內容',
  },
  steps: {
    'fetch-json': '取得版本清單',
    installer: '下載載入器安裝器',
    'game-files': '下載遊戲資源檔案',
    'loader-libs': '下載載入器資源檔案',
    'install-loader': '安裝載入器',
    'install-optifine': '安裝 OptiFine',
    'download-addons': '下載附加內容',
    finalize: '校驗與收尾',
    'download-modpack': '下載整合包',
    'parse-modpack': '解析整合包',
    'download-files': '下載整合包檔案',
    'download-deps': '下載前置資源',
    'download-main': '下載資源本體',
    overrides: '釋放覆蓋檔案',
    'install-game': '安裝遊戲與載入器',
    'copy-files': '複製實例內容',
  },
  speedLabel: '下載速度',
  quickInstallName: '安裝: {name}',
  stepsDone: '{done}/{total} 步完成',
  filter: {
    all: '全部',
    downloading: '下載中',
    paused: '已暫停',
    completed: '已完成',
    failed: '失敗',
  },
  title: '下載中心',
  subtitle: '{count} 個任務',
  clearFinished: '清除已完成/失敗',
  taskCount: '{count} 個任務',
  empty: '暫無下載任務',
  emptyHint: '在"實例"頁面選擇版本並開始下載，任務將顯示在此處',
  goToInstances: '前往實例',
  addonsCount: '+ {count} 個附加',
  createdAt: '建立於 {date}',
  completedAt: '完成於 {date}',
  resume: '繼續',
  pause: '暫停',
  cancel: '取消',
  retry: '重試',
  remove: '移除',
  statusText: {
    done: '下載完成',
    failedWith: '失敗: {error}',
    failed: '下載失敗',
    pausedProgress: '已暫停 {progress}%',
    waiting: '等待中',
    downloading: '下載中',
    connecting: '連線中…',
  },
  filesCount: '{done}/{total} 檔案',
  errors: {
    taskExpired: '任務已過期（後端已重啟）',
    downloadFailed: '下載失敗',
    cannotVerify: '無法連線後端驗證任務狀態',
    statusUnknown: '任務狀態無法確認（後端未回報該工作階段）',
    taskInvalid: '任務已失效',
  },
} as const
