// 後端錯誤訊息（前端錯誤碼對映展示，zh-HK）
export default {
  notFound: '請求的資源不存在',
  forbidden: '沒有權限執行此操作',
  badRequest: '請求參數有誤',
  internalError: '伺服器內部錯誤',
  upstreamError: '上游服務請求失敗',
  requestTimeout: '請求逾時，請稍後重試',
  unknown: '請求失敗，請稍後重試',
  licenseNotFound: '許可證未啟動',
  licenseDecryptFailed: '許可證解密失敗',
  licenseSignatureInvalid: '許可證簽名無效',
  licensePublicKeyUnavailable: '許可證公鑰不可用',
  licenseExpired: '許可證已過期',
  licenseRemoteCheckFailed: '許可證遠端校驗失敗',
  licenseIoError: '許可證檔案讀取失敗',
  tokenExpired: '登入令牌已過期，請重新登入',
  networkError: '無法連線微軟認證服務，請檢查網絡後重試，或改用離線模式啟動',
  mcApiError: 'Minecraft 官方 API 請求失敗',
  fsAuthRequired: '檔案系統存取未授權',
  pluginMissingDependency: '插件缺少必要的前置依賴',
  connectorTimeout: '聯機操作逾時，請檢查網絡後重試',
  exportDiagnosticsFailed: '匯出診斷報告失敗',
  modpackParseFailed: '整合包解析失敗',
  skinUploadFailed: '皮膚上載失敗',
  skinSaveFailed: '皮膚儲存失敗',
  skinResetFailed: '皮膚重設失敗',
} as const
