// 實例詳情（zh-HK）
export default {
  tabs: {
    overview: '概況',
    settings: '設定',
    gamesettings: '遊戲設定',
    saves: '存檔',
    screenshots: '截圖',
    mods: 'Mod',
    resourcepacks: '資源包',
    shaderpacks: '光影包',
    datapacks: '數據包',
    servers: '伺服器',
  },
  confirm: {
    cancel: '取消',
    deleting: '刪除中...',
    delete: '刪除',
    confirm: '確定',
  },
  time: {
    minutes: '{count} 分鐘',
    hours: '{count} 小時',
    hoursMinutes: '{hours} 小時 {minutes} 分鐘',
    never: '從未',
    justNow: '剛剛',
    minutesAgo: '{count} 分鐘前',
    hoursAgo: '{count} 小時前',
  },
  openFolder: '開啟資料夾',
  loading: '載入中...',
  noMatch: '無匹配',
  empty: '暫無',
  deleteSelected: '刪除 {count}',
  batchDeleteTitle: '批次刪除{type}',
  batchDeleteConfirm: '確定要刪除選取的 {count} 個{type}嗎？將被移至資源回收筒。',
  saves: {
    search: '搜尋存檔...',
    noMatch: '無匹配存檔',
    empty: '暫無存檔',
    type: '存檔',
  },
  saveSettings: {
    title: '存檔設定',
    restoreFromOld: '從 level.dat_old 復原',
    restoreFromOldConfirm: '將用 level.dat_old 覆蓋目前 level.dat（目前內容會備份為 level.dat.qomicex.bak），確定復原嗎？',
    runningWarning: '該實例正在執行，遊戲儲存時會覆蓋修改，建議先退出遊戲再編輯',
    sectionBasic: '基本資訊',
    sectionWeather: '天氣與時間',
    sectionSpawn: '重生點與商人',
    sectionBorder: '世界邊界',
    levelName: '存檔名稱',
    gameType: '遊戲模式',
    gameTypeSurvival: '生存',
    gameTypeCreative: '創造',
    gameTypeAdventure: '冒險',
    gameTypeSpectator: '旁觀',
    difficulty: '難度',
    difficultyPeaceful: '和平',
    difficultyEasy: '簡單',
    difficultyNormal: '普通',
    difficultyHard: '困難',
    allowCommands: '允許作弊',
    hardcore: '極限模式',
    difficultyLocked: '鎖定難度',
    time: '世界時間（Time）',
    dayTime: '晝夜時間（DayTime）',
    raining: '下雨',
    thundering: '雷暴',
    clearWeatherTime: '晴天剩餘時間',
    rainTime: '降雨剩餘時間',
    thunderTime: '雷暴剩餘時間',
    spawnX: '重生點 X',
    spawnY: '重生點 Y',
    spawnZ: '重生點 Z',
    randomSeed: '世界種子',
    wanderingTraderSpawnChance: '流浪商人機率',
    wanderingTraderSpawnDelay: '流浪商人延遲',
    borderCenterX: '邊界中心 X',
    borderCenterZ: '邊界中心 Z',
    borderSize: '邊界大小',
    borderSafeZone: '安全區',
    borderDamagePerBlock: '邊界外傷害/格',
    borderWarningBlocks: '警告距離',
    borderWarningTime: '警告時間（秒）',
    gameRules: '遊戲規則',
    ruleKeepInventory: '死亡不掉落（keepInventory）',
    ruleDoDaylightCycle: '晝夜循環（doDaylightCycle）',
    ruleDoFireTick: '火焰蔓延（doFireTick）',
    ruleMobGriefing: '生物破壞方塊（mobGriefing）',
    ruleDoMobSpawning: '生物生成（doMobSpawning）',
    ruleDoWeatherCycle: '天氣循環（doWeatherCycle）',
    ruleDoMobLoot: '生物掉落物（doMobLoot）',
    ruleDoTileDrops: '方塊掉落物（doTileDrops）',
    ruleDoEntityDrops: '實體掉落物（doEntityDrops）',
    ruleDoNaturalRegeneration: '自然生命回復（doNaturalRegeneration）',
    ruleDoImmediateRespawn: '立即重生（doImmediateRespawn）',
    ruleDoInsomnia: '幻翼生成（doInsomnia）',
    ruleDoPatrolSpawning: '掠奪者巡邏隊（doPatrolSpawning）',
    ruleDoTraderSpawning: '流浪商人生成（doTraderSpawning）',
    ruleDrowningDamage: '遇溺傷害（drowningDamage）',
    ruleFallDamage: '摔落傷害（fallDamage）',
    ruleFireDamage: '火焰傷害（fireDamage）',
    ruleFreezeDamage: '冰凍傷害（freezeDamage）',
    ruleShowDeathMessages: '死亡訊息（showDeathMessages）',
    ruleAnnounceAdvancements: '公告進度（announceAdvancements）',
    ruleCommandBlockOutput: '指令方塊輸出（commandBlockOutput）',
    ruleSendCommandFeedback: '指令回饋（sendCommandFeedback）',
    ruleReducedDebugInfo: '簡化除錯資訊（reducedDebugInfo）',
    ruleDisableElytraMovementCheck: '停用鞘翅移動檢查（disableElytraMovementCheck）',
    ruleSpectatorsGenerateChunks: '旁觀者生成區塊（spectatorsGenerateChunks）',
    ruleDoLimitedCrafting: '限制合成（doLimitedCrafting）',
    ruleRandomTickSpeed: '隨機刻速度',
    ruleSpawnRadius: '重生點半徑',
    ruleMaxEntityCramming: '實體堆疊上限',
    save: '儲存',
    saving: '儲存中...',
    saved: '存檔設定已儲存',
    loadFailed: '讀取存檔設定失敗: {error}',
    saveFailed: '儲存存檔設定失敗: {error}',
    restored: '已從 level.dat_old 復原',
    restoreFailed: '復原失敗: {error}',
  },
  screenshots: {
    search: '搜尋截圖...',
    noMatch: '無匹配截圖',
    empty: '暫無截圖',
    type: '截圖',
  },
  resourcepacks: {
    search: '搜尋資源包...',
    noMatch: '無匹配資源包',
    empty: '暫無資源包',
    type: '資源包',
    install: '安裝資源包',
    loadFailed: '載入資源包失敗: {error}',
  },
  shaderpacks: {
    search: '搜尋光影包...',
    noMatch: '無匹配光影包',
    empty: '暫無光影包',
    type: '光影包',
    install: '安裝光影包',
    loadFailed: '載入光影包失敗: {error}',
  },
  datapacks: {
    search: '搜尋數據包...',
    noMatch: '無匹配數據包',
    empty: '暫無數據包',
    type: '數據包',
    install: '安裝數據包',
  },
  mods: {
    management: 'Mod 管理',
    noModsHint: '該實例不可使用 Mod，需要使用 Forge、Fabric 等載入器',
    search: '搜尋 Mod...',
    checkUpdates: '檢查更新',
    install: '安裝 Mod',
    fetchingRemoteInfo: '正在取得遠端資訊（Modrinth/CurseForge 匹配 id、圖示、中文名）...',
    readingMods: '正在讀取 Mod 資訊',
    loadFailed: '載入 Mod 列表失敗：{error}',
    noMatch: '無匹配 Mod',
    empty: '暫無 Mod',
    enable: '啟用',
    disable: '停用',
    updateMods: '更新模組',
    filterAll: '全部',
    updatable: '可更新',
    duplicate: '重複',
    sortNameAsc: '名稱 A-Z',
    sortNameDesc: '名稱 Z-A',
    sortTimeDesc: '最新優先',
    sortTimeAsc: '最早優先',
    sortSizeDesc: '最大優先',
    sortSizeAsc: '最小優先',
    batchEnable: '批次啟用',
    batchDisable: '批次停用',
    batchDelete: '批次刪除',
    batchConfirm: '確定要{action}{count} 個 Mod 嗎？',
    moveToRecycleBin: '將被移至資源回收筒。',
    processing: '處理中...',
    checkingUpdates: '正在檢查模組更新…',
    foundUpdates: '發現 {count} 個模組可更新',
    addedToDownload: '已加入下載列表 {count} 個任務',
    updatedCount: '已更新 {count} 個模組',
    updateResult: '完成 {success} 個，失敗 {failed} 個{failures}',
    updateFailed: '更新模組失敗',
    loadFailedGeneric: '載入失敗: {error}',
    unknownError: '未知錯誤',
  },
  servers: {
    search: '搜尋伺服器...',
    pingAll: '全部測速',
    addServer: '新增伺服器',
    edit: '編輯',
    ping: '測速',
    copyIp: '複製 IP',
    quickJoin: '快速加入',
    delete: '刪除',
    online: '在線',
    offline: '離線',
    pinging: '測速中...',
    lanGames: '局域網遊戲 ({count})',
    lanGame: '局域網遊戲',
    join: '加入',
    deleteConfirm: '確定要刪除伺服器「{ip}」嗎？',
    deleteTitle: '刪除伺服器',
    addTitle: '新增伺服器',
    editTitle: '編輯伺服器',
    name: '伺服器名稱',
    address: '伺服器位址',
    updating: '更新中...',
    adding: '新增中...',
    save: '儲存',
    add: '新增',
    copiedIp: '已複製 IP 位址',
    copyFailed: '複製失敗',
    pingDone: '測速完成: {ping}ms',
    addressOffline: '{address} 離線',
    pingFailed: '測速失敗',
    deleted: '已刪除伺服器',
    deleteFailed: '刪除失敗',
    updated: '已更新「{name}」',
    added: '已新增「{name}」',
    opFailed: '操作失敗',
    loadFailed: '載入伺服器列表失敗',
  },
  overview: {
    launch: '啟動',
    unpin: '取消固定',
    pin: '固定到主頁',
    gameVersion: '遊戲版本',
    loader: '載入器',
    pureVanilla: '純淨原版',
    lastPlayed: '最後遊玩',
    totalPlayTime: '累計遊玩',
    modpackInfo: '整合包資訊',
    modpackName: '整合包名稱',
    version: '版本',
    author: '作者',
    summary: '簡介',
    quickActions: '快速操作',
    defaultAccount: '預設帳戶',
    launchGame: '啟動遊戲',
    instanceSettings: '實例設定',
    verifyIntegrity: '檢查資源完整性',
    repairing: '正在補全 {progress}%',
    openGameDir: '開啟遊戲目錄',
    exportModpack: '匯出整合包',
    deleteInstance: '刪除實例',
    refresh: '重新整理',
  },
  settingsTab: {
    instanceName: '實例名稱',
    instanceIcon: '實例圖示',
    gameVersion: '遊戲版本',
    javaRuntime: 'Java 執行環境',
    autoSelect: '自動選擇',
    integrity: '資源完整性',
    checkIntegrity: '檢查資源完整性',
    repairing: '正在補全 {progress}%',
    missingFiles: '缺失 {count} 個檔案',
    autoRepairing: '正在自動補全...',
    integrityOk: '資源完整',
    versionIsolation: '版本隔離',
    followGlobal: '跟隨全域設定',
    on: '開啟',
    off: '關閉',
    isolationDesc: '每個版本使用獨立的 mods/config/saves 目錄',
    skipIntegrity: '跳過資源完整性檢查',
    skipIntegrityDesc: '啟動時跳過檔案完整性檢查，可能因缺少檔案導致遊戲崩潰',
    memoryAllocation: '記憶體分配',
    auto: '自動',
    custom: '自訂',
    totalMem: '總記憶體 {size} GiB',
    usedMem: '已使用 {size} GiB',
    gameAlloc: '遊戲分配 {size} GiB',
    remainingMem: '剩餘 {size} GiB',
    jvmArgs: 'JVM 參數',
    linkedAccount: '關聯帳戶',
    unlinked: '未關聯',
    saving: '儲存中...',
  },
  gamesettings: {
    search: '搜尋設定項...',
    noMatch: '無匹配設定項',
    empty: '暫無遊戲設定',
    pressKey: '按下按鍵...',
    add: '新增',
    addPlaceholder: '輸入名稱…',
    remove: '移除',
    keys: {
      unbound: '未綁定',
      space: '空格',
      enter: '回車',
      backspace: '退格',
      leftShift: '左 Shift',
      rightShift: '右 Shift',
      leftControl: '左 Ctrl',
      rightControl: '右 Ctrl',
      leftAlt: '左 Alt',
      rightAlt: '右 Alt',
      leftSuper: '左 Win',
      rightSuper: '右 Win',
      menu: '選單鍵',
      mouseLeft: '滑鼠左鍵',
      mouseRight: '滑鼠右鍵',
      mouseMiddle: '滑鼠中鍵',
      mouseButton: '滑鼠按鍵 {n}',
      keypad: '小鍵盤 {n}',
      keypadAdd: '小鍵盤 +',
      keypadSubtract: '小鍵盤 -',
      keypadMultiply: '小鍵盤 *',
      keypadDivide: '小鍵盤 /',
      keypadDecimal: '小鍵盤 .',
      keypadEnter: '小鍵盤 回車',
    },
  },
  launch: {
    launchFailed: '啟動失敗',
    instanceRunningConfirm: '目前實例正在執行中，是否啟動新實例？',
    instanceRunningTitle: '實例執行中',
    backToList: '返回實例列表',
    instanceNotFound: '實例不存在',
    loadingInstance: '載入實例...',
    deleteInstanceConfirm: '確定要刪除實例「{name}」嗎？其版本資料夾將被永久刪除。',
  },
} as const
