// 實例列表（zh-HK）
export default {
  title: '遊戲實例',
  subtitle: '{count} 個版本',
  type: {
    release: '正式版',
    snapshot: '快照',
    old_beta: '遠古測試版',
    old_alpha: '遠古阿爾法',
    april_fools: '愚人節版',
  },
  category: {
    all: '全部',
    release: '正式版',
    snapshot: '快照',
    april_fools: '愚人節版',
    old_beta: '遠古測試版',
    old_alpha: '遠古阿爾法',
  },
  sort: {
    recommended: '推薦排序',
    newest: '最新優先',
    oldest: '最早優先',
    'name-asc': '名稱 A-Z',
    'name-desc': '名稱 Z-A',
  },
  loaderFilter: {
    all: '全部',
    modded: '模組',
    vanilla: '原版',
    snapshot: '快照',
    april_fools: '愚人節',
    broken: '錯誤',
  },
  groups: '自訂分組',
  manageGroups: '管理分組',
  groupNamePlaceholder: '輸入分組名稱...',
  noGroups: '暫無自訂分組',
  groupsHint: '實例可新增到多個自訂分組中，點擊切換',
  downloadTitle: '下載新版本',
  categoryLabel: '分類',
  searchPlaceholder: '搜尋版本...',
  remoteCount: '共 {count} 個遠端版本',
  filteredCount: '篩選後 {count} 個',
  noRemoteMatch: '沒有匹配的遠端版本',
  noRemoteMatchHint: '試試調整分類、排序或搜尋關鍵字',
  releaseDate: '發佈日期 {date}',
  select: '選擇',
  configTitle: '配置下載',
  instanceName: '實例名稱',
  instanceNamePlaceholder: '輸入實例名稱...',
  gameVersion: '遊戲版本',
  loader: '模組載入器',
  loaderPlaceholder: '選擇載入器',
  noneVanilla: '無（純淨原版）',
  versionPlaceholder: '選擇版本',
  loadingVersions: '載入中...',
  noVersionData: '暫無版本數據',
  latestRecommended: '最新版 {version} (推薦)',
  recommended: ' (推薦)',
  selectLoaderFirst: '先選擇載入器',
  latestVersion: '最新版 {version}',
  addons: '附加內容',
  optional: '(可選)',
  fetchingAddons: '正在取得附加內容...',
  onlyGameFiles: '僅下載遊戲檔案，執行記憶體和 Java 等配置可在建立後調整',
  noLoaderAvailable: '暫無可用載入器版本，無法下載',
  cancel: '取消',
  startDownload: '開始下載',
  repairName: '補全 {name}',
  pickGameDirTitle: '選擇遊戲目錄',
  enterDirPath: '請輸入遊戲目錄路徑:',
  chooseDir: '選擇目錄',
  addDir: '新增目錄',
  selectDirFirst: '請先選擇一個遊戲目錄，再開始下載。',
  noLoaderVersions: '未取得 {loader} 的可用版本列表，無法下載。請檢查網絡或稍後重試。',
  selectLoaderVersion: '請選擇 {loader} 的具體版本後再下載。',
  createFailed: '建立失敗: {error}',
  createInstanceFailed: '建立實例失敗: {error}',
  launchFailed: '啟動失敗: {error}',
  launchFailedDetail: '啟動失敗: {error}\n{detail}',
  refresh: '重新整理',
  dirManagerTitle: '目錄管理',
  currentDir: '目前目錄',
  noDir: '暫無目錄',
  noDirHint: '點擊下方按鈕新增一個遊戲目錄',
  dirCount: '共 {count} 個目錄，點擊選擇目前使用的目錄',
  inUse: '目前使用中',
  rename: '重新命名',
  setCurrent: '設為目前使用',
  moveUp: '上移',
  moveDown: '下移',
  openDir: '開啟目錄',
  remove: '移除',
  manualAdd: '手動新增',
  browseAdd: '瀏覽新增',
  instanceSettings: '實例設定',
  basicInfo: '基本資訊',
  repairFiles: '補全檔案',
  versionName: '版本名稱',
  gameDir: '遊戲目錄',
  notCreatedYet: '此版本尚未在啟動器中建立，無法補全檔案。',
  repairDesc: '掃描並下載此實例缺失的 Minecraft 遊戲檔案（libraries、assets、client.jar）。',
  addedToDownload: '已加入下載任務',
  goToDownloadCenter: '前往下載中心查看',
  repairCompleted: '補全已完成',
  repairFailed: '補全失敗',
  retry: '重試',
  startRepair: '開始補全檔案',
  selectGameDir: '選擇遊戲目錄',
  savedDirs: '已儲存的目錄',
  manage: '管理',
  noDirInManager: '暫無目錄，可在管理中新增',
  scanning: '掃描中...',
  import: '匯入',
  openGameDir: '開啟遊戲目錄',
  selectMcDir: '請選擇 Minecraft 遊戲目錄',
  selectMcDirHint: '選擇一個包含 versions 資料夾的 .minecraft 目錄',
  browseAndSelect: '瀏覽並選擇',
  noMatch: '沒有匹配的版本',
  noVersionDetected: '該目錄下未偵測到任何 Minecraft 版本',
  needVersionsFolder: '請確認目錄下存在 versions/ 資料夾',
  available: '可用',
  unavailable: '不可用',
  launch: '啟動',
  settings: '設定',
  unpin: '取消固定',
  pinToHome: '固定到主頁',
  openFolder: '開啟資料夾',
} as const
