// 執行/啟動流程（zh-HK）
export default {
  gameCrashed: '遊戲已崩潰',
  gameCrashTitle: '遊戲崩潰',
  launchFailedTitle: '啟動失敗',
  gameExitedAbnormally: '遊戲異常退出 (代碼: {code})',
  launchError: '啟動過程中出現錯誤',
  analysisUnavailable: '分析服務暫不可用',
  gameExited: '遊戲已退出',
  gameStarted: '遊戲已啟動',
  preparingLaunch: '準備啟動...',
  javaIncompatibleTitle: 'Java 版本不相容',
  javaIncompatible: '目前選擇的 Java {current} 不滿足 Minecraft {game} 的需求（需要 Java {required}），是否繼續啟動？',
  launchCancelled: '已取消啟動',
  gameStopped: '已停止遊戲',
  timeSeconds: '{count}秒',
  timeMinutes: '{count}分{sec}秒',
  timeHours: '{hours}小時{mins}分',
  instancesRunning: '{count} 個實例正在執行',
  noRunningGame: '暫無執行中的遊戲',
  goToInstances: '前往實例管理',
  title: '執行中的遊戲',
  runningFor: '已執行 {time}',
} as const
