// 設定頁（zh-HK；批0 含 category 導覽 + appearance 外觀核心項，其餘由遷移批次補充）
export default {
  category: {
    launcher: '啟動器設定',
    basic: '基礎設定',
    launch: '啟動設定',
    download: '下載設定',
    storage: '儲存與緩存',
    network: '網絡設定',
    java: 'Java 執行環境',
    plugins: '插件',
    appearance: '外觀',
    toolbox: '工具箱',
    logs: '日誌',
    about: '關於',
    debug: '除錯',
  },
  saved: '設定已儲存',
  appearance: {
    title: '介面',
    language: '介面語言',
    followSystem: '跟隨系統',
    theme: '主題',
    dark: '深色',
    light: '亮色',
    themeColor: '主題色',
    themeColorCustom: '自訂顏色',
    themeColorBackground: '跟隨背景（莫奈取色）',
    themeColorReset: '還原預設',
    themeColorDesc: '自訂全域強調色，用於按鈕、高亮同選中狀態。設為預設時使用啟動器預設配色。',
    componentMaterial: '組件材質',
    componentMaterialDefault: '默認',
    componentMaterialFrosted: '毛玻璃',
    componentMaterialAcrylic: '亞克力玻璃',
    componentMaterialAero: 'Aero',
    componentMaterialLiquid: '液態玻璃',
    componentMaterialLiquidPreview: '液態玻璃（預覽）',
    componentMaterialLiquidWarning: '預覽功能：液態玻璃對每個卡片實時做位移折射渲染，性能開銷較大；長列表（如大量模組）可能出現明顯卡頓甚至無響應。',
    componentMaterialLiquidConfirmTitle: '啟用液態玻璃？',
    componentMaterialLiquidConfirmBody: '液態玻璃為預覽功能，性能開銷較大；長列表（如大量模組）可能明顯卡頓甚至界面無響應。仍要啟用嗎？',
    glassBlurLow: '清晰',
    glassBlurHigh: '模糊',
    animations: '頁面動畫',
    animationsDesc: '開啟後頁面切換、彈窗等帶有過渡動畫效果',
    animationSpeed: '動畫速度',
    slow: '慢',
    normal: '正常',
    fast: '快',
    maxFrameRate: '幀率上限',
    maxFrameRateUnlimited: '不限',
    maxFrameRateDesc: '限制啟動器介面的渲染幀率，降低資源佔用。設為不限則使用顯示器的原始重新整理率。',
    cornerRadius: '圓角',
    windowCorners: '視窗圓角',
    windowCornersDesc: '僅在不使用系統框架時生效',
    cornerSharp: '直角',
    cornerDefault: '預設（8px）',
    cornerLarge: '大圓角',
    font: '字型',
    fontFamily: '介面字型',
    fontDefault: '預設字型',
    fontDesc: '選擇系統已安裝字型，全域 UI 即時生效',
    fontPreviewTitle: '字型預覽',
    fontPreviewText: 'Qomicex 啟動器 — 中文示例 123 ABC',
    fontReset: '回復預設字型',
    background: '背景',
    backgroundImage: '背景圖片',
    noBackgrounds: '暫無背景圖片',
    openFolder: '開啟資料夾',
    backgroundsHint: '放入圖片即可出現在上方列表中',
    backgroundRandom: '每次啟動隨機挑選',
    backgroundRandomDesc: '從背景資料夾中隨機選擇一張圖片',
    clearBackground: '清除背景',
    opacity: '不透明度',
    transparent: '透明',
    opaque: '不透明',
    blur: '模糊',
    sharp: '清晰',
    watermark: '水印',
    watermarkEnabled: '顯示主頁水印文字',
    watermarkEnabledDesc: '在主頁中央顯示可自訂的文字',
    watermarkText: '水印內容',
    watermarkSubtext: '副標題',
    watermarkSubtextPlaceholder: '啟動器',
  },
  launcher: {
    title: '啟動器設定',
    dataDir: '數據目錄',
    dataDirDesc: '啟動器數據儲存位置，更改後需重啟啟動器生效',
    dataDirChanged: '數據目錄已更改，重啟啟動器後生效',
    saveFailed: '設定失敗',
    downloadThreads: '下載執行緒數',
    downloadThreadsDesc: '同時下載的檔案數量（1-512），數值越大下載越快但佔用頻寬越多',
    fileChunkThreads: '分片執行緒數',
    fileChunkThreadsDesc: '單檔分片並行的數量：關閉=不分片直傳，自動=引擎預設，或手動指定 1-16',
    fileChunkThreadsOff: '關閉',
    fileChunkThreadsAuto: '自動',
    versionIsolation: '版本隔離',
    versionIsolationDesc: '每個版本使用獨立的 mods/config/saves 目錄，建議保持開啟',
    closeAfterLaunch: '啟動遊戲後關閉啟動器',
    closeAfterLaunchDesc: '遊戲啟動後自動關閉本啟動器',
    autoReportErrors: '自動上報嚴重錯誤日誌',
    autoReportErrorsDesc: '啟動器出現崩潰等嚴重錯誤時，自動上載錯誤日誌與設備資訊（系統/硬件）協助定位問題；普通啟動失敗、下載安裝錯誤不會上報',
    downloadSource: '下載源',
    downloadSourceName: { 0: '官方源', 1: 'BMCLAPI 鏡像' },
    modSource: '資源下載源',
    modSourceName: { 0: 'Modrinth/CurseForge 官方', 1: 'MCIM 鏡像' },
    resourceDownloadSource: '檔案下載源',
    resourceDownloadSourceName: { 0: '官方源', 1: 'QML Mirror', 2: 'QML Mirror HK' },
    resourceDownloadSourceDesc: '揀 MOD 檔案下載用嘅 CDN：官方源直連原站，QML Mirror 為QML鏡像。',
    autoSelectFileDownloadSource: '自動選擇下載源',
    autoSelectFileDownloadSourceDesc: '自動揀延遲最低嘅可用下載源',
    refreshLatency: '重新整理延遲',
    autoSelectDownloadSource: '自動選擇最快下載源',
    autoSelectDownloadSourceDesc: '啟動時和每次安裝前自動偵測並選擇延遲最低的下載源',
    autoSelectModSource: '自動選擇最快資源下載源',
    autoSelectModSourceDesc: '自動偵測 Modrinth/CurseForge API 鏡像並選擇延遲最低的',
    translationProvider: '翻譯介面',
    translationDefault: 'MyMemory (預設)',
    translationGoogle: 'Google Translate',
    translationProviderDesc: '選擇翻譯資源詳細介紹和簡介時使用的翻譯服務',
    bingApiKeyPlaceholder: '輸入 Azure Translator API Key',
    bingApiKeyDesc: '在 Azure Portal 建立 Translator 資源取得 Key，區域需設為 global',
    downloadTimeout: '下載逾時 (秒)',
    downloadTimeoutDesc: '單個檔案下載無回應超過此時間則自動重試（0=不逾時，1-120 秒）',
    enableHttp3: '啟用 HTTP/3 檔案下載（實驗性）',
    enableHttp3Desc: '開啟後下載優先使用 HTTP/3，伺服器不支援時自動回退到 HTTP/2；關閉則強制使用 HTTP/2',
    http1Parallel: 'HTTP/1.1 並行連線下載',
    http1ParallelDesc: '每個檔案用獨立 TCP 連線並行下載，可在按連線限速嘅 CDN（如 Modrinth/CurseForge）上大幅提升下載速度；關閉則回退 HTTP/2 多路復用',
    logLevelLabel: '日誌等級',
    logLevel: { error: '錯誤', warn: '警告', info: '資訊', debug: '除錯', trace: '追蹤' },
    logLevelDesc: '控制控制台和日誌檔案的輸出詳細程度，資訊等級為預設',
    storageCache: '儲存與快取',
    versionListCache: '版本列表快取',
    versionListCacheDesc: '清理 Forge 版本列表的 HTML 快取檔案',
    clearCache: '清理快取',
    curseforgeConcurrency: 'CurseForge 版本列表並發數',
    curseforgeConcurrencyDesc: '同時拉取的頁面數量（1-20），數值越大版本列表載入越快',
    curseforgeTtl: 'CurseForge 版本列表快取有效期（秒）',
    curseforgeTtlDesc: '0 = 永久快取（直到重啟或手動清除），預設 300 秒（5 分鐘）',
    curseforgeCache: 'CurseForge 版本快取',
    curseforgeCacheDesc: '清除 CurseForge 版本列表的記憶體快取',
    clearCurseforgeCache: '清除 CurseForge 版本快取',
    cacheCleared: '已清理快取，刪除 {count} 個檔案',
    cacheClearFailed: '清理快取失敗',
    curseforgeCacheCleared: 'CurseForge 版本快取已清除',
    curseforgeCacheClearFailed: '清除 CurseForge 快取失敗',
  },
  network: {
    title: '網絡設定',
    proxy: '代理設定',
    proxyMode: '使用邊種代理',
    proxyOff: '不使用代理',
    proxySystem: '使用系統代理',
    http: 'HTTP(S) 代理',
    socks5: 'SOCKS5 代理',
    proxyModeDesc: '為下載同資源請求設定代理伺服器',
    proxyHost: '代理伺服器位址',
    proxyHostPlaceholder: '例如 127.0.0.1:7890',
    proxyHostDesc: '格式：host:port；只有揀咗 HTTP(S) 或 SOCKS5 代理先會生效',
    ignoreSslCert: '忽略 SSL 憑證驗證',
    ignoreSslCertDesc: '下載或請求時唔驗證 TLS 憑證（適用於自簽憑證/內網代理等情境，請審慎開啟）',
  },
  java: {
    title: 'Java 執行環境',
    ready: '就緒',
    detected: '已偵測',
    available: '可用',
    quickScan: '快速掃描',
    deepScan: '深度掃描',
    manualAdd: '手動新增',
    downloadJava: '下載 Java',
    refreshList: '重新整理列表',
    scanningQuick: '正在快速掃描...',
    scanningDeep: '正在深度掃描...',
    scanDoneFound: '掃描完成，發現 {count} 個新版',
    scanDoneNone: '掃描完成，無新版',
    scanFailed: '掃描失敗',
    refreshing: '正在重新整理...',
    scanningRuntime: '正在掃描 Java 執行環境...',
    noRuntimeDetected: '尚未偵測到 Java 執行環境',
    noRuntimeHint: '點擊"快速掃描"自動偵測系統中的 Java，或手動新增',
    startScan: '開始掃描',
    usable: '可用',
    unusable: '不可用',
    openFolder: '開啟資料夾',
    availableCount: '{valid} / {total} 可用',
    showInvalid: '顯示無效項',
    defaultConfig: '預設配置',
    defaultRuntime: '預設 Java 執行環境',
    autoSelect: '自動選擇',
    defaultRuntimeDesc: '建議使用自動選擇，啟動器會為每個遊戲版本自動匹配最佳 Java 執行環境',
    memoryAllocation: '記憶體分配',
    memoryAuto: '自動',
    memoryCustom: '自訂',
    totalMemory: '總記憶體 {value} GiB',
    usedMemory: '已使用 {value} GiB',
    gameMemory: '遊戲分配 {value} GiB',
    remainingMemory: '剩餘 {value} GiB',
    jvmArgs: '額外 JVM 參數',
    jvmArgsDesc: '啟動 Minecraft 時附加的 JVM 參數',
    pickJavaExecutable: '選擇 Java 可執行檔案',
    unrecognizedPath: '無法識別該路徑下的 Java 執行環境',
    added: '已新增 {name} {version}',
    loadCatalogFailed: '載入 Java 下載目錄失敗',
    addedToDownload: '已加入下載中心: {name}',
    downloadFailed: '啟動 Java 下載失敗',
    deleteConfirm: '確定要刪除 "{name}" 嗎？',
    deleteTitle: '刪除 Java',
    deleted: '已刪除 {name}',
    deleteFailed: '刪除失敗',
    manualAddTitle: '手動新增 Java',
    executablePath: 'Java 可執行檔案路徑',
    browse: '瀏覽',
    executablePathDesc: '選擇或輸入 Java 可執行檔案的完整路徑',
    verifying: '驗證中...',
    add: '新增',
    distribution: '發行版',
    recommended: '(推薦)',
    mainVersion: 'Java 主版本',
    platform: '平台',
    architecture: '架構',
    targetDir: '目標目錄',
    resolving: '解析中...',
    startDownload: '開始下載',
  },
  plugins: {
    title: '插件管理',
    installedCount: '{count} 個已安裝',
    searchPlaceholder: '搜尋插件...',
    installing: '安裝中...',
    install: '安裝插件',
    noneInstalled: '尚未安裝任何插件',
    noMatch: '無匹配的插件',
    changesApplied: '更改已生效',
    saveFailed: '儲存失敗',
    uninstallConfirm: '確定卸載此插件？',
    uninstalled: '插件已卸載',
    uninstallFailed: '卸載失敗',
    installSuccess: '插件安裝成功',
    installFailed: '安裝失敗: {message}',
    permissions: '權限 ({count})',
    contributes: '擴充點',
  },
  about: {
    aboutApp: '關於 {name}',
    beta: '測試版',
    stable: '穩定版',
    feedback: '意見回饋',
    viewRepository: '查看倉庫',
    versionInfo: '版本資訊',
    appVersion: '應用程式版本',
    versionHash: '版本哈希',
    os: '作業系統',
    architecture: '系統架構',
    memory: '記憶體',
    license: '許可證',
    licenseActivated: '已啟動',
    licenseNotActivated: '未啟動',
    licenseInvalid: '無效',
    channel: '頻道',
    expiry: '到期',
    permanent: '永久有效',
    machineCode: '機器碼',
    changeLicense: '更換許可證',
    activateLicense: '啟動許可證',
    copyMachineCode: '複製機器碼',
    update: '更新',
    checking: '檢查中...',
    checkUpdate: '檢查更新',
    upToDate: '已是最新版本',
    checkUpdateFailed: '檢查更新失敗',
    developers: '開發者',
    acknowledgements: '鳴謝',
    referenceProjects: '參考項目',
    backendDependencies: '後端依賴',
    frontendDependencies: '前端依賴',
    openSourceLicense: '開源協議',
    licenseNotice: '本程式基於 {name} 開源協議發佈',
    viewLicense: '查看協議',
    copyrightPrivacy: '版權與私隱',
    copyrightStatement: '版權聲明',
    copyrightStatementDesc: '查看本軟件的版權歸屬與開源許可資訊',
    userAgreement: '用戶協議',
    privacyPolicy: '私隱政策',
    appDescription: '一個現代的 Minecraft 啟動器，支援多版本管理、模組載入器相容、帳戶管理等功能。',
    roleProjectLead: '項目發起人 / 主要開發者',
    serviceModrinth: 'Mod 和資源搜尋 API',
    serviceModpack: '整合包 API',
    serviceBmclapi: '提供BMCLAPI下載鏡像服務',
    serviceMcmod: '中文 Mod 數據庫',
    serviceMinecraft: 'Minecraft 官方網站,支援正版!',
    serviceMinecraftName: 'Minecraft 官網',
    serviceModrinthName: 'Modrinth',
    serviceCurseForgeName: 'CurseForge',
    serviceFtbName: 'FTB',
    serviceBmclapiName: 'bangbang93',
    serviceMcmodName: 'mcmod',
    refVersionCheck: '版本偵測參考',
    refModloaderInstaller: 'ModLoader 安裝器參考',
    refLaunchFlow: '啟動流程參考',
    depBackendRuntime: 'Rust 後端執行環境',
    depCoreLibraries: '核心庫',
    depCoreFramework: '核心框架',
    depUiComponents: 'UI 元件',
    depStylesTools: '樣式與工具',
    depAnimation: '動畫',
    depRendering: '渲染與展示',
    depInHouse: '自研',
  },
} as const
