// 雜項工具/除錯/日誌/閃屏（zh-HK）
export default {
  toolbox: {
    title: '自訂檔案下載',
    description: '透過啟動器下載任意檔案到指定資料夾',
    urlLabel: '下載位址 (URL)',
    savePathLabel: '儲存路徑',
    autoFillPlaceholder: '選擇資料夾後自動填寫',
    pickFolder: '選擇資料夾',
    submitting: '送出中...',
    startDownload: '開始下載',
    downloadFailed: '下載失敗',
  },
  logs: {
    title: '日誌管理',
    loadFailed: '載入日誌列表失敗',
    exportedTo: '已匯出到 {dest}',
    downloadStarted: '已開始下載',
    deleteConfirm: '確定要刪除 "{name}" 嗎？',
    deleteTitle: '刪除日誌',
    deleted: '已刪除',
    deleteFailed: '刪除失敗',
    openDirFailed: '無法開啟目錄',
    openFailed: '無法開啟檔案',
    exportAll: '匯出全部',
    exportGz: '匯出 (.gz)',
    filesLabel: '日誌檔案',
    currentSession: '目前工作階段',
    none: '暫無日誌',
    emptyDescription: '啟動器和後端執行時會產生日誌檔案',
    open: '開啟',
    openContainingDir: '開啟所在目錄',
    retentionHint: '自動保留最近 10 條日誌，超出自動清理最舊檔案',
    currentSessionSuffix: '{count} 條目前工作階段',
    fileCountSuffix: '{count} 個檔案',
    truncated: '已截斷（僅尾部 2MB）',
    searchPlaceholder: '搜尋日誌...',
    levelAll: '全部級別',
    levelError: '錯誤',
    levelWarn: '警告',
    levelInfo: '資訊',
    noMatch: '無匹配日誌行',
    debugLogsCount: '除錯日誌 ({count})',
  },
  debug: {
    liveLogs: '即時日誌',
    autoScroll: '自動捲動',
    clear: '清空',
    exportLogs: '匯出日誌',
    triggerDump: '觸發 Dump',
    noLogs: '暫無日誌...',
    diagnostics: '啟動器診斷',
    systemInfo: '系統資訊',
    versionInfo: '版本資訊',
    connectivity: '連通狀態',
    apiHealthCheck: 'API 健康檢查',
    pathInfo: '路徑資訊',
    toggleDisableAnimations: '停用動畫',
    toggleShowComponentBoundaries: '顯示元件邊界',
    toggleSimulateApiErrors: '模擬 API 錯誤',
    toggleNetworkLogging: '網絡請求日誌',
    toggleDisableCaching: '停用快取',
    toggleLogOverlay: '日誌浮層（全域）',
    toggleShowFps: '幀率顯示（右上角）',
    togglesTitle: '除錯開關（暫時，重新啟動歸零）',
    clearTasksConfirm: '確定要清除所有下載任務列表嗎？此操作不可復原。',
    clearTasksTitle: '清除下載任務',
    tasksCleared: '下載任務列表已清除',
    dataManagement: '數據管理',
    downloadTaskList: '下載任務列表',
    clearTasksDescription: '清除 localStorage 中的下載任務記錄',
    clearTasksButton: '清除下載任務列表',
    dumpExported: '日誌已匯出到: {path}',
  },
  splash: {
    preparing: '正在準備啟動...',
    almostReady: '即將就緒...',
  },
  analysis: {
    title: '分析結果',
    pageTitle: '日誌分析',
    inputTitle: '輸入 Minecraft 日誌',
    pastePlaceholder: '貼上 Minecraft 日誌內容...',
    analyzeButton: '分析日誌',
    analyzing: '分析中...',
    analyzeFailed: '分析失敗',
    gameVersion: '遊戲版本',
    modLoader: '模組載入器',
    noIssues: '未發現明顯問題',
    criticalCount: '{count} 嚴重',
    errorCount: '{count} 錯誤',
    warningCount: '{count} 警告',
    suggestedSolutions: '建議解決方案',
    stackTrace: '異常堆疊',
    categoryMemory: '記憶體',
    categoryModConflict: '模組衝突',
    categoryJavaRelated: 'Java 相關',
    categoryResource: '資源',
    categoryPerformance: '效能',
    categoryNetwork: '網絡',
  },
  errors: {
    pageRenderError: '頁面渲染異常',
  },
  notifier: {
    downloadCompleted: '{name} 下載完成',
  },
} as const
