// 首次啟動初始化精靈（zh-HK）
export default {
  title: '歡迎使用 Qomicex',
  subtitle: '首次啟動需要完成一些基本設定',
  stepLabel: '第 {current}/{total} 步',
  // 步驟標籤
  stepMode: '設定方式',
  stepLanguage: '語言',
  stepTheme: '主題',
  stepDirectories: '目錄',
  stepDownloadSource: '下載源',
  stepJava: 'Java 執行環境',
  stepMemory: '記憶體',
  stepDone: '完成',
  // 模式選擇
  modeTitle: '選擇設定方式',
  modeDesc: '兩種模式都包含語言、主題、Java 與記憶體設定',
  quickTitle: '快速設定',
  quickDesc: '自動推薦配置，只需少量確認即可開始使用',
  customTitle: '自訂設定',
  customDesc: '逐步配置，額外包含下載源、數據目錄與遊戲目錄',
  // 語言
  languageTitle: '選擇介面語言',
  languageDesc: '語言設定即時生效，之後可在設定中隨時更改',
  // 主題
  themeTitle: '選擇外觀主題',
  themeDesc: '深色/淺色主題可在設定中隨時切換',
  dark: '深色',
  light: '淺色',
  // 目錄
  dirTitle: '選擇目錄',
  dirDesc: '數據目錄存放啟動器配置，遊戲目錄存放 Minecraft 遊戲檔案',
  dataDir: '數據目錄',
  dataDirDesc: '啟動器配置、快取等數據存放位置',
  gameDir: '遊戲目錄',
  gameDirDesc: 'Minecraft 遊戲檔案（.minecraft）所在位置',
  browse: '瀏覽...',
  // 下載源
  downloadTitle: '選擇下載源',
  downloadDesc: '建議選擇延遲最低的源，測速結果僅供參考',
  downloadSource: '遊戲檔案下載源',
  modSource: '模組源',
  autoSelect: '自動選擇最優',
  pinging: '測速中...',
  pingFailed: '測速失敗',
  // Java
  javaTitle: '配置 Java 執行環境',
  javaDesc: '需要 Java 8 / 17 / 21 三個執行環境，缺失的版本可在線下載',
  javaScanning: '正在深度掃描 Java 執行環境...',
  javaScanAgain: '重新掃描',
  javaFound: '已找到',
  javaMissing: '未找到',
  javaDownload: '下載',
  javaDownloading: '下載中 {progress}%',
  javaDownloaded: '已下載',
  javaDownloadFailed: '下載失敗',
  javaVersion8: 'Java 8',
  javaVersion17: 'Java 17',
  javaVersion21: 'Java 21',
  javaReady: '所有必需版本已就緒',
  javaRequired: '所有必需版本就緒後即可繼續',
  javaSkip: '跳過',
  javaSkipConfirmTitle: '跳過 Java 檢測',
  javaSkipConfirm: 'Java 環境不完整，部分遊戲版本可能無法啟動。確定要跳過嗎？',
  // 記憶體
  memoryTitle: '分配記憶體',
  memoryDesc: '建議使用自動分配',
  memoryAuto: '自動分配（推薦）',
  memoryAutoDesc: '根據系統可用記憶體自動計算',
  memoryCustom: '自訂',
  memoryCustomDesc: '手動指定最大記憶體',
  memoryMb: 'MB',
  // 完成
  doneTitle: '設定完成',
  doneDesc: '初始化數據已儲存，開始使用 Qomicex 吧！',
  doneSummary: '本次已完成配置：',
  finish: '開始使用',
  saving: '儲存中...',
  saveFailed: '儲存失敗，請重試',
  default: '預設',
} as const
