// Детали аккаунта (ru-RU)
export default {
  capeUnequipped: 'Плащ снят',
  capeEquipped: 'Плащ надет',
  capeSwitchFailed: 'Не удалось сменить плащ, войдите снова и повторите',
  skinUploaded: 'Скин загружен',
  skinUploadFailed: 'Не удалось загрузить скин',
  resetSkinConfirm: 'Сбросить на скин по умолчанию?',
  skinReset: 'Скин сброшен',
  skinResetFailed: 'Не удалось сбросить скин',
  skinSavedTo: 'Скин сохранён в {dest}',
  skinDownloaded: 'Скин скачан',
  skinDownloadFailed: 'Не удалось скачать скин',
  deleteAccountConfirm: 'Удалить этот аккаунт?',
  loading: 'Загрузка…',
  showNameTag: 'Показывать метку имени',
  showCape: 'Показывать плащ',
  downloadSkin: 'Скачать скин',
  accountInfo: 'Информация об аккаунте',
  name: 'Имя',
  type: 'Тип',
  authServer: 'Сервер аутентификации',
  skinModel: 'Модель скина',
  slim: 'Стройная (Slim)',
  classic: 'Классическая (Classic)',
  cape: 'Плащ',
  none: 'Нет',
  hasSkin: 'Есть',
  refreshSkin: 'Обновить скин',
  switchCape: 'Сменить плащ',
  uploadSkin: 'Загрузить скин',
  chooseArmModel: 'Выберите модель рук',
  skinPreview: 'Предпросмотр скина',
  classicArm: 'Классические руки',
  slimArm: 'Стройные руки',
  resetSkin: 'Сбросить скин',
  goToSkinSite: 'Перейти на сайт скинов',
  deleteAccount: 'Удалить аккаунт',
} as const