// Аккаунты (ru-RU)
export default {
  loginErrors: {
    accessDenied: 'Вы отменили или отклонили авторизацию в браузере',
    expiredToken: 'Срок действия кода истёк, войдите снова',
    invalidGrant: 'Авторизация недействительна, войдите снова',
    loginFailed: 'Ошибка входа: {code}',
  },
  methodLabel: {
    offline: 'Офлайн',
    thirdParty: 'Сторонний',
    thirdPartyWith: 'Сторонний/{server}',
    unified: 'Единый пропуск',
  },
  dataCorrupted: 'Файл данных аккаунта повреждён или изменился машинный код; файл удалён. Добавьте аккаунт заново.',
  microsoft: {
    gettingInfo: 'Получение данных для входа…',
    openingBrowser: 'Открытие браузера…',
    codeCopied: 'Код скопирован в буфер обмена. Войдите в аккаунт Microsoft в браузере\nКод: {code}',
    loginTimeout: 'Тайм-аут входа, войдите снова',
    gettingAccount: 'Получение информации об аккаунте…',
    loginSuccess: 'Вход выполнен',
    noRole: 'Не удалось получить доступную роль',
    stepFetching: 'Получение данных для входа',
    stepWaiting: 'Ожидание авторизации',
    stepFetchingInfo: 'Получение информации об аккаунте',
    codeCopiedShort: 'Код скопирован',
    browserOpened: 'Браузер открыт автоматически',
    relogin: 'Войти снова',
  },
  deleteConfirm: 'Удалить этот аккаунт?',
  deleteTitle: 'Удалить аккаунт',
  batchDeleteConfirm: 'Удалить выбранные аккаунты ({count})?',
  batchDeleteTitle: 'Массовое удаление',
  title: 'Управление аккаунтами',
  refresh: 'Обновить',
  addAccount: 'Добавить аккаунт',
  add: 'Добавить',
  filterAll: 'Все фильтры',
  filterName: 'Имя',
  filterLoginMethod: 'Способ входа',
  filterServer: 'Сервер',
  searchPlaceholder: 'Поиск аккаунтов…',
  noMatch: 'Нет подходящих аккаунтов',
  noAccounts: 'Нет аккаунтов',
  setDefault: 'Сделать основным',
  deleteSelected: 'Удалить: {count}',
  addTitle: 'Добавить аккаунт',
  tabOffline: 'Офлайн',
  tabUnified: 'Единый пропуск',
  offline: {
    playerName: 'Имя игрока',
    playerNamePlaceholder: 'Введите имя пользователя в офлайне',
    uuid: 'UUID (необязательно, оставьте пустым для автогенерации)',
    uuidPlaceholder: 'Например: 069a79f4-44e9-4726-a5be-fca90e38aaf5',
    add: 'Добавить офлайн-аккаунт',
  },
  ygg: {
    presetServer: 'Предустановленный сервер',
    email: 'Эл. почта',
    password: 'Пароль',
    customServerAddr: 'Адрес пользовательского сервера',
    login: 'Войти',
    loginLoading: 'Вход…',
    saving: 'Сохранение…',
    chooseRole: 'Выберите роль для входа:',
    back: 'Назад',
    confirmCount: 'Подтвердить ({count})',
    dndHint: 'или перетащите сервер аутентификации сюда из веб-страницы',
    dndTitle: 'Добавить сервер аутентификации',
    dndConfirm: 'Добавить этот сервер аутентификации?\n{url}',
    resolvedTo: 'Адрес API: {url}',
    resolveFailed: 'Не удалось подключиться к этому адресу, будет использован исходный адрес',
    httpWarning: 'Предупреждение: этот сервер аутентификации использует незашифрованный протокол HTTP, пароль будет передан открытым текстом, есть риск утечки',
  },
  unified: {
    desc: 'Единый пропуск — это система аутентификации, используемая на некоторых серверах Minecraft, требует ввода идентификатора сервера.',
    serverId: 'ID сервера',
    serverIdPlaceholder: 'Например: lilu',
    email: 'Эл. почта',
    password: 'Пароль',
    login: 'Войти',
    loginLoading: 'Вход…',
    oauthLogin: 'Вход через Microsoft OAuth',
  },
} as const