// Общие сообщения (ru-RU)
export default {
  ok: 'ОК',
  cancel: 'Отмена',
  close: 'Закрыть',
  save: 'Сохранить',
  create: 'Создать',
  delete: 'Удалить',
  edit: 'Редактировать',
  confirm: 'Подтвердить',
  loading: 'Загрузка…',
  noData: 'Нет данных',
  comingSoon: 'Скоро',
  retry: 'Повторить',
  refresh: 'Обновить',
  copy: 'Копировать',
  copied: 'Скопировано',
  search: 'Поиск',
  select: 'Выбрать',
  back: 'Назад',
  next: 'Далее',
  prev: 'Предыдущий',
  unknown: 'Неизвестно',
  all: 'Все',
  none: 'Нет',
  enabled: 'Включено',
  disabled: 'Отключено',
  error: 'Ошибка',
  warning: 'Предупреждение',
  success: 'Успешно',
  failed: 'Не удалось',
  info: 'Информация',
  input: 'Ввод',
  inputPlaceholder: 'Введите…',
  batchSelected: 'Выбрано: {count}',
  selectAll: 'Выбрать все',
  deselect: 'Снять выбор',
  noMatch: 'Нет совпадений',
  pendingTasksCloseConfirm: 'Есть незавершённые задачи, после закрытия все задачи будут удалены.\n\nЗакрыть?',
  language: 'Язык интерфейса',
  theme: 'Тема',
  dark: 'Тёмная',
  light: 'Светлая',
  externalLink: 'Внешняя ссылка',
  seeMore: 'Показать ещё',
  goto: 'Перейти',
  name: 'Имя',
  version: 'Версия',
  status: 'Статус',
  action: 'Действие',
  detail: 'Подробнее',
  optional: 'Необязательно',
  javaRuntimeRequired: 'Для запуска Minecraft требуется среда выполнения Java.\n\nВы можете установить её через «Настройки → Java → Загрузить Java» или вручную указать путь к установленной Java.',
  javaRuntimeRequiredTitle: 'Среда выполнения Java не обнаружена',
} as const