// Сетевая игра (ru-RU)
export default {
  hostBadge: 'Хост',
  kick: 'Выгнать',
  kickReviewTitle: 'Игрок запрашивает повторное подключение',
  kickReviewBody: 'Игрок «{name}» хочет вернуться в комнату. Разрешить?',
  kickReviewAllow: 'Разрешить',
  kickReviewReject: 'Отклонить',
  kickReviewRejectSilent: 'Отклонить и больше не спрашивать',
  kickedPlayersTitle: 'Выгнанные игроки ({count})',
  unban: 'Снять блокировку',
  noPlayers: 'Нет игроков',
  playerList: 'Список игроков ({count})',
  hostMods: 'Моды хоста',
  matchInstances: 'Подходящие экземпляры ({count})',
  scanningMatch: 'Сканирование локальных экземпляров и сравнение с модами хоста…',
  noHostMods: 'Хост не опубликовал список модов (или идёт сканирование)',
  missingModsDesc: 'Моды с меткой «отсутствует» не входят в экземпляр {instance}{countSuffix} (локальный экземпляр с наибольшим покрытием модов хоста)',
  missingModsCountSuffix: ', всего {count}',
  noVersionInfo: 'Хост не предоставил информацию о версии, невозможно определить отсутствующие моды',
  missingTooltip: 'Этот мод отсутствует в наилучшем совпадающем экземпляре (с наибольшим покрытием модов хоста)',
  missing: 'Отсутствует',
  scanningLocal: 'Сканирование локальных экземпляров…',
  noVersionForMatch: 'Хост не предоставил информацию о версии, невозможно сопоставить локальные экземпляры',
  noMatchingInstance: 'Нет локального экземпляра с той же версией/загрузчиком игры, что у хоста',
  matchedInstances: 'Совпадающие экземпляры ({count})',
  modsConsistent: 'Моды совпадают ({count})',
  quickLaunch: 'Быстрый запуск',
  unmatchedInstances: 'Несовпадающие экземпляры ({count}), запуск с игнорированием различий',
  modsInconsistent: 'Моды не совпадают ({count})',
  forceLaunchTitle: 'Игнорировать различия в модах и присоединиться к комнате на этом локальном экземпляре',
  forceLaunch: 'Игнорировать различия и запустить',
  noLocalInstance: 'Нет доступных локальных экземпляров',
  gameCrashed: 'Игра завершилась аварийно',
  launchFailed: 'Ошибка запуска',
  invalidPort: 'Введите корректный порт (1-65535)',
  selectInstanceFirst: 'Сначала выберите экземпляр',
  enterRoomCode: 'Введите код комнаты',
  roomNotReady: 'Комната ещё не готова',
  natCheckFailed: 'Не удалось определить тип NAT',
  natTypes: {
    cone: { label: 'Полный конус', tooltip: 'UDP: свободный  TCP: средний' },
    symmetric: { label: 'Строго симметричный', tooltip: 'UDP: строгий  TCP: строгий' },
    blocked: { label: 'Непроходимый', tooltip: 'UDP: блокирован  TCP: блокирован' },
    unknown: { label: 'Неопределён', tooltip: 'Тип NAT неизвестен' },
  },
  title: 'Сетевая игра',
  subtitle: 'Создайте или присоединитесь к комнате сетевой игры',
  natCheck: 'Проверка NAT',
  easyTierDownloadFailed: 'Ошибка загрузки EasyTier: {error}',
  retry: 'Повторить',
  easyTierStatus: {
    resolving: 'Определение самого быстрого источника загрузки…',
    extracting: 'Распаковка EasyTier…',
    downloading: 'Загрузка компонента сетевой игры EasyTier…',
  },
  tabCreate: 'Создать комнату',
  tabJoin: 'Присоединиться',
  createTitle: 'Запустить экземпляр и создать комнату',
  selectInstance: 'Выберите экземпляр',
  pleaseSelect: 'Выберите…',
  starting: 'Запуск…',
  startAndCreate: 'Запустить и создать комнату',
  openLanHint: 'После запуска нажмите в игре «Открыть для локальной сети», порт будет определён автоматически.',
  manualStarted: 'Экземпляр уже запущен вручную? Нажмите здесь',
  scanPortTitle: 'Сканирование локального порта',
  scanningPorts: 'Сканирование портов Java-процесса…',
  portDetected: 'Порт обнаружен',
  createRoom: 'Создать комнату',
  manualPort: 'или введите порт вручную',
  joinTitle: 'Присоединиться к комнате',
  roomCode: 'Код комнаты',
  joining: 'Подключение…',
  joinRoom: 'Присоединиться',
  gotIt: 'Понятно',
  cancel: 'Отмена',
  closeRoom: 'Закрыть комнату',
  serverAddress: 'Адрес сервера',
  hostVersion: 'Версия хоста: {version}',
  leaveRoom: 'Выйти из комнаты',
} as const