// Панель управления (ru-RU)
export default {
  account: 'Аккаунт',
  noDefaultAccount: 'Аккаунт по умолчанию не задан',
  defaultAccount: 'Аккаунт по умолчанию',
  addInSettings: 'Добавить в настройках',
  manageAccounts: 'Управление аккаунтами',
  lastPlayed: 'Последняя игра: {date}',
  status: 'Статус',
  ready: 'Готов',
  launch: 'Запуск',
  noPinnedInstance: 'Ещё нет закреплённых экземпляров',
  goToInstances: 'Перейти к экземплярам',
  editLayout: 'Изменить макет',
  editMode: 'Режим редактирования: перетаскивайте для размещения, тяните правый нижний угол для изменения размера',
  addWidget: 'Добавить виджет',
  resetLayout: 'Сбросить макет',
  allWidgetsVisible: 'Все виджеты отображаются',
  done: 'Готово',
  widget: {
    watermark: 'Водяной знак',
    account: 'Аккаунт',
    instance: 'Экземпляр по умолчанию',
    launch: 'Запуск',
    announcements: 'Объявления',
  },
} as const