// Подсказки внешнего запуска (deep link qomicex-launcher://, issue #127)
export default {
  launchNotFound: 'Экземпляр не найден: {target}',
  joinConfirmTitle: 'Присоединиться к комнате',
  joinConfirmDesc: 'Веб-страница запрашивает присоединение к комнате {code}. Продолжить?',
  joinFailed: 'Не удалось присоединиться к комнате: {message}',
  installPluginConfirmTitle: 'Установить плагин',
  installPluginConfirmDesc: 'Запрос поступил от {host}; будет установлен плагин {name}. Продолжайте только если доверяете этому источнику.',
  installPluginSlugConfirmDesc: 'Веб-страница запрашивает установку плагина из магазина {slug}. Продолжить?',
  installModpackConfirmTitle: 'Установить модпак',
  installModpackConfirmDesc: 'Веб-страница запрашивает установку модпака {name} (источник: {source}). Продолжить?',
  installStarted: 'Установка начата',
  installFailed: 'Не удалось установить: {message}',
  cancelled: 'Действие отменено',
  registerTitle: 'Связать внешние ссылки',
  registerDesc: 'Зарегистрировать лаунчер как обработчик ссылок qomicex-launcher://? После регистрации веб-страницы и ярлыки смогут открывать лаунчер напрямую.',
  registerSuccess: 'Связь с внешними ссылками установлена',
  registerFailed: 'Не удалось связать. Повторите попытку позже в настройках',
  registerDeclined: 'Пропущено. Больше не будем спрашивать автоматически',
  launchAmbiguous: 'Найдено несколько экземпляров ({count}) с именем «{target}», поэтому непонятно, какой из них запускать. Укажите формат каталог:имя-экземпляра, например {example}',
  launchAmbiguousExample: '/path/to/game:имя-экземпляра',
}
