// Общие диалоги/карточки (ru-RU)
export default {
  // Этап установки/загрузки (как в downloads.stage, для динамической отрисовки ключей в диалогах)
  stage: {
    queued: 'В очереди',
    'downloading-json': 'Загрузка JSON версии',
    downloading: 'Загрузка файлов игры',
    'downloading-libraries': 'Загрузка библиотек',
    'downloading-assets': 'Загрузка ресурсов',
    'downloading-mainjar': 'Загрузка основного файла',
    'downloading-loader': 'Загрузка загрузчика',
    'downloading-loader-libs': 'Загрузка библиотек загрузчика',
    'installing-loader': 'Установка загрузчика',
    'downloading-addons': 'Загрузка дополнений',
    'downloading-modpack': 'Загрузка модпака',
    'parsing-modpack': 'Разбор модпака',
    'modpack-files': 'Загрузка файлов модпака',
    'modpack-overrides': 'Распаковка файлов замены',
  },
  // Общие тексты для всех диалогов/карточек
  common: {
    unknownError: 'Неизвестная ошибка',
    deleting: 'Удаление…',
    viewDetail: 'Подробнее',
    openFolder: 'Открыть папку',
    openFailed: 'Ошибка открытия',
    deleted: 'Удалено: «{name}»',
    deleteFailed: 'Ошибка удаления: {error}',
    taskExpired: 'Срок действия задачи истёк (бэкенд не сообщил об этой сессии)',
    downloadTimeout: 'Тайм-аут загрузки (возможно, продолжается в фоне)',
    downloadStalled: 'Загрузка остановилась (долго нет прогресса)',
    cancelled: 'Загрузка отменена',
    downloadFailed: 'Ошибка загрузки',
    startFailed: 'Не удалось запустить загрузку',
  },
  // Подтверждение удаления (по типу ресурса)
  confirmDelete: {
    titleMod: 'Удалить мод',
    titleSave: 'Удалить мир',
    titleScreenshot: 'Удалить скриншот',
    titleShader: 'Удалить шейдерпак',
    titleDataPack: 'Удалить датапак',
    titleResourcePack: 'Удалить ресурспак',
    bodyMod: 'Удалить мод «{name}»? Он будет перемещён в корзину.',
    bodySave: 'Удалить мир «{name}»? Он будет перемещён в корзину.',
    bodyScreenshot: 'Удалить скриншот «{name}»? Он будет перемещён в корзину.',
    bodyShader: 'Удалить шейдерпак «{name}»? Он будет перемещён в корзину.',
    bodyDataPack: 'Удалить датапак «{name}»? Он будет перемещён в корзину.',
    bodyResourcePack: 'Удалить ресурспак «{name}»? Он будет перемещён в корзину.',
  },
  // Прогресс запуска
  launchProgress: {
    title: 'Запуск игры',
    titleFailed: 'Ошибка запуска',
    stage: {
      starting: 'Подготовка',
      checking: 'Проверка целостности файлов',
      repairing: 'Дозаполнение файлов',
      'logging-in': 'Проверка аккаунта',
      authlib: 'Настройка внешнего входа',
      natives: 'Распаковка нативных библиотек',
      building: 'Построение параметров запуска',
      preparing: 'Подготовка окружения',
      launching: 'Запуск игры',
      running: 'Игра запущена',
      crashed: 'Игра завершилась аварийно',
      failed: 'Ошибка запуска',
      completed: 'Игра завершена',
      cancelled: 'Отменено',
    },
    viewCrashReport: 'Просмотреть отчёт о вылете',
    processId: 'ID процесса: {pid}',
    startingUp: 'Запуск…',
  },
  // Анализ вылета
  crashAnalysis: {
    copyAll: 'Копировать всё',
    copyDetail: 'Подробности:\n{detail}',
    copyArgs: 'Параметры запуска:\n{args}',
    copyCrashReport: 'Отчёт о вылете:\n{crashReport}',
    copyLogLink: 'Ссылка на журнал: {url}',
    exporting: 'Экспорт…',
    exportReport: 'Экспортировать отчёт диагностики',
    exportFailed: 'Ошибка экспорта',
    detail: 'Подробности ошибки',
    crashReport: 'Отчёт о вылете',
    launchArgs: 'Параметры запуска',
    analyzing: 'Анализ отчёта о вылете…',
    noResult: 'Нет результата анализа',
    scanQr: 'Отсканируйте, чтобы открыть полный журнал',
  },
  // Импорт модпака
  import: {
    title: 'Импорт модпака',
    parsing: 'Разбор файла модпака…',
    modpackName: 'Название модпака',
    gameVersion: 'Версия игры',
    loader: 'Загрузчик',
    instanceName: 'Название экземпляра',
    startInstall: 'Начать установку',
    connecting: 'Подключение…',
    installing: 'Установка: {name}',
    completed: '✓ Установлено!',
    completedDetail: 'Модпак успешно установлен как экземпляр «{name}»',
    failedWith: 'Ошибка установки: {error}',
    seeDownloadPage: 'Подробности смотрите на странице загрузок',
    viewInstance: 'Открыть экземпляр',
    backgroundDownload: 'Загрузка в фоне',
    parseFailed: 'Ошибка разбора',
    installFailed: 'Ошибка установки',
  },
  // Установка модпака (онлайн)
  modpackInstall: {
    title: 'Установка модпака',
    modpackLabel: 'Модпак',
    gameVersion: 'Версия игры',
    loader: 'Загрузчик',
    instanceName: 'Название экземпляра',
    startInstall: 'Начать установку',
    resolving: 'Разбор и установка…',
    connecting: 'Подключение…',
    installing: 'Установка: {name}',
    completed: '✓ Установлено!',
    completedDetail: 'Модпак успешно установлен как экземпляр «{name}»',
    failedWith: 'Ошибка установки: {error}',
    seeDownloadPage: 'Подробности смотрите на странице загрузок',
    viewInstance: 'Открыть экземпляр',
    backgroundDownload: 'Загрузка в фоне',
    cancelled: 'Отменено',
    installFailed: 'Ошибка установки',
  },
  // Экспорт модпака
  modpackExport: {
    title: 'Экспорт модпака',
    format: 'Формат экспорта',
    include: 'Включаемое содержимое',
    includeSaves: 'Включить миры',
    includeScreenshots: 'Включить скриншоты',
    packInfo: 'Информация о паке',
    packName: 'Название',
    packVersion: 'Версия',
    packAuthor: 'Автор',
    exportingTitle: 'Экспорт…',
    stageLookup: 'Определение отпечатков файлов',
    stageManifest: 'Создание файла конфигурации',
    stagePacking: 'Упаковка игровых файлов: {file}',
    cancelExport: 'Отмена',
    cancelConfirm: 'Отменить экспорт?',
    exportCancelled: 'Экспорт отменён',
    exportSaved: '✓ Экспорт завершён',
    exportSavedTo: '✓ Экспорт завершён (сохранено в: {path})',
    fileName: 'Имя файла экспорта',
    startExport: 'Начать экспорт',
    exporting: 'Упаковка… (для больших пакетов может потребоваться время)',
    exported: '✓ Экспорт завершён',
    exportFailed: 'Ошибка экспорта',
    selectAll: 'Выбрать все',
    deselectAll: 'Снять выбор',
    selectedSummary: 'Выбрано элементов: {count} · {size}',
    loading: 'Чтение списка файлов…',
    loadFailed: 'Ошибка чтения списка файлов',
    retry: 'Повторить',
    empty: 'Нет файлов для экспорта',
    fileCount: 'Элементов: {count}',
    expand: 'Развернуть',
    collapse: 'Свернуть',
    catMods: 'Моды',
    catResourcepacks: 'Ресурспаки',
    catShaderpacks: 'Шейдеры',
    catSaves: 'Миры',
    catScreenshots: 'Скриншоты',
    catConfig: 'Конфигурация',
  },
  // Обновление версии
  update: {
    foundNew: 'Найдена новая версия {version}',
    noNotes: 'Нет описания обновления',
    downloadFailed: 'Ошибка загрузки',
    done: 'Обновление завершено',
    downloading: 'Загрузка {progress}%',
    later: 'Позже',
    installing: 'Установка…',
    downloadingAction: 'Загрузка…',
    updateNow: 'Обновить сейчас',
    retry: 'Повторить',
    cancelDownload: 'Отменить загрузку',
    released: 'Выпущено: {date}',
    viewRelease: 'Просмотр релиза',
    requiredNotice: 'Это обязательное обновление. Для продолжения работы необходимо обновиться',
  },
  // Активация лицензии
  license: {
    title: 'Активировать лицензию',
    loadFailed: 'Ошибка загрузки',
    activateFailed: 'Ошибка активации',
    active: 'Лицензия активирована',
    id: 'ID: {licenseId}',
    expireAt: 'Истекает: {date}',
    permanent: 'Бессрочная',
    machineCode: 'Машинный код устройства',
    copyMachineCode: 'Копировать машинный код',
    tokenLabel: 'Токен лицензии',
    tokenPlaceholder: 'Вставьте токен лицензии, выданный администратором…',
    tokenHint: 'Свяжитесь с администратором, чтобы получить новый токен лицензии. Введите токен и нажмите «Активировать» для проверки.',
    exitLauncher: 'Выйти из лаунчера',
    verifying: 'Проверка…',
    activate: 'Активировать',
  },
  // Повторный вход Microsoft
  microsoftReauth: {
    title: 'Учётные данные Microsoft истекли',
    description: 'Срок действия учётных данных вашего аккаунта Microsoft истёк, для запуска игры требуется повторный вход.',
    reauth: 'Войти в Microsoft снова',
  },
  // Аккаунт не задан
  noAccount: {
    title: 'Аккаунт не задан',
    description: 'Для запуска игры требуется аккаунт Minecraft, сначала добавьте аккаунт.',
    goToAccounts: 'Перейти к аккаунтам',
    addAccount: 'Добавить аккаунт',
  },
  // Выбор аккаунта по умолчанию
  accountSelect: {
    title: 'Выбор аккаунта по умолчанию',
    description: 'Выберите аккаунт по умолчанию; он будет использоваться при запуске игры.',
    noAccounts: 'Нет аккаунтов',
  },
  // Смена версии
  versionPicker: {
    title: 'Смена версии — {name}',
    loadingVersions: 'Загрузка списка версий…',
    noVersions: 'Нет доступных версий',
    switching: 'Смена…',
    switch: 'Сменить',
  },
  // Обновление модов
  modUpdate: {
    title: 'Проверка обновлений модов',
    checkFailed: 'Ошибка проверки обновлений',
    addedToDownloadList: 'Добавлено в список загрузки: {count} задач',
    updatedCount: 'Обновлено модов: {count}',
    completedWithFailed: 'Успешно: {success}, не удалось: {failed}{failNames}',
    batchFailed: 'Ошибка массового обновления',
    allUpToDate: 'Все моды обновлены',
    updating: 'Обновление…',
    updateCount: 'Обновить модов: {count}',
  },
  // Объявление
  announcement: {
    gotIt: 'Понятно',
  },
  // Управление плащами
  cape: {
    title: 'Смена плаща',
    noCapes: 'У этого аккаунта нет доступных плащей',
    loadingShort: 'Загрузка',
    inUse: 'Используется',
    clickToEquip: 'Нажмите, чтобы надеть',
  },
  // Установка ресурса
  resourceInstall: {
    title: 'Установка {name}',
    selectInstance: 'Выберите экземпляр',
    loadingInstances: 'Загрузка списка экземпляров…',
    instancesLoadFailed: 'Ошибка загрузки списка экземпляров',
    noInstances: 'Нет экземпляров, сначала создайте экземпляр',
    searchPlaceholder: 'Поиск экземпляров…',
    default: 'По умолчанию',
    selectVersion: 'Выберите версию',
    selectInstanceFirst: 'Сначала выберите экземпляр',
    loadingVersions: 'Загрузка списка версий…',
    versionsLoadFailed: 'Ошибка загрузки списка версий',
    selectVersionPlaceholder: 'Выберите версию',
    noVersions: 'Нет доступных версий',
    depsTitle: 'Требуемые моды',
    parsingDeps: 'Разбор требуемых модов…',
    depsLoadFailed: 'Ошибка загрузки требуемых модов',
    noDeps: 'Нет требуемых модов',
    installed: 'Установлено',
    pending: 'Ожидает установки',
    noDownloadableFile: 'У этой версии нет файлов для загрузки',
    downloadFailedWith: 'Ошибка загрузки «{name}»: {error}',
    downloading: 'Загрузка',
    installConfirm: 'Подтвердить установку',
    installing: 'Установка…',
    installingWithName: 'Загрузка {name} ({step}/{total})',
    installedDone: 'Установлено: {name}',
  },
  // Карточка мода
  mod: {
    mcwiki: 'MCWiki',
    changeVersion: 'Сменить версию',
    update: 'Обновить',
    addedToDownloadList: 'Добавлено в список загрузки',
    updatedWithName: '«{name}» обновлён',
    updateFailedWithName: 'Ошибка обновления «{name}»',
    updateFailed: 'Ошибка обновления',
    updateAvailableTo: 'Доступно обновление до {version}',
    unknownVersion: 'Неизвестная версия',
  },
  // Карточка мира
  save: {
    backup: 'Резервная копия',
    rename: 'Переименовать',
    quickJoin: 'Быстрый вход',
    lastPlayed: 'Последняя игра: {date}',
    settings: 'Настройки',
  },
  // Диалог уведомления об авторских правах
  legal: {
    title: 'Уведомление об авторских правах',
    content: `**Qomicex Launcher** разработан и поддерживается командой **Qomicex**, авторские права принадлежат команде Qomicex.
  
- Это ПО опубликовано по лицензии с открытым исходным кодом **GPL-3.0 License**; при соблюдении условий лицензии его можно свободно использовать, копировать, изменять и распространять.
- Это ПО не состоит ни в каких отношениях подчинённости, сотрудничества или одобрения с **Mojang Studios / Microsoft** и их продуктами.
- **Minecraft** и связанные названия, знаки и авторские права принадлежат **Mojang Studios / Microsoft**.
- Это ПО не содержит саму игру Minecraft; права на игровые ресурсы принадлежат их правообладателям.
- Используя это ПО, вы подтверждаете, что прочитали и согласны с «Пользовательским соглашением» и «Политикой конфиденциальности».`,
  },
} as const