// Центр загрузок (ru-RU)
export default {
  status: {
    queued: 'В очереди',
    downloading: 'Загрузка',
    paused: 'Приостановлено',
    completed: 'Завершено',
    failed: 'Не удалось',
    cancelled: 'Отменено',
  },
  stage: {
    queued: 'В очереди',
    'fetching-json': 'Получение списка версий',
    'downloading-installer': 'Скачивание установщика загрузчика',
    downloading: 'Загрузка файлов игры',
    'scanning-base': 'Сканирование файлов игры',
    'downloading-base': 'Скачивание файлов игры',
    'scanning-loader-libs': 'Сканирование библиотек загрузчика',
    'downloading-loader-libs': 'Загрузка библиотек загрузчика',
    'installing-optifine': 'Установка OptiFine',
    'downloading-addons': 'Загрузка дополнений',
    'downloading-additional-files': 'Загрузка дополнительных файлов',
    'installing-loader': 'Установка загрузчика',
    'verifying-jar': 'Проверка основного jar',
    finishing: 'Завершение',
    'downloading-json': 'Загрузка JSON версии',
    'downloading-libraries': 'Загрузка библиотек',
    'downloading-assets': 'Загрузка ресурсов',
    'downloading-mainjar': 'Загрузка основного файла',
    'downloading-loader': 'Загрузка загрузчика',
    'downloading-modpack': 'Загрузка модпака',
    'parsing-modpack': 'Разбор модпака',
    'modpack-files': 'Загрузка файлов модпака',
    'modpack-overrides': 'Распаковка файлов замены',
  },
  steps: {
    fetchJson: 'Получение списка версий',
    installer: 'Скачать установщик загрузчика',
    gameFiles: 'Скачать файлы игры',
    loaderLibs: 'Скачать библиотеки загрузчика',
    installLoader: 'Установить загрузчик',
    installOptifine: 'Установить OptiFine',
    downloadAddons: 'Скачать дополнения',
    finalize: 'Проверка и завершение',
    downloadModpack: 'Скачать модпак',
    parseModpack: 'Разобрать модпак',
    installGame: 'Установить игру',
    downloadFiles: 'Скачать файлы модпака',
    overrides: 'Распаковать файлы замены',
  },
  speedLabel: 'Скорость загрузки',
  stepsDone: 'Выполнено шагов: {done}/{total}',
  filter: {
    all: 'Все',
    downloading: 'Загрузка',
    paused: 'Приостановлено',
    completed: 'Завершено',
    failed: 'Не удалось',
  },
  title: 'Центр загрузок',
  subtitle: 'Задач: {count}',
  clearFinished: 'Удалить завершённые/ошибочные',
  taskCount: 'Задач: {count}',
  empty: 'Нет задач загрузки',
  emptyHint: 'Выберите версию на странице «Экземпляры» и начните загрузку — задачи появятся здесь',
  goToInstances: 'Перейти к экземплярам',
  addonsCount: 'Дополнений: +{count}',
  createdAt: 'Создано: {date}',
  completedAt: 'Завершено: {date}',
  resume: 'Продолжить',
  pause: 'Пауза',
  cancel: 'Отмена',
  retry: 'Повторить',
  remove: 'Удалить',
  statusText: {
    done: 'Загрузка завершена',
    failedWith: 'Не удалось: {error}',
    failed: 'Ошибка загрузки',
    pausedProgress: 'Приостановлено {progress}%',
    waiting: 'Ожидание',
    downloading: 'Загрузка',
    connecting: 'Подключение…',
  },
  filesCount: 'Файлов: {done}/{total}',
  errors: {
    taskExpired: 'Срок действия задачи истёк (бэкенд был перезапущен)',
    downloadFailed: 'Ошибка загрузки',
    cannotVerify: 'Не удалось подключиться к бэкенду для проверки статуса задачи',
    statusUnknown: 'Не удалось подтвердить статус задачи (бэкенд не сообщил об этой сессии)',
    taskInvalid: 'Задача недействительна',
  },
} as const