// Сообщения об ошибках бэкенда (отображение по кодам ошибок фронтенда, ru-RU)
export default {
  notFound: 'Запрошенный ресурс не найден',
  forbidden: 'Нет прав на выполнение этого действия',
  badRequest: 'Некорректные параметры запроса',
  internalError: 'Внутренняя ошибка сервера',
  upstreamError: 'Сбой запроса к вышестоящему сервису',
  requestTimeout: 'Время ожидания запроса истекло, повторите позже',
  unknown: 'Запрос не выполнен, повторите позже',
  licenseNotFound: 'Лицензия не активирована',
  licenseDecryptFailed: 'Не удалось расшифровать лицензию',
  licenseSignatureInvalid: 'Недействительная подпись лицензии',
  licensePublicKeyUnavailable: 'Открытый ключ лицензии недоступен',
  licenseExpired: 'Срок действия лицензии истёк',
  licenseRemoteCheckFailed: 'Сбой удалённой проверки лицензии',
  licenseIoError: 'Не удалось прочитать файл лицензии',
  tokenExpired: 'Срок действия токена входа истёк, войдите снова',
  networkError:
    'Не удалось подключиться к сервису аутентификации Microsoft. Проверьте сеть или запустите игру в автономном режиме',
  mcApiError: 'Ошибка запроса к официальному API Minecraft',
  fsAuthRequired: 'Доступ к файловой системе не авторизован',
  pluginMissingDependency: 'Плагину не хватает необходимых зависимостей',
  connectorTimeout: 'Тайм-аут сетевой игры, проверьте сеть и повторите',
  exportDiagnosticsFailed: 'Не удалось экспортировать отчёт диагностики',
  modpackParseFailed: 'Не удалось разобрать модпак',
  skinUploadFailed: 'Не удалось загрузить скин',
  skinSaveFailed: 'Не удалось сохранить скин',
  skinResetFailed: 'Не удалось сбросить скин',
} as const