// Список экземпляров (ru-RU)
export default {
  title: 'Игровые экземпляры',
  subtitle: 'Версий: {count}',
  type: {
    release: 'Релиз',
    snapshot: 'Снимок',
    old_beta: 'Древняя бета',
    old_alpha: 'Древняя альфа',
    april_fools: 'Первоапрельская',
  },
  category: {
    all: 'Все',
    release: 'Релиз',
    snapshot: 'Снимок',
    april_fools: 'Первоапрельская',
    old_beta: 'Древняя бета',
    old_alpha: 'Древняя альфа',
  },
  sort: {
    recommended: 'Рекомендуемая сортировка',
    newest: 'Сначала новые',
    oldest: 'Сначала старые',
    'name-asc': 'Имя А-Я',
    'name-desc': 'Имя Я-А',
  },
  loaderFilter: {
    all: 'Все',
    modded: 'Моды',
    vanilla: 'Ваниль',
    snapshot: 'Снимок',
    april_fools: 'Первоапрельская',
    broken: 'Ошибка',
  },
  groups: 'Пользовательские группы',
  manageGroups: 'Управление группами',
  groupNamePlaceholder: 'Введите название группы…',
  noGroups: 'Нет пользовательских групп',
  groupsHint: 'Экземпляр можно добавить в несколько пользовательских групп, нажмите для переключения',
  downloadTitle: 'Скачать новую версию',
  categoryLabel: 'Категория',
  searchPlaceholder: 'Поиск версий…',
  remoteCount: 'Удалённых версий: {count}',
  filteredCount: 'После фильтра: {count}',
  noRemoteMatch: 'Нет подходящих удалённых версий',
  noRemoteMatchHint: 'Попробуйте изменить категорию, сортировку или ключевые слова',
  releaseDate: 'Дата выпуска {date}',
  select: 'Выбрать',
  configTitle: 'Настройка загрузки',
  instanceName: 'Название экземпляра',
  instanceNamePlaceholder: 'Введите название экземпляра…',
  gameVersion: 'Версия игры',
  loader: 'Загрузчик модов',
  loaderPlaceholder: 'Выберите загрузчик',
  noneVanilla: 'Нет (чистая ваниль)',
  versionPlaceholder: 'Выберите версию',
  loadingVersions: 'Загрузка…',
  noVersionData: 'Нет данных о версии',
  latestRecommended: 'Последняя {version} (рекомендуется)',
  recommended: ' (рекомендуется)',
  selectLoaderFirst: 'Сначала выберите загрузчик',
  latestVersion: 'Последняя {version}',
  addons: 'Дополнения',
  optional: '(необязательно)',
  fetchingAddons: 'Получение дополнений…',
  onlyGameFiles: 'Будут скачаны только файлы игры; настройки памяти и Java можно изменить после создания',
  noLoaderAvailable: 'Нет доступных версий загрузчика, загрузка невозможна',
  cancel: 'Отмена',
  startDownload: 'Начать загрузку',
  repairName: 'Дозаполнить {name}',
  pickGameDirTitle: 'Выберите игровой каталог',
  enterDirPath: 'Введите путь к игровому каталогу:',
  chooseDir: 'Выбрать каталог',
  addDir: 'Добавить каталог',
  selectDirFirst: 'Сначала выберите игровой каталог, затем начните загрузку.',
  noLoaderVersions: 'Не удалось получить список доступных версий {loader}, загрузка невозможна. Проверьте сеть или повторите позже.',
  selectLoaderVersion: 'Выберите конкретную версию {loader}, затем загрузите.',
  createFailed: 'Ошибка создания: {error}',
  createInstanceFailed: 'Ошибка создания экземпляра: {error}',
  launchFailed: 'Ошибка запуска: {error}',
  launchFailedDetail: 'Ошибка запуска: {error}\n{detail}',
  refresh: 'Обновить',
  dirManagerTitle: 'Управление каталогами',
  currentDir: 'Текущий каталог',
  noDir: 'Каталогов нет',
  noDirHint: 'Нажмите кнопку ниже, чтобы добавить игровой каталог',
  dirCount: 'Всего каталогов: {count}; отметьте каталог, используемый в данный момент',
  openDir: 'Открыть каталог',
  remove: 'Удалить',
  manualAdd: 'Добавить вручную',
  browseAdd: 'Добавить через обзор',
  instanceSettings: 'Настройки экземпляра',
  basicInfo: 'Основная информация',
  repairFiles: 'Дозаполнить файлы',
  versionName: 'Название версии',
  gameDir: 'Игровой каталог',
  notCreatedYet: 'Эта версия ещё не создана в лаунчере, дозаполнить файлы невозможно.',
  repairDesc: 'Сканирование и загрузка недостающих файлов Minecraft этого экземпляра (libraries, assets, client.jar).',
  addedToDownload: 'Добавлено в задачи загрузки',
  goToDownloadCenter: 'Перейти в центр загрузок',
  repairCompleted: 'Дозаполнение завершено',
  repairFailed: 'Ошибка дозаполнения',
  retry: 'Повторить',
  startRepair: 'Начать дозаполнение файлов',
  selectGameDir: 'Выберите игровой каталог',
  savedDirs: 'Сохранённые каталоги',
  manage: 'Управление',
  noDirInManager: 'Каталогов нет, их можно добавить в управлении',
  scanning: 'Сканирование…',
  import: 'Импорт',
  openGameDir: 'Открыть игровой каталог',
  selectMcDir: 'Выберите игровой каталог Minecraft',
  selectMcDirHint: 'Выберите каталог .minecraft, содержащий папку versions',
  browseAndSelect: 'Обзор и выбор',
  noMatch: 'Нет подходящих версий',
  noVersionDetected: 'В этом каталоге не обнаружено ни одной версии Minecraft',
  needVersionsFolder: 'Убедитесь, что в каталоге есть папка versions/',
  available: 'Доступна',
  unavailable: 'Недоступна',
  launch: 'Запуск',
  settings: 'Настройки',
  unpin: 'Открепить',
  pinToHome: 'Закрепить на главной',
  openFolder: 'Открыть папку',
} as const