// Детали экземпляра (ru-RU)
export default {
  tabs: {
    overview: 'Обзор',
    settings: 'Настройки',
    gamesettings: 'Настройки игры',
    saves: 'Миры',
    screenshots: 'Скриншоты',
    mods: 'Моды',
    resourcepacks: 'Ресурспаки',
    shaderpacks: 'Шейдерпаки',
    datapacks: 'Датапаки',
    servers: 'Серверы',
    schematics: 'Схемы',
  },
  confirm: {
    cancel: 'Отмена',
    deleting: 'Удаление…',
    delete: 'Удалить',
    confirm: 'Подтвердить',
  },
  time: {
    minutes: '{count} мин',
    hours: '{count} ч',
    hoursMinutes: '{hours} ч {minutes} мин',
    never: 'Никогда',
    justNow: 'Только что',
    minutesAgo: '{count} мин назад',
    hoursAgo: '{count} ч назад',
  },
  openFolder: 'Открыть папку',
  loading: 'Загрузка…',
  noMatch: 'Нет совпадений',
  empty: 'Пусто',
  deleteSelected: 'Удалить: {count}',
  batchDeleteTitle: 'Массовое удаление {type}',
  batchDeleteConfirm: 'Удалить выбранные {type} ({count})? Они будут перемещены в корзину.',
  saves: {
    search: 'Поиск миров…',
    noMatch: 'Нет подходящих миров',
    empty: 'Миров нет',
    type: 'Мир',
  },
  saveSettings: {
    title: 'Настройки мира',
    restoreFromOld: 'Восстановить из level.dat_old',
    restoreFromOldConfirm: 'Файл level.dat_old перезапишет текущий level.dat (текущее содержимое будет сохранено как level.dat.qomicex.bak). Восстановить?',
    runningWarning: 'Этот экземпляр запущен; при сохранении игры изменения будут перезаписаны. Рекомендуется выйти из игры перед редактированием',
    sectionBasic: 'Основная информация',
    sectionWeather: 'Погода и время',
    sectionSpawn: 'Точка появления и торговец',
    sectionBorder: 'Граница мира',
    levelName: 'Название мира',
    gameType: 'Режим игры',
    gameTypeSurvival: 'Выживание',
    gameTypeCreative: 'Творчество',
    gameTypeAdventure: 'Приключение',
    gameTypeSpectator: 'Наблюдение',
    difficulty: 'Сложность',
    difficultyPeaceful: 'Мирная',
    difficultyEasy: 'Лёгкая',
    difficultyNormal: 'Обычная',
    difficultyHard: 'Сложная',
    allowCommands: 'Разрешить читы',
    hardcore: 'Хардкор',
    difficultyLocked: 'Заблокированная сложность',
    time: 'Мировое время (Time)',
    dayTime: 'Время суток (DayTime)',
    raining: 'Дождь',
    thundering: 'Гроза',
    clearWeatherTime: 'Оставшееся время ясной погоды',
    rainTime: 'Оставшееся время дождя',
    thunderTime: 'Оставшееся время грозы',
    spawnX: 'Точка появления X',
    spawnY: 'Точка появления Y',
    spawnZ: 'Точка появления Z',
    randomSeed: 'Сид мира',
    wanderingTraderSpawnChance: 'Вероятность странствующего торговца',
    wanderingTraderSpawnDelay: 'Задержка странствующего торговца',
    borderCenterX: 'Центр границы X',
    borderCenterZ: 'Центр границы Z',
    borderSize: 'Размер границы',
    borderSafeZone: 'Безопасная зона',
    borderDamagePerBlock: 'Урон вне границы/блок',
    borderWarningBlocks: 'Расстояние предупреждения',
    borderWarningTime: 'Время предупреждения (сек)',
    gameRules: 'Игровые правила',
    ruleKeepInventory: 'Сохранять инвентарь после смерти (keepInventory)',
    ruleDoDaylightCycle: 'Цикл дня и ночи (doDaylightCycle)',
    ruleDoFireTick: 'Распространение огня (doFireTick)',
    ruleMobGriefing: 'Разрушение блоков существами (mobGriefing)',
    ruleDoMobSpawning: 'Появление существ (doMobSpawning)',
    ruleDoWeatherCycle: 'Смена погоды (doWeatherCycle)',
    ruleDoMobLoot: 'Дроп существ (doMobLoot)',
    ruleDoTileDrops: 'Дроп блоков (doTileDrops)',
    ruleDoEntityDrops: 'Дроп сущностей (doEntityDrops)',
    ruleDoNaturalRegeneration: 'Естественное восстановление здоровья (doNaturalRegeneration)',
    ruleDoImmediateRespawn: 'Мгновенное возрождение (doImmediateRespawn)',
    ruleDoInsomnia: 'Появление фантомов (doInsomnia)',
    ruleDoPatrolSpawning: 'Патрули разбойников (doPatrolSpawning)',
    ruleDoTraderSpawning: 'Появление странствующего торговца (doTraderSpawning)',
    ruleDrowningDamage: 'Урон от утопления (drowningDamage)',
    ruleFallDamage: 'Урон от падения (fallDamage)',
    ruleFireDamage: 'Урон от огня (fireDamage)',
    ruleFreezeDamage: 'Урон от замерзания (freezeDamage)',
    ruleShowDeathMessages: 'Сообщения о смерти (showDeathMessages)',
    ruleAnnounceAdvancements: 'Уведомления о достижениях (announceAdvancements)',
    ruleCommandBlockOutput: 'Вывод командного блока (commandBlockOutput)',
    ruleSendCommandFeedback: 'Обратная связь команд (sendCommandFeedback)',
    ruleReducedDebugInfo: 'Упрощённая отладочная информация (reducedDebugInfo)',
    ruleDisableElytraMovementCheck: 'Отключить проверку движения элитр (disableElytraMovementCheck)',
    ruleSpectatorsGenerateChunks: 'Генерация чанков наблюдателем (spectatorsGenerateChunks)',
    ruleDoLimitedCrafting: 'Ограниченное создание (doLimitedCrafting)',
    ruleRandomTickSpeed: 'Скорость случайных тиков',
    ruleSpawnRadius: 'Радиус точки появления',
    ruleMaxEntityCramming: 'Максимум сущностей в одном месте',
    save: 'Сохранить',
    saving: 'Сохранение…',
    saved: 'Настройки мира сохранены',
    loadFailed: 'Не удалось прочитать настройки мира: {error}',
    saveFailed: 'Не удалось сохранить настройки мира: {error}',
    restored: 'Восстановлено из level.dat_old',
    restoreFailed: 'Ошибка восстановления: {error}',
  },
  screenshots: {
    search: 'Поиск скриншотов…',
    noMatch: 'Нет подходящих скриншотов',
    empty: 'Скриншотов нет',
    type: 'Скриншот',
  },
  resourcepacks: {
    search: 'Поиск ресурспаков…',
    noMatch: 'Нет подходящих ресурспаков',
    empty: 'Ресурспаков нет',
    type: 'Ресурспак',
    install: 'Установить ресурспак',
    loadFailed: 'Не удалось загрузить ресурспаки: {error}',
  },
  shaderpacks: {
    search: 'Поиск шейдерпаков…',
    noMatch: 'Нет подходящих шейдерпаков',
    empty: 'Шейдерпаков нет',
    type: 'Шейдерпак',
    install: 'Установить шейдерпак',
    loadFailed: 'Не удалось загрузить шейдерпаки: {error}',
  },
  datapacks: {
    search: 'Поиск датапаков…',
    noMatch: 'Нет подходящих датапаков',
    empty: 'Датапаков нет',
    type: 'Датапак',
    install: 'Установить датапак',
  },
  schematics: {
    search: 'Поиск схем…',
    noMatch: 'Подходящих схем нет',
    empty: 'Схем пока нет (импортируйте или поместите файлы в папку schematics)',
    type: 'схема',
    import: 'Импортировать схему',
    imported: 'Импортировано: {name}',
    importFailed: 'Ошибка импорта',
    deleteFailed: 'Ошибка удаления',
    renamed: 'Переименовано в {name}',
    renameFailed: 'Ошибка переименования',
    renameTitle: 'Переименовать схему',
    renamePlaceholder: 'Новое имя файла',
    preview: 'Просмотр',
    rename: 'Переименовать',
    delete: 'Удалить',
    previewTitle: 'Просмотр: {name}',
    parsing: 'Разбор схемы…',
    buildingPreview: 'Построение 3D-просмотра…',
    overCap: 'Слишком много блоков — переключено в режим списка материалов',
    overCapHint: 'Слишком много блоков для 3D-отображения',
    largeSize: 'Большая схема ({count} блоков), отрисовка может быть медленной',
    totalBlocks: '{count} блоков',
    byAuthor: 'Автор: {author}',
    materialsOnly: 'только материалы',
    missingBlocks: '{count} блоков без текстур (показаны как камень)',
    materials: 'Материалы ({count})',
    copy: 'Копировать список материалов',
    minY: 'Нижний слой',
    maxY: 'Верхний слой',
    mouseSensitivity: 'Чувствительность мыши',
    moveSpeed: 'Скорость движения',
    controlsHint: 'ЛКМ: панорама · СКМ: вращение · Колесо: масштаб · WASD: движение',
  },
  mods: {
    management: 'Управление модами',
    noModsHint: 'Этот экземпляр не поддерживает моды, требуется загрузчик, например Forge, Fabric',
    search: 'Поиск модов…',
    checkUpdates: 'Проверить обновления',
    install: 'Установить мод',
    fetchingRemoteInfo: 'Получение удалённой информации (id Matches Modrinth/CurseForge, иконка, русское название)…',
    readingMods: 'Чтение информации о модах',
    loadFailed: 'Не удалось загрузить список модов: {error}',
    noMatch: 'Нет подходящих модов',
    empty: 'Модов нет',
    enable: 'Включить',
    disable: 'Отключить',
    updateMods: 'Обновить моды',
    filterAll: 'Все',
    updatable: 'Доступны обновления',
    duplicate: 'Дубликат',
    sortNameAsc: 'Имя А-Я',
    sortNameDesc: 'Имя Я-А',
    sortTimeDesc: 'Сначала новые',
    sortTimeAsc: 'Сначала старые',
    sortSizeDesc: 'Сначала большие',
    sortSizeAsc: 'Сначала маленькие',
    batchEnable: 'Включить все',
    batchDisable: 'Отключить все',
    batchDelete: 'Удалить выбранные',
    batchConfirm: '{action} мод(ы) ({count})?',
    moveToRecycleBin: 'Будут перемещены в корзину.',
    processing: 'Обработка…',
    checkingUpdates: 'Проверка обновлений модов…',
    foundUpdates: 'Обновлений доступно: {count}',
    addedToDownload: 'Добавлено в список загрузки: {count} задач',
    updatedCount: 'Обновлено модов: {count}',
    updateResult: 'Успешно: {success}, не удалось: {failed}{failures}',
    updateFailed: 'Ошибка обновления модов',
    loadFailedGeneric: 'Ошибка загрузки: {error}',
    unknownError: 'Неизвестная ошибка',
  },
  servers: {
    search: 'Поиск серверов…',
    pingAll: 'Проверить все',
    addServer: 'Добавить сервер',
    edit: 'Изменить',
    ping: 'Проверка',
    copyIp: 'Копировать IP',
    quickJoin: 'Быстрое подключение',
    delete: 'Удалить',
    online: 'Онлайн',
    offline: 'Офлайн',
    pinging: 'Проверка…',
    lanGames: 'Игры в локальной сети ({count})',
    lanGame: 'Игра в локальной сети',
    join: 'Присоединиться',
    deleteConfirm: 'Удалить сервер «{ip}»?',
    deleteTitle: 'Удалить сервер',
    addTitle: 'Добавить сервер',
    editTitle: 'Изменить сервер',
    name: 'Название сервера',
    address: 'Адрес сервера',
    updating: 'Обновление…',
    adding: 'Добавление…',
    save: 'Сохранить',
    add: 'Добавить',
    copiedIp: 'IP-адрес скопирован',
    copyFailed: 'Ошибка копирования',
    pingDone: 'Проверка завершена: {ping} мс',
    addressOffline: '{address} офлайн',
    pingFailed: 'Ошибка проверки',
    deleted: 'Сервер удалён',
    deleteFailed: 'Ошибка удаления',
    updated: '«{name}» обновлён',
    added: '«{name}» добавлен',
    opFailed: 'Ошибка операции',
    loadFailed: 'Не удалось загрузить список серверов',
    empty: 'Серверов нет',
    noMatch: 'Подходящих серверов не найдено',
  },
  overview: {
    launch: 'Запуск',
    unpin: 'Открепить',
    pin: 'Закрепить на главной',
    gameVersion: 'Версия игры',
    loader: 'Загрузчик',
    pureVanilla: 'Чистая ваниль',
    lastPlayed: 'Последняя игра',
    totalPlayTime: 'Общее время игры',
    modpackInfo: 'Информация о модпаке',
    modpackName: 'Название модпака',
    version: 'Версия',
    author: 'Автор',
    summary: 'Описание',
    quickActions: 'Быстрые действия',
    defaultAccount: 'Аккаунт по умолчанию',
    launchGame: 'Запустить игру',
    instanceSettings: 'Настройки экземпляра',
    verifyIntegrity: 'Проверить целостность ресурсов',
    repairing: 'Дозаполнение {progress}%',
    openGameDir: 'Открыть игровой каталог',
    exportModpack: 'Экспортировать модпак',
    deleteInstance: 'Удалить экземпляр',
    refresh: 'Обновить',
  },
  settingsTab: {
    instanceName: 'Название экземпляра',
    instanceIcon: 'Иконка экземпляра',
    gameVersion: 'Версия игры',
    javaRuntime: 'Среда выполнения Java',
    autoSelect: 'Автовыбор',
    integrity: 'Целостность ресурсов',
    checkIntegrity: 'Проверить целостность ресурсов',
    repairing: 'Дозаполнение {progress}%',
    missingFiles: 'Отсутствующих файлов: {count}',
    autoRepairing: 'Автодозаполнение…',
    integrityOk: 'Ресурсы целы',
    versionIsolation: 'Изоляция версий',
    followGlobal: 'Следовать глобальным настройкам',
    on: 'Вкл',
    off: 'Выкл',
    isolationDesc: 'Каждая версия использует отдельные каталоги mods/config/saves',
    skipIntegrity: 'Пропустить проверку целостности ресурсов',
    skipIntegrityDesc: 'При запуске проверка целостности файлов пропускается; при отсутствии файлов игра может вылететь',
    memoryAllocation: 'Выделение памяти',
    auto: 'Авто',
    custom: 'Вручную',
    totalMem: 'Всего памяти: {size} ГиБ',
    usedMem: 'Используется: {size} ГиБ',
    gameAlloc: 'Выделено игре: {size} ГиБ',
    remainingMem: 'Осталось: {size} ГиБ',
    jvmArgs: 'Аргументы JVM',
    linkedAccount: 'Связанный аккаунт',
    unlinked: 'Не связан',
    saving: 'Сохранение…',
  },
  gamesettings: {
    search: 'Поиск параметров…',
    noMatch: 'Нет подходящих параметров',
    empty: 'Нет настроек игры',
    pressKey: 'Нажмите клавишу…',
    add: 'Добавить',
    addPlaceholder: 'Введите имя…',
    remove: 'Удалить',
    keys: {
      unbound: 'Не назначено',
      space: 'Пробел',
      enter: 'Enter',
      backspace: 'Backspace',
      leftShift: 'Левый Shift',
      rightShift: 'Правый Shift',
      leftControl: 'Левый Ctrl',
      rightControl: 'Правый Ctrl',
      leftAlt: 'Левый Alt',
      rightAlt: 'Правый Alt',
      leftSuper: 'Левый Win',
      rightSuper: 'Правый Win',
      menu: 'Клавиша меню',
      mouseLeft: 'Левая кнопка мыши',
      mouseRight: 'Правая кнопка мыши',
      mouseMiddle: 'Средняя кнопка мыши',
      mouseButton: 'Кнопка мыши {n}',
      keypad: 'Цифровая клавиатура {n}',
      keypadAdd: 'Цифр. клавиатура +',
      keypadSubtract: 'Цифр. клавиатура -',
      keypadMultiply: 'Цифр. клавиатура *',
      keypadDivide: 'Цифр. клавиатура /',
      keypadDecimal: 'Цифр. клавиатура .',
      keypadEnter: 'Цифр. клавиатура Enter',
    },
  },
  launch: {
    launchFailed: 'Ошибка запуска',
    instanceRunningConfirm: 'Этот экземпляр уже запущен. Запустить новый экземпляр?',
    instanceRunningTitle: 'Экземпляр запущен',
    backToList: 'Вернуться к списку экземпляров',
    instanceNotFound: 'Экземпляр не найден',
    loadingInstance: 'Загрузка экземпляра…',
    deleteInstanceConfirm: 'Удалить экземпляр «{name}»? Его папка версии будет удалена навсегда.',
  },
} as const