// Плагины (ru-RU)
export default {
  notFound: 'Плагин не найден',
  notActivated: 'Плагин не активирован',
  installTitle: 'Установить плагин',
  permissionsRequest: 'Этот плагин запрашивает следующие разрешения:',
  highRisk: 'Высокий риск',
  caution: 'Требует внимания',
  normal: 'Обычное',
  cancel: 'Отмена',
  confirmInstall: 'Подтвердить установку',
  fileAuthRequest: 'Плагин «{pluginId}» запрашивает доступ к пути:\n{path}\n\nРазрешить?',
  fileAuthDenied: 'Пользователь отклонил авторизацию доступа к файлам',
  fileAuthFailed: 'Ошибка авторизации',
  permission: {
    instanceRead: 'Чтение списка экземпляров',
    instanceWrite: 'Создание/изменение/удаление экземпляров',
    accountRead: 'Чтение списка аккаунтов',
    licenseRead: 'Чтение информации о лицензии',
    configRead: 'Чтение конфигурации лаунчера',
    configWrite: 'Изменение конфигурации лаунчера',
    cacheAccess: 'Чтение и запись кэша плагинов',
    endpointDiscover: 'Получение API-эндпоинтов бэкенда',
    pageList: 'Получение списка страниц',
    networkFetch: 'Отправка HTTP-запросов',
    networkCorsProxy: 'CORS-прокси запросов',
    networkWebsocket: 'WebSocket-подключения',
    networkProxy: 'Изменение прокси-настроек',
    uiInjectSidebar: 'Внедрение в меню боковой панели',
    uiInjectSettings: 'Внедрение в страницу настроек',
    uiPictureInPicture: 'Окно «картинка в картинке»',
    uiSubWindow: 'Отдельное дочернее окно',
    uiContextMenu: 'Внедрение контекстного меню',
    uiToast: 'Уведомления в приложении',
    uiNavigate: 'Переход между страницами',
    systemInfo: 'Чтение системной информации и данных лаунчера',
    systemNotification: 'Отправка системных уведомлений',
    clipboardRead: 'Чтение буфера обмена',
    clipboardWrite: 'Запись в буфер обмена',
    wasmExecute: 'Выполнение WASM-модулей',
    pluginInstall: 'Установка/удаление/обновление плагинов',
    pluginList: 'Чтение списка установленных плагинов',
    resourceRead: 'Чтение файлов игровых ресурсов',
    resourceWrite: 'Запись файлов игровых ресурсов',
    javaManage: 'Управление средой выполнения Java',
    downloadManage: 'Управление задачами загрузки',
    gameProcess: 'Запуск и остановка игрового процесса',
    gameLog: 'Отслеживание журнала игры',
    connectorHost: 'Запуск/остановка сетевой игры',
    connectorScan: 'Сканирование локальной сети для сетевой игры',
    shellExecute: 'Выполнение системных команд',
    filesystemRead: 'Чтение файловой системы',
    filesystemWrite: 'Запись в файловую систему',
  },
} as const