// Ресурсный центр (ru-RU)
export default {
  sources: {
    all: 'Все',
  },
  categories: {
    mod: 'Моды',
    modpack: 'Модпаки',
    shader: 'Шейдеры',
    resourcepack: 'Ресурспаки',
    datapack: 'Датапаки',
    save: 'Миры',
  },
  sort: {
    relevance: 'По релевантности',
    downloads: 'По скачиваниям',
    updated: 'По обновлению',
    newest: 'Новые',
    name: 'По имени',
    recommended: 'Рекомендуемое',
    installs: 'По установкам',
  },
  unknownAuthor: 'Неизвестный автор',
  install: 'Установить',
  viewDetail: 'Подробнее',
  originalSite: 'Оригинальный сайт',
  searchFailed: 'Ошибка поиска',
  backendUnreachable: 'Не удалось подключиться к бэкенду, убедитесь, что он запущен',
  title: 'Ресурсный центр',
  sourceLabel: 'Источник',
  categoryLabel: 'Категория',
  searchPlaceholder: 'Поиск {category}…',
  search: 'Поиск',
  gameVersionLabel: 'Версия игры',
  allVersions: 'Все версии',
  loaderLabel: 'Загрузчик',
  allLoaders: 'Все загрузчики',
  notFound: 'Ресурсы не найдены',
  notFoundHint: 'Попробуйте изменить ключевые слова, источник или категорию',
  retry: 'Повторить',
  loading: 'Загрузка…',
  loadMore: 'Загрузить ещё ({current}/{total})',
  allShown: 'Показаны все результаты: {count}',
} as const