// Детали ресурса (ru-RU)
export default {
  prereqMods: 'Требуемые моды',
  basedOn: 'Разобрано на основе {version}',
  parsingPrereq: 'Разбор требуемых модов…',
  noPrereq: 'У этой версии нет требуемых модов',
  addedToDownload: 'Добавлено в список загрузки',
  downloadFailed: 'Ошибка загрузки',
  exportFailed: 'Ошибка экспорта',
  loadDetailFailed: 'Не удалось загрузить детали ресурса',
  loadVersionsTimeout: 'Тайм-аут загрузки списка версий',
  loadVersionsFailed: 'Не удалось загрузить список версий',
  title: 'Детали ресурса',
  refresh: 'Обновить',
  originalPage: 'Исходная страница',
  loadFailed: 'Ошибка загрузки',
  notFound: 'Ресурс не найден',
  latest: 'Последняя {version}',
  noDescription: 'Нет описания',
  translating: 'Перевод…',
  collapseTranslation: 'Скрыть перевод',
  translateDescription: 'Перевести описание',
  translatedMark: 'пер.',
  unknownAuthor: 'Неизвестный автор',
  categoryTags: 'Теги категорий',
  detailedIntro: 'Подробное описание',
  showOriginal: 'Показать оригинал',
  translateBody: 'Перевести описание',
  expand: 'Развернуть',
  collapse: 'Свернуть',
  noMoreContent: 'Больше описания нет',
  selectVersionInstall: 'Выберите версию для установки',
  gameVersion: 'Версия игры',
  allVersions: 'Все версии',
  loader: 'Загрузчик',
  allLoaders: 'Все загрузчики',
  fetchingVersions: 'Получение списка версий',
  versionCount: 'Всего версий: {count}',
  filteredCount: 'После фильтра: {count}',
  noVersionUnderFilter: 'Нет доступных версий при текущем фильтре',
  install: 'Установить',
  saveAs: 'Сохранить как',
  // #162 сохранения мира: распаковка в saves/<имя>/; при совпадении — переименование.
  saveNameConflict: 'Сохранение с именем «{name}» уже существует',
  saveNameConflictHint: 'Выберите другое имя для карты, чтобы не перезаписать существующий мир.',
  saveNameTitle: 'Назовите карту',
  saveNamePlaceholder: 'Имя сохранения',
  loading: 'Загрузка…',
  getDownload: 'Получить загрузку',
  mcmod: 'MCWiki',
  copyName: 'Копировать название ресурса',
  copyNameFailed: 'Не удалось скопировать',
  noDownload: 'Нет загрузок',
  loadMore: 'Загрузить ещё ({count})',
} as const