// Ресурсный центр (ru-RU)
export default {
  sources: {
    all: 'Агрегация',
  },
  categories: {
    aggregate: 'Агрегация',
    mod: 'Моды',
    modpack: 'Модпаки',
    shader: 'Шейдеры',
    resourcepack: 'Ресурспаки',
    datapack: 'Датапаки',
    save: 'Миры',
  },
  sort: {
    relevance: 'По релевантности',
    downloads: 'По скачиваниям',
    updated: 'По обновлению',
    newest: 'Новые',
    name: 'По имени',
    recommended: 'Рекомендуемое',
    installs: 'По установкам',
  },
  unknownAuthor: 'Неизвестный автор',
  install: 'Установить',
  viewDetail: 'Подробнее',
  searchFailed: 'Ошибка поиска',
  backendUnreachable: 'Не удалось подключиться к бэкенду, убедитесь, что он запущен',
  title: 'Ресурсный центр',
  sourceLabel: 'Источник',
  categoryLabel: 'Категория',
  searchPlaceholder: 'Поиск {category}…',
  search: 'Поиск',
  gameVersionLabel: 'Версия игры',
  allVersions: 'Все версии',
  loaderLabel: 'Загрузчик',
  allLoaders: 'Все загрузчики',
  sortLabel: 'Сортировка',
  categoryFilterLabel: 'Фильтр категорий',
  clearFilter: 'Очистить фильтр',
  expandTags: 'Показать все',
  collapseTags: 'Свернуть',
  expandFilters: 'Показать фильтры',
  collapseFilters: 'Скрыть фильтры',
  notFound: 'Ресурсы не найдены',
  notFoundHint: 'Попробуйте изменить ключевые слова, источник или категорию',
  retry: 'Повторить',
  loading: 'Загрузка…',
  loadMore: 'Загрузить ещё ({current}/{total})',
  allShown: 'Показаны все результаты: {count}',
  mode: {
    searchPlaceholder: 'Поиск ресурсов, ключевых слов…',
  },
  favorites: {
    viewSearch: 'Поиск',
    viewLabel: 'Избранное',
    viewLabelWithCount: 'Избранное ({count})',
    searchPlaceholder: 'Поиск в избранном…',
    add: 'В избранное',
    remove: 'Убрать из избранного',
    added: 'Добавлено в избранное',
    removed: 'Удалено из избранного',
    failed: 'Не удалось изменить избранное',
    loadFailed: 'Не удалось загрузить избранное',
    emptyTitle: 'Избранного пока нет',
    emptyHint: 'Нажмите ♥ в результатах поиска или на странице ресурса',
    filteredEmpty: 'Нет избранного, соответствующего текущим фильтрам',
    filteredEmptyHint: 'Переключите источник / категорию выше или фильтры папок и тегов слева',
    allShown: 'Всего в избранном: {count}',
    folders: {
      railTitle: 'Папки',
      all: 'Все',
      unfiled: 'Без папки',
      loading: 'Загрузка…',
      create: 'Новая папка',
      createPlaceholder: 'Название папки',
      rename: 'Переименовать',
      renamePlaceholder: 'Название папки',
      emptyName: 'Название папки не может быть пустым',
      created: 'Папка «{name}» создана',
      renamed: 'Папка переименована',
      failed: 'Не удалось выполнить действие с папкой',
      delete: 'Удалить',
      deleteTitle: 'Удалить папку',
      deleteBodyWithItems:
        '{count} элементов избранного из папки «{name}» будут исключены из неё (само избранное сохранится). Отменить это нельзя.',
      deleteBodyEmpty: 'В папке «{name}» нет избранного. После удаления отменить его нельзя.',
      deleted: 'Папка удалена ({count} элементов избранного исключено)',
    },
    note: {
      label: 'Заметка',
      placeholder: 'Например, назначение и требования к версии',
    },
    tags: {
      label: 'Теги',
      filterLabel: 'Фильтр по тегам',
      placeholder: 'Введите тег и нажмите Enter',
      remove: 'Удалить тег «{tag}»',
      hint: 'Enter или запятая для добавления, не более {max}',
      limitReached: 'Достигнут предел: {max}',
    },
    edit: {
      open: 'Изменить избранное',
      title: 'Изменить избранное',
      folderLabel: 'Папки',
      noFolders: 'Папок пока нет — сначала создайте её в меню папок.',
      folderHintNone: 'Папка не выбрана — элемент попадёт в «Без папки».',
      folderHintCount: 'Выбрано папок: {count}.',
      cancel: 'Отмена',
      save: 'Сохранить',
      saving: 'Сохранение…',
      saved: 'Сохранено',
      failed: 'Не удалось сохранить',
    },
  },
} as const