// Процесс запуска/работы (ru-RU)
export default {
  gameCrashed: 'Игра вылетела',
  gameCrashTitle: 'Вылет игры',
  launchFailedTitle: 'Ошибка запуска',
  gameExitedAbnormally: 'Игра завершилась аварийно (код: {code})',
  launchError: 'При запуске произошла ошибка',
  analysisUnavailable: 'Сервис анализа временно недоступен',
  gameExited: 'Игра завершена',
  gameStarted: 'Игра запущена',
  preparingLaunch: 'Подготовка к запуску…',
  javaIncompatibleTitle: 'Несовместимая версия Java',
  javaIncompatible: 'Текущая Java {current} не соответствует требованиям Minecraft {game} (нужна Java {required}). Продолжить запуск?',
  launchCancelled: 'Запуск отменён',
  gameStopped: 'Игра остановлена',
  timeSeconds: '{count} с',
  timeMinutes: '{count} мин {sec} с',
  timeHours: '{hours} ч {mins} мин',
  instancesRunning: 'Экземпляров запущено: {count}',
  noRunningGame: 'Нет запущенных игр',
  goToInstances: 'Перейти к экземплярам',
  title: 'Запущенные игры',
  runningFor: 'Работает {time}',
} as const