// Страница настроек (ru-RU; пакет 0: навигация category + основные элементы appearance, остальное дополняется миграционными пакетами)
export default {
  category: {
    launcher: 'Лаунчер',
    java: 'Среда выполнения Java',
    plugins: 'Плагины',
    appearance: 'Внешний вид',
    toolbox: 'Инструменты',
    logs: 'Журналы',
    about: 'О программе',
    debug: 'Отладка',
  },
  saved: 'Настройки сохранены',
  appearance: {
    title: 'Интерфейс',
    language: 'Язык интерфейса',
    followSystem: 'Как в системе',
    theme: 'Тема',
    dark: 'Тёмная',
    light: 'Светлая',
    animations: 'Анимации страниц',
    animationsDesc: 'При включении переходы между страницами, диалоги и т.д. получают плавные анимации',
    animationSpeed: 'Скорость анимации',
    slow: 'Медленно',
    normal: 'Обычно',
    fast: 'Быстро',
    maxFrameRate: 'Предел частоты кадров',
    maxFrameRateUnlimited: 'Без ограничения',
    maxFrameRateDesc: 'Ограничивает частоту кадров интерфейса лаунчера, снижая нагрузку на ресурсы. Без ограничения используется родная частота обновления монитора.',
    cornerRadius: 'Скругление углов',
    windowCorners: 'Скругление углов окна',
    windowCornersDesc: 'Применяется только при отключении системной рамки',
    cornerSharp: 'Прямые углы',
    cornerDefault: 'По умолчанию (8px)',
    cornerLarge: 'Большое скругление',
    font: 'Шрифт',
    fontFamily: 'Шрифт интерфейса',
    fontDefault: 'Шрифт по умолчанию',
    fontDesc: 'Выберите установленный в системе шрифт, применяется ко всему интерфейсу сразу',
    fontPreviewTitle: 'Предпросмотр шрифта',
    fontPreviewText: 'Qomicex Launcher — Пример 123 ABC',
    fontReset: 'Восстановить шрифт по умолчанию',
    background: 'Фон',
    backgroundImage: 'Изображение фона',
    noBackgrounds: 'Нет изображений фона',
    openFolder: 'Открыть папку',
    backgroundsHint: 'Поместите изображения, и они появятся в списке выше',
    backgroundRandom: 'Случайный выбор при каждом запуске',
    backgroundRandomDesc: 'Случайно выбирать одно изображение из папки фонов',
    clearBackground: 'Очистить фон',
    opacity: 'Непрозрачность',
    transparent: 'Прозрачный',
    opaque: 'Непрозрачный',
    blur: 'Размытие',
    sharp: 'Чётко',
    watermark: 'Водяной знак',
    watermarkEnabled: 'Показывать текст водяного знака на главной',
    watermarkEnabledDesc: 'Показывать настраиваемый текст в центре главной страницы',
    watermarkText: 'Содержимое водяного знака',
    watermarkSubtext: 'Подзаголовок',
    watermarkSubtextPlaceholder: 'Лаунчер',
  },
  launcher: {
    title: 'Настройки лаунчера',
    dataDir: 'Каталог данных',
    dataDirDesc: 'Место хранения данных лаунчера; после изменения требуется перезапуск лаунчера',
    dataDirChanged: 'Каталог данных изменён, вступит в силу после перезапуска лаунчера',
    saveFailed: 'Ошибка настройки',
    downloadThreads: 'Потоков загрузки',
    downloadThreadsDesc: 'Количество одновременно загружаемых файлов (1-512): чем больше, тем быстрее, но выше расход трафика',
    fileChunkThreads: 'Потоков на фрагмент файла',
    fileChunkThreadsDesc: 'Потоков загрузки фрагментов одного файла (0=по умолчанию, максимум 16): чем больше, тем быстрее загрузка одного файла',
    maxConnections: 'Максимум соединений',
    maxConnectionsDesc: 'Максимум соединений с каждым сервером (8-256), вступает в силу после перезапуска',
    versionIsolation: 'Изоляция версий',
    versionIsolationDesc: 'Каждая версия использует отдельные каталоги mods/config/saves, рекомендуется оставить включённой',
    closeAfterLaunch: 'Закрывать лаунчер после запуска игры',
    closeAfterLaunchDesc: 'Автоматически закрывать лаунчер после запуска игры',
    autoReportErrors: 'Автоматически отправлять журналы серьёзных ошибок',
    autoReportErrorsDesc: 'При серьёзной ошибке, например вылете лаунчера, автоматически отправляются журналы ошибок и сведения об устройстве (система/оборудование) для диагностики; обычные ошибки запуска и установки не отправляются',
    downloadSource: 'Источник загрузки',
    downloadSourceName: { 0: 'Официальный источник', 1: 'Зеркало BMCLAPI' },
    modSource: 'Источник ресурсов',
    modSourceName: { 0: 'Официальный Modrinth/CurseForge', 1: 'Зеркало MCIM' },
    refreshLatency: 'Обновить задержку',
    autoSelectDownloadSource: 'Автовыбор самого быстрого источника загрузки',
    autoSelectDownloadSourceDesc: 'При запуске и перед каждой установкой автоматически определять и выбирать источник с наименьшей задержкой',
    autoSelectModSource: 'Автовыбор самого быстрого источника ресурсов',
    autoSelectModSourceDesc: 'Автоматически определять зеркало API Modrinth/CurseForge и выбирать с наименьшей задержкой',
    translationProvider: 'Сервис перевода',
    translationDefault: 'MyMemory (по умолчанию)',
    translationGoogle: 'Google Translate (нужен прокси)',
    translationProviderDesc: 'Сервис перевода, используемый при переводе подробного описания и введения ресурсов',
    bingApiKeyPlaceholder: 'Введите Azure Translator API Key',
    bingApiKeyDesc: 'Создайте ресурс Translator в Azure Portal для получения Key, регион должен быть global',
    downloadTimeout: 'Тайм-аут загрузки (сек)',
    downloadTimeoutDesc: 'Если отдельный файл не отвечает дольше этого времени, загрузка автоматически повторяется (0=без тайм-аута, 1-120 сек)',
    logLevelLabel: 'Уровень журнала',
    logLevel: { error: 'Ошибка', warn: 'Предупреждение', info: 'Информация', debug: 'Отладка', trace: 'Трассировка' },
    logLevelDesc: 'Управляет детальностью вывода в консоль и файлы журнала, по умолчанию — информационный уровень',
    storageCache: 'Хранилище и кэш',
    versionListCache: 'Кэш списка версий',
    versionListCacheDesc: 'Очистить HTML-файлы кэша списка версий Forge',
    clearCache: 'Очистить кэш',
    curseforgeConcurrency: 'Параллельность списка версий CurseForge',
    curseforgeConcurrencyDesc: 'Количество одновременно загружаемых страниц (1-20): чем больше, тем быстрее загружается список версий',
    curseforgeTtl: 'Срок кэша списка версий CurseForge (сек)',
    curseforgeTtlDesc: '0 = постоянный кэш (до перезапуска или ручной очистки), по умолчанию 300 сек (5 минут)',
    curseforgeCache: 'Кэш версий CurseForge',
    curseforgeCacheDesc: 'Очистить кэш в памяти списка версий CurseForge',
    clearCurseforgeCache: 'Очистить кэш версий CurseForge',
    cacheCleared: 'Кэш очищен, удалено файлов: {count}',
    cacheClearFailed: 'Ошибка очистки кэша',
    curseforgeCacheCleared: 'Кэш версий CurseForge очищен',
    curseforgeCacheClearFailed: 'Ошибка очистки кэша CurseForge',
  },
  java: {
    title: 'Среда выполнения Java',
    ready: 'Готово',
    detected: 'Обнаружена',
    available: 'Доступна',
    quickScan: 'Быстрое сканирование',
    deepScan: 'Глубокое сканирование',
    manualAdd: 'Добавить вручную',
    downloadJava: 'Скачать Java',
    refreshList: 'Обновить список',
    scanningQuick: 'Быстрое сканирование…',
    scanningDeep: 'Глубокое сканирование…',
    scanDoneFound: 'Сканирование завершено, найдено новых: {count}',
    scanDoneNone: 'Сканирование завершено, новых нет',
    scanFailed: 'Ошибка сканирования',
    refreshing: 'Обновление…',
    scanningRuntime: 'Сканирование сред выполнения Java…',
    noRuntimeDetected: 'Среды выполнения Java не обнаружены',
    noRuntimeHint: 'Нажмите «Быстрое сканирование», чтобы автоматически найти Java в системе, или добавьте вручную',
    startScan: 'Начать сканирование',
    usable: 'Доступна',
    unusable: 'Недоступна',
    openFolder: 'Открыть папку',
    availableCount: 'Доступно: {valid} / {total}',
    defaultConfig: 'Конфигурация по умолчанию',
    defaultRuntime: 'Среда Java по умолчанию',
    autoSelect: 'Автовыбор',
    defaultRuntimeDesc: 'Рекомендуется автовыбор: лаунчер автоматически подберёт лучшую среду Java для каждой версии игры',
    memoryAllocation: 'Выделение памяти',
    memoryAuto: 'Авто',
    memoryCustom: 'Вручную',
    totalMemory: 'Всего памяти: {value} ГиБ',
    usedMemory: 'Используется: {value} ГиБ',
    gameMemory: 'Выделено игре: {value} ГиБ',
    remainingMemory: 'Осталось: {value} ГиБ',
    jvmArgs: 'Дополнительные аргументы JVM',
    jvmArgsDesc: 'Аргументы JVM, добавляемые при запуске Minecraft',
    pickJavaExecutable: 'Выберите исполняемый файл Java',
    unrecognizedPath: 'Не удалось распознать среду Java по этому пути',
    added: 'Добавлена: {name} {version}',
    loadCatalogFailed: 'Не удалось загрузить каталог загрузки Java',
    addedToDownload: 'Добавлено в центр загрузок: {name}',
    downloadFailed: 'Не удалось запустить загрузку Java',
    deleteConfirm: 'Удалить «{name}»?',
    deleteTitle: 'Удалить Java',
    deleted: 'Удалена: {name}',
    deleteFailed: 'Ошибка удаления',
    manualAddTitle: 'Добавить Java вручную',
    executablePath: 'Путь к исполняемому файлу Java',
    browse: 'Обзор',
    executablePathDesc: 'Выберите или введите полный путь к исполняемому файлу Java',
    verifying: 'Проверка…',
    add: 'Добавить',
    distribution: 'Дистрибутив',
    recommended: '(рекомендуется)',
    mainVersion: 'Основная версия Java',
    platform: 'Платформа',
    architecture: 'Архитектура',
    targetDir: 'Целевой каталог',
    resolving: 'Разрешение…',
    startDownload: 'Начать загрузку',
  },
  plugins: {
    title: 'Управление плагинами',
    installedCount: 'Установлено: {count}',
    searchPlaceholder: 'Поиск плагинов…',
    installing: 'Установка…',
    install: 'Установить плагин',
    noneInstalled: 'Плагины не установлены',
    noMatch: 'Нет подходящих плагинов',
    changesApplied: 'Изменения применены',
    saveFailed: 'Ошибка сохранения',
    uninstallConfirm: 'Удалить этот плагин?',
    uninstalled: 'Плагин удалён',
    uninstallFailed: 'Ошибка удаления',
    installSuccess: 'Плагин установлен',
    installFailed: 'Ошибка установки: {message}',
    permissions: 'Разрешения ({count})',
    contributes: 'Точки расширения',
  },
  about: {
    aboutApp: 'О программе {name}',
    beta: 'Бета-версия',
    stable: 'Стабильная версия',
    feedback: 'Обратная связь',
    viewRepository: 'Открыть репозиторий',
    versionInfo: 'Информация о версии',
    appVersion: 'Версия приложения',
    versionHash: 'Хэш версии',
    os: 'Операционная система',
    architecture: 'Архитектура системы',
    memory: 'Память',
    license: 'Лицензия',
    licenseActivated: 'Активирована',
    licenseNotActivated: 'Не активирована',
    licenseInvalid: 'Недействительна',
    channel: 'Канал',
    expiry: 'Срок действия',
    permanent: 'Бессрочная',
    machineCode: 'Машинный код',
    changeLicense: 'Сменить лицензию',
    activateLicense: 'Активировать лицензию',
    copyMachineCode: 'Копировать машинный код',
    update: 'Обновить',
    checking: 'Проверка…',
    checkUpdate: 'Проверить обновления',
    upToDate: 'Установлена последняя версия',
    checkUpdateFailed: 'Ошибка проверки обновлений',
    developers: 'Разработчики',
    acknowledgements: 'Благодарности',
    referenceProjects: 'Справочные проекты',
    backendDependencies: 'Зависимости бэкенда',
    frontendDependencies: 'Зависимости фронтенда',
    openSourceLicense: 'Лицензия с открытым исходным кодом',
    licenseNotice: 'Эта программа опубликована по лицензии с открытым исходным кодом {name}',
    viewLicense: 'Просмотреть лицензию',
    copyrightPrivacy: 'Авторские права и конфиденциальность',
    copyrightStatement: 'Уведомление об авторских правах',
    copyrightStatementDesc: 'Просмотр сведений о правообладателе и лицензии с открытым исходным кодом этого ПО',
    userAgreement: 'Пользовательское соглашение',
    privacyPolicy: 'Политика конфиденциальности',
    appDescription: 'Современный лаунчер Minecraft с поддержкой управления несколькими версиями, совместимости с загрузчиками модов, управления аккаунтами и других функций.',
    roleProjectLead: 'Автор проекта / основной разработчик',
    serviceModrinth: 'API поиска модов и ресурсов',
    serviceModpack: 'API модпаков',
    serviceBmclapi: 'Сервис зеркала загрузки BMCLAPI',
    serviceMcmod: 'База данных китайских модов',
    serviceMinecraft: 'Официальный сайт Minecraft, поддержка лицензий!',
    serviceMinecraftName: 'Официальный сайт Minecraft',
    refVersionCheck: 'Справочник по проверке версий',
    refModloaderInstaller: 'Справочник по установщику ModLoader',
    refLaunchFlow: 'Справочник по процессу запуска',
    depBackendRuntime: 'Среда выполнения бэкенда Rust',
    depCoreLibraries: 'Основные библиотеки',
    depCoreFramework: 'Основной фреймворк',
    depUiComponents: 'UI-компоненты',
    depStylesTools: 'Стили и инструменты',
    depAnimation: 'Анимации',
    depRendering: 'Отрисовка и отображение',
    depInHouse: 'Собственная разработка',
  },
} as const