// Страница настроек (ru-RU; пакет 0: навигация category + основные элементы appearance, остальное дополняется миграционными пакетами)
export default {
  category: {
    launcher: 'Лаунчер',
    basic: 'Базовые',
    launch: 'Запуск',
    download: 'Загрузка',
    storage: 'Хранилище и кэш',
    network: 'Сеть',
    java: 'Среда выполнения Java',
    plugins: 'Плагины',
    appearance: 'Внешний вид',
    toolbox: 'Инструменты',
    logs: 'Журналы',
    about: 'О программе',
    debug: 'Отладка',
  },
  saved: 'Настройки сохранены',
  appearance: {
    title: 'Интерфейс',
    language: 'Язык интерфейса',
    followSystem: 'Как в системе',
    theme: 'Тема',
    dark: 'Тёмная',
    light: 'Светлая',
    themeColor: 'Акцентный цвет',
    themeColorCustom: 'Произвольный цвет',
    themeColorBackground: 'По фону (Monet)',
    themeColorReset: 'Сбросить',
    themeColorDesc: 'Глобальный акцентный цвет для кнопок, подсветки и выделения. По умолчанию используется стандартный цвет лаунчера.',
    componentMaterial: 'Материал',
    componentMaterialDefault: 'Стандарт',
    componentMaterialFrosted: 'Матовое стекло',
    componentMaterialAcrylic: 'Акриловое стекло',
    componentMaterialAero: 'Aero',
    componentMaterialLiquid: 'Жидкое стекло',
    componentMaterialLiquidPreview: 'Жидкое стекло (предпросмотр)',
    componentMaterialLiquidWarning: 'Функция в предпросмотре: жидкое стекло выполняет рефракцию со смещением для каждой карточки в реальном времени — высокая нагрузка; длинные списки (например, много модов) могут подтормаживать или зависать.',
    componentMaterialLiquidConfirmTitle: 'Включить жидкое стекло?',
    componentMaterialLiquidConfirmBody: 'Жидкое стекло — функция в предпросмотре с высокой нагрузкой; длинные списки (например, много модов) могут подтормаживать или зависать. Всё равно включить?',
    glassBlurLow: 'Чётко',
    glassBlurHigh: 'Размыто',
    animations: 'Анимации страниц',
    animationsDesc: 'При включении переходы между страницами, диалоги и т.д. получают плавные анимации',
    animationSpeed: 'Скорость анимации',
    slow: 'Медленно',
    normal: 'Обычно',
    fast: 'Быстро',
    maxFrameRate: 'Предел частоты кадров',
    maxFrameRateUnlimited: 'Без ограничения',
    maxFrameRateDesc: 'Ограничивает частоту кадров интерфейса лаунчера, снижая нагрузку на ресурсы. Без ограничения используется родная частота обновления монитора.',
    cornerRadius: 'Скругление углов',
    windowCorners: 'Скругление углов окна',
    windowCornersDesc: 'Применяется только при отключении системной рамки',
    cornerSharp: 'Прямые углы',
    cornerDefault: 'По умолчанию (8px)',
    cornerLarge: 'Большое скругление',
    font: 'Шрифт',
    fontFamily: 'Шрифт интерфейса',
    fontDefault: 'Шрифт по умолчанию',
    fontDesc: 'Выберите установленный в системе шрифт, применяется ко всему интерфейсу сразу',
    fontPreviewTitle: 'Предпросмотр шрифта',
    fontPreviewText: 'Qomicex Launcher — Пример 123 ABC',
    fontReset: 'Восстановить шрифт по умолчанию',
    background: 'Фон',
    backgroundImage: 'Изображение фона',
    noBackgrounds: 'Нет изображений фона',
    openFolder: 'Открыть папку',
    backgroundsHint: 'Поместите изображения, и они появятся в списке выше',
    backgroundRandom: 'Случайный выбор при каждом запуске',
    backgroundRandomDesc: 'Случайно выбирать одно изображение из папки фонов',
    clearBackground: 'Очистить фон',
    opacity: 'Непрозрачность',
    transparent: 'Прозрачный',
    opaque: 'Непрозрачный',
    blur: 'Размытие',
    sharp: 'Чётко',
    watermark: 'Водяной знак',
    watermarkEnabled: 'Показывать текст водяного знака на главной',
    watermarkEnabledDesc: 'Показывать настраиваемый текст в центре главной страницы',
    watermarkText: 'Содержимое водяного знака',
    watermarkSubtext: 'Подзаголовок',
    watermarkSubtextPlaceholder: 'Лаунчер',
  },
  launcher: {
    title: 'Настройки лаунчера',
    dataDir: 'Каталог данных',
    dataDirDesc: 'Место хранения данных лаунчера; после изменения требуется перезапуск лаунчера',
    dataDirChanged: 'Каталог данных изменён, вступит в силу после перезапуска лаунчера',
    saveFailed: 'Ошибка настройки',
    downloadThreads: 'Потоков загрузки',
    downloadThreadsDesc: 'Количество одновременно загружаемых файлов (1-512): чем больше, тем быстрее, но выше расход трафика',
    fileChunkThreads: 'Потоков на фрагмент файла',
    fileChunkThreadsDesc: 'Количество параллельных фрагментов одного файла: выкл = без разделения, авто = по умолчанию, или вручную 1-16',
    fileChunkThreadsOff: 'Выкл',
    fileChunkThreadsAuto: 'Авто',
    versionIsolation: 'Изоляция версий',
    versionIsolationDesc: 'Каждая версия использует отдельные каталоги mods/config/saves, рекомендуется оставить включённой',
    closeAfterLaunch: 'Закрывать лаунчер после запуска игры',
    closeAfterLaunchDesc: 'Автоматически закрывать лаунчер после запуска игры',
    autoReportErrors: 'Автоматически отправлять журналы серьёзных ошибок',
    autoReportErrorsDesc: 'При серьёзной ошибке, например вылете лаунчера, автоматически отправляются журналы ошибок и сведения об устройстве (система/оборудование) для диагностики; обычные ошибки запуска и установки не отправляются',
    downloadSource: 'Источник загрузки',
    downloadSourceName: { 0: 'Официальный источник', 1: 'Зеркало BMCLAPI' },
    modSource: 'Источник ресурсов',
    modSourceName: { 0: 'Официальный Modrinth/CurseForge', 1: 'Зеркало MCIM' },
    resourceDownloadSource: 'Источник загрузки файлов',
    resourceDownloadSourceName: { 0: 'Официальный', 1: 'QML Mirror', 2: 'QML Mirror HK' },
    resourceDownloadSourceDesc: 'CDN для скачивания файлов модов: официальный — исходный CDN, QML Mirror — зеркало QML.',
    autoSelectFileDownloadSource: 'Автовыбор источника загрузки',
    autoSelectFileDownloadSourceDesc: 'Автоматически выбирать самый быстрый доступный источник',
    refreshLatency: 'Обновить задержку',
    autoSelectDownloadSource: 'Автовыбор самого быстрого источника загрузки',
    autoSelectDownloadSourceDesc: 'При запуске и перед каждой установкой автоматически определять и выбирать источник с наименьшей задержкой',
    autoSelectModSource: 'Автовыбор самого быстрого источника ресурсов',
    autoSelectModSourceDesc: 'Автоматически определять зеркало API Modrinth/CurseForge и выбирать с наименьшей задержкой',
    translationProvider: 'Сервис перевода',
    translationDefault: 'MyMemory (по умолчанию)',
    translationGoogle: 'Google Translate',
    translationProviderDesc: 'Сервис перевода, используемый при переводе подробного описания и введения ресурсов',
    bingApiKeyPlaceholder: 'Введите Azure Translator API Key',
    bingApiKeyDesc: 'Создайте ресурс Translator в Azure Portal для получения Key, регион должен быть global',
    downloadTimeout: 'Тайм-аут загрузки (сек)',
    downloadTimeoutDesc: 'Если отдельный файл не отвечает дольше этого времени, загрузка автоматически повторяется (0=без тайм-аута, 1-120 сек)',
    enableHttp3: 'Включить загрузку через HTTP/3 (экспериментально)',
    enableHttp3Desc: 'При включении загрузки предпочитают HTTP/3 и автоматически откатываются на HTTP/2, если сервер не поддерживает его; при отключении используется только HTTP/2',
    http1Parallel: 'Параллельные HTTP/1.1 соединения',
    http1ParallelDesc: 'Скачивайте каждый файл по отдельному TCP-соединению. Значительно ускоряет загрузку на CDN с ограничением на соединение (напр. Modrinth/CurseForge). Отключите, чтобы вернуться к мультиплексированию HTTP/2.',
    logLevelLabel: 'Уровень журнала',
    logLevel: { error: 'Ошибка', warn: 'Предупреждение', info: 'Информация', debug: 'Отладка', trace: 'Трассировка' },
    logLevelDesc: 'Управляет детальностью вывода в консоль и файлы журнала, по умолчанию — информационный уровень',
    storageCache: 'Хранилище и кэш',
    versionListCache: 'Кэш списка версий',
    versionListCacheDesc: 'Очистить HTML-файлы кэша списка версий Forge',
    clearCache: 'Очистить кэш',
    curseforgeConcurrency: 'Параллельность списка версий CurseForge',
    curseforgeConcurrencyDesc: 'Количество одновременно загружаемых страниц (1-20): чем больше, тем быстрее загружается список версий',
    curseforgeTtl: 'Срок кэша списка версий CurseForge (сек)',
    curseforgeTtlDesc: '0 = постоянный кэш (до перезапуска или ручной очистки), по умолчанию 300 сек (5 минут)',
    curseforgeCache: 'Кэш версий CurseForge',
    curseforgeCacheDesc: 'Очистить кэш в памяти списка версий CurseForge',
    clearCurseforgeCache: 'Очистить кэш версий CurseForge',
    cacheCleared: 'Кэш очищен, удалено файлов: {count}',
    cacheClearFailed: 'Ошибка очистки кэша',
    curseforgeCacheCleared: 'Кэш версий CurseForge очищен',
    curseforgeCacheClearFailed: 'Ошибка очистки кэша CurseForge',
  },
  network: {
    title: 'Сеть',
    proxy: 'Прокси',
    proxyMode: 'Тип прокси',
    proxyOff: 'Без прокси',
    proxySystem: 'Использовать системный прокси',
    http: 'HTTP(S) прокси',
    socks5: 'SOCKS5 прокси',
    proxyModeDesc: 'Настройка прокси-сервера для загрузок и запросов ресурсов',
    proxyHost: 'Адрес прокси-сервера',
    proxyHostPlaceholder: 'например 127.0.0.1:7890',
    proxyHostDesc: 'Формат: host:port; применяется только при выборе HTTP(S) или SOCKS5 прокси',
    ignoreSslCert: 'Игнорировать проверку SSL-сертификата',
    ignoreSslCertDesc: 'Не проверять TLS-сертификат при загрузке (для самоподписанных сертификатов / внутренних прокси; используйте с осторожностью)',
  },
  java: {
    title: 'Среда выполнения Java',
    ready: 'Готово',
    detected: 'Обнаружена',
    available: 'Доступна',
    quickScan: 'Быстрое сканирование',
    deepScan: 'Глубокое сканирование',
    manualAdd: 'Добавить вручную',
    downloadJava: 'Скачать Java',
    refreshList: 'Обновить список',
    scanningQuick: 'Быстрое сканирование…',
    scanningDeep: 'Глубокое сканирование…',
    scanDoneFound: 'Сканирование завершено, найдено новых: {count}',
    scanDoneNone: 'Сканирование завершено, новых нет',
    scanFailed: 'Ошибка сканирования',
    refreshing: 'Обновление…',
    scanningRuntime: 'Сканирование сред выполнения Java…',
    noRuntimeDetected: 'Среды выполнения Java не обнаружены',
    noRuntimeHint: 'Нажмите «Быстрое сканирование», чтобы автоматически найти Java в системе, или добавьте вручную',
    startScan: 'Начать сканирование',
    usable: 'Доступна',
    unusable: 'Недоступна',
    openFolder: 'Открыть папку',
    availableCount: 'Доступно: {valid} / {total}',
    showInvalid: 'Показать недоступные',
    defaultConfig: 'Конфигурация по умолчанию',
    defaultRuntime: 'Среда Java по умолчанию',
    autoSelect: 'Автовыбор',
    defaultRuntimeDesc: 'Рекомендуется автовыбор: лаунчер автоматически подберёт лучшую среду Java для каждой версии игры',
    memoryAllocation: 'Выделение памяти',
    memoryAuto: 'Авто',
    memoryCustom: 'Вручную',
    totalMemory: 'Всего памяти: {value} ГиБ',
    usedMemory: 'Используется: {value} ГиБ',
    gameMemory: 'Выделено игре: {value} ГиБ',
    remainingMemory: 'Осталось: {value} ГиБ',
    jvmArgs: 'Дополнительные аргументы JVM',
    jvmArgsDesc: 'Аргументы JVM, добавляемые при запуске Minecraft',
    pickJavaExecutable: 'Выберите исполняемый файл Java',
    unrecognizedPath: 'Не удалось распознать среду Java по этому пути',
    added: 'Добавлена: {name} {version}',
    loadCatalogFailed: 'Не удалось загрузить каталог загрузки Java',
    addedToDownload: 'Добавлено в центр загрузок: {name}',
    downloadFailed: 'Не удалось запустить загрузку Java',
    deleteConfirm: 'Удалить «{name}»?',
    deleteTitle: 'Удалить Java',
    deleted: 'Удалена: {name}',
    deleteFailed: 'Ошибка удаления',
    manualAddTitle: 'Добавить Java вручную',
    executablePath: 'Путь к исполняемому файлу Java',
    browse: 'Обзор',
    executablePathDesc: 'Выберите или введите полный путь к исполняемому файлу Java',
    verifying: 'Проверка…',
    add: 'Добавить',
    distribution: 'Дистрибутив',
    recommended: '(рекомендуется)',
    mainVersion: 'Основная версия Java',
    platform: 'Платформа',
    architecture: 'Архитектура',
    targetDir: 'Целевой каталог',
    resolving: 'Разрешение…',
    startDownload: 'Начать загрузку',
  },
  plugins: {
    title: 'Управление плагинами',
    installedCount: 'Установлено: {count}',
    searchPlaceholder: 'Поиск плагинов…',
    installing: 'Установка…',
    install: 'Установить плагин',
    noneInstalled: 'Плагины не установлены',
    noMatch: 'Нет подходящих плагинов',
    changesApplied: 'Изменения применены',
    saveFailed: 'Ошибка сохранения',
    uninstallConfirm: 'Удалить этот плагин?',
    uninstalled: 'Плагин удалён',
    uninstallFailed: 'Ошибка удаления',
    installSuccess: 'Плагин установлен',
    installFailed: 'Ошибка установки: {message}',
    permissions: 'Разрешения ({count})',
    contributes: 'Точки расширения',
    store: {
      tabBrowse: 'Обзор',
      tabManage: 'Мои плагины',
      tabAccount: 'Аккаунт',
      searchPlaceholder: 'Поиск в магазине...',
      categoryAll: 'Все',
      categoryTool: 'Инструменты',
      categoryLauncher: 'Лаунчер',
      categoryTheme: 'Темы',
      categoryIntegration: 'Интеграции',
      sortLatest: 'Новейшие',
      sortDownloads: 'По загрузкам',
      downloadsCount: '{count} загрузок',
      loadFailed: 'Не удалось загрузить магазин плагинов',
      emptyResult: 'Подходящих плагинов нет',
      prevPage: 'Назад',
      nextPage: 'Вперёд',
      pageInfo: 'Стр. {page} / {total}',
      installedBadge: 'Установлен',
      updatableBadge: 'Обновление до v{version}',
      installBtn: 'Установить',
      updateBtn: 'Обновить',
      reinstallBtn: 'Переустановить',
      installConfirmTitle: 'Установка плагина',
      updateConfirmTitle: 'Обновление плагина',
      installConfirmDesc: 'Будет установлен «{name}» v{version}.',
      permissionsNotice: 'Этот плагин запрашивает следующие разрешения:',
      noPermissions: 'Этот плагин не запрашивает разрешений.',
      installing: 'Установка...',
      installSuccess: 'Плагин успешно установлен',
      installFailed: 'Ошибка установки: {message}',
      detailVersions: 'История версий',
      detailReviews: 'Отзывы ({count})',
      noReviews: 'Отзывов пока нет',
      developerLabel: 'Разработчик:',
      permissionsCount: '{count} разрешений',
      checkUpdates: 'Проверить обновления',
      checkingUpdates: 'Проверка...',
      allUpToDate: 'Все плагины актуальны',
      updatesAvailable: 'Доступно обновлений: {count}',
      rollbackBtn: 'Откатить',
      rollbackConfirm: 'Откатить "{name}" к предыдущей версии?',
      rollbackSuccess: 'Откат к предыдущей версии выполнен',
      rollbackFailed: 'Не удалось выполнить откат: {message}',
      localInstall: 'Локальная установка',
      deviceLoginDesc: 'Вход по коду устройства: пароль вводить не нужно, подтверждение происходит в браузере.',
      deviceStart: 'Начать вход',
      deviceCodeLabel: 'Код устройства',
      deviceCopy: 'Копировать',
      deviceCopied: 'Код скопирован',
      deviceCopyFailed: 'Не удалось скопировать, запишите код вручную',
      deviceOpenPage: 'Открыть страницу подтверждения',
      deviceSteps: 'Нажмите «Открыть страницу подтверждения» → войдите в магазин → введите код выше и подтвердите. После этого вход выполнится автоматически.',
      deviceWaiting: 'Ожидание подтверждения…',
      deviceExpired: 'Срок действия кода истёк, начните заново',
      deviceCancel: 'Отмена',
      loginSuccess: 'Вход выполнен',
      loggedOut: 'Вы вышли из аккаунта',
      logout: 'Выйти',
      roleUser: 'Пользователь',
      roleDeveloper: 'Разработчик',
      roleAdmin: 'Администратор',
      levelIndividual: 'Вериф. лично',
      levelOrganization: 'Вериф. организация',
      levelOfficial: 'Официальный',
      myPlugins: 'Мои плагины',
      myPluginsEmpty: 'Опубликованных плагинов пока нет',
    },
  },
  about: {
    aboutApp: 'О программе {name}',
    beta: 'Бета-версия',
    stable: 'Стабильная версия',
    feedback: 'Обратная связь',
    viewRepository: 'Открыть репозиторий',
    versionInfo: 'Информация о версии',
    appVersion: 'Версия приложения',
    versionHash: 'Хэш версии',
    os: 'Операционная система',
    architecture: 'Архитектура системы',
    memory: 'Память',
    license: 'Лицензия',
    licenseActivated: 'Активирована',
    licenseNotActivated: 'Не активирована',
    licenseInvalid: 'Недействительна',
    channel: 'Канал',
    expiry: 'Срок действия',
    permanent: 'Бессрочная',
    machineCode: 'Машинный код',
    changeLicense: 'Сменить лицензию',
    activateLicense: 'Активировать лицензию',
    copyMachineCode: 'Копировать машинный код',
    update: 'Обновить',
    checking: 'Проверка…',
    checkUpdate: 'Проверить обновления',
    upToDate: 'Установлена последняя версия',
    checkUpdateFailed: 'Ошибка проверки обновлений',
    developers: 'Разработчики',
    acknowledgements: 'Благодарности',
    referenceProjects: 'Справочные проекты',
    backendDependencies: 'Зависимости бэкенда',
    frontendDependencies: 'Зависимости фронтенда',
    openSourceLicense: 'Лицензия с открытым исходным кодом',
    licenseNotice: 'Эта программа опубликована по лицензии с открытым исходным кодом {name}',
    viewLicense: 'Просмотреть лицензию',
    copyrightPrivacy: 'Авторские права и конфиденциальность',
    copyrightStatement: 'Уведомление об авторских правах',
    copyrightStatementDesc: 'Просмотр сведений о правообладателе и лицензии с открытым исходным кодом этого ПО',
    userAgreement: 'Пользовательское соглашение',
    privacyPolicy: 'Политика конфиденциальности',
    appDescription: 'Современный лаунчер Minecraft с поддержкой управления несколькими версиями, совместимости с загрузчиками модов, управления аккаунтами и других функций.',
    roleProjectLead: 'Автор проекта / основной разработчик',
    serviceModrinth: 'API поиска модов и ресурсов',
    serviceModpack: 'API модпаков',
    serviceBmclapi: 'Сервис зеркала загрузки BMCLAPI',
    serviceMcmod: 'База данных китайских модов',
    serviceMinecraft: 'Официальный сайт Minecraft, поддержка лицензий!',
    serviceMinecraftName: 'Официальный сайт Minecraft',
    serviceModrinthName: 'Modrinth',
    serviceCurseForgeName: 'CurseForge',
    serviceFtbName: 'FTB',
    serviceBmclapiName: 'bangbang93',
    serviceMcmodName: 'mcmod',
    refVersionCheck: 'Справочник по проверке версий',
    refModloaderInstaller: 'Справочник по установщику ModLoader',
    refLaunchFlow: 'Справочник по процессу запуска',
    depBackendRuntime: 'Среда выполнения бэкенда Rust',
    depCoreLibraries: 'Основные библиотеки',
    depCoreFramework: 'Основной фреймворк',
    depUiComponents: 'UI-компоненты',
    depStylesTools: 'Стили и инструменты',
    depAnimation: 'Анимации',
    depRendering: 'Отрисовка и отображение',
    depInHouse: 'Собственная разработка',
  },
} as const