// Прочие инструменты/отладка/журналы/заставка (ru-RU)
export default {
  toolbox: {
    title: 'Загрузка пользовательских файлов',
    description: 'Скачать любой файл через лаунчер в указанную папку',
    urlLabel: 'Адрес загрузки (URL)',
    savePathLabel: 'Путь сохранения',
    autoFillPlaceholder: 'Будет заполнено автоматически после выбора папки',
    pickFolder: 'Выбрать папку',
    submitting: 'Отправка…',
    startDownload: 'Начать загрузку',
    startDownloadCount: 'Начать загрузку ({count})',
    urlHint: 'Одна ссылка на строку, поддерживается пакетное добавление',
    toastAdded: 'Добавлено задач загрузки: {count}',
    toastPartial: 'Успешно: {ok}, с ошибками: {failed}',
    invalidLines: 'Пропущено неверных строк: {count}',
    downloadFailed: 'Ошибка загрузки',
  },
  logs: {
    title: 'Управление журналами',
    loadFailed: 'Не удалось загрузить список журналов',
    exportedTo: 'Экспортировано в {dest}',
    downloadStarted: 'Загрузка начата',
    deleteConfirm: 'Удалить «{name}»?',
    deleteTitle: 'Удалить журнал',
    deleted: 'Удалено',
    deleteFailed: 'Ошибка удаления',
    openDirFailed: 'Не удалось открыть папку',
    openFailed: 'Не удалось открыть файл',
    exportAll: 'Экспортировать все',
    exportGz: 'Экспорт (.gz)',
    filesLabel: 'Файлы журналов',
    currentSession: 'Текущая сессия',
    none: 'Журналов нет',
    emptyDescription: 'Лаунчер и бэкенд создают файлы журналов во время работы',
    open: 'Открыть',
    openContainingDir: 'Открыть папку с файлом',
    retentionHint: 'Автоматически сохраняются последние 10 журналов, самые старые файлы удаляются',
    currentSessionSuffix: 'Записей текущей сессии: {count}',
    fileCountSuffix: 'Файлов: {count}',
    truncated: 'Сокращено (только последние 2 МБ)',
    searchPlaceholder: 'Поиск по журналу…',
    levelAll: 'Все уровни',
    levelError: 'Ошибка',
    levelWarn: 'Предупреждение',
    levelInfo: 'Информация',
    noMatch: 'Нет подходящих строк журнала',
    debugLogsCount: 'Журналы отладки ({count})',
  },
  debug: {
    liveLogs: 'Живой журнал',
    autoScroll: 'Автопрокрутка',
    clear: 'Очистить',
    exportLogs: 'Экспортировать журнал',
    triggerDump: 'Снять дамп',
    noLogs: 'Журналов нет…',
    diagnostics: 'Диагностика лаунчера',
    systemInfo: 'Системная информация',
    versionInfo: 'Информация о версии',
    connectivity: 'Состояние подключения',
    apiHealthCheck: 'Проверка работоспособности API',
    pathInfo: 'Информация о путях',
    toggleDisableAnimations: 'Отключить анимации',
    toggleShowComponentBoundaries: 'Показать границы компонентов',
    toggleSimulateApiErrors: 'Имитация ошибок API',
    toggleNetworkLogging: 'Журнал сетевых запросов',
    toggleDisableCaching: 'Отключить кэширование',
    toggleLogOverlay: 'Наложение журнала (глобально)',
    toggleShowFps: 'Отображение FPS (в правом верхнем углу)',
    togglesTitle: 'Переключатели отладки (временные, сбрасываются при перезапуске)',
    clearTasksConfirm: 'Очистить все задачи загрузки? Это действие необратимо.',
    clearTasksTitle: 'Очистить задачи загрузки',
    tasksCleared: 'Список задач загрузки очищен',
    dataManagement: 'Управление данными',
    downloadTaskList: 'Список задач загрузки',
    clearTasksDescription: 'Очистить записи о задачах загрузки в localStorage',
    clearTasksButton: 'Очистить список задач загрузки',
    dumpExported: 'Журнал экспортирован в: {path}',
  },
  splash: {
    preparing: 'Подготовка к запуску…',
    almostReady: 'Почти готово…',
  },
  analysis: {
    title: 'Результат анализа',
    pageTitle: 'Анализ журнала',
    inputTitle: 'Введите журнал Minecraft',
    pastePlaceholder: 'Вставьте содержимое журнала Minecraft…',
    analyzeButton: 'Анализировать журнал',
    analyzing: 'Анализ…',
    analyzeFailed: 'Ошибка анализа',
    gameVersion: 'Версия игры',
    modLoader: 'Загрузчик модов',
    noIssues: 'Явных проблем не обнаружено',
    criticalCount: 'Критических: {count}',
    errorCount: 'Ошибок: {count}',
    warningCount: 'Предупреждений: {count}',
    suggestedSolutions: 'Рекомендуемые решения',
    stackTrace: 'Куча вызовов',
    categoryMemory: 'Память',
    categoryModConflict: 'Конфликт модов',
    categoryJavaRelated: 'Связано с Java',
    categoryResource: 'Ресурсы',
    categoryPerformance: 'Производительность',
    categoryNetwork: 'Сеть',
  },
  errors: {
    pageRenderError: 'Ошибка отрисовки страницы',
  },
  notifier: {
    downloadCompleted: '{name} загружен',
  },
} as const