// 通用高频文案（en）
export default {
  ok: 'OK',
  cancel: 'Cancel',
  close: 'Close',
  save: 'Save',
  create: 'Create',
  delete: 'Delete',
  edit: 'Edit',
  confirm: 'Confirm',
  loading: 'Loading...',
  noData: 'No data',
  comingSoon: 'Coming soon',
  retry: 'Retry',
  refresh: 'Refresh',
  copy: 'Copy',
  copied: 'Copied',
  search: 'Search',
  select: 'Select',
  back: 'Back',
  next: 'Next',
  prev: 'Previous',
  unknown: 'Unknown',
  all: 'All',
  none: 'None',
  enabled: 'Enabled',
  disabled: 'Disabled',
  error: 'Error',
  warning: 'Warning',
  success: 'Success',
  failed: 'Failed',
  info: 'Info',
  input: 'Input',
  inputPlaceholder: 'Enter...',
  batchSelected: '{count} selected',
  selectAll: 'Select all',
  deselect: 'Clear selection',
  noMatch: 'No matches',
  pendingTasksCloseConfirm: 'There are unfinished tasks. Closing will delete all tasks.\n\nAre you sure you want to close?',
  language: 'Language',
  theme: 'Theme',
  dark: 'Dark',
  light: 'Light',
  externalLink: 'External link',
  seeMore: 'See more',
  goto: 'Go to',
  name: 'Name',
  version: 'Version',
  status: 'Status',
  action: 'Action',
  detail: 'Details',
  optional: 'Optional',
  javaRuntimeRequired: 'Launching Minecraft requires a Java runtime.\n\nYou can install Java quickly via Settings → Java → Download Java, or add an existing Java path manually.',
  javaRuntimeRequiredTitle: 'No Java runtime detected',
} as const
