// Dashboard (en)
export default {
  account: 'Account',
  noDefaultAccount: 'No default account set',
  defaultAccount: 'Default account',
  addInSettings: 'Add in settings',
  manageAccounts: 'Manage accounts',
  lastPlayed: 'Last played {date}',
  status: 'Status',
  ready: 'Ready',
  launch: 'Launch',
  noPinnedInstance: 'No pinned instance',
  goToInstances: 'Go to instances',
  editLayout: 'Edit layout',
  editMode: 'Edit mode: drag to arrange, drag bottom-right corner to resize',
  addWidget: 'Add widget',
  resetLayout: 'Reset layout',
  allWidgetsVisible: 'All widgets are visible',
  done: 'Done',
  widget: {
    watermark: 'Watermark',
    account: 'Account',
    instance: 'Default instance',
    launch: 'Launch',
    announcements: 'Announcements',
  },
} as const
