// Download center (en)
export default {
  status: {
    queued: 'Queued',
    downloading: 'Downloading',
    paused: 'Paused',
    completed: 'Completed',
    failed: 'Failed',
    cancelled: 'Cancelled',
  },
  stage: {
    queued: 'Queued',
    'downloading-json': 'Downloading version JSON',
    downloading: 'Downloading game files',
    'downloading-libraries': 'Downloading libraries',
    'downloading-assets': 'Downloading assets',
    'downloading-mainjar': 'Downloading main jar',
    'downloading-loader': 'Downloading loader',
    'downloading-loader-libs': 'Downloading loader libraries',
    'installing-loader': 'Installing loader',
    'downloading-addons': 'Downloading add-ons',
    'downloading-modpack': 'Downloading modpack',
    'parsing-modpack': 'Parsing modpack',
    'modpack-files': 'Downloading modpack files',
    'modpack-overrides': 'Extracting overrides',
  },
  filter: {
    all: 'All',
    downloading: 'Downloading',
    paused: 'Paused',
    completed: 'Completed',
    failed: 'Failed',
  },
  title: 'Download Center',
  subtitle: '{count} task(s)',
  clearFinished: 'Clear completed/failed',
  taskCount: '{count} task(s)',
  empty: 'No download tasks',
  emptyHint: 'Select a version on the Instances page to start downloading; tasks appear here',
  goToInstances: 'Go to instances',
  addonsCount: '+ {count} add-on(s)',
  createdAt: 'Created {date}',
  completedAt: 'Completed {date}',
  resume: 'Resume',
  pause: 'Pause',
  cancel: 'Cancel',
  retry: 'Retry',
  remove: 'Remove',
  statusText: {
    done: 'Download complete',
    failedWith: 'Failed: {error}',
    failed: 'Download failed',
    pausedProgress: 'Paused {progress}%',
    waiting: 'Waiting',
    downloading: 'Downloading',
    connecting: 'Connecting…',
  },
  filesCount: '{done}/{total} files',
  errors: {
    taskExpired: 'Task expired (backend restarted)',
    downloadFailed: 'Download failed',
    cannotVerify: 'Cannot connect to backend to verify task status',
    statusUnknown: 'Task status could not be confirmed (backend did not report this session)',
    taskInvalid: 'Task is no longer valid',
  },
} as const
