// Backend error messages (mapped from error codes on the frontend, en)
export default {
  notFound: 'Requested resource was not found',
  forbidden: 'You do not have permission to perform this action',
  badRequest: 'Invalid request parameters',
  internalError: 'Internal server error',
  upstreamError: 'Upstream service request failed',
  requestTimeout: 'Request timed out, please try again later',
  unknown: 'Request failed, please try again later',
  licenseNotFound: 'License is not activated',
  licenseDecryptFailed: 'License decryption failed',
  licenseSignatureInvalid: 'Invalid license signature',
  licensePublicKeyUnavailable: 'License public key unavailable',
  licenseExpired: 'License has expired',
  licenseRemoteCheckFailed: 'License remote verification failed',
  licenseIoError: 'Failed to read license file',
  tokenExpired: 'Login token expired, please sign in again',
  networkError:
    'Cannot reach the Microsoft authentication service. Check your network or launch in offline mode',
  mcApiError: 'Minecraft official API request failed',
  fsAuthRequired: 'Filesystem access not authorized',
  pluginMissingDependency: 'Plugin is missing required dependencies',
  connectorTimeout: 'Connection operation timed out, please check your network and retry',
  exportDiagnosticsFailed: 'Failed to export diagnostics report',
  modpackParseFailed: 'Failed to parse modpack',
  skinUploadFailed: 'Failed to upload skin',
  skinSaveFailed: 'Failed to save skin',
  skinResetFailed: 'Failed to reset skin',
  pluginSignatureMissing: 'Plugin package is missing signature. The developer needs to sign this package',
  pluginSignatureInvalid: 'Plugin package signature verification failed — the package may be tampered',
  pluginSignatureCertInvalid: 'Plugin signature certificate is invalid (root key verification failed)',
  pluginSignatureHashMismatch: 'Plugin package signature hash mismatch — the package may be tampered',
  noRollbackSnapshot: 'No rollback snapshot available for this plugin',
} as const
