// Resource detail (en)
export default {
  prereqMods: 'Prerequisite mods',
  basedOn: 'Resolved from {version}',
  parsingPrereq: 'Parsing prerequisite mods...',
  noPrereq: 'This version has no prerequisite mods',
  addedToDownload: 'Added to download list',
  downloadFailed: 'Download failed',
  exportFailed: 'Export failed',
  loadDetailFailed: 'Failed to load resource details',
  loadVersionsTimeout: 'Timed out loading version list',
  loadVersionsFailed: 'Failed to load version list',
  title: 'Resource Details',
  refresh: 'Refresh',
  originalPage: 'Original page',
  loadFailed: 'Load failed',
  notFound: 'Resource not found',
  latest: 'Latest {version}',
  noDescription: 'No description',
  translating: 'Translating...',
  collapseTranslation: 'Collapse translation',
  translateDescription: 'Translate description',
  translatedMark: 'Translated',
  unknownAuthor: 'Unknown author',
  categoryTags: 'Category tags',
  detailedIntro: 'Detailed introduction',
  showOriginal: 'Show original',
  translateBody: 'Translate introduction',
  expand: 'Expand',
  collapse: 'Collapse',
  noMoreContent: 'No more content',
  selectVersionInstall: 'Select version to install',
  gameVersion: 'Game version',
  allVersions: 'All versions',
  loader: 'Loader',
  allLoaders: 'All loaders',
  fetchingVersions: 'Fetching version list',
  versionCount: '{count} version(s)',
  filteredCount: '{count} after filter',
  noVersionUnderFilter: 'No available versions under current filters',
  install: 'Install',
  saveAs: 'Save as',
  loading: 'Loading...',
  getDownload: 'Get download',
  noDownload: 'No downloads',
  loadMore: 'Load more ({count})',
} as const
