// Resource center (en)
export default {
  categories: {
    mod: 'Mods',
    modpack: 'Modpacks',
    shader: 'Shaders',
    resourcepack: 'Resource Packs',
    datapack: 'Data Packs',
    save: 'Saves',
  },
  sort: {
    relevance: 'Relevance',
    downloads: 'Downloads',
    updated: 'Updated',
    newest: 'Newest',
    name: 'Name',
    recommended: 'Recommended',
    installs: 'Installs',
  },
  unknownAuthor: 'Unknown author',
  install: 'Install',
  viewDetail: 'View details',
  originalSite: 'Original site',
  searchFailed: 'Search failed',
  backendUnreachable: 'Cannot connect to backend service, please make sure it is running',
  title: 'Resource Center',
  sourceLabel: 'Source',
  categoryLabel: 'Category',
  searchPlaceholder: 'Search {category}...',
  search: 'Search',
  gameVersionLabel: 'Game version',
  allVersions: 'All versions',
  loaderLabel: 'Loader',
  allLoaders: 'All loaders',
  notFound: 'No resources found',
  notFoundHint: 'Try different keywords, source or category',
  retry: 'Retry',
  loading: 'Loading...',
  loadMore: 'Load more ({current}/{total})',
  allShown: 'All {count} results shown',
} as const
