// Accounts (en)
export default {
  loginErrors: {
    accessDenied: 'You cancelled or denied the authorization in the browser',
    expiredToken: 'The verification code has expired, please sign in again',
    invalidGrant: 'Authorization is invalid, please sign in again',
    loginFailed: 'Login failed: {code}',
  },
  methodLabel: {
    offline: 'Offline',
    thirdParty: 'Third-party',
    thirdPartyWith: 'Third-party/{server}',
    unified: 'Unified Pass',
  },
  dataCorrupted: 'Account data file is corrupted or the machine code changed. The file was deleted, please add the account again.',
  microsoft: {
    gettingInfo: 'Fetching sign-in info...',
    openingBrowser: 'Opening browser...',
    codeCopied: 'Verification code copied to clipboard. Sign in to your Microsoft account in the browser.\nCode: {code}',
    loginTimeout: 'Sign-in timed out, please try again',
    gettingAccount: 'Fetching account info...',
    loginSuccess: 'Signed in',
    noRole: 'No available role obtained',
    stepFetching: 'Fetching sign-in info',
    stepWaiting: 'Waiting for authorization',
    stepFetchingInfo: 'Fetching account info',
    codeCopiedShort: 'Code copied',
    browserOpened: 'Browser opened automatically',
    relogin: 'Sign in again',
  },
  deleteConfirm: 'Delete this account?',
  deleteTitle: 'Delete account',
  batchDeleteConfirm: 'Delete the selected {count} account(s)?',
  batchDeleteTitle: 'Batch delete',
  title: 'Account Management',
  refresh: 'Refresh',
  addAccount: 'Add account',
  add: 'Add',
  filterAll: 'All filters',
  filterName: 'Name',
  filterLoginMethod: 'Login method',
  filterServer: 'Server',
  searchPlaceholder: 'Search accounts...',
  noMatch: 'No matching accounts',
  noAccounts: 'No accounts',
  setDefault: 'Set as default',
  deleteSelected: 'Delete {count}',
  addTitle: 'Add Account',
  tabOffline: 'Offline',
  tabUnified: 'Unified',
  offline: {
    playerName: 'Player name',
    playerNamePlaceholder: 'Enter offline username',
    uuid: 'UUID (optional, auto-generated if empty)',
    uuidPlaceholder: 'e.g. 069a79f4-44e9-4726-a5be-fca90e38aaf5',
    add: 'Add offline account',
  },
  ygg: {
    presetServer: 'Preset server',
    email: 'Email',
    password: 'Password',
    customServerAddr: 'Custom server address',
    login: 'Sign in',
    loginLoading: 'Signing in...',
    saving: 'Saving...',
    chooseRole: 'Choose a role to sign in:',
    back: 'Back',
    confirmCount: 'Confirm ({count})',
  },
  unified: {
    desc: 'Unified Pass is an authentication system used by some Minecraft servers; a server ID is required.',
    serverId: 'Server ID',
    serverIdPlaceholder: 'e.g. lilu',
    email: 'Email',
    password: 'Password',
    login: 'Sign in',
    loginLoading: 'Signing in...',
    oauthLogin: 'Microsoft OAuth Sign-in',
  },
} as const
