// Deep link (qomicex-launcher://) prompts, issue #127
export default {
  launchNotFound: 'Instance not found: {target}',
  joinConfirmTitle: 'Join Room',
  joinConfirmDesc: 'A web page is requesting to join room {code}. Continue?',
  joinFailed: 'Could not join the room: {message}',
  installPluginConfirmTitle: 'Install Plugin',
  installPluginConfirmDesc: 'This request comes from {host} and will install the plugin {name}. Continue only if you trust this source.',
  installPluginSlugConfirmDesc: 'A web page is requesting to install the store plugin {slug}. Continue?',
  installModpackConfirmTitle: 'Install Modpack',
  installModpackConfirmDesc: 'A web page is requesting to install the modpack {name} (source: {source}). Continue?',
  installStarted: 'Installation started',
  installFailed: 'Installation failed: {message}',
  cancelled: 'Action cancelled',
  registerTitle: 'Associate Deep Links',
  registerDesc: 'Register the launcher as the handler for qomicex-launcher:// links? Once registered, websites and shortcuts can open the launcher directly.',
  registerSuccess: 'Deep link association enabled',
  registerFailed: 'Association failed. You can try again later in Settings.',
  registerDeclined: 'Skipped. You will not be asked again automatically.',
  launchAmbiguous: '{count} instances are all named "{target}", so it is not clear which one to launch. Please use the directory:instance-name form instead, for example {example}',
}
