// Backend error messages (mapped from error codes on the frontend, en)
export default {
  notFound: 'Requested resource was not found',
  forbidden: 'You do not have permission to perform this action',
  badRequest: 'Invalid request parameters',
  internalError: 'Internal server error',
  upstreamError: 'Upstream service request failed',
  requestTimeout: 'Request timed out, please try again later',
  unknown: 'Request failed, please try again later',
  licenseNotFound: 'Licence is not activated',
  licenseDecryptFailed: 'Licence decryption failed',
  licenseSignatureInvalid: 'Invalid licence signature',
  licensePublicKeyUnavailable: 'Licence public key unavailable',
  licenseExpired: 'Licence has expired',
  licenseRemoteCheckFailed: 'Licence remote verification failed',
  licenseIoError: 'Failed to read licence file',
  tokenExpired: 'Login token expired, please sign in again',
  mcApiError: 'Minecraft official API request failed',
  fsAuthRequired: 'Filesystem access not authorized',
  pluginMissingDependency: 'Plugin is missing required dependencies',
  connectorTimeout: 'Connection operation timed out, please check your network and retry',
  exportDiagnosticsFailed: 'Failed to export diagnostics report',
  modpackParseFailed: 'Failed to parse modpack',
  skinUploadFailed: 'Failed to upload skin',
  skinSaveFailed: 'Failed to save skin',
  skinResetFailed: 'Failed to reset skin',
} as const
