// Instance detail (en)
export default {
  tabs: {
    overview: 'Overview',
    settings: 'Settings',
    gamesettings: 'Game Settings',
    saves: 'Saves',
    screenshots: 'Screenshots',
    mods: 'Mods',
    resourcepacks: 'Resource Packs',
    shaderpacks: 'Shader Packs',
    datapacks: 'Data Packs',
    servers: 'Servers',
    schematics: 'Schematics',
  },
  confirm: {
    cancel: 'Cancel',
    deleting: 'Deleting...',
    delete: 'Delete',
    confirm: 'Confirm',
  },
  time: {
    minutes: '{count} min',
    hours: '{count} h',
    hoursMinutes: '{hours} h {minutes} min',
    never: 'Never',
    justNow: 'Just now',
    minutesAgo: '{count} min ago',
    hoursAgo: '{count} h ago',
  },
  openFolder: 'Open folder',
  loading: 'Loading...',
  noMatch: 'No matches',
  empty: 'Empty',
  deleteSelected: 'Delete {count}',
  batchDeleteTitle: 'Delete {type}',
  batchDeleteConfirm: 'Delete the selected {count} {type}? They will be moved to recycle bin.',
  saves: {
    search: 'Search saves...',
    noMatch: 'No matching saves',
    empty: 'No saves',
    type: 'saves',
  },
  saveSettings: {
    title: 'Save Settings',
    restoreFromOld: 'Restore from level.dat_old',
    restoreFromOldConfirm: 'This will overwrite the current level.dat with level.dat_old (the current content will be backed up as level.dat.qomicex.bak). Continue?',
    runningWarning: 'This instance is running; the game will overwrite your changes when it saves. Close the game first to edit safely.',
    sectionBasic: 'Basic info',
    sectionWeather: 'Weather & time',
    sectionSpawn: 'Spawn & trader',
    sectionBorder: 'World border',
    levelName: 'World name',
    gameType: 'Game mode',
    gameTypeSurvival: 'Survival',
    gameTypeCreative: 'Creative',
    gameTypeAdventure: 'Adventure',
    gameTypeSpectator: 'Spectator',
    difficulty: 'Difficulty',
    difficultyPeaceful: 'Peaceful',
    difficultyEasy: 'Easy',
    difficultyNormal: 'Normal',
    difficultyHard: 'Hard',
    allowCommands: 'Allow cheats',
    hardcore: 'Hardcore mode',
    difficultyLocked: 'Lock difficulty',
    time: 'World time (Time)',
    dayTime: 'Day time (DayTime)',
    raining: 'Raining',
    thundering: 'Thundering',
    clearWeatherTime: 'Clear weather time',
    rainTime: 'Rain time',
    thunderTime: 'Thunder time',
    spawnX: 'Spawn X',
    spawnY: 'Spawn Y',
    spawnZ: 'Spawn Z',
    randomSeed: 'World seed',
    wanderingTraderSpawnChance: 'Wandering trader chance',
    wanderingTraderSpawnDelay: 'Wandering trader delay',
    borderCenterX: 'Border center X',
    borderCenterZ: 'Border center Z',
    borderSize: 'Border size',
    borderSafeZone: 'Safe zone',
    borderDamagePerBlock: 'Damage per block outside',
    borderWarningBlocks: 'Warning distance',
    borderWarningTime: 'Warning time (s)',
    gameRules: 'Game rules',
    ruleKeepInventory: 'Keep inventory (keepInventory)',
    ruleDoDaylightCycle: 'Daylight cycle (doDaylightCycle)',
    ruleDoFireTick: 'Fire spread (doFireTick)',
    ruleMobGriefing: 'Mob griefing (mobGriefing)',
    ruleDoMobSpawning: 'Mob spawning (doMobSpawning)',
    ruleDoWeatherCycle: 'Weather cycle (doWeatherCycle)',
    ruleDoMobLoot: 'Mob loot (doMobLoot)',
    ruleDoTileDrops: 'Tile drops (doTileDrops)',
    ruleDoEntityDrops: 'Entity drops (doEntityDrops)',
    ruleDoNaturalRegeneration: 'Natural regeneration (doNaturalRegeneration)',
    ruleDoImmediateRespawn: 'Immediate respawn (doImmediateRespawn)',
    ruleDoInsomnia: 'Insomnia (doInsomnia)',
    ruleDoPatrolSpawning: 'Patrol spawning (doPatrolSpawning)',
    ruleDoTraderSpawning: 'Trader spawning (doTraderSpawning)',
    ruleDrowningDamage: 'Drowning damage (drowningDamage)',
    ruleFallDamage: 'Fall damage (fallDamage)',
    ruleFireDamage: 'Fire damage (fireDamage)',
    ruleFreezeDamage: 'Freeze damage (freezeDamage)',
    ruleShowDeathMessages: 'Show death messages (showDeathMessages)',
    ruleAnnounceAdvancements: 'Announce advancements (announceAdvancements)',
    ruleCommandBlockOutput: 'Command block output (commandBlockOutput)',
    ruleSendCommandFeedback: 'Command feedback (sendCommandFeedback)',
    ruleReducedDebugInfo: 'Reduced debug info (reducedDebugInfo)',
    ruleDisableElytraMovementCheck: 'Disable elytra movement check (disableElytraMovementCheck)',
    ruleSpectatorsGenerateChunks: 'Spectators generate chunks (spectatorsGenerateChunks)',
    ruleDoLimitedCrafting: 'Limited crafting (doLimitedCrafting)',
    ruleRandomTickSpeed: 'Random tick speed',
    ruleSpawnRadius: 'Spawn radius',
    ruleMaxEntityCramming: 'Entity cramming',
    save: 'Save',
    saving: 'Saving...',
    saved: 'Save settings saved',
    loadFailed: 'Failed to load save settings: {error}',
    saveFailed: 'Failed to save save settings: {error}',
    restored: 'Restored from level.dat_old',
    restoreFailed: 'Restore failed: {error}',
  },
  screenshots: {
    search: 'Search screenshots...',
    noMatch: 'No matching screenshots',
    empty: 'No screenshots',
    type: 'screenshots',
  },
  resourcepacks: {
    search: 'Search resource packs...',
    noMatch: 'No matching resource packs',
    empty: 'No resource packs',
    type: 'resource packs',
    install: 'Install resource pack',
    loadFailed: 'Failed to load resource packs: {error}',
  },
  shaderpacks: {
    search: 'Search shader packs...',
    noMatch: 'No matching shader packs',
    empty: 'No shader packs',
    type: 'shader packs',
    install: 'Install shader pack',
    loadFailed: 'Failed to load shader packs: {error}',
  },
  datapacks: {
    search: 'Search data packs...',
    noMatch: 'No matching data packs',
    empty: 'No data packs',
    type: 'data packs',
    install: 'Install data pack',
  },
  schematics: {
    search: 'Search schematics...',
    noMatch: 'No matching schematics',
    empty: 'No schematics yet (import one, or drop files into the schematics folder)',
    type: 'schematic',
    import: 'Import schematic',
    imported: 'Imported {name}',
    importFailed: 'Import failed',
    deleteFailed: 'Delete failed',
    renamed: 'Renamed to {name}',
    renameFailed: 'Rename failed',
    renameTitle: 'Rename schematic',
    renamePlaceholder: 'New file name',
    preview: 'Preview',
    rename: 'Rename',
    delete: 'Delete',
    previewTitle: 'Preview {name}',
    parsing: 'Parsing schematic...',
    buildingPreview: 'Building 3D preview...',
    overCap: 'Too many blocks — degraded to material list mode',
    overCapHint: 'Too many blocks to render in 3D',
    largeSize: 'Large schematic ({count} blocks), rendering may be slow',
    totalBlocks: '{count} blocks',
    byAuthor: 'by {author}',
    materialsOnly: 'materials only',
    missingBlocks: '{count} blocks missing textures (shown as stone)',
    materials: 'Materials ({count})',
    copy: 'Copy material list',
    minY: 'Min layer',
    maxY: 'Max layer',
    controlsHint: 'Left drag: pan · Middle drag: rotate · Wheel: zoom · WASD: move',
  },
  mods: {
    management: 'Mod Management',
    noModsHint: 'This instance cannot use mods; a loader such as Forge or Fabric is required',
    search: 'Search mods...',
    checkUpdates: 'Check updates',
    install: 'Install Mod',
    fetchingRemoteInfo: 'Fetching remote info (Modrinth/CurseForge id, icon, name)...',
    readingMods: 'Reading mod info',
    loadFailed: 'Failed to load mod list: {error}',
    noMatch: 'No matching mods',
    empty: 'No mods',
    enable: 'Enable',
    disable: 'Disable',
    updateMods: 'Update mods',
    filterAll: 'All',
    updatable: 'Updatable',
    duplicate: 'Duplicate',
    sortNameAsc: 'Name A-Z',
    sortNameDesc: 'Name Z-A',
    sortTimeDesc: 'Newest first',
    sortTimeAsc: 'Oldest first',
    sortSizeDesc: 'Largest first',
    sortSizeAsc: 'Smallest first',
    batchEnable: 'Enable selected',
    batchDisable: 'Disable selected',
    batchDelete: 'Delete selected',
    batchConfirm: 'Confirm to {action} {count} mod(s)?',
    moveToRecycleBin: 'They will be moved to recycle bin.',
    processing: 'Processing...',
    checkingUpdates: 'Checking for mod updates…',
    foundUpdates: 'Found {count} mods with updates',
    addedToDownload: 'Added {count} task(s) to download list',
    updatedCount: 'Updated {count} mods',
    updateResult: '{success} done, {failed} failed{failures}',
    updateFailed: 'Failed to update mods',
    loadFailedGeneric: 'Failed to load: {error}',
    unknownError: 'Unknown error',
  },
  servers: {
    search: 'Search servers...',
    pingAll: 'Ping all',
    addServer: 'Add server',
    edit: 'Edit',
    ping: 'Ping',
    copyIp: 'Copy IP',
    quickJoin: 'Quick join',
    delete: 'Delete',
    online: 'Online',
    offline: 'Offline',
    pinging: 'Pinging...',
    lanGames: 'LAN games ({count})',
    lanGame: 'LAN game',
    join: 'Join',
    deleteConfirm: 'Delete server "{ip}"?',
    deleteTitle: 'Delete Server',
    addTitle: 'Add Server',
    editTitle: 'Edit Server',
    name: 'Server name',
    address: 'Server address',
    updating: 'Updating...',
    adding: 'Adding...',
    save: 'Save',
    add: 'Add',
    copiedIp: 'IP address copied',
    copyFailed: 'Copy failed',
    pingDone: 'Ping: {ping}ms',
    addressOffline: '{address} is offline',
    pingFailed: 'Ping failed',
    deleted: 'Server deleted',
    deleteFailed: 'Delete failed',
    updated: 'Updated "{name}"',
    added: 'Added "{name}"',
    opFailed: 'Operation failed',
    loadFailed: 'Failed to load server list',
  },
  overview: {
    launch: 'Launch',
    unpin: 'Unpin',
    pin: 'Pin to home',
    gameVersion: 'Game version',
    loader: 'Loader',
    pureVanilla: 'Pure vanilla',
    lastPlayed: 'Last played',
    totalPlayTime: 'Total play time',
    modpackInfo: 'Modpack info',
    modpackName: 'Modpack name',
    version: 'Version',
    author: 'Author',
    summary: 'Summary',
    quickActions: 'Quick actions',
    defaultAccount: 'Default account',
    launchGame: 'Launch Game',
    instanceSettings: 'Instance settings',
    verifyIntegrity: 'Verify file integrity',
    repairing: 'Repairing {progress}%',
    openGameDir: 'Open game directory',
    exportModpack: 'Export Modpack',
    deleteInstance: 'Delete instance',
    refresh: 'Refresh',
  },
  settingsTab: {
    instanceName: 'Instance name',
    instanceIcon: 'Instance icon',
    gameVersion: 'Game version',
    javaRuntime: 'Java runtime',
    autoSelect: 'Auto select',
    integrity: 'File integrity',
    checkIntegrity: 'Check file integrity',
    repairing: 'Repairing {progress}%',
    missingFiles: '{count} missing file(s)',
    autoRepairing: 'Auto repairing...',
    integrityOk: 'Files complete',
    versionIsolation: 'Version isolation',
    followGlobal: 'Follow global setting',
    on: 'On',
    off: 'Off',
    isolationDesc: 'Each version uses separate mods/config/saves directories',
    skipIntegrity: 'Skip file integrity check',
    skipIntegrityDesc: 'Skips file integrity check at launch; may crash if files are missing',
    memoryAllocation: 'Memory allocation',
    auto: 'Auto',
    custom: 'Custom',
    totalMem: 'Total memory {size} GiB',
    usedMem: 'Used {size} GiB',
    gameAlloc: 'Game allocation {size} GiB',
    remainingMem: 'Remaining {size} GiB',
    jvmArgs: 'JVM arguments',
    linkedAccount: 'Linked account',
    unlinked: 'Not linked',
    saving: 'Saving...',
  },
  gamesettings: {
    search: 'Search settings...',
    noMatch: 'No matching settings',
    empty: 'No game settings',
    pressKey: 'Press a key...',
    add: 'Add',
    addPlaceholder: 'Enter name…',
    remove: 'Remove',
    keys: {
      unbound: 'Unbound',
      space: 'Space',
      enter: 'Enter',
      backspace: 'Backspace',
      leftShift: 'Left Shift',
      rightShift: 'Right Shift',
      leftControl: 'Left Ctrl',
      rightControl: 'Right Ctrl',
      leftAlt: 'Left Alt',
      rightAlt: 'Right Alt',
      leftSuper: 'Left Win',
      rightSuper: 'Right Win',
      menu: 'Menu',
      mouseLeft: 'Left Mouse',
      mouseRight: 'Right Mouse',
      mouseMiddle: 'Middle Mouse',
      mouseButton: 'Mouse Button {n}',
      keypad: 'Numpad {n}',
      keypadAdd: 'Numpad +',
      keypadSubtract: 'Numpad -',
      keypadMultiply: 'Numpad *',
      keypadDivide: 'Numpad /',
      keypadDecimal: 'Numpad .',
      keypadEnter: 'Numpad Enter',
    },
  },
  launch: {
    launchFailed: 'Launch failed',
    instanceRunningConfirm: 'This instance is already running. Launch a new instance?',
    instanceRunningTitle: 'Instance running',
    backToList: 'Back to instances',
    instanceNotFound: 'Instance not found',
    loadingInstance: 'Loading instance...',
    deleteInstanceConfirm: 'Delete instance "{name}"? Its version folder will be permanently removed.',
  },
} as const
