// Plugins (en)
export default {
  notFound: 'Plugin not found',
  notActivated: 'Plugin not activated',
  webviewPlaceholder: 'This plugin has been opened in a separate window',
  webviewFocus: 'Focus window',
  installTitle: 'Install Plugin',
  permissionsRequest: 'This plugin requests the following permissions:',
  highRisk: 'High risk',
  caution: 'Caution',
  normal: 'Normal',
  cancel: 'Cancel',
  confirmInstall: 'Confirm Install',
  fileAuthRequest: 'Plugin "{pluginId}" requests access to path:\n{path}\n\nAllow?',
  fileAuthDenied: 'File access authorization was denied by user',
  fileAuthFailed: 'Authorization failed',
  permission: {
    instanceRead: 'Read instance list',
    instanceWrite: 'Create/Modify/Delete instances',
    accountRead: 'Read account list',
    licenseRead: 'Read licence info',
    configRead: 'Read launcher config',
    configWrite: 'Modify launcher config',
    cacheAccess: 'Read/write plugin cache',
    endpointDiscover: 'Get backend API endpoints',
    pageList: 'Get page list',
    networkFetch: 'Send HTTP requests',
    networkCorsProxy: 'CORS proxy requests',
    networkWebsocket: 'WebSocket connections',
    networkProxy: 'Modify proxy settings',
    uiInjectSidebar: 'Inject sidebar menu',
    uiInjectSettings: 'Inject settings page',
    uiPictureInPicture: 'Picture-in-picture window',
    uiSubWindow: 'Standalone sub-window',
    uiContextMenu: 'Inject context menu',
    uiToast: 'In-app notifications',
    uiNavigate: 'Navigate pages',
    systemInfo: 'Read system and launcher info',
    systemNotification: 'Send system notifications',
    clipboardRead: 'Read clipboard',
    clipboardWrite: 'Write clipboard',
    wasmExecute: 'Execute WASM modules',
    pluginInstall: 'Install/Uninstall/Update plugins',
    pluginList: 'Read installed plugin list',
    pluginLog: 'Write plugin logs (for debugging)',
    resourceRead: 'Read game resource files',
    resourceWrite: 'Write game resource files',
    javaManage: 'Manage Java runtimes',
    downloadManage: 'Manage download tasks',
    gameProcess: 'Start/stop game processes',
    gameLog: 'Read game logs',
    connectorHost: 'Start/stop multiplayer',
    connectorScan: 'Scan LAN multiplayer',
    shellExecute: 'Execute system commands',
    filesystemRead: 'Read filesystem',
    filesystemWrite: 'Write filesystem',
  },
} as const
