// Resource center (en)
export default {
  sources: {
    all: 'Aggregate',
  },
  categories: {
    aggregate: 'Aggregate',
    mod: 'Mods',
    modpack: 'Modpacks',
    shader: 'Shaders',
    resourcepack: 'Resource Packs',
    datapack: 'Data Packs',
    save: 'Saves',
  },
  sort: {
    relevance: 'Relevance',
    downloads: 'Downloads',
    updated: 'Updated',
    newest: 'Newest',
    name: 'Name',
    recommended: 'Recommended',
    installs: 'Installs',
  },
  unknownAuthor: 'Unknown author',
  install: 'Install',
  viewDetail: 'View details',
  searchFailed: 'Search failed',
  backendUnreachable: 'Cannot connect to backend service, please make sure it is running',
  title: 'Resource Centre',
  sourceLabel: 'Source',
  categoryLabel: 'Category',
  searchPlaceholder: 'Search {category}...',
  search: 'Search',
  gameVersionLabel: 'Game version',
  allVersions: 'All versions',
  loaderLabel: 'Loader',
  allLoaders: 'All loaders',
  categoryFilterLabel: 'Category filter',
  clearFilter: 'Clear filter',
  expandTags: 'Show all',
  collapseTags: 'Collapse',
  expandFilters: 'Show filters',
  collapseFilters: 'Hide filters',
  notFound: 'No resources found',
  notFoundHint: 'Try different keywords, source or category',
  retry: 'Retry',
  loading: 'Loading...',
  loadMore: 'Load more ({current}/{total})',
  allShown: 'All {count} results shown',
  mode: {
    searchPlaceholder: 'Search resources, keywords...',
  },
  favorites: {
    viewSearch: 'Search',
    viewLabel: 'Favourites',
    viewLabelWithCount: 'Favourites ({count})',
    searchPlaceholder: 'Search favourites...',
    add: 'Add to favourites',
    remove: 'Remove from favourites',
    added: 'Added to favourites',
    removed: 'Removed from favourites',
    failed: 'Favourite action failed',
    loadFailed: 'Failed to load favourites',
    emptyTitle: 'No favourites yet',
    emptyHint: 'Click the heart in search results or on a resource page to add one',
    filteredEmpty: 'No favourites match the current filters',
    filteredEmptyHint:
      'Switch the resource source / category above, or the folder and tag filters on the left',
    allShown: '{count} favourites',
    folders: {
      railTitle: 'Folders',
      all: 'All',
      unfiled: 'Unfiled',
      loading: 'Loading...',
      create: 'New folder',
      createPlaceholder: 'Folder name',
      rename: 'Rename',
      renamePlaceholder: 'Folder name',
      emptyName: 'Folder name cannot be empty',
      created: 'Created folder "{name}"',
      renamed: 'Folder renamed',
      failed: 'Folder action failed',
      delete: 'Delete',
      deleteTitle: 'Delete folder',
      deleteBodyWithItems:
        '"{name}" and its {count} favourites will be deleted. This cannot be undone.',
      deleteBodyEmpty: '"{name}" has no favourites. Deleting it cannot be undone.',
      deleted: 'Deleted folder ({count} favourites)',
    },
    note: {
      label: 'Note',
      placeholder: 'Record usage, version requirements, etc.',
    },
    tags: {
      label: 'Tags',
      filterLabel: 'Filter by tag',
      placeholder: 'Type a tag and press Enter',
      remove: 'Remove tag "{tag}"',
      hint: 'Press Enter or comma to add, up to {max}',
      limitReached: 'Limit of {max} reached',
    },
    edit: {
      open: 'Edit favourite',
      title: 'Edit favourite',
      folderLabel: 'Folder',
      none: 'Unfiled',
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving...',
      saved: 'Saved',
      failed: 'Failed to save',
    },
  },
} as const
