// Resource center (en)
export default {
  sources: {
    all: 'All',
  },
  categories: {
    mod: 'Mods',
    modpack: 'Modpacks',
    shader: 'Shaders',
    resourcepack: 'Resource Packs',
    datapack: 'Data Packs',
    save: 'Saves',
  },
  sort: {
    relevance: 'Relevance',
    downloads: 'Downloads',
    updated: 'Updated',
    newest: 'Newest',
    name: 'Name',
    recommended: 'Recommended',
    installs: 'Installs',
  },
  unknownAuthor: 'Unknown author',
  install: 'Install',
  viewDetail: 'View details',
  originalSite: 'Original site',
  searchFailed: 'Search failed',
  backendUnreachable: 'Cannot connect to backend service, please make sure it is running',
  title: 'Resource Centre',
  sourceLabel: 'Source',
  categoryLabel: 'Category',
  searchPlaceholder: 'Search {category}...',
  search: 'Search',
  gameVersionLabel: 'Game version',
  allVersions: 'All versions',
  loaderLabel: 'Loader',
  allLoaders: 'All loaders',
  categoryFilterLabel: 'Category filter',
  clearFilter: 'Clear filter',
  expandTags: 'Show all',
  collapseTags: 'Collapse',
  notFound: 'No resources found',
  notFoundHint: 'Try different keywords, source or category',
  retry: 'Retry',
  loading: 'Loading...',
  loadMore: 'Load more ({current}/{total})',
  allShown: 'All {count} results shown',
  favorites: {
    viewSearch: 'Search',
    viewLabel: 'Favourites',
    viewLabelWithCount: 'Favourites ({count})',
    filterHint: 'Favourites are filtered by the source / category tabs above',
    add: 'Add to favourites',
    remove: 'Remove from favourites',
    added: 'Added to favourites',
    removed: 'Removed from favourites',
    failed: 'Favourite action failed',
    loadFailed: 'Failed to load favourites',
    emptyTitle: 'No favourites yet',
    emptyHint: 'Click the heart in search results or on a resource page to add one',
    filteredEmpty: 'No favourites in this source / category',
    filteredEmptyHint: 'Switch the source or category above to see other favourites',
    allShown: '{count} favourites',
  },
} as const
