// Launch / running flow (en)
export default {
  gameCrashed: 'Game crashed',
  gameCrashTitle: 'Game crashed',
  launchFailedTitle: 'Launch failed',
  gameExitedAbnormally: 'Game exited abnormally (code: {code})',
  launchError: 'An error occurred during launch',
  analysisUnavailable: 'Crash analysis service unavailable',
  gameExited: 'Game exited',
  gameStarted: 'Game started',
  preparingLaunch: 'Preparing to launch...',
  javaIncompatibleTitle: 'Incompatible Java version',
  javaIncompatible: 'Selected Java {current} does not meet the requirement of Minecraft {game} (requires Java {required}). Continue launching?',
  launchCancelled: 'Launch cancelled',
  gameStopped: 'Game stopped',
  timeSeconds: '{count}s',
  timeMinutes: '{count}m {sec}s',
  timeHours: '{hours}h {mins}m',
  instancesRunning: '{count} instance(s) running',
  noRunningGame: 'No running games',
  goToInstances: 'Go to instances',
  title: 'Running Games',
  runningFor: 'Running for {time}',
} as const
