// Settings page (en; batch0 covers category nav + appearance core, rest filled by migration batches)
export default {
  category: {
    launcher: 'Launcher',
    basic: 'Basic',
    launch: 'Launch',
    download: 'Download',
    storage: 'Storage & Cache',
    network: 'Network',
    java: 'Java Runtime',
    plugins: 'Plugins',
    appearance: 'Appearance',
    toolbox: 'Toolbox',
    logs: 'Logs',
    about: 'About',
    debug: 'Debug',
  },
  saved: 'Settings saved',
  appearance: {
    title: 'Interface',
    language: 'Language',
    followSystem: 'Follow system',
    theme: 'Theme',
    dark: 'Dark',
    light: 'Light',
    themeColor: 'Accent color',
    themeColorCustom: 'Custom color',
    themeColorBackground: 'Follow background (Monet colors)',
    themeColorReset: 'Reset to default',
    themeColorDesc: 'Custom global accent color for buttons, highlights and selections. Default uses the launcher theme color.',
    componentMaterial: 'Component material',
    componentMaterialDefault: 'Default',
    componentMaterialFrosted: 'Frosted glass',
    componentMaterialAcrylic: 'Acrylic glass',
    componentMaterialAero: 'Aero',
    componentMaterialLiquid: 'Liquid glass',
    componentMaterialLiquidPreview: 'Liquid glass (Preview)',
    componentMaterialLiquidWarning: 'Preview feature: liquid glass renders real-time displacement refraction on every card, which is performance-heavy; long lists (e.g. many mods) may stutter or even freeze the UI.',
    componentMaterialLiquidConfirmTitle: 'Enable liquid glass?',
    componentMaterialLiquidConfirmBody: 'Liquid glass is a preview feature with heavy performance cost; long lists (e.g. many mods) may stutter or freeze the UI. Enable anyway?',
    glassBlurLow: 'Clear',
    glassBlurHigh: 'Blurred',
    animations: 'Page animations',
    animationsDesc: 'Enables transition animations for page switches and dialogs',
    animationSpeed: 'Animation speed',
    slow: 'Slow',
    normal: 'Normal',
    fast: 'Fast',
    maxFrameRate: 'Max frame rate',
    maxFrameRateUnlimited: 'Unlimited',
    maxFrameRateDesc: 'Limits the frame rate of the launcher UI to reduce resource usage. Unlimited uses the display refresh rate.',
    cornerRadius: 'Corner radius',
    windowCorners: 'Window corners',
    windowCornersDesc: 'Only takes effect when not using the system frame',
    cornerSharp: 'Sharp',
    cornerDefault: 'Default (8px)',
    cornerLarge: 'Large',
    font: 'Font',
    fontFamily: 'UI font',
    fontDefault: 'Default font',
    fontDesc: 'Pick an installed system font; the whole UI updates instantly',
    fontPreviewTitle: 'Font preview',
    fontPreviewText: 'Qomicex Launcher — sample 123 ABC',
    fontReset: 'Restore default font',
    background: 'Background',
    backgroundImage: 'Background image',
    noBackgrounds: 'No background images',
    openFolder: 'Open folder',
    backgroundsHint: 'Drop images here and they appear in the list above',
    backgroundRandom: 'Pick randomly on each launch',
    backgroundRandomDesc: 'Picks a random image from the background folder',
    clearBackground: 'Clear background',
    opacity: 'Opacity',
    transparent: 'Transparent',
    opaque: 'Opaque',
    blur: 'Blur',
    sharp: 'Sharp',
    watermark: 'Watermark',
    watermarkEnabled: 'Show watermark text on home page',
    watermarkEnabledDesc: 'Shows customisable text in the centre of the home page',
    watermarkText: 'Watermark text',
    watermarkSubtext: 'Subtitle',
    watermarkSubtextPlaceholder: 'Launcher',
  },
  launcher: {
    title: 'Launcher settings',
    dataDir: 'Data directory',
    dataDirDesc: 'Where launcher data is stored; a restart is required after changing',
    dataDirChanged: 'Data directory changed; takes effect after restarting the launcher',
    saveFailed: 'Failed to save settings',
    downloadThreads: 'Download threads',
    downloadThreadsDesc: 'Number of files downloaded at the same time (1-512). Higher values download faster but use more bandwidth',
    fileChunkThreads: 'Chunk threads',
    fileChunkThreadsDesc: 'Number of parallel chunks per file: off = single stream, auto = engine default, or manually set 1-16',
    fileChunkThreadsOff: 'Off',
    fileChunkThreadsAuto: 'Auto',
    versionIsolation: 'Version isolation',
    versionIsolationDesc: 'Each version uses separate mods/config/saves directories; keeping this on is recommended',
    closeAfterLaunch: 'Close launcher after launching the game',
    closeAfterLaunchDesc: 'Automatically closes the launcher after the game starts',
    autoReportErrors: 'Auto-report severe error logs',
    autoReportErrorsDesc: 'Automatically uploads error logs and device info (system/hardware) when the launcher hits a severe error like a crash, to help troubleshooting; ordinary launch failures and download/install errors are not reported',
    downloadSource: 'Download source',
    downloadSourceName: { 0: 'Official', 1: 'BMCLAPI mirror' },
    modSource: 'Resource download source',
    modSourceName: { 0: 'Modrinth/CurseForge official', 1: 'MCIM mirror' },
    resourceDownloadSource: 'File download source',
    resourceDownloadSourceName: { 0: 'Official', 1: 'QML Mirror', 2: 'QML Mirror HK' },
    resourceDownloadSourceDesc: 'CDN used for MOD file downloads: Official connects to the original CDN, QML Mirror is the QML mirror.',
    autoSelectFileDownloadSource: 'Auto-select download source',
    autoSelectFileDownloadSourceDesc: 'Automatically use the fastest available source.',
    refreshLatency: 'Refresh latency',
    autoSelectDownloadSource: 'Auto-select fastest download source',
    autoSelectDownloadSourceDesc: 'Automatically detects and picks the lowest-latency download source at startup and before each install',
    autoSelectModSource: 'Auto-select fastest resource download source',
    autoSelectModSourceDesc: 'Automatically detects Modrinth/CurseForge API mirrors and picks the lowest-latency one',
    translationProvider: 'Translation provider',
    translationDefault: 'MyMemory (default)',
    translationGoogle: 'Google Translate',
    translationProviderDesc: 'Selects the translation service used for resource descriptions and summaries',
    bingApiKeyPlaceholder: 'Enter your Azure Translator API Key',
    bingApiKeyDesc: 'Create a Translator resource in Azure Portal to get a Key; the region must be set to global',
    downloadTimeout: 'Download timeout (seconds)',
    downloadTimeoutDesc: 'A file with no response for longer than this is retried automatically (0=no timeout, 1-120 seconds)',
    enableHttp3: 'Enable HTTP/3 file downloads (experimental)',
    enableHttp3Desc: 'When enabled, downloads prefer HTTP/3 and automatically fall back to HTTP/2 if the server does not support it; when disabled, downloads use HTTP/2 only',
    http1Parallel: 'Force HTTP/1.1 parallel connections',
    http1ParallelDesc: 'When on, every file downloads over its own TCP connection. Default off = per-source auto: per-connection-limited CDNs (e.g. Modrinth) use parallel, other sources (Mojang/BMCLAPI) use HTTP/2.',
    logLevelLabel: 'Log level',
    logLevel: { error: 'Error', warn: 'Warning', info: 'Info', debug: 'Debug', trace: 'Trace' },
    logLevelDesc: 'Controls verbosity of console and log file output; info is the default',
    storageCache: 'Storage & cache',
    versionListCache: 'Version list cache',
    versionListCacheDesc: 'Clears the HTML cache of the Forge version list',
    clearCache: 'Clear cache',
    curseforgeConcurrency: 'CurseForge version list concurrency',
    curseforgeConcurrencyDesc: 'Number of pages fetched concurrently (1-20). Higher values load the version list faster',
    curseforgeTtl: 'CurseForge version list cache TTL (seconds)',
    curseforgeTtlDesc: '0 = cache forever (until restart or manual clear), default 300 seconds (5 minutes)',
    curseforgeCache: 'CurseForge version cache',
    curseforgeCacheDesc: 'Clears the in-memory CurseForge version list cache',
    clearCurseforgeCache: 'Clear CurseForge version cache',
    cacheCleared: 'Cache cleared, {count} file(s) deleted',
    cacheClearFailed: 'Failed to clear cache',
    curseforgeCacheCleared: 'CurseForge version cache cleared',
    curseforgeCacheClearFailed: 'Failed to clear CurseForge cache',
  },
  network: {
    title: 'Network',
    proxy: 'Proxy',
    proxyMode: 'Proxy type',
    proxyOff: 'No proxy',
    proxySystem: 'Use system proxy',
    http: 'HTTP(S) proxy',
    socks5: 'SOCKS5 proxy',
    proxyModeDesc: 'Configure a proxy server for downloads and resource requests',
    proxyHost: 'Proxy server address',
    proxyHostPlaceholder: 'e.g. 127.0.0.1:7890',
    proxyHostDesc: 'Format: host:port; only used when HTTP(S) or SOCKS5 proxy is selected',
    ignoreSslCert: 'Ignore SSL certificate verification',
    ignoreSslCertDesc: 'Skip TLS certificate verification when downloading or requesting (for self-signed certs / internal proxies; use with caution)',
  },
  java: {
    title: 'Java Runtime',
    ready: 'Ready',
    detected: 'Detected',
    available: 'Available',
    quickScan: 'Quick scan',
    deepScan: 'Deep scan',
    manualAdd: 'Add manually',
    downloadJava: 'Download Java',
    refreshList: 'Refresh list',
    scanningQuick: 'Quick scanning...',
    scanningDeep: 'Deep scanning...',
    scanDoneFound: 'Scan complete, found {count} new version(s)',
    scanDoneNone: 'Scan complete, no new versions',
    scanFailed: 'Scan failed',
    refreshing: 'Refreshing...',
    scanningRuntime: 'Scanning for Java runtimes...',
    noRuntimeDetected: 'No Java runtime detected yet',
    noRuntimeHint: 'Click "Quick scan" to detect Java on your system, or add one manually',
    startScan: 'Start scan',
    usable: 'Available',
    unusable: 'Unavailable',
    openFolder: 'Open folder',
    availableCount: '{valid} / {total} available',
    showInvalid: 'Show unavailable',
    defaultConfig: 'Default configuration',
    defaultRuntime: 'Default Java runtime',
    autoSelect: 'Auto-select',
    defaultRuntimeDesc: 'Auto-select is recommended: the launcher picks the best Java runtime for each game version',
    memoryAllocation: 'Memory allocation',
    memoryAuto: 'Auto',
    memoryCustom: 'Custom',
    totalMemory: 'Total {value} GiB',
    usedMemory: 'Used {value} GiB',
    gameMemory: 'Game allocation {value} GiB',
    remainingMemory: 'Remaining {value} GiB',
    jvmArgs: 'Additional JVM arguments',
    jvmArgsDesc: 'JVM arguments passed when launching Minecraft',
    pickJavaExecutable: 'Select Java executable',
    unrecognizedPath: 'Cannot recognize a Java runtime at this path',
    added: 'Added {name} {version}',
    loadCatalogFailed: 'Failed to load Java download catalog',
    addedToDownload: 'Added to download centre: {name}',
    downloadFailed: 'Failed to start Java download',
    deleteConfirm: 'Are you sure you want to delete "{name}"?',
    deleteTitle: 'Delete Java',
    deleted: 'Deleted {name}',
    deleteFailed: 'Failed to delete',
    manualAddTitle: 'Add Java manually',
    executablePath: 'Java executable path',
    browse: 'Browse',
    executablePathDesc: 'Select or enter the full path to a Java executable',
    verifying: 'Verifying...',
    add: 'Add',
    distribution: 'Distribution',
    recommended: '(recommended)',
    mainVersion: 'Java major version',
    platform: 'Platform',
    architecture: 'Architecture',
    targetDir: 'Target directory',
    resolving: 'Resolving...',
    startDownload: 'Start download',
  },
  plugins: {
    title: 'Plugin management',
    installedCount: '{count} installed',
    searchPlaceholder: 'Search plugins...',
    installing: 'Installing...',
    install: 'Install plugin',
    noneInstalled: 'No plugins installed yet',
    noMatch: 'No matching plugins',
    changesApplied: 'Changes applied',
    saveFailed: 'Failed to save',
    uninstallConfirm: 'Are you sure you want to uninstall this plugin?',
    uninstalled: 'Plugin uninstalled',
    uninstallFailed: 'Failed to uninstall',
    installSuccess: 'Plugin installed successfully',
    installFailed: 'Install failed: {message}',
    permissions: 'Permissions ({count})',
    contributes: 'Contributes',
  },
  about: {
    aboutApp: 'About {name}',
    beta: 'Beta',
    stable: 'Stable',
    feedback: 'Feedback',
    viewRepository: 'View repository',
    versionInfo: 'Version information',
    appVersion: 'App version',
    versionHash: 'Version hash',
    os: 'Operating system',
    architecture: 'System architecture',
    memory: 'Memory',
    license: 'Licence',
    licenseActivated: 'Activated',
    licenseNotActivated: 'Not activated',
    licenseInvalid: 'Invalid',
    channel: 'Channel',
    expiry: 'Expires',
    permanent: 'Permanent',
    machineCode: 'Machine code',
    changeLicense: 'Change licence',
    activateLicense: 'Activate licence',
    copyMachineCode: 'Copy machine code',
    update: 'Update',
    checking: 'Checking...',
    checkUpdate: 'Check for updates',
    upToDate: 'Already up to date',
    checkUpdateFailed: 'Failed to check for updates',
    developers: 'Developers',
    acknowledgements: 'Acknowledgements',
    referenceProjects: 'Reference projects',
    backendDependencies: 'Backend dependencies',
    frontendDependencies: 'Frontend dependencies',
    openSourceLicense: 'Open-source licence',
    licenseNotice: 'This program is released under the {name} open-source licence',
    viewLicense: 'View licence',
    copyrightPrivacy: 'Copyright & privacy',
    copyrightStatement: 'Copyright notice',
    copyrightStatementDesc: "View this software's copyright ownership and open-source licence information",
    userAgreement: 'User agreement',
    privacyPolicy: 'Privacy policy',
    appDescription: 'A modern Minecraft launcher with multi-version management, mod loader compatibility, account management and more.',
    roleProjectLead: 'Project founder / lead developer',
    serviceModrinth: 'Mod and resource search API',
    serviceModpack: 'Modpack API',
    serviceBmclapi: 'Provides BMCLAPI download mirror service',
    serviceMcmod: 'Chinese mod database',
    serviceMinecraft: 'Minecraft official website, support the game!',
    serviceMinecraftName: 'Minecraft Official Website',
    serviceModrinthName: 'Modrinth',
    serviceCurseForgeName: 'CurseForge',
    serviceFtbName: 'FTB',
    serviceBmclapiName: 'bangbang93',
    serviceMcmodName: 'mcmod',
    refVersionCheck: 'Version detection reference',
    refModloaderInstaller: 'ModLoader installer reference',
    refLaunchFlow: 'Launch flow reference',
    depBackendRuntime: 'Rust backend runtime',
    depCoreLibraries: 'Core libraries',
    depCoreFramework: 'Core framework',
    depUiComponents: 'UI components',
    depStylesTools: 'Styles & tools',
    depAnimation: 'Animation',
    depRendering: 'Rendering & display',
    depInHouse: 'In-house',
  },
} as const
