// 账户详情（zh-CN）
export default {
  capeUnequipped: '披风已卸下',
  capeEquipped: '披风已装备',
  capeSwitchFailed: '披风切换失败，请重新登录后重试',
  skinUploaded: '皮肤上传成功',
  skinUploadFailed: '皮肤上传失败',
  resetSkinConfirm: '确定要重置为默认皮肤吗？',
  skinReset: '皮肤已重置',
  skinResetFailed: '皮肤重置失败',
  skinSavedTo: '皮肤已保存到 {dest}',
  skinDownloaded: '皮肤已下载',
  skinDownloadFailed: '皮肤下载失败',
  deleteAccountConfirm: '确定要删除此账户吗？',
  loading: '加载中...',
  showNameTag: '显示名称标签',
  showCape: '显示披风',
  downloadSkin: '下载皮肤',
  accountInfo: '账户信息',
  name: '名称',
  type: '类型',
  authServer: '验证服务器',
  skinModel: '皮肤模型',
  slim: '纤细 (Slim)',
  classic: '经典 (Classic)',
  cape: '披风',
  none: '无',
  hasSkin: '有',
  refreshSkin: '刷新皮肤',
  switchCape: '切换披风',
  uploadSkin: '上传皮肤',
  chooseArmModel: '选择手臂模型',
  skinPreview: '皮肤预览',
  classicArm: '经典手臂',
  slimArm: '纤细手臂',
  resetSkin: '重置皮肤',
  goToSkinSite: '前往皮肤站',
  deleteAccount: '删除账户',
} as const
