// 账户（zh-CN）
export default {
  loginErrors: {
    accessDenied: '你在浏览器中取消或拒绝了授权',
    expiredToken: '验证码已过期，请重新登录',
    invalidGrant: '授权无效，请重新登录',
    loginFailed: '登录失败：{code}',
  },
  methodLabel: {
    offline: '离线',
    thirdParty: '第三方',
    thirdPartyWith: '第三方/{server}',
    unified: '统一通行证',
  },
  dataCorrupted: '账户数据文件已损坏或机器码变更，文件已被删除，请重新添加账户。',
  microsoft: {
    gettingInfo: '正在获取登录信息...',
    openingBrowser: '正在打开浏览器...',
    codeCopied: '验证码已复制到剪贴板，请在浏览器中登录 Microsoft 账号\n验证码: {code}',
    loginTimeout: '登录超时，请重新登录',
    gettingAccount: '正在获取账户信息...',
    loginSuccess: '登录成功',
    noRole: '未获取到可用角色',
    stepFetching: '获取登录信息',
    stepWaiting: '等待授权',
    stepFetchingInfo: '获取账户信息',
    codeCopiedShort: '验证码已复制',
    browserOpened: '浏览器已自动打开',
    relogin: '重新登录',
  },
  deleteConfirm: '确定要删除此账户吗？',
  deleteTitle: '删除账户',
  batchDeleteConfirm: '确定要删除选中的 {count} 个账户吗？',
  batchDeleteTitle: '批量删除',
  title: '账户管理',
  refresh: '刷新',
  addAccount: '添加账户',
  add: '添加',
  filterAll: '全部筛选',
  filterName: '名称',
  filterLoginMethod: '登录方式',
  filterServer: '服务器',
  searchPlaceholder: '搜索账户...',
  noMatch: '无匹配账户',
  noAccounts: '暂无账户',
  setDefault: '设为默认',
  deleteSelected: '删除 {count}',
  addTitle: '添加账户',
  tabOffline: '离线',
  tabUnified: '统一通',
  offline: {
    playerName: '玩家名称',
    playerNamePlaceholder: '输入离线模式用户名',
    uuid: 'UUID（可选，留空自动生成）',
    uuidPlaceholder: '例如: 069a79f4-44e9-4726-a5be-fca90e38aaf5',
    add: '添加离线账户',
  },
  ygg: {
    presetServer: '预设服务器',
    email: '邮箱',
    password: '密码',
    customServerAddr: '自定义服务器地址',
    login: '登录',
    loginLoading: '登录中...',
    saving: '保存中...',
    chooseRole: '选择要登录的角色：',
    back: '返回',
    confirmCount: '确认 ({count})',
  },
  unified: {
    desc: '统一通行证是部分 Minecraft 服务器使用的认证系统，需要输入服务器 ID。',
    serverId: '服务器 ID',
    serverIdPlaceholder: '例如: lilu',
    email: '邮箱',
    password: '密码',
    login: '登录',
    loginLoading: '登录中...',
    oauthLogin: 'Microsoft OAuth 登录',
  },
} as const
