// 通用高频文案（zh-CN）
export default {
  ok: '确定',
  cancel: '取消',
  close: '关闭',
  save: '保存',
  delete: '删除',
  edit: '编辑',
  confirm: '确认',
  loading: '加载中...',
  noData: '暂无数据',
  comingSoon: '即将上线',
  retry: '重试',
  refresh: '刷新',
  copy: '复制',
  copied: '已复制',
  search: '搜索',
  select: '选择',
  back: '返回',
  next: '下一步',
  prev: '上一个',
  unknown: '未知',
  all: '全部',
  none: '无',
  enabled: '已启用',
  disabled: '已禁用',
  error: '错误',
  warning: '警告',
  success: '成功',
  failed: '失败',
  language: '界面语言',
  theme: '主题',
  dark: '深色',
  light: '亮色',
  externalLink: '外部链接',
  seeMore: '查看更多',
  goto: '前往',
  name: '名称',
  version: '版本',
  status: '状态',
  action: '操作',
  detail: '详情',
  optional: '可选',
  javaRuntimeRequired: '启动 Minecraft 需要 Java 运行时环境。\n\n你可以使用「设置 → Java → 下载 Java」功能快速安装，或手动添加已安装的 Java 路径。',
  javaRuntimeRequiredTitle: '未检测到 Java 运行时',
} as const
