// 联机（zh-CN）
export default {
  hostBadge: '房主',
  kick: '踢出',
  noPlayers: '暂无玩家',
  playerList: '玩家列表 ({count})',
  hostMods: '房主 Mods',
  matchInstances: '匹配实例 ({count})',
  scanningMatch: '正在扫描本地实例与房主 mods 比对...',
  noHostMods: '房主未发布 mods 列表（或扫描中）',
  missingModsDesc: '标"缺失"的 mod 未含于实例 {instance}{countSuffix}（覆盖房主 mods 最多的本地实例）',
  missingModsCountSuffix: '，共 {count} 个',
  noVersionInfo: '房主未提供版本信息，无法判定哪些 mod 缺失',
  missingTooltip: '该 mod 在最佳匹配实例（覆盖房主 mods 最多者）中缺失',
  missing: '缺失',
  scanningLocal: '正在扫描本地实例...',
  noVersionForMatch: '房主未提供版本信息，无法匹配本地实例',
  noMatchingInstance: '没有与房主游戏版本/loader 相同的本地实例',
  matchedInstances: '一致实例（{count}）',
  modsConsistent: 'mods 一致 ({count})',
  quickLaunch: '快捷启动',
  unmatchedInstances: '不一致实例（{count}）可忽略差异启动',
  modsInconsistent: 'mods 不一致 ({count})',
  forceLaunchTitle: '忽略 mod 差异，直接以此为本地实例加入房间',
  forceLaunch: '忽略差异强制启动',
  noLocalInstance: '暂无可用本地实例',
  gameCrashed: '游戏异常退出',
  launchFailed: '启动失败',
  invalidPort: '请输入有效端口 (1-65535)',
  selectInstanceFirst: '请选择一个实例',
  enterRoomCode: '请输入房间码',
  roomNotReady: '房间尚未就绪',
  natCheckFailed: 'NAT 类型检测失败',
  natTypes: {
    cone: { label: '完全锥形', tooltip: 'UDP: 宽松  TCP: 中等' },
    symmetric: { label: '严格对称', tooltip: 'UDP: 严格  TCP: 严格' },
    blocked: { label: '不可穿透', tooltip: 'UDP: 阻断  TCP: 阻断' },
    unknown: { label: '不确定', tooltip: 'NAT 类型未知' },
  },
  title: '联机',
  subtitle: '创建或加入联机房间',
  natCheck: 'NAT 检测',
  easyTierDownloadFailed: 'EasyTier 下载失败：{error}',
  retry: '重试',
  easyTierStatus: {
    resolving: '正在测速选择最快下载源…',
    extracting: '正在解压 EasyTier…',
    downloading: '正在下载 EasyTier 联机组件…',
  },
  tabCreate: '创建房间',
  tabJoin: '加入房间',
  createTitle: '启动实例并创建房间',
  selectInstance: '选择实例',
  pleaseSelect: '请选择...',
  starting: '正在启动…',
  startAndCreate: '启动并创建房间',
  openLanHint: '启动后请在游戏内点击"对局域网开放"，将自动探测端口。',
  manualStarted: '已手动启动实例？点击这里',
  scanPortTitle: '扫描本地端口',
  scanningPorts: '正在扫描 Java 进程端口…',
  portDetected: '检测到端口',
  createRoom: '创建房间',
  manualPort: '或者手动输入端口',
  joinTitle: '加入房间',
  roomCode: '房间码',
  joining: '正在加入…',
  joinRoom: '加入房间',
  gotIt: '知道了',
  cancel: '取消',
  closeRoom: '关闭房间',
  serverAddress: '服务器地址',
  hostVersion: '房主版本：{version}',
  leaveRoom: '退出房间',
} as const
