// 仪表盘（zh-CN）
export default {
  account: '账户',
  noDefaultAccount: '未设置默认账户',
  defaultAccount: '默认账户',
  addInSettings: '在设置中添加',
  manageAccounts: '管理账户',
  lastPlayed: '上次游玩 {date}',
  status: '状态',
  ready: '准备就绪',
  launch: '启动',
  noPinnedInstance: '尚未固定实例',
  goToInstances: '前往实例管理',
  editLayout: '编辑布局',
  editMode: '编辑模式：拖动排列组件，拖动右下角调整大小',
  addWidget: '添加组件',
  resetLayout: '恢复默认布局',
  allWidgetsVisible: '所有组件均已显示',
  done: '完成',
  widget: {
    watermark: '水印',
    account: '账户',
    instance: '默认实例',
    launch: '启动',
    announcements: '公告',
  },
} as const
