// 外部唤起（qomicex-launcher:// 深链，issue #127）的提示文案
export default {
  launchNotFound: '未找到实例：{target}',
  joinConfirmTitle: '加入联机房间',
  joinConfirmDesc: '网页请求加入房间 {code}，是否继续？',
  joinFailed: '加入房间失败：{message}',
  installPluginConfirmTitle: '安装插件',
  installPluginConfirmDesc: '此请求来自 {host}，将安装插件 {name}。仅在你信任该来源时继续。',
  installPluginSlugConfirmDesc: '网页请求安装商店插件 {slug}，是否继续？',
  installModpackConfirmTitle: '安装整合包',
  installModpackConfirmDesc: '网页请求安装整合包 {name}（来源 {source}），是否继续？',
  installStarted: '已开始安装',
  installFailed: '安装失败：{message}',
  cancelled: '已取消该操作',
  registerTitle: '关联外部唤起链接',
  registerDesc: '是否把启动器注册为 qomicex-launcher:// 链接的打开方式？注册后，网页或快捷方式可以直接唤起启动器。',
  registerSuccess: '已关联外部唤起链接',
  registerFailed: '关联失败，稍后可在设置中重试',
  registerDeclined: '已跳过，之后不再自动询问',
}
