// 通用弹窗/卡片（zh-CN）
export default {
  // 安装/下载阶段（与 downloads.stage 相同，供弹窗渲染动态 key）
  stage: {
    queued: '排队中',
    'downloading-json': '下载版本 JSON',
    downloading: '下载游戏文件',
    'downloading-libraries': '下载支持库',
    'downloading-assets': '下载资源文件',
    'downloading-mainjar': '下载主文件',
    'downloading-loader': '下载加载器',
    'downloading-loader-libs': '下载加载器库',
    'installing-loader': '安装加载器',
    'downloading-addons': '下载附加内容',
    'downloading-modpack': '下载整合包',
    'parsing-modpack': '解析整合包',
    'modpack-files': '下载整合包文件',
    'modpack-overrides': '解压覆盖文件',
  },
  // 跨弹窗/卡片通用文案
  common: {
    unknownError: '未知错误',
    deleting: '删除中...',
    viewDetail: '查看详情',
    openFolder: '打开文件夹',
    openFailed: '打开失败',
    deleted: '已删除「{name}」',
    deleteFailed: '删除失败: {error}',
    taskExpired: '任务已过期（后端未报告该会话）',
    downloadTimeout: '下载超时（可能仍在后台进行）',
    downloadStalled: '下载停滞（长时间无进度）',
    cancelled: '下载已取消',
    downloadFailed: '下载失败',
    startFailed: '下载启动失败',
  },
  // 删除确认（按资源类型）
  confirmDelete: {
    titleMod: '删除 Mod',
    titleSave: '删除存档',
    titleScreenshot: '删除截图',
    titleShader: '删除光影包',
    titleDataPack: '删除数据包',
    titleResourcePack: '删除资源包',
    bodyMod: '确定要删除 Mod「{name}」吗？将被移至回收站。',
    bodySave: '确定要删除存档「{name}」吗？将被移至回收站。',
    bodyScreenshot: '确定要删除截图「{name}」吗？将被移至回收站。',
    bodyShader: '确定要删除光影包「{name}」吗？将被移至回收站。',
    bodyDataPack: '确定要删除数据包「{name}」吗？将被移至回收站。',
    bodyResourcePack: '确定要删除资源包「{name}」吗？将被移至回收站。',
  },
  // 启动进度
  launchProgress: {
    title: '启动游戏',
    titleFailed: '启动失败',
    stage: {
      starting: '准备中',
      checking: '检查文件完整性',
      repairing: '补全文件',
      'logging-in': '验证账户',
      authlib: '配置外置登录',
      natives: '解压原生库',
      building: '构建启动参数',
      preparing: '准备环境',
      launching: '启动游戏',
      running: '游戏运行中',
      crashed: '游戏异常退出',
      failed: '启动失败',
      completed: '游戏已退出',
      cancelled: '已取消',
    },
    viewCrashReport: '查看崩溃报告',
    processId: '进程 ID: {pid}',
    startingUp: '正在启动...',
  },
  // 崩溃分析
  crashAnalysis: {
    copyAll: '复制全部',
    copyDetail: '详情:\n{detail}',
    copyArgs: '启动参数:\n{args}',
    copyCrashReport: '崩溃报告:\n{crashReport}',
    copyLogLink: '日志链接: {url}',
    exporting: '导出中...',
    exportReport: '导出诊断报告',
    exportFailed: '导出失败',
    detail: '错误详情',
    crashReport: '崩溃报告',
    launchArgs: '启动参数',
    analyzing: '正在分析崩溃报告...',
    noResult: '暂无分析结果',
    scanQr: '扫描查看完整日志',
  },
  // 导入整合包
  import: {
    title: '导入整合包',
    parsing: '正在解析整合包文件...',
    modpackName: '整合包名称',
    gameVersion: '游戏版本',
    loader: '加载器',
    instanceName: '实例名称',
    startInstall: '开始安装',
    connecting: '正在连接...',
    installing: '安装中：{name}',
    completed: '✓ 安装完成！',
    completedDetail: '整合包已成功安装为实例「{name}」',
    failedWith: '安装失败：{error}',
    seeDownloadPage: '请查看下载页了解详情',
    viewInstance: '查看实例',
    backgroundDownload: '后台下载',
    parseFailed: '解析失败',
    installFailed: '安装失败',
  },
  // 安装整合包（在线）
  modpackInstall: {
    title: '安装整合包',
    modpackLabel: '整合包',
    gameVersion: '游戏版本',
    loader: '加载器',
    instanceName: '实例名称',
    startInstall: '开始安装',
    resolving: '正在解析并安装...',
    connecting: '正在连接...',
    installing: '安装中：{name}',
    completed: '✓ 安装完成！',
    completedDetail: '整合包已成功安装为实例「{name}」',
    failedWith: '安装失败：{error}',
    seeDownloadPage: '请查看下载页了解详情',
    viewInstance: '查看实例',
    backgroundDownload: '后台下载',
    cancelled: '已取消',
    installFailed: '安装失败',
  },
  // 版本更新
  update: {
    foundNew: '发现新版本 {version}',
    noNotes: '暂无更新说明',
    downloadFailed: '下载失败',
    done: '更新完成',
    downloading: '下载中 {progress}%',
    later: '下次再说',
    installing: '安装中...',
    downloadingAction: '下载中...',
    updateNow: '立即更新',
  },
  // 许可证激活
  license: {
    title: '激活许可证',
    loadFailed: '加载失败',
    activateFailed: '激活失败',
    active: '许可证已激活',
    id: 'ID: {licenseId}',
    expireAt: '过期: {date}',
    permanent: '永久',
    machineCode: '本机机器码',
    copyMachineCode: '复制机器码',
    tokenLabel: '许可证 Token',
    tokenPlaceholder: '粘贴管理员提供的许可证 Token...',
    tokenHint: '联系管理员获取新许可证 Token。输入后点击激活按钮进行验证。',
    exitLauncher: '退出启动器',
    verifying: '验证中...',
    activate: '激活',
  },
  // Microsoft 重新登录
  microsoftReauth: {
    title: 'Microsoft 账户凭证已过期',
    description: '你的 Microsoft 账户凭证已过期，需要重新登录才能启动游戏。',
    reauth: '重新登录 Microsoft',
  },
  // 未设置账户
  noAccount: {
    title: '尚未设置账户',
    description: '启动游戏需要一个 Minecraft 账户，请先添加账户。',
    goToAccounts: '去账户管理',
    addAccount: '添加账户',
  },
  // 选择默认账户
  accountSelect: {
    title: '选择默认账户',
    description: '请选择一个账户作为默认账户，启动游戏时将使用该账户。',
    noAccounts: '暂无账户',
  },
  // 更换版本
  versionPicker: {
    title: '更换版本 — {name}',
    loadingVersions: '加载版本列表...',
    noVersions: '没有可用的版本',
    switching: '更换中...',
    switch: '更换',
  },
  // 模组更新
  modUpdate: {
    title: '检查模组更新',
    checkFailed: '检查更新失败',
    addedToDownloadList: '已加入下载列表 {count} 个任务',
    updatedCount: '已更新 {count} 个模组',
    completedWithFailed: '完成 {success} 个，失败 {failed} 个{failNames}',
    batchFailed: '批量更新失败',
    allUpToDate: '所有模组已是最新版本',
    updating: '更新中...',
    updateCount: '更新 {count} 个模组',
  },
  // 公告
  announcement: {
    gotIt: '知道了',
  },
  // 披风管理
  cape: {
    title: '切换披风',
    noCapes: '该账户暂无可用披风',
    loadingShort: '加载中',
    inUse: '使用中',
    clickToEquip: '点击装备',
  },
  // 资源安装
  resourceInstall: {
    title: '安装 {name}',
    selectInstance: '选择实例',
    loadingInstances: '加载实例列表中...',
    instancesLoadFailed: '加载实例列表失败',
    noInstances: '暂无实例，请先创建实例',
    searchPlaceholder: '搜索实例...',
    default: '默认',
    selectVersion: '选择版本',
    selectInstanceFirst: '请先选择一个实例',
    loadingVersions: '正在加载版本列表...',
    versionsLoadFailed: '加载版本列表失败',
    selectVersionPlaceholder: '请选择版本',
    noVersions: '无可用版本',
    depsTitle: '前置模组',
    parsingDeps: '正在解析前置模组...',
    depsLoadFailed: '加载前置模组失败',
    noDeps: '无前置模组',
    installed: '已安装',
    pending: '待安装',
    noDownloadableFile: '该版本没有可下载的文件',
    downloadFailedWith: '"{name}" 下载失败: {error}',
    downloading: '正在下载',
    installConfirm: '确认安装',
    installing: '安装中...',
    installingWithName: '正在下载 {name} ({step}/{total})',
    installedDone: '安装完成：{name}',
  },
  // 模组卡片
  mod: {
    mcwiki: 'MC百科',
    changeVersion: '更换版本',
    update: '更新',
    addedToDownloadList: '已加入下载列表',
    updatedWithName: '已更新「{name}」',
    updateFailedWithName: '更新「{name}」失败',
    updateFailed: '更新失败',
    updateAvailableTo: '可更新至 {version}',
    unknownVersion: '未知版本',
  },
  // 存档卡片
  save: {
    backup: '备份',
    rename: '重命名',
    quickJoin: '快速进入',
    lastPlayed: '上次游玩: {date}',
  },
  // 版权声明弹窗
  legal: {
    title: '版权声明',
    content: `**Qomicex Launcher** 由 **Qomicex 团队** 开发并维护，版权归 Qomicex 团队所有。

- 本软件基于 **GPL-3.0 License** 开源协议发布，您可以在遵守该协议的前提下自由使用、复制、修改与分发。
- 本软件与 **Mojang Studios / Microsoft** 及其旗下产品不存在任何从属、合作或背书关系。
- **Minecraft** 及相关名称、标识、版权均归 **Mojang Studios / Microsoft** 所有。
- 本软件不包含 Minecraft 游戏本体；游戏资源版权归其各自所有者所有。
- 使用本软件即表示您已阅读并同意《用户协议》与《隐私政策》。`,
  },
} as const
