// 下载中心（zh-CN）
export default {
  status: {
    queued: '排队中',
    downloading: '下载中',
    paused: '已暂停',
    completed: '已完成',
    failed: '失败',
    cancelled: '已取消',
  },
  stage: {
    queued: '排队中',
    'downloading-json': '下载版本 JSON',
    downloading: '下载游戏文件',
    'downloading-libraries': '下载支持库',
    'downloading-assets': '下载资源文件',
    'downloading-mainjar': '下载主文件',
    'downloading-loader': '下载加载器',
    'downloading-loader-libs': '下载加载器库',
    'installing-loader': '安装加载器',
    'downloading-addons': '下载附加内容',
    'downloading-modpack': '下载整合包',
    'parsing-modpack': '解析整合包',
    'modpack-files': '下载整合包文件',
    'modpack-overrides': '解压覆盖文件',
  },
  filter: {
    all: '全部',
    downloading: '下载中',
    paused: '已暂停',
    completed: '已完成',
    failed: '失败',
  },
  title: '下载中心',
  subtitle: '{count} 个任务',
  clearFinished: '清除已完成/失败',
  taskCount: '{count} 个任务',
  empty: '暂无下载任务',
  emptyHint: '在"实例"页面选择版本并开始下载，任务将显示在此处',
  goToInstances: '前往实例',
  addonsCount: '+ {count} 个附加',
  createdAt: '创建于 {date}',
  completedAt: '完成于 {date}',
  resume: '继续',
  pause: '暂停',
  cancel: '取消',
  retry: '重试',
  remove: '移除',
  statusText: {
    done: '下载完成',
    failedWith: '失败: {error}',
    failed: '下载失败',
    pausedProgress: '已暂停 {progress}%',
    waiting: '等待中',
    downloading: '下载中',
    connecting: '连接中…',
  },
  filesCount: '{done}/{total} 文件',
  errors: {
    taskExpired: '任务已过期（后端已重启）',
    downloadFailed: '下载失败',
    cannotVerify: '无法连接后端验证任务状态',
    statusUnknown: '任务状态无法确认（后端未报告该会话）',
    taskInvalid: '任务已失效',
  },
} as const
