// 后端错误消息（前端错误码映射展示，zh-CN）
export default {
  notFound: '请求的资源不存在',
  forbidden: '没有权限执行此操作',
  badRequest: '请求参数有误',
  internalError: '服务器内部错误',
  upstreamError: '上游服务请求失败',
  requestTimeout: '请求超时，请稍后重试',
  unknown: '请求失败，请稍后重试',
  licenseNotFound: '许可证未激活',
  licenseDecryptFailed: '许可证解密失败',
  licenseSignatureInvalid: '许可证签名无效',
  licensePublicKeyUnavailable: '许可证公钥不可用',
  licenseExpired: '许可证已过期',
  licenseRemoteCheckFailed: '许可证远程校验失败',
  licenseIoError: '许可证文件读取失败',
  tokenExpired: '登录令牌已过期，请重新登录',
  mcApiError: 'Minecraft 官方 API 请求失败',
  fsAuthRequired: '文件系统访问未授权',
  pluginMissingDependency: '插件缺少必要的前置依赖',
} as const
