// 实例列表（zh-CN）
export default {
  title: '游戏实例',
  subtitle: '{count} 个版本',
  type: {
    release: '正式版',
    snapshot: '快照',
    old_beta: '远古测试版',
    old_alpha: '远古阿尔法',
    april_fools: '愚人节版',
  },
  category: {
    all: '全部',
    release: '正式版',
    snapshot: '快照',
    april_fools: '愚人节版',
    old_beta: '远古测试版',
    old_alpha: '远古阿尔法',
  },
  sort: {
    recommended: '推荐排序',
    newest: '最新优先',
    oldest: '最早优先',
    'name-asc': '名称 A-Z',
    'name-desc': '名称 Z-A',
  },
  loaderFilter: {
    all: '全部',
    modded: '模组',
    vanilla: '原版',
    snapshot: '快照',
    april_fools: '愚人节',
    broken: '错误',
  },
  downloadTitle: '下载新版本',
  categoryLabel: '分类',
  searchPlaceholder: '搜索版本...',
  remoteCount: '共 {count} 个远程版本',
  filteredCount: '筛选后 {count} 个',
  noRemoteMatch: '没有匹配的远程版本',
  noRemoteMatchHint: '试试调整分类、排序或搜索关键词',
  releaseDate: '发布日期 {date}',
  select: '选择',
  configTitle: '配置下载',
  instanceName: '实例名称',
  instanceNamePlaceholder: '输入实例名称...',
  gameVersion: '游戏版本',
  loader: '模组加载器',
  loaderPlaceholder: '选择加载器',
  noneVanilla: '无（纯净原版）',
  versionPlaceholder: '选择版本',
  loadingVersions: '加载中...',
  noVersionData: '暂无版本数据',
  latestRecommended: '最新版 {version} (推荐)',
  recommended: ' (推荐)',
  selectLoaderFirst: '先选择加载器',
  latestVersion: '最新版 {version}',
  addons: '附加内容',
  optional: '(可选)',
  fetchingAddons: '正在获取附加内容...',
  onlyGameFiles: '仅下载游戏文件，运行内存和 Java 等配置可在创建后调整',
  noLoaderAvailable: '暂无可用加载器版本，无法下载',
  cancel: '取消',
  startDownload: '开始下载',
  repairName: '补全 {name}',
  pickGameDirTitle: '选择游戏目录',
  enterDirPath: '请输入游戏目录路径:',
  chooseDir: '选择目录',
  addDir: '添加目录',
  selectDirFirst: '请先选择一个游戏目录，再开始下载。',
  noLoaderVersions: '未获取到 {loader} 的可用版本列表，无法下载。请检查网络或稍后重试。',
  selectLoaderVersion: '请选择 {loader} 的具体版本后再下载。',
  createFailed: '创建失败: {error}',
  createInstanceFailed: '创建实例失败: {error}',
  launchFailed: '启动失败: {error}',
  launchFailedDetail: '启动失败: {error}\n{detail}',
  refresh: '刷新',
  dirManagerTitle: '目录管理',
  noDir: '暂无目录',
  noDirHint: '点击下方按钮添加一个游戏目录',
  dirCount: '共 {count} 个目录，勾选标记当前使用的目录',
  openDir: '打开目录',
  remove: '移除',
  manualAdd: '手动添加',
  browseAdd: '浏览添加',
  instanceSettings: '实例设置',
  basicInfo: '基本信息',
  repairFiles: '补全文件',
  versionName: '版本名称',
  gameDir: '游戏目录',
  notCreatedYet: '此版本尚未在启动器中创建，无法补全文件。',
  repairDesc: '扫描并下载此实例缺失的 Minecraft 游戏文件（libraries、assets、client.jar）。',
  addedToDownload: '已加入下载任务',
  goToDownloadCenter: '前往下载中心查看',
  repairCompleted: '补全已完成',
  repairFailed: '补全失败',
  retry: '重试',
  startRepair: '开始补全文件',
  selectGameDir: '选择游戏目录',
  savedDirs: '已保存的目录',
  manage: '管理',
  noDirInManager: '暂无目录，可在管理中添加',
  scanning: '扫描中...',
  import: '导入',
  openGameDir: '打开游戏目录',
  selectMcDir: '请选择 Minecraft 游戏目录',
  selectMcDirHint: '选择一个包含 versions 文件夹的 .minecraft 目录',
  browseAndSelect: '浏览并选择',
  noMatch: '没有匹配的版本',
  noVersionDetected: '该目录下未检测到任何 Minecraft 版本',
  needVersionsFolder: '请确认目录下存在 versions/ 文件夹',
  available: '可用',
  unavailable: '不可用',
  launch: '启动',
  settings: '设置',
  unpin: '取消固定',
  pinToHome: '固定到主页',
  openFolder: '打开文件夹',
} as const
