// 实例详情（zh-CN）
export default {
  tabs: {
    overview: '概况',
    settings: '设置',
    gamesettings: '游戏设置',
    saves: '存档',
    screenshots: '截图',
    resourcepacks: '资源包',
    shaderpacks: '光影包',
    datapacks: '数据包',
    servers: '服务器',
  },
  confirm: {
    cancel: '取消',
    deleting: '删除中...',
    delete: '删除',
    confirm: '确定',
  },
  time: {
    minutes: '{count} 分钟',
    hours: '{count} 小时',
    hoursMinutes: '{hours} 小时 {minutes} 分钟',
    never: '从未',
    justNow: '刚刚',
    minutesAgo: '{count} 分钟前',
    hoursAgo: '{count} 小时前',
  },
  openFolder: '打开文件夹',
  loading: '加载中...',
  noMatch: '无匹配',
  empty: '暂无',
  deleteSelected: '删除 {count}',
  batchDeleteTitle: '批量删除{type}',
  batchDeleteConfirm: '确定要删除选中的 {count} 个{type}吗？将被移至回收站。',
  saves: {
    search: '搜索存档...',
    noMatch: '无匹配存档',
    empty: '暂无存档',
    type: '存档',
  },
  screenshots: {
    search: '搜索截图...',
    noMatch: '无匹配截图',
    empty: '暂无截图',
    type: '截图',
  },
  resourcepacks: {
    search: '搜索资源包...',
    noMatch: '无匹配资源包',
    empty: '暂无资源包',
    type: '资源包',
    install: '安装资源包',
    loadFailed: '加载资源包失败: {error}',
  },
  shaderpacks: {
    search: '搜索光影包...',
    noMatch: '无匹配光影包',
    empty: '暂无光影包',
    type: '光影包',
    install: '安装光影包',
    loadFailed: '加载光影包失败: {error}',
  },
  datapacks: {
    search: '搜索数据包...',
    noMatch: '无匹配数据包',
    empty: '暂无数据包',
    type: '数据包',
    install: '安装数据包',
  },
  mods: {
    management: 'Mod 管理',
    noModsHint: '该实例不可使用 Mod，需要使用 Forge、Fabric 等加载器',
    search: '搜索 Mod...',
    checkUpdates: '检查更新',
    install: '安装 Mod',
    fetchingRemoteInfo: '正在获取远程信息（Modrinth/CurseForge 匹配 id、图标、中文名）...',
    readingMods: '正在读取 Mod 信息',
    loadFailed: '加载 Mod 列表失败：{error}',
    noMatch: '无匹配 Mod',
    empty: '暂无 Mod',
    enable: '启用',
    disable: '禁用',
    updateMods: '更新模组',
    filterAll: '全部',
    updatable: '可更新',
    duplicate: '重复',
    sortNameAsc: '名称 A-Z',
    sortNameDesc: '名称 Z-A',
    sortTimeDesc: '最新优先',
    sortTimeAsc: '最早优先',
    sortSizeDesc: '最大优先',
    sortSizeAsc: '最小优先',
    batchEnable: '批量启用',
    batchDisable: '批量禁用',
    batchDelete: '批量删除',
    batchConfirm: '确定要{action}{count} 个 Mod 吗？',
    moveToRecycleBin: '将被移至回收站。',
    processing: '处理中...',
    checkingUpdates: '正在检查模组更新…',
    foundUpdates: '发现 {count} 个模组可更新',
    addedToDownload: '已加入下载列表 {count} 个任务',
    updatedCount: '已更新 {count} 个模组',
    updateResult: '完成 {success} 个，失败 {failed} 个{failures}',
    updateFailed: '更新模组失败',
    loadFailedGeneric: '加载失败: {error}',
    unknownError: '未知错误',
  },
  servers: {
    search: '搜索服务器...',
    pingAll: '全部测速',
    addServer: '添加服务器',
    edit: '编辑',
    ping: '测速',
    copyIp: '复制 IP',
    quickJoin: '快速加入',
    delete: '删除',
    online: '在线',
    offline: '离线',
    pinging: '测速中...',
    lanGames: '局域网游戏 ({count})',
    lanGame: '局域网游戏',
    join: '加入',
    deleteConfirm: '确定要删除服务器「{ip}」吗？',
    addTitle: '添加服务器',
    editTitle: '编辑服务器',
    name: '服务器名称',
    address: '服务器地址',
    updating: '更新中...',
    adding: '添加中...',
    save: '保存',
    add: '添加',
    copiedIp: '已复制 IP 地址',
    copyFailed: '复制失败',
    pingDone: '测速完成: {ping}ms',
    addressOffline: '{address} 离线',
    pingFailed: '测速失败',
    deleted: '已删除服务器',
    deleteFailed: '删除失败',
    updated: '已更新「{name}」',
    added: '已添加「{name}」',
    opFailed: '操作失败',
    loadFailed: '加载服务器列表失败',
  },
  overview: {
    launch: '启动',
    unpin: '取消固定',
    pin: '固定到主页',
    gameVersion: '游戏版本',
    loader: '加载器',
    pureVanilla: '纯净原版',
    lastPlayed: '最后游玩',
    totalPlayTime: '累计游玩',
    modpackInfo: '整合包信息',
    modpackName: '整合包名称',
    version: '版本',
    author: '作者',
    summary: '简介',
    quickActions: '快速操作',
    defaultAccount: '默认账户',
    launchGame: '启动游戏',
    instanceSettings: '实例设置',
    verifyIntegrity: '检查资源完整性',
    repairing: '正在补全 {progress}%',
    openGameDir: '打开游戏目录',
    deleteInstance: '删除实例',
    refresh: '刷新',
  },
  settingsTab: {
    instanceName: '实例名称',
    instanceIcon: '实例图标',
    gameVersion: '游戏版本',
    javaRuntime: 'Java 运行时',
    autoSelect: '自动选择',
    integrity: '资源完整性',
    checkIntegrity: '检查资源完整性',
    repairing: '正在补全 {progress}%',
    missingFiles: '缺失 {count} 个文件',
    autoRepairing: '正在自动补全...',
    integrityOk: '资源完整',
    versionIsolation: '版本隔离',
    followGlobal: '跟随全局设置',
    on: '开启',
    off: '关闭',
    isolationDesc: '每个版本使用独立的 mods/config/saves 目录',
    skipIntegrity: '跳过资源完整性检查',
    skipIntegrityDesc: '启动时跳过文件完整性检查，可能因缺少文件导致游戏崩溃',
    memoryAllocation: '内存分配',
    auto: '自动',
    custom: '自定义',
    totalMem: '总内存 {size} GiB',
    usedMem: '已使用 {size} GiB',
    gameAlloc: '游戏分配 {size} GiB',
    remainingMem: '剩余 {size} GiB',
    jvmArgs: 'JVM 参数',
    linkedAccount: '关联账号',
    unlinked: '未关联',
    saving: '保存中...',
  },
  gamesettings: {
    search: '搜索设置项...',
    noMatch: '无匹配设置项',
    empty: '暂无游戏设置',
    pressKey: '按下按键...',
  },
  launch: {
    launchFailed: '启动失败',
    instanceRunningConfirm: '当前实例正在运行中，是否启动新实例？',
    instanceRunningTitle: '实例运行中',
    backToList: '返回实例列表',
    instanceNotFound: '实例不存在',
    loadingInstance: '加载实例...',
    deleteInstanceConfirm: '确定要删除实例「{name}」吗？其版本文件夹将被永久删除。',
  },
} as const
