// 实例详情（zh-CN）
export default {
  tabs: {
    overview: '概况',
    settings: '设置',
    gamesettings: '游戏设置',
    saves: '存档',
    screenshots: '截图',
    mods: 'Mod',
    resourcepacks: '资源包',
    shaderpacks: '光影包',
    datapacks: '数据包',
    schematics: '投影原理图',
    servers: '服务器',
  },
  confirm: {
    cancel: '取消',
    deleting: '删除中...',
    delete: '删除',
    confirm: '确定',
  },
  time: {
    minutes: '{count} 分钟',
    hours: '{count} 小时',
    hoursMinutes: '{hours} 小时 {minutes} 分钟',
    never: '从未',
    justNow: '刚刚',
    minutesAgo: '{count} 分钟前',
    hoursAgo: '{count} 小时前',
  },
  openFolder: '打开文件夹',
  loading: '加载中...',
  noMatch: '无匹配',
  empty: '暂无',
  deleteSelected: '删除 {count}',
  batchDeleteTitle: '批量删除{type}',
  batchDeleteConfirm: '确定要删除选中的 {count} 个{type}吗？将被移至回收站。',
  saves: {
    search: '搜索存档...',
    noMatch: '无匹配存档',
    empty: '暂无存档',
    type: '存档',
  },
  saveSettings: {
    title: '存档设置',
    restoreFromOld: '从 level.dat_old 恢复',
    restoreFromOldConfirm: '将用 level.dat_old 覆盖当前 level.dat（当前内容会备份为 level.dat.qomicex.bak），确定恢复吗？',
    runningWarning: '该实例正在运行，游戏保存时会覆盖修改，建议先退出游戏再编辑',
    sectionBasic: '基础信息',
    sectionWeather: '天气与时间',
    sectionSpawn: '出生点与商人',
    sectionBorder: '世界边界',
    levelName: '存档名称',
    gameType: '游戏模式',
    gameTypeSurvival: '生存',
    gameTypeCreative: '创造',
    gameTypeAdventure: '冒险',
    gameTypeSpectator: '旁观',
    difficulty: '难度',
    difficultyPeaceful: '和平',
    difficultyEasy: '简单',
    difficultyNormal: '普通',
    difficultyHard: '困难',
    allowCommands: '允许作弊',
    hardcore: '极限模式',
    difficultyLocked: '锁定难度',
    time: '世界时间（Time）',
    dayTime: '昼夜时间（DayTime）',
    raining: '下雨',
    thundering: '雷暴',
    clearWeatherTime: '晴天剩余时间',
    rainTime: '降雨剩余时间',
    thunderTime: '雷暴剩余时间',
    spawnX: '出生点 X',
    spawnY: '出生点 Y',
    spawnZ: '出生点 Z',
    randomSeed: '世界种子',
    wanderingTraderSpawnChance: '流浪商人概率',
    wanderingTraderSpawnDelay: '流浪商人延迟',
    borderCenterX: '边界中心 X',
    borderCenterZ: '边界中心 Z',
    borderSize: '边界大小',
    borderSafeZone: '安全区',
    borderDamagePerBlock: '边界外伤害/格',
    borderWarningBlocks: '警告距离',
    borderWarningTime: '警告时间（秒）',
    gameRules: '游戏规则',
    ruleKeepInventory: '死亡不掉落（keepInventory）',
    ruleDoDaylightCycle: '昼夜循环（doDaylightCycle）',
    ruleDoFireTick: '火焰蔓延（doFireTick）',
    ruleMobGriefing: '生物破坏方块（mobGriefing）',
    ruleDoMobSpawning: '生物生成（doMobSpawning）',
    ruleDoWeatherCycle: '天气循环（doWeatherCycle）',
    ruleDoMobLoot: '生物掉落物（doMobLoot）',
    ruleDoTileDrops: '方块掉落物（doTileDrops）',
    ruleDoEntityDrops: '实体掉落物（doEntityDrops）',
    ruleDoNaturalRegeneration: '自然生命恢复（doNaturalRegeneration）',
    ruleDoImmediateRespawn: '立即重生（doImmediateRespawn）',
    ruleDoInsomnia: '幻翼生成（doInsomnia）',
    ruleDoPatrolSpawning: '掠夺者巡逻队（doPatrolSpawning）',
    ruleDoTraderSpawning: '流浪商人生成（doTraderSpawning）',
    ruleDrowningDamage: '溺水伤害（drowningDamage）',
    ruleFallDamage: '摔落伤害（fallDamage）',
    ruleFireDamage: '火焰伤害（fireDamage）',
    ruleFreezeDamage: '冰冻伤害（freezeDamage）',
    ruleShowDeathMessages: '死亡消息（showDeathMessages）',
    ruleAnnounceAdvancements: '公告进度（announceAdvancements）',
    ruleCommandBlockOutput: '命令方块输出（commandBlockOutput）',
    ruleSendCommandFeedback: '命令反馈（sendCommandFeedback）',
    ruleReducedDebugInfo: '简化调试信息（reducedDebugInfo）',
    ruleDisableElytraMovementCheck: '禁用鞘翅移动检查（disableElytraMovementCheck）',
    ruleSpectatorsGenerateChunks: '旁观者生成区块（spectatorsGenerateChunks）',
    ruleDoLimitedCrafting: '限制合成（doLimitedCrafting）',
    ruleRandomTickSpeed: '随机刻速度',
    ruleSpawnRadius: '出生点半径',
    ruleMaxEntityCramming: '实体堆叠上限',
    save: '保存',
    saving: '保存中...',
    saved: '存档设置已保存',
    loadFailed: '读取存档设置失败: {error}',
    saveFailed: '保存存档设置失败: {error}',
    restored: '已从 level.dat_old 恢复',
    restoreFailed: '恢复失败: {error}',
  },
  screenshots: {
    search: '搜索截图...',
    noMatch: '无匹配截图',
    empty: '暂无截图',
    type: '截图',
  },
  resourcepacks: {
    search: '搜索资源包...',
    noMatch: '无匹配资源包',
    empty: '暂无资源包',
    type: '资源包',
    install: '安装资源包',
    loadFailed: '加载资源包失败: {error}',
  },
  shaderpacks: {
    search: '搜索光影包...',
    noMatch: '无匹配光影包',
    empty: '暂无光影包',
    type: '光影包',
    install: '安装光影包',
    loadFailed: '加载光影包失败: {error}',
  },
  datapacks: {
    search: '搜索数据包...',
    noMatch: '无匹配数据包',
    empty: '暂无数据包',
    type: '数据包',
    install: '安装数据包',
  },
  schematics: {
    search: '搜索原理图...',
    noMatch: '无匹配原理图',
    empty: '暂无原理图（可导入，或放入 schematics 文件夹）',
    type: '原理图',
    import: '导入原理图',
    imported: '已导入 {name}',
    importFailed: '导入失败',
    deleteFailed: '删除失败',
    renamed: '已重命名为 {name}',
    renameFailed: '重命名失败',
    renameTitle: '重命名原理图',
    renamePlaceholder: '新文件名',
    preview: '预览',
    rename: '重命名',
    delete: '删除',
    previewTitle: '预览 {name}',
    parsing: '正在解析原理图...',
    buildingPreview: '正在构建 3D 预览...',
    overCap: '方块数过多，已降级为材料列表模式',
    overCapHint: '方块数过多，暂不渲染 3D',
    largeSize: '原理图较大（{count} 方块），渲染可能较慢',
    totalBlocks: '{count} 个方块',
    byAuthor: '作者：{author}',
    materialsOnly: '仅材料列表',
    missingBlocks: '{count} 个方块缺少材质（已用石替代显示）',
    materials: '材料 ({count})',
    copy: '复制材料列表',
    minY: '最低层',
    maxY: '最高层',
    controlsHint: '左键拖拽平移 · 中键旋转 · 滚轮缩放 · WASD 移动',
  },
  mods: {
    management: 'Mod 管理',
    noModsHint: '该实例不可使用 Mod，需要使用 Forge、Fabric 等加载器',
    search: '搜索 Mod...',
    checkUpdates: '检查更新',
    install: '安装 Mod',
    fetchingRemoteInfo: '正在获取远程信息（Modrinth/CurseForge 匹配 id、图标、中文名）...',
    readingMods: '正在读取 Mod 信息',
    loadFailed: '加载 Mod 列表失败：{error}',
    noMatch: '无匹配 Mod',
    empty: '暂无 Mod',
    enable: '启用',
    disable: '禁用',
    updateMods: '更新模组',
    filterAll: '全部',
    updatable: '可更新',
    duplicate: '重复',
    sortNameAsc: '名称 A-Z',
    sortNameDesc: '名称 Z-A',
    sortTimeDesc: '最新优先',
    sortTimeAsc: '最早优先',
    sortSizeDesc: '最大优先',
    sortSizeAsc: '最小优先',
    batchEnable: '批量启用',
    batchDisable: '批量禁用',
    batchDelete: '批量删除',
    batchConfirm: '确定要{action}{count} 个 Mod 吗？',
    moveToRecycleBin: '将被移至回收站。',
    processing: '处理中...',
    checkingUpdates: '正在检查模组更新…',
    foundUpdates: '发现 {count} 个模组可更新',
    addedToDownload: '已加入下载列表 {count} 个任务',
    updatedCount: '已更新 {count} 个模组',
    updateResult: '完成 {success} 个，失败 {failed} 个{failures}',
    updateFailed: '更新模组失败',
    loadFailedGeneric: '加载失败: {error}',
    unknownError: '未知错误',
  },
  servers: {
    search: '搜索服务器...',
    pingAll: '全部测速',
    addServer: '添加服务器',
    edit: '编辑',
    ping: '测速',
    copyIp: '复制 IP',
    quickJoin: '快速加入',
    delete: '删除',
    online: '在线',
    offline: '离线',
    pinging: '测速中...',
    lanGames: '局域网游戏 ({count})',
    lanGame: '局域网游戏',
    join: '加入',
    deleteConfirm: '确定要删除服务器「{ip}」吗？',
    deleteTitle: '删除服务器',
    addTitle: '添加服务器',
    editTitle: '编辑服务器',
    name: '服务器名称',
    address: '服务器地址',
    updating: '更新中...',
    adding: '添加中...',
    save: '保存',
    add: '添加',
    copiedIp: '已复制 IP 地址',
    copyFailed: '复制失败',
    pingDone: '测速完成: {ping}ms',
    addressOffline: '{address} 离线',
    pingFailed: '测速失败',
    deleted: '已删除服务器',
    deleteFailed: '删除失败',
    updated: '已更新「{name}」',
    added: '已添加「{name}」',
    opFailed: '操作失败',
    loadFailed: '加载服务器列表失败',
  },
  overview: {
    launch: '启动',
    unpin: '取消固定',
    pin: '固定到主页',
    gameVersion: '游戏版本',
    loader: '加载器',
    pureVanilla: '纯净原版',
    lastPlayed: '最后游玩',
    totalPlayTime: '累计游玩',
    modpackInfo: '整合包信息',
    modpackName: '整合包名称',
    version: '版本',
    author: '作者',
    summary: '简介',
    quickActions: '快速操作',
    defaultAccount: '默认账户',
    launchGame: '启动游戏',
    instanceSettings: '实例设置',
    verifyIntegrity: '检查资源完整性',
    repairing: '正在补全 {progress}%',
    openGameDir: '打开游戏目录',
    exportModpack: '导出整合包',
    deleteInstance: '删除实例',
    refresh: '刷新',
  },
  settingsTab: {
    instanceName: '实例名称',
    instanceIcon: '实例图标',
    gameVersion: '游戏版本',
    javaRuntime: 'Java 运行时',
    autoSelect: '自动选择',
    integrity: '资源完整性',
    checkIntegrity: '检查资源完整性',
    repairing: '正在补全 {progress}%',
    missingFiles: '缺失 {count} 个文件',
    autoRepairing: '正在自动补全...',
    integrityOk: '资源完整',
    versionIsolation: '版本隔离',
    followGlobal: '跟随全局设置',
    on: '开启',
    off: '关闭',
    isolationDesc: '每个版本使用独立的 mods/config/saves 目录',
    skipIntegrity: '跳过资源完整性检查',
    skipIntegrityDesc: '启动时跳过文件完整性检查，可能因缺少文件导致游戏崩溃',
    memoryAllocation: '内存分配',
    auto: '自动',
    custom: '自定义',
    totalMem: '总内存 {size} GiB',
    usedMem: '已使用 {size} GiB',
    gameAlloc: '游戏分配 {size} GiB',
    remainingMem: '剩余 {size} GiB',
    jvmArgs: 'JVM 参数',
    linkedAccount: '关联账号',
    unlinked: '未关联',
    saving: '保存中...',
  },
  gamesettings: {
    search: '搜索设置项...',
    noMatch: '无匹配设置项',
    empty: '暂无游戏设置',
    pressKey: '按下按键...',
    add: '添加',
    addPlaceholder: '输入名称…',
    remove: '移除',
    keys: {
      unbound: '未绑定',
      space: '空格',
      enter: '回车',
      backspace: '退格',
      leftShift: '左 Shift',
      rightShift: '右 Shift',
      leftControl: '左 Ctrl',
      rightControl: '右 Ctrl',
      leftAlt: '左 Alt',
      rightAlt: '右 Alt',
      leftSuper: '左 Win',
      rightSuper: '右 Win',
      menu: '菜单键',
      mouseLeft: '鼠标左键',
      mouseRight: '鼠标右键',
      mouseMiddle: '鼠标中键',
      mouseButton: '鼠标按键 {n}',
      keypad: '小键盘 {n}',
      keypadAdd: '小键盘 +',
      keypadSubtract: '小键盘 -',
      keypadMultiply: '小键盘 *',
      keypadDivide: '小键盘 /',
      keypadDecimal: '小键盘 .',
      keypadEnter: '小键盘 回车',
    },
  },
  launch: {
    launchFailed: '启动失败',
    instanceRunningConfirm: '当前实例正在运行中，是否启动新实例？',
    instanceRunningTitle: '实例运行中',
    backToList: '返回实例列表',
    instanceNotFound: '实例不存在',
    loadingInstance: '加载实例...',
    deleteInstanceConfirm: '确定要删除实例「{name}」吗？其版本文件夹将被永久删除。',
  },
} as const
