// 插件（zh-CN）
export default {
  notFound: '插件未找到',
  notActivated: '插件未激活',
  installTitle: '安装插件',
  permissionsRequest: '此插件申请以下权限：',
  highRisk: '高危权限',
  caution: '需注意',
  normal: '普通',
  cancel: '取消',
  confirmInstall: '确认安装',
  fileAuthRequest: '插件「{pluginId}」请求访问路径：\n{path}\n\n是否允许？',
  fileAuthDenied: '用户拒绝了文件访问授权',
  fileAuthFailed: '授权失败',
  permission: {
    instanceRead: '读取实例列表',
    instanceWrite: '创建/修改/删除实例',
    accountRead: '读取账号列表',
    licenseRead: '读取许可证信息',
    configRead: '读取启动器配置',
    configWrite: '修改启动器配置',
    cacheAccess: '读写插件缓存',
    endpointDiscover: '获取后端 API 端点',
    pageList: '获取页面列表',
    networkFetch: '发送 HTTP 请求',
    networkCorsProxy: 'CORS 代理请求',
    networkWebsocket: 'WebSocket 连接',
    networkProxy: '修改代理设置',
    uiInjectSidebar: '注入侧边栏菜单',
    uiInjectSettings: '注入设置页',
    uiPictureInPicture: '画中画窗口',
    uiSubWindow: '独立子窗口',
    uiContextMenu: '注入右键菜单',
    uiToast: '应用内通知',
    uiNavigate: '跳转页面',
    systemInfo: '读取系统和启动器信息',
    systemNotification: '发送系统通知',
    clipboardRead: '读取剪贴板',
    clipboardWrite: '写入剪贴板',
    wasmExecute: '执行 WASM 模块',
    pluginInstall: '安装/卸载/更新插件',
    pluginList: '读取已安装插件列表',
    resourceRead: '读取游戏资源文件',
    resourceWrite: '写入游戏资源文件',
    javaManage: '管理 Java 运行时',
    downloadManage: '管理下载任务',
    gameProcess: '启停游戏进程',
    gameLog: '检测游戏日志',
    connectorHost: '启停联机',
    connectorScan: '扫描局域网联机',
    shellExecute: '执行系统命令',
    filesystemRead: '读取文件系统',
    filesystemWrite: '写入文件系统',
  },
} as const
