// 资源中心（zh-CN）
export default {
  categories: {
    mod: '模组',
    modpack: '整合包',
    shader: '光影',
    resourcepack: '材质包',
    datapack: '数据包',
    save: '存档',
  },
  sort: {
    relevance: '相关度',
    downloads: '下载量',
    updated: '更新时间',
    newest: '最新发布',
    name: '名称',
    recommended: '推荐',
    installs: '安装量',
  },
  unknownAuthor: '未知作者',
  install: '安装',
  viewDetail: '查看详情',
  originalSite: '原站',
  searchFailed: '搜索失败',
  backendUnreachable: '无法连接到后端服务，请确保后端已启动',
  title: '资源中心',
  sourceLabel: '资源源',
  categoryLabel: '资源分类',
  searchPlaceholder: '搜索{category}...',
  search: '搜索',
  gameVersionLabel: '游戏版本',
  allVersions: '全部版本',
  loaderLabel: '加载器',
  allLoaders: '全部加载器',
  notFound: '未找到相关资源',
  notFoundHint: '尝试更换关键词、资源源或分类',
  retry: '重试',
  loading: '加载中...',
  loadMore: '加载更多（{current}/{total}）',
  allShown: '已显示全部 {count} 个结果',
} as const
