// 资源中心（zh-CN）
export default {
  sources: {
    all: '全部',
  },
  categories: {
    mod: '模组',
    modpack: '整合包',
    shader: '光影',
    resourcepack: '材质包',
    datapack: '数据包',
    save: '存档',
  },
  sort: {
    relevance: '相关度',
    downloads: '下载量',
    updated: '更新时间',
    newest: '最新发布',
    name: '名称',
    recommended: '推荐',
    installs: '安装量',
  },
  unknownAuthor: '未知作者',
  install: '安装',
  viewDetail: '查看详情',
  originalSite: '原站',
  searchFailed: '搜索失败',
  backendUnreachable: '无法连接到后端服务，请确保后端已启动',
  title: '资源中心',
  sourceLabel: '资源源',
  categoryLabel: '资源分类',
  searchPlaceholder: '搜索{category}...',
  search: '搜索',
  gameVersionLabel: '游戏版本',
  allVersions: '全部版本',
  loaderLabel: '加载器',
  allLoaders: '全部加载器',
  categoryFilterLabel: '类别筛选',
  clearFilter: '清除筛选',
  expandTags: '展开全部',
  collapseTags: '收起',
  notFound: '未找到相关资源',
  notFoundHint: '尝试更换关键词、资源源或分类',
  retry: '重试',
  loading: '加载中...',
  loadMore: '加载更多（{current}/{total}）',
  allShown: '已显示全部 {count} 个结果',
  mode: {
    label: '浏览模式',
    browse: '资源',
    searchPlaceholder: '搜索资源、关键词...',
  },
  favorites: {
    viewSearch: '搜索',
    viewLabel: '收藏',
    viewLabelWithCount: '收藏（{count}）',
    searchPlaceholder: '搜索收藏...',
    add: '收藏',
    remove: '取消收藏',
    added: '已加入收藏',
    removed: '已取消收藏',
    failed: '收藏操作失败',
    loadFailed: '收藏加载失败',
    emptyTitle: '还没有收藏',
    emptyHint: '在搜索结果或资源详情页点击 ♥ 即可收藏',
    filteredEmpty: '当前筛选条件下没有收藏',
    filteredEmptyHint: '切换上方资源源 / 资源分类，或左侧收藏夹与标签筛选',
    allShown: '共 {count} 个收藏',
    folders: {
      railTitle: '收藏夹',
      all: '全部',
      unfiled: '未分组',
      loading: '加载中...',
      create: '新建收藏夹',
      createPlaceholder: '收藏夹名称',
      rename: '重命名',
      renamePlaceholder: '收藏夹名称',
      emptyName: '收藏夹名称不能为空',
      created: '已创建收藏夹「{name}」',
      renamed: '已重命名收藏夹',
      failed: '收藏夹操作失败',
      delete: '删除',
      deleteTitle: '删除收藏夹',
      deleteBodyWithItems: '「{name}」及其中的 {count} 个收藏都会被删除，此操作不可撤销。',
      deleteBodyEmpty: '「{name}」中没有收藏，删除后不可撤销。',
      deleted: '已删除收藏夹（含 {count} 个收藏）',
    },
    note: {
      label: '备注',
      placeholder: '记录用途、版本要求等',
    },
    tags: {
      label: '标签',
      filterLabel: '标签筛选',
      placeholder: '输入标签后回车',
      remove: '移除标签「{tag}」',
      hint: '回车或逗号添加，最多 {max} 个',
      limitReached: '已达上限 {max} 个',
    },
    edit: {
      open: '编辑收藏',
      title: '编辑收藏',
      folderLabel: '收藏夹',
      none: '未分组',
      cancel: '取消',
      save: '保存',
      saving: '保存中...',
      saved: '已保存',
      failed: '保存失败',
    },
  },
} as const
