// 资源详情（zh-CN）
export default {
  prereqMods: '前置模组',
  basedOn: '基于 {version} 解析',
  parsingPrereq: '正在解析前置模组...',
  noPrereq: '此版本没有前置模组',
  addedToDownload: '已加入下载列表',
  downloadFailed: '下载失败',
  exportFailed: '导出失败',
  loadDetailFailed: '加载资源详情失败',
  loadVersionsTimeout: '加载版本列表超时',
  loadVersionsFailed: '加载版本列表失败',
  title: '资源详情',
  refresh: '刷新',
  originalPage: '原始页面',
  loadFailed: '加载失败',
  notFound: '资源不存在',
  latest: '最新 {version}',
  noDescription: '暂无简介',
  translating: '翻译中...',
  collapseTranslation: '收起翻译',
  translateDescription: '翻译简介',
  translatedMark: '译',
  unknownAuthor: '未知作者',
  categoryTags: '分类标签',
  detailedIntro: '详细介绍',
  showOriginal: '显示原文',
  translateBody: '翻译详细介绍',
  expand: '展开',
  collapse: '收起',
  noMoreContent: '暂无更多介绍',
  selectVersionInstall: '选择版本安装',
  gameVersion: '游戏版本',
  allVersions: '全部版本',
  loader: '加载器',
  allLoaders: '全部加载器',
  fetchingVersions: '正在获取版本列表',
  versionCount: '共 {count} 个版本',
  filteredCount: '筛选后 {count} 个',
  noVersionUnderFilter: '当前筛选条件下没有可用版本',
  install: '安装',
  saveAs: '另存为',
  loading: '加载中...',
  getDownload: '获取下载',
  noDownload: '暂无下载',
  loadMore: '加载更多 ({count} 个)',
} as const
