// 运行/启动流程（zh-CN）
export default {
  gameCrashed: '游戏已崩溃',
  gameCrashTitle: '游戏崩溃',
  launchFailedTitle: '启动失败',
  gameExitedAbnormally: '游戏异常退出 (代码: {code})',
  launchError: '启动过程中出现错误',
  analysisUnavailable: '分析服务暂不可用',
  gameExited: '游戏已退出',
  gameStarted: '游戏已启动',
  preparingLaunch: '准备启动...',
  javaIncompatibleTitle: 'Java 版本不兼容',
  javaIncompatible: '当前选择的 Java {current} 不满足 Minecraft {game} 的需求（需要 Java {required}），是否继续启动？',
  launchCancelled: '已取消启动',
  gameStopped: '已停止游戏',
  timeSeconds: '{count}秒',
  timeMinutes: '{count}分{sec}秒',
  timeHours: '{hours}小时{mins}分',
  instancesRunning: '{count} 个实例正在运行',
  noRunningGame: '暂无运行中的游戏',
  goToInstances: '前往实例管理',
  title: '运行中的游戏',
  runningFor: '已运行 {time}',
} as const
