// 设置页（zh-CN；批0 含 category 导航 + appearance 外观核心项，其余由迁移批次补充）
export default {
  category: {
    launcher: '启动器设置',
    basic: '基础设置',
    launch: '启动设置',
    download: '下载设置',
    storage: '储存与缓存',
    network: '网络设置',
    java: 'Java 运行时',
    plugins: '插件',
    appearance: '外观',
    toolbox: '工具箱',
    logs: '日志',
    about: '关于',
    debug: '调试',
  },
  saved: '设置已保存',
  appearance: {
    title: '界面',
    language: '界面语言',
    followSystem: '跟随系统',
    theme: '主题',
    themePreset: '主题预设',
    dark: '深色',
    light: '亮色',
    themeColor: '主题色',
    themeColorCustom: '自定义颜色',
    themeColorBackground: '跟随背景（莫奈取色）',
    themeColorReset: '恢复默认',
    themeColorDesc: '自定义全局强调色，用于按钮、高亮与选中态。设为默认时使用启动器默认配色。',
    componentMaterial: '组件材质',
    componentMaterialDefault: '默认',
    componentMaterialFrosted: '毛玻璃',
    componentMaterialAcrylic: '亚克力玻璃',
    componentMaterialAero: 'Aero',
    componentMaterialLiquid: '液态玻璃',
    componentMaterialLiquidPreview: '液态玻璃（预览）',
    componentMaterialLiquidWarning: '预览功能：液态玻璃对每个卡片实时做位移折射渲染，性能开销较大；长列表（如大量模组）可能出现明显卡顿甚至界面无响应。',
    componentMaterialLiquidConfirmTitle: '启用液态玻璃？',
    componentMaterialLiquidConfirmBody: '液态玻璃为预览功能，性能开销较大；长列表（如大量模组）可能明显卡顿甚至界面无响应。仍要启用吗？',
    glassBlurLow: '清晰',
    glassBlurHigh: '模糊',
    animations: '页面动画',
    animationsDesc: '开启后页面切换、弹窗等带有过渡动画效果',
    animationSpeed: '动画速度',
    slow: '慢',
    normal: '正常',
    fast: '快',
    maxFrameRate: '帧率上限',
    maxFrameRateUnlimited: '不限',
    maxFrameRateDesc: '限制启动器界面的渲染帧率，降低资源占用。设为不限则使用显示器的原始刷新率。',
    cornerRadius: '圆角',
    windowCorners: '窗口圆角',
    windowCornersDesc: '仅在不使用系统框架时生效',
    cornerSharp: '直角',
    cornerDefault: '默认（8px）',
    cornerLarge: '大圆角',
    font: '字体',
    fontFamily: '界面字体',
    fontDefault: '默认字体',
    fontDesc: '选择系统已安装字体，全局 UI 立即生效',
    fontPreviewTitle: '字体预览',
    fontPreviewText: 'Qomicex 启动器 — 中文示例 123 ABC',
    fontReset: '恢复默认字体',
    background: '背景',
    backgroundImage: '背景图片',
    noBackgrounds: '暂无背景图片',
    openFolder: '打开文件夹',
    backgroundsHint: '放入图片即可出现在上方列表中',
    backgroundRandom: '每次启动随机挑选',
    backgroundRandomDesc: '从背景文件夹中随机选择一张图片',
    clearBackground: '清除背景',
    opacity: '不透明度',
    transparent: '透明',
    opaque: '不透明',
    blur: '模糊',
    sharp: '清晰',
    watermark: '水印',
    watermarkEnabled: '显示主页水印文字',
    watermarkEnabledDesc: '在主页中央显示可自定义的文字',
    watermarkText: '水印内容',
    watermarkSubtext: '副标题',
    watermarkSubtextPlaceholder: '启动器',
  },
  launcher: {
    title: '启动器设置',
    dataDir: '数据目录',
    dataDirDesc: '启动器数据存储位置，更改后需重启启动器生效',
    dataDirChanged: '数据目录已更改，重启启动器后生效',
    saveFailed: '设置失败',
    downloadThreads: '下载线程数',
    downloadThreadsDesc: '同时下载的文件数量（1-512），数值越大下载越快但占用带宽越多',
    fileChunkThreads: '分片线程数',
    fileChunkThreadsDesc: '单个文件分片并行的数量：关闭=不分片直传，自动=引擎默认，或手动指定 1-16',
    fileChunkThreadsOff: '关闭',
    fileChunkThreadsAuto: '自动',
    versionIsolation: '版本隔离',
    versionIsolationDesc: '每个版本使用独立的 mods/config/saves 目录，推荐保持开启',
    closeAfterLaunch: '启动游戏后关闭启动器',
    closeAfterLaunchDesc: '游戏启动后自动关闭本启动器',
    autoReportErrors: '自动上报严重错误日志',
    autoReportErrorsDesc: '启动器出现崩溃等严重错误时，自动上传错误日志与设备信息（系统/硬件）帮助定位问题；普通启动失败、下载安装错误不会上报',
    telemetry: '匿名插件错误遥测',
    telemetryDesc: '开启后，插件加载或运行出错时自动上报匿名错误类别（仅插件 ID、版本、错误类型与启动器版本，不含路径、堆栈或任何隐私数据），用于自动暂停异常的插件版本灰度。默认关闭',
    downloadSource: '下载源',
    downloadSourceName: { 0: '官方源', 1: 'BMCLAPI 镜像' },
    modSource: '资源下载源',
    modSourceName: { 0: 'Modrinth/CurseForge 官方', 1: 'MCIM 镜像' },
    resourceDownloadSource: '文件下载源',
    resourceDownloadSourceName: { 0: '官方源', 1: 'QML Mirror', 2: 'QML Mirror HK' },
    resourceDownloadSourceDesc: '选择 MOD 文件下载用的 CDN：官方源直连原站，QML Mirror 为QML镜像。',
    autoSelectFileDownloadSource: '自动选择下载源',
    autoSelectFileDownloadSourceDesc: '自动选用延迟最低的可用下载源',
    refreshLatency: '刷新延迟',
    autoSelectDownloadSource: '自动选择最快下载源',
    autoSelectDownloadSourceDesc: '启动时和每次安装前自动检测并选择延迟最低的下载源',
    autoSelectModSource: '自动选择最快资源下载源',
    autoSelectModSourceDesc: '自动检测 Modrinth/CurseForge API 镜像并选择延迟最低的',
    translationProvider: '翻译接口',
    translationDefault: 'MyMemory (默认)',
    translationGoogle: 'Google Translate (需梯子)',
    translationProviderDesc: '选择翻译资源详细介绍和简介时使用的翻译服务',
    bingApiKeyPlaceholder: '输入 Azure Translator API Key',
    bingApiKeyDesc: '在 Azure Portal 创建 Translator 资源获取 Key，区域需设为 global',
    downloadTimeout: '下载超时 (秒)',
    downloadTimeoutDesc: '单个文件下载无响应超过此时间则自动重试（0=不超时，1-120 秒）',
    enableHttp3: '启用 HTTP/3 文件下载（实验性）',
    enableHttp3Desc: '开启后下载优先使用 HTTP/3，服务器不支持时自动回退到 HTTP/2；关闭则强制使用 HTTP/2',
    http1Parallel: '强制 HTTP/1.1 并行连接下载',
    http1ParallelDesc: '开启时所有下载都用独立 TCP 连接并行。默认关闭 = 按来源自动：Modrinth 等按连接限速的源自动用并行，Mojang/BMCLAPI 等其余源用 HTTP/2',
    fileNaming: '资源文件命名方式',
    fileNamingDesc: '自定义下载资源（Mod/光影/材质等）的文件命名格式，仅对新下载的文件生效',
    naming: {
      cnNameVer: '[中文名]英文名-版本',
      nameCnVer: '[英文名]中文名-版本',
      cnNamePlainVer: '中文名-英文名-版本',
      cnVer: '中文名-版本',
      nameVer: '英文名-版本',
      cn: '中文名',
      name: '英文名',
    },
    logLevelLabel: '日志等级',
    logLevel: { error: '错误', warn: '警告', info: '信息', debug: '调试', trace: '跟踪' },
    logLevelDesc: '控制控制台和日志文件的输出详细程度，信息等级为默认',
    storageCache: '存储与缓存',
    versionListCache: '版本列表缓存',
    versionListCacheDesc: '清理 Forge 版本列表的 HTML 缓存文件',
    clearCache: '清理缓存',
    curseforgeConcurrency: 'CurseForge 版本列表并发数',
    curseforgeConcurrencyDesc: '同时拉取的页面数量（1-20），数值越大版本列表加载越快',
    curseforgeTtl: 'CurseForge 版本列表缓存有效期（秒）',
    curseforgeTtlDesc: '0 = 永久缓存（直到重启或手动清除），默认 300 秒（5 分钟）',
    curseforgeCache: 'CurseForge 版本缓存',
    curseforgeCacheDesc: '清除 CurseForge 版本列表的内存缓存',
    clearCurseforgeCache: '清除 CurseForge 版本缓存',
    cacheCleared: '已清理缓存，删除 {count} 个文件',
    cacheClearFailed: '清理缓存失败',
    curseforgeCacheCleared: 'CurseForge 版本缓存已清除',
    curseforgeCacheClearFailed: '清除 CurseForge 缓存失败',
  },
  network: {
    title: '网络设置',
    proxy: '代理设置',
    proxyMode: '代理类型',
    proxyOff: '不使用代理',
    proxySystem: '使用系统代理',
    http: 'HTTP(S) 代理',
    socks5: 'SOCKS5 代理',
    proxyModeDesc: '为下载和资源请求配置代理服务器',
    proxyHost: '代理服务器地址',
    proxyHostPlaceholder: '例如 127.0.0.1:7890',
    proxyHostDesc: '格式为 host:port；仅当选择了 HTTP(S) 或 SOCKS5 代理时生效',
    ignoreSslCert: '忽略 SSL 证书校验',
    ignoreSslCertDesc: '下载或请求时不校验 TLS 证书（适用于自签名证书/内网代理等场景，请谨慎开启）',
  },
  java: {
    title: 'Java 运行时',
    ready: '就绪',
    detected: '已检测',
    available: '可用',
    quickScan: '快速扫描',
    deepScan: '深度扫描',
    manualAdd: '手动添加',
    downloadJava: '下载 Java',
    refreshList: '刷新列表',
    scanningQuick: '正在快速扫描...',
    scanningDeep: '正在深度扫描...',
    scanDoneFound: '扫描完成，发现 {count} 个新版',
    scanDoneNone: '扫描完成，无新版',
    scanFailed: '扫描失败',
    refreshing: '正在刷新...',
    scanningRuntime: '正在扫描 Java 运行时...',
    noRuntimeDetected: '尚未检测到 Java 运行时',
    noRuntimeHint: '点击"快速扫描"自动检测系统中的 Java，或手动添加',
    startScan: '开始扫描',
    usable: '可用',
    unusable: '不可用',
    openFolder: '打开文件夹',
    availableCount: '{valid} / {total} 可用',
    showInvalid: '显示无效项',
    defaultConfig: '默认配置',
    defaultRuntime: '默认 Java 运行时',
    autoSelect: '自动选择',
    defaultRuntimeDesc: '推荐使用自动选择，启动器会为每个游戏版本自动匹配最佳 Java 运行时',
    memoryAllocation: '内存分配',
    memoryAuto: '自动',
    memoryCustom: '自定义',
    totalMemory: '总内存 {value} GiB',
    usedMemory: '已使用 {value} GiB',
    gameMemory: '游戏分配 {value} GiB',
    remainingMemory: '剩余 {value} GiB',
    jvmArgs: '额外 JVM 参数',
    jvmArgsDesc: '启动 Minecraft 时附加的 JVM 参数',
    jvmArgsWarning: '非专业玩家请勿修改，错误的 JVM 参数可能导致游戏无法启动',
    pickJavaExecutable: '选择 Java 可执行文件',
    unrecognizedPath: '无法识别该路径下的 Java 运行时',
    added: '已添加 {name} {version}',
    loadCatalogFailed: '加载 Java 下载目录失败',
    addedToDownload: '已加入下载中心: {name}',
    downloadFailed: '启动 Java 下载失败',
    deleteConfirm: '确定要删除 "{name}" 吗？',
    deleteTitle: '删除 Java',
    deleted: '已删除 {name}',
    deleteFailed: '删除失败',
    manualAddTitle: '手动添加 Java',
    executablePath: 'Java 可执行文件路径',
    browse: '浏览',
    executablePathDesc: '选择或输入 Java 可执行文件的完整路径',
    verifying: '验证中...',
    add: '添加',
    distribution: '发行版',
    recommended: '(推荐)',
    mainVersion: 'Java 主版本',
    platform: '平台',
    architecture: '架构',
    targetDir: '目标目录',
    resolving: '解析中...',
    startDownload: '开始下载',
  },
  plugins: {
    title: '插件管理',
    installedCount: '{count} 个已安装',
    searchPlaceholder: '搜索插件...',
    installing: '安装中...',
    install: '安装插件',
    noneInstalled: '尚未安装任何插件',
    noMatch: '无匹配的插件',
    changesApplied: '更改已生效',
    saveFailed: '保存失败',
    uninstallConfirm: '确定卸载此插件？',
    uninstalled: '插件已卸载',
    uninstallFailed: '卸载失败',
    installSuccess: '插件安装成功',
    installFailed: '安装失败: {message}',
    permissions: '权限 ({count})',
    contributes: '扩展点',
    store: {
      tabBrowse: '浏览插件',
      tabManage: '插件管理',
      tabAccount: '账户管理',
      searchPlaceholder: '搜索商店插件...',
      categoryAll: '全部',
      categoryTool: '工具',
      categoryLauncher: '启动器',
      categoryTheme: '主题',
      categoryIntegration: '集成',
      sortLatest: '最新发布',
      sortDownloads: '最多下载',
      downloadsCount: '{count} 次下载',
      loadFailed: '插件商店加载失败',
      emptyResult: '没有匹配的插件',
      prevPage: '上一页',
      nextPage: '下一页',
      pageInfo: '第 {page} / {total} 页',
      installedBadge: '已安装',
      updatableBadge: '可更新 v{version}',
      installBtn: '安装',
      updateBtn: '更新',
      reinstallBtn: '重装',
      installConfirmTitle: '安装插件',
      updateConfirmTitle: '更新插件',
      installConfirmDesc: '即将安装「{name}」v{version}。',
      permissionsNotice: '该插件申请以下权限：',
      noPermissions: '该插件未申请任何权限。',
      installing: '安装中...',
      installSuccess: '插件安装成功',
      installFailed: '安装失败：{message}',
      detailVersions: '版本历史',
      detailReviews: '用户评价（{count}）',
      noReviews: '暂无评价',
      developerLabel: '开发者',
      permissionsCount: '{count} 项权限',
      checkUpdates: '检查更新',
      checkingUpdates: '检查中...',
      allUpToDate: '全部插件均为最新版本',
      updatesAvailable: '{count} 个插件可更新',
      rollbackBtn: '回滚',
      rollbackConfirm: '将「{name}」回滚到上一个版本？',
      rollbackSuccess: '已回滚到上一个版本',
      rollbackFailed: '回滚失败：{message}',
      localInstall: '本地安装',
      deviceLoginDesc: '使用设备码登录：无需在本机输入密码，授权过程在浏览器中完成。',
      deviceStart: '发起登录',
      deviceCodeLabel: '授权码',
      deviceCopy: '复制',
      deviceCopied: '授权码已复制',
      deviceCopyFailed: '复制失败，请手动记录授权码',
      deviceOpenPage: '打开授权页面',
      deviceSteps: '点击「打开授权页面」→ 登录插件商店 → 输入上方授权码并确认授权，完成后此处会自动登录。',
      deviceWaiting: '等待授权中…',
      deviceExpired: '授权码已过期，请重新发起登录',
      deviceCancel: '取消',
      loginSuccess: '登录成功',
      loggedOut: '已退出登录',
      logout: '退出登录',
      roleUser: '普通用户',
      roleDeveloper: '开发者',
      roleAdmin: '管理员',
      levelIndividual: '个人认证',
      levelOrganization: '组织认证',
      levelOfficial: '官方认证',
      myPlugins: '我的插件',
      myPluginsEmpty: '尚未发布任何插件',
    },
  },
  about: {
    aboutApp: '关于 {name}',
    beta: '测试版',
    stable: '稳定版',
    feedback: '反馈',
    viewRepository: '查看仓库',
    versionInfo: '版本信息',
    appVersion: '应用版本',
    versionHash: '版本哈希',
    os: '操作系统',
    architecture: '系统架构',
    memory: '内存',
    license: '许可证',
    licenseActivated: '已激活',
    licenseNotActivated: '未激活',
    licenseInvalid: '无效',
    channel: '频道',
    expiry: '到期',
    permanent: '永久有效',
    machineCode: '机器码',
    changeLicense: '更换许可证',
    activateLicense: '激活许可证',
    copyMachineCode: '复制机器码',
    update: '更新',
    checking: '检查中...',
    checkUpdate: '检查更新',
    upToDate: '已是最新版本',
    checkUpdateFailed: '检查更新失败',
    developers: '开发者',
    acknowledgements: '鸣谢',
    referenceProjects: '参考项目',
    backendDependencies: '后端依赖',
    frontendDependencies: '前端依赖',
    openSourceLicense: '开源协议',
    licenseNotice: '本程序基于 {name} 开源协议发布',
    viewLicense: '查看协议',
    copyrightPrivacy: '版权与隐私',
    copyrightStatement: '版权声明',
    copyrightStatementDesc: '查看本软件的版权归属与开源许可信息',
    userAgreement: '用户协议',
    privacyPolicy: '隐私政策',
    appDescription: '一个现代化的 Minecraft 启动器，支持多版本管理、模组加载器兼容、账户管理等功能。',
    roleProjectLead: '项目发起人 / 主要开发者',
    serviceModrinth: 'Mod 和资源搜索 API',
    serviceModpack: '整合包 API',
    serviceBmclapi: '提供BMCLAPI下载镜像服务',
    serviceMcmod: '中文 Mod 数据库',
    serviceMinecraft: 'Minecraft 官方网站,支持正版!',
    serviceMinecraftName: 'Minecraft 官网',
    serviceModrinthName: 'Modrinth',
    serviceCurseForgeName: 'CurseForge',
    serviceFtbName: 'FTB',
    serviceBmclapiName: 'bangbang93',
    serviceMcmodName: 'mcmod',
    refVersionCheck: '版本检测参考',
    refModloaderInstaller: 'ModLoader 安装器参考',
    refLaunchFlow: '启动流程参考',
    depBackendRuntime: 'Rust 后端运行时',
    depCoreLibraries: '核心库',
    depCoreFramework: '核心框架',
    depUiComponents: 'UI 组件',
    depStylesTools: '样式与工具',
    depAnimation: '动画',
    depRendering: '渲染与展示',
    depInHouse: '自研',
  },
} as const
