// 设置页（zh-CN；批0 含 category 导航 + appearance 外观核心项，其余由迁移批次补充）
export default {
  category: {
    launcher: '启动器',
    java: 'Java 运行时',
    plugins: '插件',
    appearance: '外观',
    toolbox: '工具箱',
    logs: '日志',
    about: '关于',
    debug: '调试',
  },
  saved: '设置已保存',
  appearance: {
    title: '界面',
    language: '界面语言',
    theme: '主题',
    dark: '深色',
    light: '亮色',
    animations: '页面动画',
    animationsDesc: '开启后页面切换、弹窗等带有过渡动画效果',
    animationSpeed: '动画速度',
    slow: '慢',
    normal: '正常',
    fast: '快',
    maxFrameRate: '帧率上限',
    maxFrameRateUnlimited: '不限',
    maxFrameRateDesc: '限制启动器界面的渲染帧率，降低资源占用。设为不限则使用显示器的原始刷新率。',
    cornerRadius: '圆角',
    windowCorners: '窗口圆角',
    windowCornersDesc: '仅在不使用系统框架时生效',
    cornerSharp: '直角',
    cornerDefault: '默认（8px）',
    cornerLarge: '大圆角',
    background: '背景',
    backgroundImage: '背景图片',
    noBackgrounds: '暂无背景图片',
    openFolder: '打开文件夹',
    backgroundsHint: '放入图片即可出现在上方列表中',
    backgroundRandom: '每次启动随机挑选',
    backgroundRandomDesc: '从背景文件夹中随机选择一张图片',
    clearBackground: '清除背景',
    opacity: '不透明度',
    transparent: '透明',
    opaque: '不透明',
    blur: '模糊',
    sharp: '清晰',
    watermark: '水印',
    watermarkEnabled: '显示主页水印文字',
    watermarkEnabledDesc: '在主页中央显示可自定义的文字',
    watermarkText: '水印内容',
    watermarkSubtext: '副标题',
    watermarkSubtextPlaceholder: '启动器',
  },
  launcher: {
    title: '启动器设置',
    dataDir: '数据目录',
    dataDirDesc: '启动器数据存储位置，更改后需重启启动器生效',
    dataDirChanged: '数据目录已更改，重启启动器后生效',
    saveFailed: '设置失败',
    downloadThreads: '下载线程数',
    downloadThreadsDesc: '同时下载的文件数量（1-512），数值越大下载越快但占用带宽越多',
    fileChunkThreads: '分片线程数',
    fileChunkThreadsDesc: '单文件分片下载线程数（0=自动，最大 16），数值越大单文件下载越快',
    maxConnections: '最大连接数',
    maxConnectionsDesc: '每个服务器的最大连接数（8-256），重启后生效',
    versionIsolation: '版本隔离',
    versionIsolationDesc: '每个版本使用独立的 mods/config/saves 目录，推荐保持开启',
    closeAfterLaunch: '启动游戏后关闭启动器',
    closeAfterLaunchDesc: '游戏启动后自动关闭本启动器',
    downloadSource: '下载源',
    downloadSourceName: { 0: '官方源', 1: 'BMCLAPI 镜像' },
    modSource: '资源下载源',
    modSourceName: { 0: 'Modrinth/CurseForge 官方', 1: 'MCIM 镜像' },
    refreshLatency: '刷新延迟',
    autoSelectDownloadSource: '自动选择最快下载源',
    autoSelectDownloadSourceDesc: '启动时和每次安装前自动检测并选择延迟最低的下载源',
    autoSelectModSource: '自动选择最快资源下载源',
    autoSelectModSourceDesc: '自动检测 Modrinth/CurseForge API 镜像并选择延迟最低的',
    translationProvider: '翻译接口',
    translationDefault: 'MyMemory (默认)',
    translationGoogle: 'Google Translate (需梯子)',
    translationProviderDesc: '选择翻译资源详细介绍和简介时使用的翻译服务',
    bingApiKeyPlaceholder: '输入 Azure Translator API Key',
    bingApiKeyDesc: '在 Azure Portal 创建 Translator 资源获取 Key，区域需设为 global',
    downloadTimeout: '下载超时 (秒)',
    downloadTimeoutDesc: '单个文件下载无响应超过此时间则自动重试（0=不超时，1-120 秒）',
    logLevelLabel: '日志等级',
    logLevel: { error: '错误', warn: '警告', info: '信息', debug: '调试', trace: '跟踪' },
    logLevelDesc: '控制控制台和日志文件的输出详细程度，信息等级为默认',
    storageCache: '存储与缓存',
    versionListCache: '版本列表缓存',
    versionListCacheDesc: '清理 Forge 版本列表的 HTML 缓存文件',
    clearCache: '清理缓存',
    curseforgeConcurrency: 'CurseForge 版本列表并发数',
    curseforgeConcurrencyDesc: '同时拉取的页面数量（1-20），数值越大版本列表加载越快',
    curseforgeTtl: 'CurseForge 版本列表缓存有效期（秒）',
    curseforgeTtlDesc: '0 = 永久缓存（直到重启或手动清除），默认 300 秒（5 分钟）',
    curseforgeCache: 'CurseForge 版本缓存',
    curseforgeCacheDesc: '清除 CurseForge 版本列表的内存缓存',
    clearCurseforgeCache: '清除 CurseForge 版本缓存',
    cacheCleared: '已清理缓存，删除 {count} 个文件',
    cacheClearFailed: '清理缓存失败',
    curseforgeCacheCleared: 'CurseForge 版本缓存已清除',
    curseforgeCacheClearFailed: '清除 CurseForge 缓存失败',
  },
  java: {
    title: 'Java 运行时',
    ready: '就绪',
    detected: '已检测',
    available: '可用',
    quickScan: '快速扫描',
    deepScan: '深度扫描',
    manualAdd: '手动添加',
    downloadJava: '下载 Java',
    refreshList: '刷新列表',
    scanningQuick: '正在快速扫描...',
    scanningDeep: '正在深度扫描...',
    scanDoneFound: '扫描完成，发现 {count} 个新版',
    scanDoneNone: '扫描完成，无新版',
    scanFailed: '扫描失败',
    refreshing: '正在刷新...',
    scanningRuntime: '正在扫描 Java 运行时...',
    noRuntimeDetected: '尚未检测到 Java 运行时',
    noRuntimeHint: '点击"快速扫描"自动检测系统中的 Java，或手动添加',
    startScan: '开始扫描',
    usable: '可用',
    unusable: '不可用',
    openFolder: '打开文件夹',
    availableCount: '{valid} / {total} 可用',
    defaultConfig: '默认配置',
    defaultRuntime: '默认 Java 运行时',
    autoSelect: '自动选择',
    defaultRuntimeDesc: '推荐使用自动选择，启动器会为每个游戏版本自动匹配最佳 Java 运行时',
    memoryAllocation: '内存分配',
    memoryAuto: '自动',
    memoryCustom: '自定义',
    totalMemory: '总内存 {value} GiB',
    usedMemory: '已使用 {value} GiB',
    gameMemory: '游戏分配 {value} GiB',
    remainingMemory: '剩余 {value} GiB',
    jvmArgs: '额外 JVM 参数',
    jvmArgsDesc: '启动 Minecraft 时附加的 JVM 参数',
    pickJavaExecutable: '选择 Java 可执行文件',
    unrecognizedPath: '无法识别该路径下的 Java 运行时',
    added: '已添加 {name} {version}',
    loadCatalogFailed: '加载 Java 下载目录失败',
    addedToDownload: '已加入下载中心: {name}',
    downloadFailed: '启动 Java 下载失败',
    deleteConfirm: '确定要删除 "{name}" 吗？',
    deleteTitle: '删除 Java',
    deleted: '已删除 {name}',
    deleteFailed: '删除失败',
    manualAddTitle: '手动添加 Java',
    executablePath: 'Java 可执行文件路径',
    browse: '浏览',
    executablePathDesc: '选择或输入 Java 可执行文件的完整路径',
    verifying: '验证中...',
    add: '添加',
    distribution: '发行版',
    recommended: '(推荐)',
    mainVersion: 'Java 主版本',
    platform: '平台',
    architecture: '架构',
    targetDir: '目标目录',
    resolving: '解析中...',
    startDownload: '开始下载',
  },
  plugins: {
    title: '插件管理',
    installedCount: '{count} 个已安装',
    searchPlaceholder: '搜索插件...',
    installing: '安装中...',
    install: '安装插件',
    noneInstalled: '尚未安装任何插件',
    noMatch: '无匹配的插件',
    changesApplied: '更改已生效',
    saveFailed: '保存失败',
    uninstallConfirm: '确定卸载此插件？',
    uninstalled: '插件已卸载',
    uninstallFailed: '卸载失败',
    installSuccess: '插件安装成功',
    installFailed: '安装失败: {message}',
    permissions: '权限 ({count})',
    contributes: '扩展点',
  },
  about: {
    aboutApp: '关于 {name}',
    beta: '测试版',
    stable: '稳定版',
    feedback: '反馈',
    viewRepository: '查看仓库',
    versionInfo: '版本信息',
    appVersion: '应用版本',
    versionHash: '版本哈希',
    os: '操作系统',
    architecture: '系统架构',
    memory: '内存',
    license: '许可证',
    licenseActivated: '已激活',
    licenseNotActivated: '未激活',
    licenseInvalid: '无效',
    channel: '频道',
    expiry: '到期',
    permanent: '永久有效',
    machineCode: '机器码',
    changeLicense: '更换许可证',
    activateLicense: '激活许可证',
    copyMachineCode: '复制机器码',
    update: '更新',
    checking: '检查中...',
    checkUpdate: '检查更新',
    upToDate: '已是最新版本',
    checkUpdateFailed: '检查更新失败',
    developers: '开发者',
    acknowledgements: '鸣谢',
    referenceProjects: '参考项目',
    backendDependencies: '后端依赖',
    frontendDependencies: '前端依赖',
    openSourceLicense: '开源协议',
    licenseNotice: '本程序基于 {name} 开源协议发布',
    viewLicense: '查看协议',
    copyrightPrivacy: '版权与隐私',
    copyrightStatement: '版权声明',
    copyrightStatementDesc: '查看本软件的版权归属与开源许可信息',
    userAgreement: '用户协议',
    privacyPolicy: '隐私政策',
    appDescription: '一个现代化的 Minecraft 启动器，支持多版本管理、模组加载器兼容、账户管理等功能。',
    roleProjectLead: '项目发起人 / 主要开发者',
    serviceModrinth: 'Mod 和资源搜索 API',
    serviceModpack: '整合包 API',
    serviceBmclapi: '提供BMCLAPI下载镜像服务',
    serviceMcmod: '中文 Mod 数据库',
    serviceMinecraft: 'Minecraft 官方网站,支持正版!',
    refVersionCheck: '版本检测参考',
    refModloaderInstaller: 'ModLoader 安装器参考',
    refLaunchFlow: '启动流程参考',
    depBackendRuntime: 'Rust 后端运行时',
    depCoreLibraries: '核心库',
    depCoreFramework: '核心框架',
    depUiComponents: 'UI 组件',
    depStylesTools: '样式与工具',
    depAnimation: '动画',
    depRendering: '渲染与展示',
  },
} as const
