// 杂项工具/调试/日志/闪屏（zh-CN）
export default {
  toolbox: {
    title: '自定义文件下载',
    description: '通过启动器下载任意文件到指定文件夹',
    urlLabel: '下载地址 (URL)',
    savePathLabel: '保存路径',
    autoFillPlaceholder: '选择文件夹后自动填充',
    pickFolder: '选择文件夹',
    submitting: '提交中...',
    startDownload: '开始下载',
    downloadFailed: '下载失败',
  },
  logs: {
    title: '日志管理',
    loadFailed: '加载日志列表失败',
    exportedTo: '已导出到 {dest}',
    downloadStarted: '已开始下载',
    deleteConfirm: '确定要删除 "{name}" 吗？',
    deleteTitle: '删除日志',
    deleted: '已删除',
    deleteFailed: '删除失败',
    openDirFailed: '无法打开目录',
    openFailed: '无法打开文件',
    exportAll: '导出全部',
    exportGz: '导出 (.gz)',
    filesLabel: '日志文件',
    currentSession: '当前会话',
    none: '暂无日志',
    emptyDescription: '启动器和后端运行时会产生日志文件',
    open: '打开',
    openContainingDir: '打开所在目录',
    retentionHint: '自动保留最近 10 条日志，超出自动清理最旧文件',
    currentSessionSuffix: '{count} 条当前会话',
    fileCountSuffix: '{count} 个文件',
    debugLogsCount: '调试日志 ({count})',
  },
  debug: {
    liveLogs: '实时日志',
    autoScroll: '自动滚动',
    clear: '清空',
    exportLogs: '导出日志',
    triggerDump: '触发 Dump',
    noLogs: '暂无日志...',
    diagnostics: '启动器诊断',
    systemInfo: '系统信息',
    versionInfo: '版本信息',
    connectivity: '连通状态',
    apiHealthCheck: 'API 健康检查',
    pathInfo: '路径信息',
    toggleDisableAnimations: '禁用动画',
    toggleShowComponentBoundaries: '显示组件边界',
    toggleSimulateApiErrors: '模拟 API 错误',
    toggleNetworkLogging: '网络请求日志',
    toggleDisableCaching: '禁用缓存',
    toggleLogOverlay: '日志浮层（全局）',
    toggleShowFps: '帧率显示（右上角）',
    togglesTitle: '调试开关（临时，重启归零）',
    clearTasksConfirm: '确定要清除所有下载任务列表吗？此操作不可撤销。',
    clearTasksTitle: '清除下载任务',
    tasksCleared: '下载任务列表已清除',
    dataManagement: '数据管理',
    downloadTaskList: '下载任务列表',
    clearTasksDescription: '清除 localStorage 中的下载任务记录',
    clearTasksButton: '清除下载任务列表',
    dumpExported: '日志已导出到: {path}',
  },
  splash: {
    preparing: '正在准备启动...',
    almostReady: '即将就绪...',
  },
  analysis: {
    title: '分析结果',
    pageTitle: '日志分析',
    inputTitle: '输入 Minecraft 日志',
    pastePlaceholder: '粘贴 Minecraft 日志内容...',
    analyzeButton: '分析日志',
    analyzing: '分析中...',
    analyzeFailed: '分析失败',
    gameVersion: '游戏版本',
    modLoader: '模组加载器',
    noIssues: '未发现明显问题',
    criticalCount: '{count} 严重',
    errorCount: '{count} 错误',
    warningCount: '{count} 警告',
    suggestedSolutions: '建议解决方案',
    stackTrace: '异常堆栈',
    categoryMemory: '内存',
    categoryModConflict: '模组冲突',
    categoryJavaRelated: 'Java 相关',
    categoryResource: '资源',
    categoryPerformance: '性能',
    categoryNetwork: '网络',
  },
  errors: {
    pageRenderError: '页面渲染异常',
  },
  notifier: {
    downloadCompleted: '{name} 下载完成',
  },
} as const
