// 首次启动初始化向导（zh-CN）
export default {
  title: '欢迎使用 Qomicex',
  subtitle: '首次启动需要完成一些基础设置',
  stepLabel: '第 {current}/{total} 步',
  // 步骤标签
  stepMode: '设置方式',
  stepLanguage: '语言',
  stepTheme: '主题',
  stepDirectories: '目录',
  stepDownloadSource: '下载源',
  stepJava: 'Java 运行时',
  stepMemory: '内存',
  stepDone: '完成',
  // 模式选择
  modeTitle: '选择设置方式',
  modeDesc: '两种模式都包含语言、主题、Java 与内存设置',
  quickTitle: '快速设置',
  quickDesc: '自动推荐配置，只需少量确认即可开始使用',
  customTitle: '自定义设置',
  customDesc: '逐步配置，额外包含下载源、数据目录与游戏目录',
  // 语言
  languageTitle: '选择界面语言',
  languageDesc: '语言设置立即生效，之后可在设置中随时更改',
  // 主题
  themeTitle: '选择外观主题',
  themeDesc: '深色/浅色主题可在设置中随时切换',
  dark: '深色',
  light: '浅色',
  // 目录
  dirTitle: '选择目录',
  dirDesc: '数据目录存放启动器配置，游戏目录存放 Minecraft 游戏文件',
  dataDir: '数据目录',
  dataDirDesc: '启动器配置、缓存等数据存放位置',
  gameDir: '游戏目录',
  gameDirDesc: 'Minecraft 游戏文件（.minecraft）所在位置',
  browse: '浏览...',
  // 下载源
  downloadTitle: '选择下载源',
  downloadDesc: '建议选择延迟最低的源，测速结果仅供参考',
  downloadSource: '游戏文件下载源',
  modSource: '模组源',
  autoSelect: '自动选择最优',
  pinging: '测速中...',
  pingFailed: '测速失败',
  // Java
  javaTitle: '配置 Java 运行时',
  javaDesc: '需要 Java 8 / 17 / 21 三个运行时，缺失的版本可在线下载',
  javaScanning: '正在深度扫描 Java 运行时...',
  javaScanAgain: '重新扫描',
  javaFound: '已找到',
  javaMissing: '未找到',
  javaDownload: '下载',
  javaDownloading: '下载中 {progress}%',
  javaDownloaded: '已下载',
  javaDownloadFailed: '下载失败',
  javaVersion8: 'Java 8',
  javaVersion17: 'Java 17',
  javaVersion21: 'Java 21',
  javaReady: '所有必需版本已就绪',
  javaRequired: '所有必需版本就绪后即可继续',
  // 内存
  memoryTitle: '分配内存',
  memoryDesc: '建议使用自动分配',
  memoryAuto: '自动分配（推荐）',
  memoryAutoDesc: '根据系统可用内存自动计算',
  memoryCustom: '自定义',
  memoryCustomDesc: '手动指定最大内存',
  memoryMb: 'MB',
  // 完成
  doneTitle: '设置完成',
  doneDesc: '初始化数据已保存，开始使用 Qomicex 吧！',
  doneSummary: '本次已完成配置：',
  finish: '开始使用',
  saving: '保存中...',
  saveFailed: '保存失败，请重试',
  default: '默认',
} as const
