// 帳號（zh-TW）
export default {
  loginErrors: {
    accessDenied: '你在瀏覽器中取消或拒絕了授權',
    expiredToken: '驗證碼已過期，請重新登入',
    invalidGrant: '授權無效，請重新登入',
    loginFailed: '登入失敗：{code}',
  },
  methodLabel: {
    offline: '離線',
    thirdParty: '第三方',
    thirdPartyWith: '第三方/{server}',
    unified: '統一通行證',
  },
  dataCorrupted: '帳號資料檔案已損毀或機器碼變更，檔案已被刪除，請重新新增帳號。',
  microsoft: {
    gettingInfo: '正在取得登入資訊...',
    openingBrowser: '正在開啟瀏覽器...',
    codeCopied: '驗證碼已複製到剪貼簿，請在瀏覽器中登入 Microsoft 帳號\n驗證碼: {code}',
    loginTimeout: '登入逾時，請重新登入',
    gettingAccount: '正在取得帳號資訊...',
    loginSuccess: '登入成功',
    noRole: '未取得可用角色',
    stepFetching: '取得登入資訊',
    stepWaiting: '等待授權',
    stepFetchingInfo: '取得帳號資訊',
    codeCopiedShort: '驗證碼已複製',
    browserOpened: '瀏覽器已自動開啟',
    relogin: '重新登入',
  },
  deleteConfirm: '確定要刪除此帳號嗎？',
  deleteTitle: '刪除帳號',
  batchDeleteConfirm: '確定要刪除選中的 {count} 個帳號嗎？',
  batchDeleteTitle: '批次刪除',
  title: '帳號管理',
  refresh: '重新整理',
  addAccount: '新增帳號',
  add: '新增',
  filterAll: '全部篩選',
  filterName: '名稱',
  filterLoginMethod: '登入方式',
  filterServer: '伺服器',
  searchPlaceholder: '搜尋帳號...',
  noMatch: '無相符帳號',
  noAccounts: '暫無帳號',
  setDefault: '設為預設',
  deleteSelected: '刪除 {count}',
  addTitle: '新增帳號',
  tabOffline: '離線',
  tabUnified: '統一通',
  offline: {
    playerName: '玩家名稱',
    playerNamePlaceholder: '輸入離線模式使用者名稱',
    uuid: 'UUID（可選，留空自動產生）',
    uuidPlaceholder: '例如: 069a79f4-44e9-4726-a5be-fca90e38aaf5',
    add: '新增離線帳號',
    idFormatWarning: '你輸入的玩家 ID 不符合標準（3-16 位，只可以包含英文字母、數字與底線），可能導致部分版本的遊戲無法啟動或發生錯誤。\n強烈建議使用規範的玩家 ID！\n如果你堅持，仍然可以繼續建立帳號。',
  },
  ygg: {
    presetServer: '預設伺服器',
    email: '電子郵件',
    password: '密碼',
    customServerAddr: '自訂伺服器位址',
    login: '登入',
    loginLoading: '登入中...',
    saving: '儲存中...',
    chooseRole: '選擇要登入的角色：',
    back: '返回',
    confirmCount: '確認 ({count})',
    dndHint: '或將驗證伺服器從網頁拖曳到此處',
    dndTitle: '新增驗證伺服器',
    dndConfirm: '是否新增此驗證伺服器？\n{url}',
    resolvedTo: 'API 位址：{url}',
    resolveFailed: '無法連線該位址，將按原位址嘗試',
    httpWarning: '警告：該驗證伺服器使用明文 HTTP 協定，密碼將以明文傳輸，存在外洩風險',
  },
  unified: {
    desc: '統一通行證是部分 Minecraft 伺服器使用的認證系統，需要輸入伺服器 ID。',
    serverId: '伺服器 ID',
    serverIdPlaceholder: '例如: lilu',
    email: '電子郵件',
    password: '密碼',
    login: '登入',
    loginLoading: '登入中...',
    oauthLogin: 'Microsoft OAuth 登入',
  },
} as const
