// 帳號詳情（zh-TW）
export default {
  capeUnequipped: '披風已卸下',
  capeEquipped: '披風已裝備',
  capeSwitchFailed: '披風切換失敗，請重新登入後重試',
  skinUploaded: '面板上傳成功',
  skinUploadFailed: '面板上傳失敗',
  resetSkinConfirm: '確定要重設為預設面板嗎？',
  skinReset: '面板已重設',
  skinResetFailed: '面板重設失敗',
  skinSavedTo: '面板已儲存到 {dest}',
  skinDownloaded: '面板已下載',
  skinDownloadFailed: '面板下載失敗',
  deleteAccountConfirm: '確定要刪除此帳號嗎？',
  loading: '載入中...',
  showNameTag: '顯示名稱標籤',
  showCape: '顯示披風',
  downloadSkin: '下載面板',
  accountInfo: '帳號資訊',
  name: '名稱',
  type: '類型',
  authServer: '驗證伺服器',
  skinModel: '面板模型',
  slim: '纖細 (Slim)',
  classic: '經典 (Classic)',
  cape: '披風',
  none: '無',
  hasSkin: '有',
  refreshSkin: '重新整理面板',
  switchCape: '切換披風',
  uploadSkin: '上傳面板',
  chooseArmModel: '選擇手臂模型',
  skinPreview: '面板預覽',
  classicArm: '經典手臂',
  slimArm: '纖細手臂',
  resetSkin: '重設面板',
  goToSkinSite: '前往面板站',
  deleteAccount: '刪除帳號',
} as const
