// 聯機（zh-TW）
export default {
  hostBadge: '房主',
  kick: '踢出',
  kickReviewTitle: '玩家申請重新加入',
  kickReviewBody: '玩家 "{name}" 想重新加入房間，是否允許？',
  kickReviewAllow: '允許',
  kickReviewReject: '拒絕',
  kickReviewRejectSilent: '拒絕且不再提示',
  kickedPlayersTitle: '已踢玩家 ({count})',
  unban: '解除封鎖',
  noPlayers: '暫無玩家',
  playerList: '玩家列表 ({count})',
  hostMods: '房主 Mods',
  matchInstances: '比對實例 ({count})',
  scanningMatch: '正在掃描本地實例並與房主 mods 比對...',
  noHostMods: '房主未發布 mods 列表（或掃描中）',
  missingModsDesc: '標"缺失"的 mod 未包含於實例 {instance}{countSuffix}（覆蓋房主 mods 最多的本地實例）',
  missingModsCountSuffix: '，共 {count} 個',
  noVersionInfo: '房主未提供版本資訊，無法判定哪些 mod 缺失',
  missingTooltip: '該 mod 在最佳比對實例（覆蓋房主 mods 最多者）中缺失',
  missing: '缺失',
  scanningLocal: '正在掃描本地實例...',
  noVersionForMatch: '房主未提供版本資訊，無法比對本地實例',
  noMatchingInstance: '沒有與房主遊戲版本/loader 相同的本地實例',
  matchedInstances: '一致實例（{count}）',
  modsConsistent: 'mods 一致 ({count})',
  quickLaunch: '快捷啟動',
  unmatchedInstances: '不一致實例（{count}）可忽略差異啟動',
  modsInconsistent: 'mods 不一致 ({count})',
  forceLaunchTitle: '忽略 mod 差異，直接以此為本地實例加入房間',
  forceLaunch: '忽略差異強制啟動',
  noLocalInstance: '暫無可用本地實例',
  gameCrashed: '遊戲異常結束',
  launchFailed: '啟動失敗',
  invalidPort: '請輸入有效連接埠 (1-65535)',
  selectInstanceFirst: '請先選擇一個實例',
  enterRoomCode: '請輸入房間碼',
  roomNotReady: '房間尚未就緒',
  natCheckFailed: 'NAT 類型偵測失敗',
  natTypes: {
    cone: { label: '完全錐形', tooltip: 'UDP: 寬鬆  TCP: 中等' },
    symmetric: { label: '嚴格對稱', tooltip: 'UDP: 嚴格  TCP: 嚴格' },
    blocked: { label: '不可穿透', tooltip: 'UDP: 阻斷  TCP: 阻斷' },
    unknown: { label: '不確定', tooltip: 'NAT 類型未知' },
  },
  title: '聯機',
  subtitle: '建立或加入聯機房間',
  natCheck: 'NAT 偵測',
  easyTierDownloadFailed: 'EasyTier 下載失敗：{error}',
  retry: '重試',
  easyTierStatus: {
    resolving: '正在測速選擇最快下載源…',
    extracting: '正在解壓 EasyTier…',
    downloading: '正在下載 EasyTier 聯機元件…',
  },
  tabCreate: '建立房間',
  tabJoin: '加入房間',
  createTitle: '啟動實例並建立房間',
  selectInstance: '選擇實例',
  pleaseSelect: '請選擇...',
  starting: '正在啟動…',
  startAndCreate: '啟動並建立房間',
  openLanHint: '啟動後請在遊戲內點擊"對區域網路開放"，將自動偵測連接埠。',
  manualStarted: '已手動啟動實例？點擊這裡',
  scanPortTitle: '掃描本地連接埠',
  scanningPorts: '正在掃描 Java 程序連接埠…',
  portDetected: '偵測到連接埠',
  createRoom: '建立房間',
  manualPort: '或手動輸入連接埠',
  joinTitle: '加入房間',
  roomCode: '房間碼',
  joining: '正在加入…',
  joinRoom: '加入房間',
  gotIt: '知道了',
  cancel: '取消',
  closeRoom: '關閉房間',
  serverAddress: '伺服器位址',
  hostVersion: '房主版本：{version}',
  leaveRoom: '退出房間',
} as const
