// 儀表板（zh-TW）
export default {
  account: '帳號',
  noDefaultAccount: '尚未設定預設帳號',
  defaultAccount: '預設帳號',
  addInSettings: '在設定中新增',
  manageAccounts: '管理帳號',
  lastPlayed: '上次遊玩 {date}',
  status: '狀態',
  ready: '準備就緒',
  launch: '啟動',
  noPinnedInstance: '尚未固定實例',
  goToInstances: '前往實例管理',
  editLayout: '編輯佈局',
  editMode: '編輯模式：拖動排列元件，拖動右下角調整大小',
  addWidget: '新增元件',
  resetLayout: '恢復預設佈局',
  allWidgetsVisible: '所有元件均已顯示',
  done: '完成',
  widget: {
    watermark: '浮水印',
    account: '帳號',
    instance: '預設實例',
    launch: '啟動',
    announcements: '公告',
  },
} as const
