// 外部喚起（qomicex-launcher:// 深鏈，issue #127）的提示文案
export default {
  launchNotFound: '找不到實例：{target}',
  joinConfirmTitle: '加入聯機房間',
  joinConfirmDesc: '網頁要求加入房間 {code}，是否繼續？',
  joinFailed: '加入房間失敗：{message}',
  installPluginConfirmTitle: '安裝插件',
  installPluginConfirmDesc: '此請求來自 {host}，將安裝插件 {name}。僅在你信任該來源時繼續。',
  installPluginSlugConfirmDesc: '網頁要求安裝商店插件 {slug}，是否繼續？',
  installModpackConfirmTitle: '安裝整合包',
  installModpackConfirmDesc: '網頁要求安裝整合包 {name}（來源 {source}），是否繼續？',
  installStarted: '已開始安裝',
  installFailed: '安裝失敗：{message}',
  cancelled: '已取消該操作',
  registerTitle: '關聯外部喚起連結',
  registerDesc: '是否將啟動器註冊為 qomicex-launcher:// 連結的開啟方式？註冊後，網頁或捷徑可以直接喚起啟動器。',
  registerSuccess: '已關聯外部喚起連結',
  registerFailed: '關聯失敗，稍後可在設定中重試',
  registerDeclined: '已略過，之後不再自動詢問',
  launchAmbiguous: '有 {count} 個實例都叫「{target}」，無法確定要啟動哪個。請改用 目錄:實例名 的形式，例如 {example}',
  launchAmbiguousExample: '/path/to/game:實例名',
}
