// 通用彈窗/卡片（zh-TW）
export default {
  // 安裝/下載階段（與 downloads.stage 相同，供彈窗渲染動態 key）
  stage: {
    queued: '排隊中',
    'downloading-json': '下載版本 JSON',
    downloading: '下載遊戲檔案',
    'downloading-libraries': '下載支援程式庫',
    'downloading-assets': '下載資源檔案',
    'downloading-mainjar': '下載主檔案',
    'downloading-loader': '下載載入器',
    'downloading-loader-libs': '下載載入器程式庫',
    'installing-loader': '安裝載入器',
    'downloading-addons': '下載附加內容',
    'downloading-modpack': '下載整合包',
    'parsing-modpack': '解析整合包',
    'modpack-files': '下載整合包檔案',
    'modpack-overrides': '解壓覆寫檔案',
  },
  // 跨彈窗/卡片通用文案
  common: {
    unknownError: '未知錯誤',
    deleting: '刪除中...',
    viewDetail: '查看詳情',
    openFolder: '開啟資料夾',
    openFailed: '開啟失敗',
    deleted: '已刪除「{name}」',
    deleteFailed: '刪除失敗: {error}',
    taskExpired: '任務已過期（後端未回報該工作階段）',
    downloadTimeout: '下載逾時（可能仍在背景進行）',
    downloadStalled: '下載停滯（長時間無進度）',
    cancelled: '下載已取消',
    downloadFailed: '下載失敗',
    startFailed: '下載啟動失敗',
  },
  // 刪除確認（依資源類型）
  confirmDelete: {
    titleMod: '刪除 Mod',
    titleSave: '刪除存檔',
    titleScreenshot: '刪除截圖',
    titleShader: '刪除光影包',
    titleDataPack: '刪除資料包',
    titleResourcePack: '刪除資源包',
    bodyMod: '確定要刪除 Mod「{name}」嗎？將被移至資源回收筒。',
    bodySave: '確定要刪除存檔「{name}」嗎？將被移至資源回收筒。',
    bodyScreenshot: '確定要刪除截圖「{name}」嗎？將被移至資源回收筒。',
    bodyShader: '確定要刪除光影包「{name}」嗎？將被移至資源回收筒。',
    bodyDataPack: '確定要刪除資料包「{name}」嗎？將被移至資源回收筒。',
    bodyResourcePack: '確定要刪除資源包「{name}」嗎？將被移至資源回收筒。',
  },
  // 啟動進度
  launchProgress: {
    title: '啟動遊戲',
    titleFailed: '啟動失敗',
    stage: {
      starting: '準備中',
      checking: '檢查檔案完整性',
      repairing: '補全檔案',
      'logging-in': '驗證帳號',
      authlib: '設定外置登入',
      natives: '解壓縮原生程式庫',
      building: '建置啟動參數',
      preparing: '準備環境',
      launching: '啟動遊戲',
      running: '遊戲執行中',
      crashed: '遊戲異常結束',
      failed: '啟動失敗',
      completed: '遊戲已結束',
      cancelled: '已取消',
    },
    viewCrashReport: '查看崩潰報告',
    processId: '程序 ID: {pid}',
    startingUp: '正在啟動...',
  },
  // 崩潰分析
  crashAnalysis: {
    copyAll: '複製全部',
    copyDetail: '詳情:\n{detail}',
    copyArgs: '啟動參數:\n{args}',
    copyCrashReport: '崩潰報告:\n{crashReport}',
    copyLogLink: '日誌連結: {url}',
    exporting: '匯出中...',
    exportReport: '匯出診斷報告',
    exportFailed: '匯出失敗',
    detail: '錯誤詳情',
    crashReport: '崩潰報告',
    launchArgs: '啟動參數',
    analyzing: '正在分析崩潰報告...',
    noResult: '暫無分析結果',
    scanQr: '掃描查看完整日誌',
  },
  // 匯入整合包
  import: {
    title: '匯入整合包',
    parsing: '正在解析整合包檔案...',
    modpackName: '整合包名稱',
    gameVersion: '遊戲版本',
    loader: '載入器',
    instanceName: '實例名稱',
    startInstall: '開始安裝',
    connecting: '正在連線...',
    installing: '安裝中：{name}',
    completed: '✓ 安裝完成！',
    completedDetail: '整合包已成功安裝為實例「{name}」',
    failedWith: '安裝失敗：{error}',
    seeDownloadPage: '請查看下載頁了解詳情',
    viewInstance: '查看實例',
    backgroundDownload: '背景下載',
    parseFailed: '解析失敗',
    installFailed: '安裝失敗',
  },
  // 安裝整合包（線上）
  modpackInstall: {
    title: '安裝整合包',
    modpackLabel: '整合包',
    gameVersion: '遊戲版本',
    loader: '載入器',
    instanceName: '實例名稱',
    startInstall: '開始安裝',
    resolving: '正在解析並安裝...',
    connecting: '正在連線...',
    installing: '安裝中：{name}',
    completed: '✓ 安裝完成！',
    completedDetail: '整合包已成功安裝為實例「{name}」',
    failedWith: '安裝失敗：{error}',
    seeDownloadPage: '請查看下載頁了解詳情',
    viewInstance: '查看實例',
    backgroundDownload: '背景下載',
    cancelled: '已取消',
    installFailed: '安裝失敗',
  },
  // 匯出整合包
  modpackExport: {
    title: '匯出整合包',
    format: '匯出格式',
    include: '包含內容',
    includeSaves: '包含存檔',
    includeScreenshots: '包含截圖',
    packInfo: '包資訊',
    packName: '名稱',
    packVersion: '版本',
    packAuthor: '作者',
    exportingTitle: '正在匯出...',
    stageLookup: '識別檔案指紋',
    stageManifest: '產生設定檔',
    stagePacking: '打包遊戲檔案: {file}',
    cancelExport: '取消',
    cancelConfirm: '確定要取消匯出嗎？',
    exportCancelled: '匯出已取消',
    exportSaved: '✓ 匯出完成',
    exportSavedTo: '✓ 匯出完成（已儲存到: {path}）',
    fileName: '匯出檔案名稱',
    startExport: '開始匯出',
    exporting: '正在打包...（大包可能需要較長時間）',
    exported: '✓ 匯出完成',
    exportFailed: '匯出失敗',
    selectAll: '全選',
    deselectAll: '全不選',
    selectedSummary: '已選 {count} 項 · {size}',
    loading: '正在讀取檔案列表...',
    loadFailed: '讀取檔案列表失敗',
    retry: '重試',
    empty: '沒有可匯出的檔案',
    fileCount: '{count} 項',
    expand: '展開',
    collapse: '摺疊',
    catMods: '模組',
    catResourcepacks: '資源包',
    catShaderpacks: '光影',
    catSaves: '存檔',
    catScreenshots: '截圖',
    catConfig: '設定',
  },
  // 版本更新
  update: {
    foundNew: '發現新版本 {version}',
    noNotes: '暫無更新說明',
    downloadFailed: '下載失敗',
    done: '更新完成',
    downloading: '下載中 {progress}%',
    later: '下次再說',
    installing: '安裝中...',
    downloadingAction: '下載中...',
    updateNow: '立即更新',
  },
  // 授權啟動
  license: {
    title: '啟動授權',
    loadFailed: '載入失敗',
    activateFailed: '啟動失敗',
    active: '授權已啟動',
    id: 'ID: {licenseId}',
    expireAt: '過期: {date}',
    permanent: '永久',
    machineCode: '本機機器碼',
    copyMachineCode: '複製機器碼',
    tokenLabel: '授權 Token',
    tokenPlaceholder: '貼上管理員提供的授權 Token...',
    tokenHint: '聯絡管理員取得新授權 Token。輸入後點擊啟動按鈕進行驗證。',
    exitLauncher: '退出啟動器',
    verifying: '驗證中...',
    activate: '啟動',
  },
  // Microsoft 重新登入
  microsoftReauth: {
    title: 'Microsoft 帳號憑證已過期',
    description: '你的 Microsoft 帳號憑證已過期，需要重新登入才能啟動遊戲。',
    reauth: '重新登入 Microsoft',
  },
  // 尚未設定帳號
  noAccount: {
    title: '尚未設定帳號',
    description: '啟動遊戲需要一個 Minecraft 帳號，請先新增帳號。',
    goToAccounts: '前往帳號管理',
    addAccount: '新增帳號',
  },
  // 選擇預設帳號
  accountSelect: {
    title: '選擇預設帳號',
    description: '請選擇一個帳號作為預設帳號，啟動遊戲時將使用該帳號。',
    noAccounts: '暫無帳號',
  },
  // 更換版本
  versionPicker: {
    title: '更換版本 — {name}',
    loadingVersions: '載入版本列表...',
    noVersions: '沒有可用的版本',
    switching: '更換中...',
    switch: '更換',
  },
  // 模組更新
  modUpdate: {
    title: '檢查模組更新',
    checkFailed: '檢查更新失敗',
    addedToDownloadList: '已加入下載列表 {count} 個任務',
    updatedCount: '已更新 {count} 個模組',
    completedWithFailed: '完成 {success} 個，失敗 {failed} 個{failNames}',
    batchFailed: '批次更新失敗',
    allUpToDate: '所有模組已是最新版本',
    updating: '更新中...',
    updateCount: '更新 {count} 個模組',
  },
  // 公告
  announcement: {
    gotIt: '知道了',
  },
  // 披風管理
  cape: {
    title: '切換披風',
    noCapes: '該帳號暫無可用披風',
    loadingShort: '載入中',
    inUse: '使用中',
    clickToEquip: '點擊裝備',
  },
  // 資源安裝
  resourceInstall: {
    title: '安裝 {name}',
    selectInstance: '選擇實例',
    loadingInstances: '載入實例列表中...',
    instancesLoadFailed: '載入實例列表失敗',
    noInstances: '暫無實例，請先建立實例',
    searchPlaceholder: '搜尋實例...',
    default: '預設',
    selectVersion: '選擇版本',
    selectInstanceFirst: '請先選擇一個實例',
    loadingVersions: '正在載入版本列表...',
    versionsLoadFailed: '載入版本列表失敗',
    selectVersionPlaceholder: '請選擇版本',
    noVersions: '無可用版本',
    depsTitle: '前置模組',
    parsingDeps: '正在解析前置模組...',
    depsLoadFailed: '載入前置模組失敗',
    noDeps: '無前置模組',
    installed: '已安裝',
    pending: '待安裝',
    noDownloadableFile: '該版本沒有可下載的檔案',
    downloadFailedWith: '"{name}" 下載失敗: {error}',
    downloading: '正在下載',
    installConfirm: '確認安裝',
    installing: '安裝中...',
    installingWithName: '正在下載 {name} ({step}/{total})',
    installedDone: '安裝完成：{name}',
  },
  // 模組卡片
  mod: {
    mcwiki: 'MC百科',
    changeVersion: '更換版本',
    update: '更新',
    addedToDownloadList: '已加入下載列表',
    updatedWithName: '已更新「{name}」',
    updateFailedWithName: '更新「{name}」失敗',
    updateFailed: '更新失敗',
    updateAvailableTo: '可更新至 {version}',
    unknownVersion: '未知版本',
  },
  // 存檔卡片
  save: {
    backup: '備份',
    rename: '重新命名',
    quickJoin: '快速進入',
    lastPlayed: '上次遊玩: {date}',
    settings: '設定',
  },
  // 版權聲明彈窗
  legal: {
    title: '版權聲明',
    content: `**Qomicex Launcher** 由 **Qomicex 團隊** 開發並維護，版權歸 Qomicex 團隊所有。

- 本軟體基於 **GPL-3.0 License** 開放原始碼授權發布，您可以在遵守該授權的前提下自由使用、複製、修改與散布。
- 本軟體與 **Mojang Studios / Microsoft** 及其旗下產品不存在任何從屬、合作或背書關係。
- **Minecraft** 及相關名稱、標誌、版權均歸 **Mojang Studios / Microsoft** 所有。
- 本軟體不包含 Minecraft 遊戲本體；遊戲資源版權歸其各自所有者所有。
- 使用本軟體即表示您已閱讀並同意《使用者協議》與《隱私權政策》。`,
  },
} as const
