// 下載中心（zh-TW）
export default {
  status: {
    queued: '排隊中',
    downloading: '下載中',
    paused: '已暫停',
    completed: '已完成',
    failed: '失敗',
    cancelled: '已取消',
  },
  stage: {
    queued: '排隊中',
    'downloading-json': '下載版本 JSON',
    downloading: '下載遊戲檔案',
    'downloading-libraries': '下載支援程式庫',
    'downloading-assets': '下載資源檔案',
    'downloading-mainjar': '下載主檔案',
    'downloading-loader': '下載載入器',
    'downloading-loader-libs': '下載載入器程式庫',
    'installing-loader': '安裝載入器',
    'downloading-addons': '下載附加內容',
    'downloading-modpack': '下載整合包',
    'parsing-modpack': '解析整合包',
    'modpack-files': '下載整合包檔案',
    'modpack-overrides': '解壓覆寫檔案',
  },
  filter: {
    all: '全部',
    downloading: '下載中',
    paused: '已暫停',
    completed: '已完成',
    failed: '失敗',
  },
  title: '下載中心',
  subtitle: '{count} 個任務',
  clearFinished: '清除已完成/失敗',
  taskCount: '{count} 個任務',
  empty: '暫無下載任務',
  emptyHint: '在"實例"頁面選擇版本並開始下載，任務將顯示在此處',
  goToInstances: '前往實例',
  addonsCount: '+ {count} 個附加',
  createdAt: '建立於 {date}',
  completedAt: '完成於 {date}',
  resume: '繼續',
  pause: '暫停',
  cancel: '取消',
  retry: '重試',
  remove: '移除',
  statusText: {
    done: '下載完成',
    failedWith: '失敗: {error}',
    failed: '下載失敗',
    pausedProgress: '已暫停 {progress}%',
    waiting: '等待中',
    downloading: '下載中',
    connecting: '連線中…',
  },
  filesCount: '{done}/{total} 檔案',
  errors: {
    taskExpired: '任務已過期（後端已重新啟動）',
    downloadFailed: '下載失敗',
    cannotVerify: '無法連線後端驗證任務狀態',
    statusUnknown: '任務狀態無法確認（後端未回報該工作階段）',
    taskInvalid: '任務已失效',
  },
} as const
