// 後端錯誤訊息（前端錯誤碼對應顯示，zh-TW）
export default {
  notFound: '要求的資源不存在',
  forbidden: '沒有權限執行此操作',
  badRequest: '請求參數有誤',
  internalError: '伺服器內部錯誤',
  upstreamError: '上游服務請求失敗',
  requestTimeout: '請求逾時，請稍後重試',
  unknown: '請求失敗，請稍後重試',
  licenseNotFound: '授權未啟動',
  licenseDecryptFailed: '授權解密失敗',
  licenseSignatureInvalid: '授權簽章無效',
  licensePublicKeyUnavailable: '授權公鑰不可用',
  licenseExpired: '授權已過期',
  licenseRemoteCheckFailed: '授權遠端驗證失敗',
  licenseIoError: '授權檔案讀取失敗',
  tokenExpired: '登入權杖已過期，請重新登入',
  mcApiError: 'Minecraft 官方 API 請求失敗',
  fsAuthRequired: '檔案系統存取未授權',
  pluginMissingDependency: '外掛缺少必要的前置依賴',
  connectorTimeout: '聯機操作逾時，請檢查網路後重試',
  exportDiagnosticsFailed: '匯出診斷報告失敗',
  modpackParseFailed: '整合包解析失敗',
  skinUploadFailed: '面板上傳失敗',
  skinSaveFailed: '面板儲存失敗',
  skinResetFailed: '面板重設失敗',
} as const
