// 插件（zh-TW）
export default {
  notFound: '插件未找到',
  notActivated: '插件未啟動',
  webviewPlaceholder: '此插件已在獨立視窗中開啟',
  webviewFocus: '聚焦視窗',
  installTitle: '安裝插件',
  permissionsRequest: '此插件申請以下權限：',
  highRisk: '高風險權限',
  caution: '需注意',
  normal: '普通',
  cancel: '取消',
  confirmInstall: '確認安裝',
  fileAuthRequest: '插件「{pluginId}」請求存取路徑：\n{path}\n\n是否允許？',
  fileAuthDenied: '使用者拒絕了檔案存取授權',
  fileAuthFailed: '授權失敗',
  permission: {
    instanceRead: '讀取實例列表',
    instanceWrite: '建立/修改/刪除實例',
    accountRead: '讀取帳號列表',
    licenseRead: '讀取授權資訊',
    configRead: '讀取啟動器設定',
    configWrite: '修改啟動器設定',
    cacheAccess: '讀寫插件暫存',
    endpointDiscover: '取得後端 API 端點',
    pageList: '取得頁面列表',
    networkFetch: '傳送 HTTP 請求',
    networkCorsProxy: 'CORS 代理請求',
    networkWebsocket: 'WebSocket 連線',
    networkProxy: '修改代理設定',
    uiInjectSidebar: '注入側邊欄選單',
    uiInjectSettings: '注入設定頁',
    uiPictureInPicture: '子母畫面視窗',
    uiSubWindow: '獨立子視窗',
    uiContextMenu: '注入右鍵選單',
    uiToast: '應用程式內通知',
    uiNavigate: '跳轉頁面',
    systemInfo: '讀取系統和啟動器資訊',
    systemNotification: '傳送系統通知',
    clipboardRead: '讀取剪貼簿',
    clipboardWrite: '寫入剪貼簿',
    wasmExecute: '執行 WASM 模組',
    pluginInstall: '安裝/卸載/更新插件',
    pluginList: '讀取已安裝插件列表',
    resourceRead: '讀取遊戲資源檔案',
    resourceWrite: '寫入遊戲資源檔案',
    javaManage: '管理 Java 執行環境',
    downloadManage: '管理下載任務',
    gameProcess: '啟停遊戲程序',
    gameLog: '偵測遊戲日誌',
    connectorHost: '啟停聯機',
    connectorScan: '掃描區域網路聯機',
    shellExecute: '執行系統指令',
    filesystemRead: '讀取檔案系統',
    filesystemWrite: '寫入檔案系統',
  },
} as const
