// 資源中心（zh-TW）
export default {
  sources: {
    all: '全部',
  },
  categories: {
    mod: '模組',
    modpack: '整合包',
    shader: '光影',
    resourcepack: '材質包',
    datapack: '資料包',
    save: '存檔',
  },
  sort: {
    relevance: '相關度',
    downloads: '下載量',
    updated: '更新時間',
    newest: '最新發布',
    name: '名稱',
    recommended: '推薦',
    installs: '安裝量',
  },
  unknownAuthor: '未知作者',
  install: '安裝',
  viewDetail: '查看詳情',
  originalSite: '原站',
  searchFailed: '搜尋失敗',
  backendUnreachable: '無法連線到後端服務，請確保後端已啟動',
  title: '資源中心',
  sourceLabel: '資源源',
  categoryLabel: '資源分類',
  searchPlaceholder: '搜尋{category}...',
  search: '搜尋',
  gameVersionLabel: '遊戲版本',
  allVersions: '全部版本',
  loaderLabel: '載入器',
  allLoaders: '全部載入器',
  categoryFilterLabel: '類別篩選',
  clearFilter: '清除篩選',
  notFound: '未找到相關資源',
  notFoundHint: '嘗試更換關鍵字、資源源或分類',
  retry: '重試',
  loading: '載入中...',
  loadMore: '載入更多（{current}/{total}）',
  allShown: '已顯示全部 {count} 個結果',
} as const
