// 資源中心（zh-TW）
export default {
  sources: {
    all: '聚合',
  },
  categories: {
    aggregate: '聚合',
    mod: '模組',
    modpack: '整合包',
    shader: '光影',
    resourcepack: '材質包',
    datapack: '資料包',
    save: '存檔',
  },
  sort: {
    relevance: '相關度',
    downloads: '下載量',
    updated: '更新時間',
    newest: '最新發布',
    name: '名稱',
    recommended: '推薦',
    installs: '安裝量',
  },
  unknownAuthor: '未知作者',
  install: '安裝',
  viewDetail: '查看詳情',
  searchFailed: '搜尋失敗',
  backendUnreachable: '無法連線到後端服務，請確保後端已啟動',
  title: '資源中心',
  sourceLabel: '資源源',
  categoryLabel: '資源分類',
  searchPlaceholder: '搜尋{category}...',
  search: '搜尋',
  gameVersionLabel: '遊戲版本',
  allVersions: '全部版本',
  loaderLabel: '載入器',
  allLoaders: '全部載入器',
  sortLabel: '排序方式',
  categoryFilterLabel: '類別篩選',
  clearFilter: '清除篩選',
  expandTags: '展開全部',
  collapseTags: '收起',
  expandFilters: '展開篩選',
  collapseFilters: '收起篩選',
  notFound: '未找到相關資源',
  notFoundHint: '嘗試更換關鍵字、資源源或分類',
  retry: '重試',
  loading: '載入中...',
  loadMore: '載入更多（{current}/{total}）',
  allShown: '已顯示全部 {count} 個結果',
  mode: {
    searchPlaceholder: '搜尋資源、關鍵字...',
  },
  favorites: {
    viewSearch: '搜尋',
    viewLabel: '收藏',
    viewLabelWithCount: '收藏（{count}）',
    searchPlaceholder: '搜尋收藏...',
    add: '收藏',
    remove: '取消收藏',
    added: '已加入收藏',
    removed: '已取消收藏',
    failed: '收藏操作失敗',
    loadFailed: '收藏載入失敗',
    emptyTitle: '還沒有收藏',
    emptyHint: '在搜尋結果或資源詳情頁點擊 ♥ 即可收藏',
    filteredEmpty: '目前篩選條件下沒有收藏',
    filteredEmptyHint: '切換上方資源源 / 資源分類，或左側收藏夾與標籤篩選',
    allShown: '共 {count} 個收藏',
    folders: {
      railTitle: '收藏夾',
      all: '全部',
      unfiled: '未分組',
      loading: '載入中...',
      create: '新增收藏夾',
      createPlaceholder: '收藏夾名稱',
      rename: '重新命名',
      renamePlaceholder: '收藏夾名稱',
      emptyName: '收藏夾名稱不能為空',
      created: '已建立收藏夾「{name}」',
      renamed: '已重新命名收藏夾',
      failed: '收藏夾操作失敗',
      delete: '刪除',
      deleteTitle: '刪除收藏夾',
      deleteBodyWithItems: '「{name}」中的 {count} 個收藏會移出該收藏夾（收藏本身保留），此操作無法復原。',
      deleteBodyEmpty: '「{name}」中沒有收藏，刪除後無法復原。',
      deleted: '已刪除收藏夾（{count} 個收藏已移出）',
    },
    note: {
      label: '備註',
      placeholder: '記錄用途、版本需求等',
    },
    tags: {
      label: '標籤',
      filterLabel: '標籤篩選',
      placeholder: '輸入標籤後按 Enter',
      remove: '移除標籤「{tag}」',
      hint: '按 Enter 或逗號新增，最多 {max} 個',
      limitReached: '已達上限 {max} 個',
    },
    edit: {
      open: '編輯收藏',
      title: '編輯收藏',
      folderLabel: '收藏夾',
      noFolders: '還沒有收藏夾，可先在收藏夾選單中新增。',
      folderHintNone: '未選取任何收藏夾，將歸入「未分組」。',
      folderHintCount: '已選取 {count} 個收藏夾。',
      cancel: '取消',
      save: '儲存',
      saving: '儲存中...',
      saved: '已儲存',
      failed: '儲存失敗',
    },
  },
} as const
