// 資源詳情（zh-TW）
export default {
  prereqMods: '前置模組',
  basedOn: '基於 {version} 解析',
  parsingPrereq: '正在解析前置模組...',
  noPrereq: '此版本沒有前置模組',
  addedToDownload: '已加入下載列表',
  downloadFailed: '下載失敗',
  exportFailed: '匯出失敗',
  loadDetailFailed: '載入資源詳情失敗',
  loadVersionsTimeout: '載入版本列表逾時',
  loadVersionsFailed: '載入版本列表失敗',
  title: '資源詳情',
  refresh: '重新整理',
  originalPage: '原始頁面',
  loadFailed: '載入失敗',
  notFound: '資源不存在',
  latest: '最新 {version}',
  noDescription: '暫無簡介',
  translating: '翻譯中...',
  collapseTranslation: '收起翻譯',
  translateDescription: '翻譯簡介',
  translatedMark: '譯',
  unknownAuthor: '未知作者',
  categoryTags: '分類標籤',
  detailedIntro: '詳細介紹',
  showOriginal: '顯示原文',
  translateBody: '翻譯詳細介紹',
  expand: '展開',
  collapse: '收起',
  noMoreContent: '暫無更多介紹',
  selectVersionInstall: '選擇版本安裝',
  gameVersion: '遊戲版本',
  allVersions: '全部版本',
  loader: '載入器',
  allLoaders: '全部載入器',
  fetchingVersions: '正在取得版本列表',
  versionCount: '共 {count} 個版本',
  filteredCount: '篩選後 {count} 個',
  noVersionUnderFilter: '目前篩選條件下沒有可用版本',
  install: '安裝',
  saveAs: '另存為',
  loading: '載入中...',
  getDownload: '取得下載',
  noDownload: '暫無下載',
  loadMore: '載入更多 ({count} 個)',
} as const
