// Account detail (en)
export default {
  capeUnequipped: 'Cape removed',
  capeEquipped: 'Cape equipped',
  capeSwitchFailed: 'Failed to switch cape, please sign in again and retry',
  skinUploaded: 'Skin uploaded',
  skinUploadFailed: 'Skin upload failed',
  resetSkinConfirm: 'Reset to the default skin?',
  skinReset: 'Skin reset',
  skinResetFailed: 'Skin reset failed',
  skinSavedTo: 'Skin saved to {dest}',
  skinDownloaded: 'Skin downloaded',
  skinDownloadFailed: 'Skin download failed',
  deleteAccountConfirm: 'Delete this account?',
  loading: 'Loading...',
  showNameTag: 'Show name tag',
  showCape: 'Show cape',
  downloadSkin: 'Download skin',
  accountInfo: 'Account info',
  name: 'Name',
  type: 'Type',
  authServer: 'Auth server',
  skinModel: 'Skin model',
  slim: 'Slim',
  classic: 'Classic',
  cape: 'Cape',
  none: 'None',
  hasSkin: 'Yes',
  refreshSkin: 'Refresh skin',
  switchCape: 'Switch cape',
  uploadSkin: 'Upload skin',
  chooseArmModel: 'Choose arm model',
  skinPreview: 'Skin preview',
  classicArm: 'Classic arms',
  slimArm: 'Slim arms',
  resetSkin: 'Reset skin',
  goToSkinSite: 'Go to skin site',
  deleteAccount: 'Delete account',
} as const
