// Connect / multiplayer (en)
export default {
  hostBadge: 'Host',
  kick: 'Kick',
  noPlayers: 'No players',
  playerList: 'Players ({count})',
  hostMods: 'Host mods',
  matchInstances: 'Matching instances ({count})',
  scanningMatch: 'Scanning local instances and comparing with host mods...',
  noHostMods: 'Host has not published a mods list (or still scanning)',
  missingModsDesc: 'Mods marked "missing" are not in instance {instance}{countSuffix} (the local instance covering the most host mods)',
  missingModsCountSuffix: ', {count} total',
  noVersionInfo: 'Host did not provide version info; cannot determine missing mods',
  missingTooltip: 'This mod is missing in the best matching instance (covers the most host mods)',
  missing: 'Missing',
  scanningLocal: 'Scanning local instances...',
  noVersionForMatch: 'Host did not provide version info; cannot match local instances',
  noMatchingInstance: 'No local instance matches the host game version/loader',
  matchedInstances: 'Matching instances ({count})',
  modsConsistent: 'mods consistent ({count})',
  quickLaunch: 'Quick launch',
  unmatchedInstances: 'Mismatched instances ({count}), can launch ignoring differences',
  modsInconsistent: 'mods differ ({count})',
  forceLaunchTitle: 'Ignore mod differences and join the room with this local instance',
  forceLaunch: 'Force launch ignoring differences',
  noLocalInstance: 'No usable local instance',
  gameCrashed: 'Game exited abnormally',
  launchFailed: 'Launch failed',
  invalidPort: 'Enter a valid port (1-65535)',
  selectInstanceFirst: 'Please select an instance',
  enterRoomCode: 'Please enter the room code',
  roomNotReady: 'Room is not ready yet',
  natCheckFailed: 'NAT type detection failed',
  natTypes: {
    cone: { label: 'Full cone', tooltip: 'UDP: open  TCP: moderate' },
    symmetric: { label: 'Symmetric', tooltip: 'UDP: strict  TCP: strict' },
    blocked: { label: 'Blocked', tooltip: 'UDP: blocked  TCP: blocked' },
    unknown: { label: 'Unknown', tooltip: 'NAT type unknown' },
  },
  title: 'Multiplayer',
  subtitle: 'Create or join a room',
  natCheck: 'NAT check',
  easyTierDownloadFailed: 'EasyTier download failed: {error}',
  retry: 'Retry',
  easyTierStatus: {
    resolving: 'Pinging to choose the fastest download source…',
    extracting: 'Extracting EasyTier…',
    downloading: 'Downloading EasyTier components…',
  },
  tabCreate: 'Create Room',
  tabJoin: 'Join Room',
  createTitle: 'Launch instance and create a room',
  selectInstance: 'Select instance',
  pleaseSelect: 'Please select...',
  starting: 'Starting…',
  startAndCreate: 'Launch and create room',
  openLanHint: 'Click "Open to LAN" in-game after launch; the port will be detected automatically.',
  manualStarted: 'Already launched manually? Click here',
  scanPortTitle: 'Scan local ports',
  scanningPorts: 'Scanning Java process ports…',
  portDetected: 'Port detected',
  createRoom: 'Create Room',
  manualPort: 'Or enter the port manually',
  joinTitle: 'Join Room',
  roomCode: 'Room code',
  joining: 'Joining…',
  joinRoom: 'Join Room',
  gotIt: 'Got it',
  cancel: 'Cancel',
  closeRoom: 'Close Room',
  serverAddress: 'Server address',
  hostVersion: 'Host version: {version}',
  leaveRoom: 'Leave Room',
} as const
