// Common dialogs / cards (en)
export default {
  // Install / download stages (same as downloads.stage, for dynamic keys in dialogs)
  stage: {
    queued: 'Queued',
    'downloading-json': 'Downloading version JSON',
    downloading: 'Downloading game files',
    'downloading-libraries': 'Downloading libraries',
    'downloading-assets': 'Downloading assets',
    'downloading-mainjar': 'Downloading main jar',
    'downloading-loader': 'Downloading loader',
    'downloading-loader-libs': 'Downloading loader libraries',
    'installing-loader': 'Installing loader',
    'downloading-addons': 'Downloading addons',
    'downloading-modpack': 'Downloading modpack',
    'parsing-modpack': 'Parsing modpack',
    'modpack-files': 'Downloading modpack files',
    'modpack-overrides': 'Extracting override files',
  },
  // Shared strings across dialogs / cards
  common: {
    unknownError: 'Unknown error',
    deleting: 'Deleting...',
    viewDetail: 'View details',
    openFolder: 'Open folder',
    openFailed: 'Failed to open',
    deleted: 'Deleted "{name}"',
    deleteFailed: 'Delete failed: {error}',
    taskExpired: 'Task expired (backend did not report this session)',
    downloadTimeout: 'Download timed out (may still be running in background)',
    downloadStalled: 'Download stalled (no progress for a long time)',
    cancelled: 'Download cancelled',
    downloadFailed: 'Download failed',
    startFailed: 'Failed to start download',
  },
  // Delete confirmations (per resource type)
  confirmDelete: {
    titleMod: 'Delete Mod',
    titleSave: 'Delete Save',
    titleScreenshot: 'Delete Screenshot',
    titleShader: 'Delete Shader Pack',
    titleDataPack: 'Delete Data Pack',
    titleResourcePack: 'Delete Resource Pack',
    bodyMod: 'Are you sure you want to delete Mod "{name}"? It will be moved to the recycle bin.',
    bodySave: 'Are you sure you want to delete the save "{name}"? It will be moved to the recycle bin.',
    bodyScreenshot: 'Are you sure you want to delete the screenshot "{name}"? It will be moved to the recycle bin.',
    bodyShader: 'Are you sure you want to delete the shader pack "{name}"? It will be moved to the recycle bin.',
    bodyDataPack: 'Are you sure you want to delete the data pack "{name}"? It will be moved to the recycle bin.',
    bodyResourcePack: 'Are you sure you want to delete the resource pack "{name}"? It will be moved to the recycle bin.',
  },
  // Launch progress
  launchProgress: {
    title: 'Launch Game',
    titleFailed: 'Launch Failed',
    stage: {
      starting: 'Preparing',
      checking: 'Checking file integrity',
      repairing: 'Repairing files',
      'logging-in': 'Verifying account',
      authlib: 'Configuring authlib',
      natives: 'Extracting native libraries',
      building: 'Building launch arguments',
      preparing: 'Preparing environment',
      launching: 'Launching game',
      running: 'Game running',
      crashed: 'Game crashed',
      failed: 'Launch failed',
      completed: 'Game exited',
      cancelled: 'Cancelled',
    },
    viewCrashReport: 'View crash report',
    processId: 'Process ID: {pid}',
    startingUp: 'Starting...',
  },
  // Crash analysis
  crashAnalysis: {
    copyAll: 'Copy All',
    copyDetail: 'Details:\n{detail}',
    copyArgs: 'Launch arguments:\n{args}',
    copyCrashReport: 'Crash report:\n{crashReport}',
    copyLogLink: 'Log link: {url}',
    exporting: 'Exporting...',
    exportReport: 'Export diagnostic report',
    exportFailed: 'Export failed',
    detail: 'Error Details',
    crashReport: 'Crash Report',
    launchArgs: 'Launch Arguments',
    analyzing: 'Analyzing crash report...',
    noResult: 'No analysis results',
    scanQr: 'Scan to view full log',
  },
  // Import modpack
  import: {
    title: 'Import Modpack',
    parsing: 'Parsing modpack file...',
    modpackName: 'Modpack Name',
    gameVersion: 'Game Version',
    loader: 'Loader',
    instanceName: 'Instance Name',
    startInstall: 'Start Install',
    connecting: 'Connecting...',
    installing: 'Installing: {name}',
    completed: '✓ Installation complete!',
    completedDetail: 'The modpack was installed as instance "{name}"',
    failedWith: 'Install failed: {error}',
    seeDownloadPage: 'See the download page for details',
    viewInstance: 'View Instance',
    backgroundDownload: 'Download in Background',
    parseFailed: 'Parse failed',
    installFailed: 'Install failed',
  },
  // Install modpack (online)
  modpackInstall: {
    title: 'Install Modpack',
    modpackLabel: 'Modpack',
    gameVersion: 'Game Version',
    loader: 'Loader',
    instanceName: 'Instance Name',
    startInstall: 'Start Install',
    resolving: 'Resolving and installing...',
    connecting: 'Connecting...',
    installing: 'Installing: {name}',
    completed: '✓ Installation complete!',
    completedDetail: 'The modpack was installed as instance "{name}"',
    failedWith: 'Install failed: {error}',
    seeDownloadPage: 'See the download page for details',
    viewInstance: 'View Instance',
    backgroundDownload: 'Download in Background',
    cancelled: 'Cancelled',
    installFailed: 'Install failed',
  },
  // App update
  update: {
    foundNew: 'New version {version} available',
    noNotes: 'No release notes',
    downloadFailed: 'Download failed',
    done: 'Update complete',
    downloading: 'Downloading {progress}%',
    later: 'Later',
    installing: 'Installing...',
    downloadingAction: 'Downloading...',
    updateNow: 'Update Now',
  },
  // License activation
  license: {
    title: 'Activate License',
    loadFailed: 'Failed to load',
    activateFailed: 'Activation failed',
    active: 'License activated',
    id: 'ID: {licenseId}',
    expireAt: 'Expires: {date}',
    permanent: 'Permanent',
    machineCode: 'Machine Code',
    copyMachineCode: 'Copy machine code',
    tokenLabel: 'License Token',
    tokenPlaceholder: 'Paste the license Token provided by the administrator...',
    tokenHint: 'Contact the administrator to get a new license Token. Enter it and click Activate to verify.',
    exitLauncher: 'Exit Launcher',
    verifying: 'Verifying...',
    activate: 'Activate',
  },
  // Microsoft re-auth
  microsoftReauth: {
    title: 'Microsoft Account Credentials Expired',
    description: 'Your Microsoft account credentials have expired. You need to sign in again to launch the game.',
    reauth: 'Sign In to Microsoft Again',
  },
  // No account
  noAccount: {
    title: 'No Account Set',
    description: 'Launching the game requires a Minecraft account. Please add an account first.',
    goToAccounts: 'Go to Account Management',
    addAccount: 'Add Account',
  },
  // Select default account
  accountSelect: {
    title: 'Select Default Account',
    description: 'Choose an account to use as the default. It will be used when launching the game.',
    noAccounts: 'No accounts',
  },
  // Version picker
  versionPicker: {
    title: 'Switch Version — {name}',
    loadingVersions: 'Loading version list...',
    noVersions: 'No versions available',
    switching: 'Switching...',
    switch: 'Switch',
  },
  // Mod updates
  modUpdate: {
    title: 'Check Mod Updates',
    checkFailed: 'Failed to check for updates',
    addedToDownloadList: 'Added {count} tasks to the download list',
    updatedCount: 'Updated {count} mods',
    completedWithFailed: 'Completed {success}, failed {failed}{failNames}',
    batchFailed: 'Batch update failed',
    allUpToDate: 'All mods are up to date',
    updating: 'Updating...',
    updateCount: 'Update {count} mods',
  },
  // Announcement
  announcement: {
    gotIt: 'Got it',
  },
  // Cape management
  cape: {
    title: 'Switch Cape',
    noCapes: 'This account has no capes available',
    loadingShort: 'Loading',
    inUse: 'In use',
    clickToEquip: 'Click to equip',
  },
  // Resource install
  resourceInstall: {
    title: 'Install {name}',
    selectInstance: 'Select Instance',
    loadingInstances: 'Loading instance list...',
    instancesLoadFailed: 'Failed to load instance list',
    noInstances: 'No instances yet. Create an instance first.',
    searchPlaceholder: 'Search instances...',
    default: 'Default',
    selectVersion: 'Select Version',
    selectInstanceFirst: 'Please select an instance first',
    loadingVersions: 'Loading version list...',
    versionsLoadFailed: 'Failed to load version list',
    selectVersionPlaceholder: 'Select a version',
    noVersions: 'No versions available',
    depsTitle: 'Dependency Mods',
    parsingDeps: 'Resolving dependency mods...',
    depsLoadFailed: 'Failed to load dependency mods',
    noDeps: 'No dependency mods',
    installed: 'Installed',
    pending: 'Pending',
    noDownloadableFile: 'This version has no downloadable files',
    downloadFailedWith: '"{name}" download failed: {error}',
    downloading: 'Downloading',
    installConfirm: 'Confirm Install',
    installing: 'Installing...',
    installingWithName: 'Downloading {name} ({step}/{total})',
    installedDone: 'Install complete: {name}',
  },
  // Mod card
  mod: {
    mcwiki: 'MC Encyclopedia',
    changeVersion: 'Switch Version',
    update: 'Update',
    addedToDownloadList: 'Added to download list',
    updatedWithName: 'Updated "{name}"',
    updateFailedWithName: 'Failed to update "{name}"',
    updateFailed: 'Update failed',
    updateAvailableTo: 'Update available to {version}',
    unknownVersion: 'Unknown version',
  },
  // Save card
  save: {
    backup: 'Backup',
    rename: 'Rename',
    quickJoin: 'Quick Join',
    lastPlayed: 'Last played: {date}',
  },
  // Copyright notice dialog
  legal: {
    title: 'Copyright Notice',
    content: `**Qomicex Launcher** is developed and maintained by the **Qomicex team**, and its copyright belongs to the Qomicex team.

- This software is released under the **GPL-3.0 License**; you may freely use, copy, modify and redistribute it under that license.
- This software has no affiliation, partnership or endorsement with **Mojang Studios / Microsoft** or their products.
- **Minecraft** and related names, logos and copyrights belong to **Mojang Studios / Microsoft**.
- This software does not include the Minecraft game itself; game resources belong to their respective owners.
- By using this software you agree to the *User Agreement* and the *Privacy Policy*.`,
  },
} as const
