// Backend error messages (mapped from error codes on the frontend, en)
export default {
  notFound: 'Requested resource was not found',
  forbidden: 'You do not have permission to perform this action',
  badRequest: 'Invalid request parameters',
  internalError: 'Internal server error',
  upstreamError: 'Upstream service request failed',
  requestTimeout: 'Request timed out, please try again later',
  unknown: 'Request failed, please try again later',
  licenseNotFound: 'License is not activated',
  licenseDecryptFailed: 'License decryption failed',
  licenseSignatureInvalid: 'Invalid license signature',
  licensePublicKeyUnavailable: 'License public key unavailable',
  licenseExpired: 'License has expired',
  licenseRemoteCheckFailed: 'License remote verification failed',
  licenseIoError: 'Failed to read license file',
  tokenExpired: 'Login token expired, please sign in again',
  mcApiError: 'Minecraft official API request failed',
  fsAuthRequired: 'Filesystem access not authorized',
  pluginMissingDependency: 'Plugin is missing required dependencies',
} as const
