// Instances list (en)
export default {
  title: 'Game Instances',
  subtitle: '{count} versions',
  type: {
    release: 'Release',
    snapshot: 'Snapshot',
    old_beta: 'Old Beta',
    old_alpha: 'Old Alpha',
    april_fools: 'April Fools',
  },
  category: {
    all: 'All',
    release: 'Release',
    snapshot: 'Snapshot',
    april_fools: 'April Fools',
    old_beta: 'Old Beta',
    old_alpha: 'Old Alpha',
  },
  sort: {
    recommended: 'Recommended',
    newest: 'Newest first',
    oldest: 'Oldest first',
    'name-asc': 'Name A-Z',
    'name-desc': 'Name Z-A',
  },
  loaderFilter: {
    all: 'All',
    modded: 'Modded',
    vanilla: 'Vanilla',
    snapshot: 'Snapshot',
    april_fools: 'April Fools',
    broken: 'Broken',
  },
  downloadTitle: 'Download a New Version',
  categoryLabel: 'Category',
  searchPlaceholder: 'Search versions...',
  remoteCount: '{count} remote versions',
  filteredCount: '{count} after filter',
  noRemoteMatch: 'No matching remote versions',
  noRemoteMatchHint: 'Try adjusting category, sort or search keywords',
  releaseDate: 'Released {date}',
  select: 'Select',
  configTitle: 'Configure Download',
  instanceName: 'Instance name',
  instanceNamePlaceholder: 'Enter instance name...',
  gameVersion: 'Game version',
  loader: 'Mod loader',
  loaderPlaceholder: 'Select loader',
  noneVanilla: 'None (pure vanilla)',
  versionPlaceholder: 'Select version',
  loadingVersions: 'Loading...',
  noVersionData: 'No version data',
  latestRecommended: 'Latest {version} (recommended)',
  recommended: ' (recommended)',
  selectLoaderFirst: 'Select a loader first',
  latestVersion: 'Latest {version}',
  addons: 'Add-ons',
  optional: '(optional)',
  fetchingAddons: 'Fetching add-ons...',
  onlyGameFiles: 'Downloads game files only; memory and Java settings can be adjusted after creation',
  noLoaderAvailable: 'No loader versions available, cannot download',
  cancel: 'Cancel',
  startDownload: 'Start Download',
  repairName: 'Repair {name}',
  pickGameDirTitle: 'Choose game directory',
  enterDirPath: 'Enter game directory path:',
  chooseDir: 'Choose directory',
  addDir: 'Add directory',
  selectDirFirst: 'Please select a game directory before downloading.',
  noLoaderVersions: 'Could not fetch available versions for {loader}. Check your network or try again later.',
  selectLoaderVersion: 'Please select a specific {loader} version to download.',
  createFailed: 'Create failed: {error}',
  createInstanceFailed: 'Failed to create instance: {error}',
  launchFailed: 'Launch failed: {error}',
  launchFailedDetail: 'Launch failed: {error}\n{detail}',
  refresh: 'Refresh',
  dirManagerTitle: 'Directory Manager',
  noDir: 'No directories',
  noDirHint: 'Click the button below to add a game directory',
  dirCount: '{count} directories, check to mark the active one',
  openDir: 'Open directory',
  remove: 'Remove',
  manualAdd: 'Add manually',
  browseAdd: 'Browse and add',
  instanceSettings: 'Instance Settings',
  basicInfo: 'Basic info',
  repairFiles: 'Repair files',
  versionName: 'Version name',
  gameDir: 'Game directory',
  notCreatedYet: 'This version has not been created in the launcher yet; files cannot be repaired.',
  repairDesc: 'Scans and downloads missing Minecraft game files (libraries, assets, client.jar) for this instance.',
  addedToDownload: 'Added to download queue',
  goToDownloadCenter: 'View in Download Center',
  repairCompleted: 'Repair completed',
  repairFailed: 'Repair failed',
  retry: 'Retry',
  startRepair: 'Start Repair',
  selectGameDir: 'Select game directory',
  savedDirs: 'Saved directories',
  manage: 'Manage',
  noDirInManager: 'No directories, add them in Manager',
  scanning: 'Scanning...',
  import: 'Import',
  openGameDir: 'Open game directory',
  selectMcDir: 'Please select a Minecraft game directory',
  selectMcDirHint: 'Choose a .minecraft directory containing a versions folder',
  browseAndSelect: 'Browse and select',
  noMatch: 'No matching versions',
  noVersionDetected: 'No Minecraft versions detected in this directory',
  needVersionsFolder: 'Please make sure a versions/ folder exists in the directory',
  available: 'Available',
  unavailable: 'Unavailable',
  launch: 'Launch',
  settings: 'Settings',
  unpin: 'Unpin',
  pinToHome: 'Pin to home',
  openFolder: 'Open folder',
} as const
