// Instance detail (en)
export default {
  tabs: {
    overview: 'Overview',
    settings: 'Settings',
    gamesettings: 'Game Settings',
    saves: 'Saves',
    screenshots: 'Screenshots',
    resourcepacks: 'Resource Packs',
    shaderpacks: 'Shader Packs',
    datapacks: 'Data Packs',
    servers: 'Servers',
  },
  confirm: {
    cancel: 'Cancel',
    deleting: 'Deleting...',
    delete: 'Delete',
    confirm: 'Confirm',
  },
  time: {
    minutes: '{count} min',
    hours: '{count} h',
    hoursMinutes: '{hours} h {minutes} min',
    never: 'Never',
    justNow: 'Just now',
    minutesAgo: '{count} min ago',
    hoursAgo: '{count} h ago',
  },
  openFolder: 'Open folder',
  loading: 'Loading...',
  noMatch: 'No matches',
  empty: 'Empty',
  deleteSelected: 'Delete {count}',
  batchDeleteTitle: 'Delete {type}',
  batchDeleteConfirm: 'Delete the selected {count} {type}? They will be moved to recycle bin.',
  saves: {
    search: 'Search saves...',
    noMatch: 'No matching saves',
    empty: 'No saves',
    type: 'saves',
  },
  screenshots: {
    search: 'Search screenshots...',
    noMatch: 'No matching screenshots',
    empty: 'No screenshots',
    type: 'screenshots',
  },
  resourcepacks: {
    search: 'Search resource packs...',
    noMatch: 'No matching resource packs',
    empty: 'No resource packs',
    type: 'resource packs',
    install: 'Install resource pack',
    loadFailed: 'Failed to load resource packs: {error}',
  },
  shaderpacks: {
    search: 'Search shader packs...',
    noMatch: 'No matching shader packs',
    empty: 'No shader packs',
    type: 'shader packs',
    install: 'Install shader pack',
    loadFailed: 'Failed to load shader packs: {error}',
  },
  datapacks: {
    search: 'Search data packs...',
    noMatch: 'No matching data packs',
    empty: 'No data packs',
    type: 'data packs',
    install: 'Install data pack',
  },
  mods: {
    management: 'Mod Management',
    noModsHint: 'This instance cannot use mods; a loader such as Forge or Fabric is required',
    search: 'Search mods...',
    checkUpdates: 'Check updates',
    install: 'Install Mod',
    fetchingRemoteInfo: 'Fetching remote info (Modrinth/CurseForge id, icon, name)...',
    readingMods: 'Reading mod info',
    loadFailed: 'Failed to load mod list: {error}',
    noMatch: 'No matching mods',
    empty: 'No mods',
    enable: 'Enable',
    disable: 'Disable',
    updateMods: 'Update mods',
    filterAll: 'All',
    updatable: 'Updatable',
    duplicate: 'Duplicate',
    sortNameAsc: 'Name A-Z',
    sortNameDesc: 'Name Z-A',
    sortTimeDesc: 'Newest first',
    sortTimeAsc: 'Oldest first',
    sortSizeDesc: 'Largest first',
    sortSizeAsc: 'Smallest first',
    batchEnable: 'Enable selected',
    batchDisable: 'Disable selected',
    batchDelete: 'Delete selected',
    batchConfirm: 'Confirm to {action} {count} mod(s)?',
    moveToRecycleBin: 'They will be moved to recycle bin.',
    processing: 'Processing...',
    checkingUpdates: 'Checking for mod updates…',
    foundUpdates: 'Found {count} mods with updates',
    addedToDownload: 'Added {count} task(s) to download list',
    updatedCount: 'Updated {count} mods',
    updateResult: '{success} done, {failed} failed{failures}',
    updateFailed: 'Failed to update mods',
    loadFailedGeneric: 'Failed to load: {error}',
    unknownError: 'Unknown error',
  },
  servers: {
    search: 'Search servers...',
    pingAll: 'Ping all',
    addServer: 'Add server',
    edit: 'Edit',
    ping: 'Ping',
    copyIp: 'Copy IP',
    quickJoin: 'Quick join',
    delete: 'Delete',
    online: 'Online',
    offline: 'Offline',
    pinging: 'Pinging...',
    lanGames: 'LAN games ({count})',
    lanGame: 'LAN game',
    join: 'Join',
    deleteConfirm: 'Delete server "{ip}"?',
    addTitle: 'Add Server',
    editTitle: 'Edit Server',
    name: 'Server name',
    address: 'Server address',
    updating: 'Updating...',
    adding: 'Adding...',
    save: 'Save',
    add: 'Add',
    copiedIp: 'IP address copied',
    copyFailed: 'Copy failed',
    pingDone: 'Ping: {ping}ms',
    addressOffline: '{address} is offline',
    pingFailed: 'Ping failed',
    deleted: 'Server deleted',
    deleteFailed: 'Delete failed',
    updated: 'Updated "{name}"',
    added: 'Added "{name}"',
    opFailed: 'Operation failed',
    loadFailed: 'Failed to load server list',
  },
  overview: {
    launch: 'Launch',
    unpin: 'Unpin',
    pin: 'Pin to home',
    gameVersion: 'Game version',
    loader: 'Loader',
    pureVanilla: 'Pure vanilla',
    lastPlayed: 'Last played',
    totalPlayTime: 'Total play time',
    modpackInfo: 'Modpack info',
    modpackName: 'Modpack name',
    version: 'Version',
    author: 'Author',
    summary: 'Summary',
    quickActions: 'Quick actions',
    defaultAccount: 'Default account',
    launchGame: 'Launch Game',
    instanceSettings: 'Instance settings',
    verifyIntegrity: 'Verify file integrity',
    repairing: 'Repairing {progress}%',
    openGameDir: 'Open game directory',
    deleteInstance: 'Delete instance',
    refresh: 'Refresh',
  },
  settingsTab: {
    instanceName: 'Instance name',
    instanceIcon: 'Instance icon',
    gameVersion: 'Game version',
    javaRuntime: 'Java runtime',
    autoSelect: 'Auto select',
    integrity: 'File integrity',
    checkIntegrity: 'Check file integrity',
    repairing: 'Repairing {progress}%',
    missingFiles: '{count} missing file(s)',
    autoRepairing: 'Auto repairing...',
    integrityOk: 'Files complete',
    versionIsolation: 'Version isolation',
    followGlobal: 'Follow global setting',
    on: 'On',
    off: 'Off',
    isolationDesc: 'Each version uses separate mods/config/saves directories',
    skipIntegrity: 'Skip file integrity check',
    skipIntegrityDesc: 'Skips file integrity check at launch; may crash if files are missing',
    memoryAllocation: 'Memory allocation',
    auto: 'Auto',
    custom: 'Custom',
    totalMem: 'Total memory {size} GiB',
    usedMem: 'Used {size} GiB',
    gameAlloc: 'Game allocation {size} GiB',
    remainingMem: 'Remaining {size} GiB',
    jvmArgs: 'JVM arguments',
    linkedAccount: 'Linked account',
    unlinked: 'Not linked',
    saving: 'Saving...',
  },
  gamesettings: {
    search: 'Search settings...',
    noMatch: 'No matching settings',
    empty: 'No game settings',
    pressKey: 'Press a key...',
  },
  launch: {
    launchFailed: 'Launch failed',
    instanceRunningConfirm: 'This instance is already running. Launch a new instance?',
    instanceRunningTitle: 'Instance running',
    backToList: 'Back to instances',
    instanceNotFound: 'Instance not found',
    loadingInstance: 'Loading instance...',
    deleteInstanceConfirm: 'Delete instance "{name}"? Its version folder will be permanently removed.',
  },
} as const
