// Settings page (en; batch0 covers category nav + appearance core, rest filled by migration batches)
export default {
  category: {
    launcher: 'Launcher',
    java: 'Java Runtime',
    plugins: 'Plugins',
    appearance: 'Appearance',
    toolbox: 'Toolbox',
    logs: 'Logs',
    about: 'About',
    debug: 'Debug',
  },
  saved: 'Settings saved',
  appearance: {
    title: 'Interface',
    language: 'Language',
    theme: 'Theme',
    dark: 'Dark',
    light: 'Light',
    animations: 'Page animations',
    animationsDesc: 'Enables transition animations for page switches and dialogs',
    animationSpeed: 'Animation speed',
    slow: 'Slow',
    normal: 'Normal',
    fast: 'Fast',
    maxFrameRate: 'Max frame rate',
    maxFrameRateUnlimited: 'Unlimited',
    maxFrameRateDesc: 'Limits the frame rate of the launcher UI to reduce resource usage. Unlimited uses the display refresh rate.',
    cornerRadius: 'Corner radius',
    windowCorners: 'Window corners',
    windowCornersDesc: 'Only takes effect when not using the system frame',
    cornerSharp: 'Sharp',
    cornerDefault: 'Default (8px)',
    cornerLarge: 'Large',
    background: 'Background',
    backgroundImage: 'Background image',
    noBackgrounds: 'No background images',
    openFolder: 'Open folder',
    backgroundsHint: 'Drop images here and they appear in the list above',
    backgroundRandom: 'Pick randomly on each launch',
    backgroundRandomDesc: 'Picks a random image from the background folder',
    clearBackground: 'Clear background',
    opacity: 'Opacity',
    transparent: 'Transparent',
    opaque: 'Opaque',
    blur: 'Blur',
    sharp: 'Sharp',
    watermark: 'Watermark',
    watermarkEnabled: 'Show watermark text on home page',
    watermarkEnabledDesc: 'Shows customizable text in the center of the home page',
    watermarkText: 'Watermark text',
    watermarkSubtext: 'Subtitle',
    watermarkSubtextPlaceholder: 'Launcher',
  },
  launcher: {
    title: 'Launcher settings',
    dataDir: 'Data directory',
    dataDirDesc: 'Where launcher data is stored; a restart is required after changing',
    dataDirChanged: 'Data directory changed; takes effect after restarting the launcher',
    saveFailed: 'Failed to save settings',
    downloadThreads: 'Download threads',
    downloadThreadsDesc: 'Number of files downloaded at the same time (1-512). Higher values download faster but use more bandwidth',
    fileChunkThreads: 'Chunk threads',
    fileChunkThreadsDesc: 'Chunk threads per file (0=auto, max 16). Higher values speed up single-file downloads',
    maxConnections: 'Max connections per server',
    maxConnectionsDesc: 'Max connections per server (8-256); takes effect after restart',
    versionIsolation: 'Version isolation',
    versionIsolationDesc: 'Each version uses separate mods/config/saves directories; keeping this on is recommended',
    closeAfterLaunch: 'Close launcher after launching the game',
    closeAfterLaunchDesc: 'Automatically closes the launcher after the game starts',
    downloadSource: 'Download source',
    downloadSourceName: { 0: 'Official', 1: 'BMCLAPI mirror' },
    modSource: 'Resource download source',
    modSourceName: { 0: 'Modrinth/CurseForge official', 1: 'MCIM mirror' },
    refreshLatency: 'Refresh latency',
    autoSelectDownloadSource: 'Auto-select fastest download source',
    autoSelectDownloadSourceDesc: 'Automatically detects and picks the lowest-latency download source at startup and before each install',
    autoSelectModSource: 'Auto-select fastest resource download source',
    autoSelectModSourceDesc: 'Automatically detects Modrinth/CurseForge API mirrors and picks the lowest-latency one',
    translationProvider: 'Translation provider',
    translationDefault: 'MyMemory (default)',
    translationGoogle: 'Google Translate (requires VPN)',
    translationProviderDesc: 'Selects the translation service used for resource descriptions and summaries',
    bingApiKeyPlaceholder: 'Enter your Azure Translator API Key',
    bingApiKeyDesc: 'Create a Translator resource in Azure Portal to get a Key; the region must be set to global',
    downloadTimeout: 'Download timeout (seconds)',
    downloadTimeoutDesc: 'A file with no response for longer than this is retried automatically (0=no timeout, 1-120 seconds)',
    logLevelLabel: 'Log level',
    logLevel: { error: 'Error', warn: 'Warning', info: 'Info', debug: 'Debug', trace: 'Trace' },
    logLevelDesc: 'Controls verbosity of console and log file output; info is the default',
    storageCache: 'Storage & cache',
    versionListCache: 'Version list cache',
    versionListCacheDesc: 'Clears the HTML cache of the Forge version list',
    clearCache: 'Clear cache',
    curseforgeConcurrency: 'CurseForge version list concurrency',
    curseforgeConcurrencyDesc: 'Number of pages fetched concurrently (1-20). Higher values load the version list faster',
    curseforgeTtl: 'CurseForge version list cache TTL (seconds)',
    curseforgeTtlDesc: '0 = cache forever (until restart or manual clear), default 300 seconds (5 minutes)',
    curseforgeCache: 'CurseForge version cache',
    curseforgeCacheDesc: 'Clears the in-memory CurseForge version list cache',
    clearCurseforgeCache: 'Clear CurseForge version cache',
    cacheCleared: 'Cache cleared, {count} file(s) deleted',
    cacheClearFailed: 'Failed to clear cache',
    curseforgeCacheCleared: 'CurseForge version cache cleared',
    curseforgeCacheClearFailed: 'Failed to clear CurseForge cache',
  },
  java: {
    title: 'Java Runtime',
    ready: 'Ready',
    detected: 'Detected',
    available: 'Available',
    quickScan: 'Quick scan',
    deepScan: 'Deep scan',
    manualAdd: 'Add manually',
    downloadJava: 'Download Java',
    refreshList: 'Refresh list',
    scanningQuick: 'Quick scanning...',
    scanningDeep: 'Deep scanning...',
    scanDoneFound: 'Scan complete, found {count} new version(s)',
    scanDoneNone: 'Scan complete, no new versions',
    scanFailed: 'Scan failed',
    refreshing: 'Refreshing...',
    scanningRuntime: 'Scanning for Java runtimes...',
    noRuntimeDetected: 'No Java runtime detected yet',
    noRuntimeHint: 'Click "Quick scan" to detect Java on your system, or add one manually',
    startScan: 'Start scan',
    usable: 'Available',
    unusable: 'Unavailable',
    openFolder: 'Open folder',
    availableCount: '{valid} / {total} available',
    defaultConfig: 'Default configuration',
    defaultRuntime: 'Default Java runtime',
    autoSelect: 'Auto-select',
    defaultRuntimeDesc: 'Auto-select is recommended: the launcher picks the best Java runtime for each game version',
    memoryAllocation: 'Memory allocation',
    memoryAuto: 'Auto',
    memoryCustom: 'Custom',
    totalMemory: 'Total {value} GiB',
    usedMemory: 'Used {value} GiB',
    gameMemory: 'Game allocation {value} GiB',
    remainingMemory: 'Remaining {value} GiB',
    jvmArgs: 'Additional JVM arguments',
    jvmArgsDesc: 'JVM arguments passed when launching Minecraft',
    pickJavaExecutable: 'Select Java executable',
    unrecognizedPath: 'Cannot recognize a Java runtime at this path',
    added: 'Added {name} {version}',
    loadCatalogFailed: 'Failed to load Java download catalog',
    addedToDownload: 'Added to download center: {name}',
    downloadFailed: 'Failed to start Java download',
    deleteConfirm: 'Are you sure you want to delete "{name}"?',
    deleteTitle: 'Delete Java',
    deleted: 'Deleted {name}',
    deleteFailed: 'Failed to delete',
    manualAddTitle: 'Add Java manually',
    executablePath: 'Java executable path',
    browse: 'Browse',
    executablePathDesc: 'Select or enter the full path to a Java executable',
    verifying: 'Verifying...',
    add: 'Add',
    distribution: 'Distribution',
    recommended: '(recommended)',
    mainVersion: 'Java major version',
    platform: 'Platform',
    architecture: 'Architecture',
    targetDir: 'Target directory',
    resolving: 'Resolving...',
    startDownload: 'Start download',
  },
  plugins: {
    title: 'Plugin management',
    installedCount: '{count} installed',
    searchPlaceholder: 'Search plugins...',
    installing: 'Installing...',
    install: 'Install plugin',
    noneInstalled: 'No plugins installed yet',
    noMatch: 'No matching plugins',
    changesApplied: 'Changes applied',
    saveFailed: 'Failed to save',
    uninstallConfirm: 'Are you sure you want to uninstall this plugin?',
    uninstalled: 'Plugin uninstalled',
    uninstallFailed: 'Failed to uninstall',
    installSuccess: 'Plugin installed successfully',
    installFailed: 'Install failed: {message}',
    permissions: 'Permissions ({count})',
    contributes: 'Contributes',
  },
  about: {
    aboutApp: 'About {name}',
    beta: 'Beta',
    stable: 'Stable',
    feedback: 'Feedback',
    viewRepository: 'View repository',
    versionInfo: 'Version information',
    appVersion: 'App version',
    versionHash: 'Version hash',
    os: 'Operating system',
    architecture: 'System architecture',
    memory: 'Memory',
    license: 'License',
    licenseActivated: 'Activated',
    licenseNotActivated: 'Not activated',
    licenseInvalid: 'Invalid',
    channel: 'Channel',
    expiry: 'Expires',
    permanent: 'Permanent',
    machineCode: 'Machine code',
    changeLicense: 'Change license',
    activateLicense: 'Activate license',
    copyMachineCode: 'Copy machine code',
    update: 'Update',
    checking: 'Checking...',
    checkUpdate: 'Check for updates',
    upToDate: 'Already up to date',
    checkUpdateFailed: 'Failed to check for updates',
    developers: 'Developers',
    acknowledgements: 'Acknowledgements',
    referenceProjects: 'Reference projects',
    backendDependencies: 'Backend dependencies',
    frontendDependencies: 'Frontend dependencies',
    openSourceLicense: 'Open-source license',
    licenseNotice: 'This program is released under the {name} open-source license',
    viewLicense: 'View license',
    copyrightPrivacy: 'Copyright & privacy',
    copyrightStatement: 'Copyright notice',
    copyrightStatementDesc: "View this software's copyright ownership and open-source license information",
    userAgreement: 'User agreement',
    privacyPolicy: 'Privacy policy',
    appDescription: 'A modern Minecraft launcher with multi-version management, mod loader compatibility, account management and more.',
    roleProjectLead: 'Project founder / lead developer',
    serviceModrinth: 'Mod and resource search API',
    serviceModpack: 'Modpack API',
    serviceBmclapi: 'Provides BMCLAPI download mirror service',
    serviceMcmod: 'Chinese mod database',
    serviceMinecraft: 'Minecraft official website, support the game!',
    refVersionCheck: 'Version detection reference',
    refModloaderInstaller: 'ModLoader installer reference',
    refLaunchFlow: 'Launch flow reference',
    depBackendRuntime: 'Rust backend runtime',
    depCoreLibraries: 'Core libraries',
    depCoreFramework: 'Core framework',
    depUiComponents: 'UI components',
    depStylesTools: 'Styles & tools',
    depAnimation: 'Animation',
    depRendering: 'Rendering & display',
  },
} as const
