// Misc tools / debug / logs / splash (en)
export default {
  toolbox: {
    title: 'Custom file download',
    description: 'Download any file to a chosen folder via the launcher',
    urlLabel: 'Download URL',
    savePathLabel: 'Save path',
    autoFillPlaceholder: 'Auto-filled after picking a folder',
    pickFolder: 'Choose folder',
    submitting: 'Submitting...',
    startDownload: 'Start download',
    downloadFailed: 'Download failed',
  },
  logs: {
    title: 'Log management',
    loadFailed: 'Failed to load log list',
    exportedTo: 'Exported to {dest}',
    downloadStarted: 'Download started',
    deleteConfirm: 'Delete "{name}"?',
    deleteTitle: 'Delete log',
    deleted: 'Deleted',
    deleteFailed: 'Delete failed',
    openDirFailed: 'Cannot open directory',
    openFailed: 'Cannot open file',
    exportAll: 'Export all',
    exportGz: 'Export (.gz)',
    filesLabel: 'Log files',
    currentSession: 'Current session',
    none: 'No logs',
    emptyDescription: 'The launcher and backend generate log files at runtime',
    open: 'Open',
    openContainingDir: 'Open containing directory',
    retentionHint: 'Keeps the latest 10 logs automatically; the oldest files are cleaned up beyond that',
    currentSessionSuffix: '{count} current session(s)',
    fileCountSuffix: '{count} file(s)',
    debugLogsCount: 'Debug logs ({count})',
  },
  debug: {
    liveLogs: 'Live logs',
    autoScroll: 'Auto-scroll',
    clear: 'Clear',
    exportLogs: 'Export logs',
    triggerDump: 'Trigger Dump',
    noLogs: 'No logs yet...',
    diagnostics: 'Launcher diagnostics',
    systemInfo: 'System info',
    versionInfo: 'Version info',
    connectivity: 'Connectivity',
    apiHealthCheck: 'API health check',
    pathInfo: 'Path info',
    toggleDisableAnimations: 'Disable animations',
    toggleShowComponentBoundaries: 'Show component boundaries',
    toggleSimulateApiErrors: 'Simulate API errors',
    toggleNetworkLogging: 'Network request logging',
    toggleDisableCaching: 'Disable caching',
    toggleLogOverlay: 'Log overlay (global)',
    toggleShowFps: 'Show FPS (top-right)',
    togglesTitle: 'Debug toggles (temporary, reset on restart)',
    clearTasksConfirm: 'Clear all download task records? This cannot be undone.',
    clearTasksTitle: 'Clear download tasks',
    tasksCleared: 'Download task list cleared',
    dataManagement: 'Data management',
    downloadTaskList: 'Download task list',
    clearTasksDescription: 'Clears download task records in localStorage',
    clearTasksButton: 'Clear download task list',
    dumpExported: 'Logs exported to: {path}',
  },
  splash: {
    preparing: 'Preparing to start...',
    almostReady: 'Almost ready...',
  },
  analysis: {
    title: 'Analysis results',
    pageTitle: 'Log analysis',
    inputTitle: 'Enter Minecraft log',
    pastePlaceholder: 'Paste Minecraft log content...',
    analyzeButton: 'Analyze log',
    analyzing: 'Analyzing...',
    analyzeFailed: 'Analysis failed',
    gameVersion: 'Game version',
    modLoader: 'Mod loader',
    noIssues: 'No obvious issues found',
    criticalCount: '{count} Critical',
    errorCount: '{count} Errors',
    warningCount: '{count} Warnings',
    suggestedSolutions: 'Suggested solutions',
    stackTrace: 'Exception stack trace',
    categoryMemory: 'Memory',
    categoryModConflict: 'Mod conflict',
    categoryJavaRelated: 'Java related',
    categoryResource: 'Resource',
    categoryPerformance: 'Performance',
    categoryNetwork: 'Network',
  },
  errors: {
    pageRenderError: 'Page rendering error',
  },
  notifier: {
    downloadCompleted: '{name} download completed',
  },
} as const
