// First-launch setup wizard (en)
export default {
  title: 'Welcome to Qomicex',
  subtitle: 'Complete a few basic settings before you start',
  stepLabel: 'Step {current}/{total}',
  // Step labels
  stepMode: 'Setup mode',
  stepLanguage: 'Language',
  stepTheme: 'Theme',
  stepDirectories: 'Directories',
  stepDownloadSource: 'Download sources',
  stepJava: 'Java runtime',
  stepMemory: 'Memory',
  stepDone: 'Done',
  // Mode selection
  modeTitle: 'Choose a setup mode',
  modeDesc: 'Both modes include language, theme, Java and memory settings',
  quickTitle: 'Quick setup',
  quickDesc: 'Recommended defaults, just a few confirmations to get started',
  customTitle: 'Custom setup',
  customDesc: 'Step-by-step configuration, plus download sources, data and game directories',
  // Language
  languageTitle: 'Choose interface language',
  languageDesc: 'Takes effect immediately; you can change it later in settings',
  // Theme
  themeTitle: 'Choose a theme',
  themeDesc: 'You can switch between dark and light themes in settings anytime',
  dark: 'Dark',
  light: 'Light',
  // Directories
  dirTitle: 'Choose directories',
  dirDesc: 'The data directory stores launcher config; the game directory stores Minecraft files',
  dataDir: 'Data directory',
  dataDirDesc: 'Where launcher config, cache and other data are stored',
  gameDir: 'Game directory',
  gameDirDesc: 'Where Minecraft game files (.minecraft) live',
  browse: 'Browse...',
  // Download sources
  downloadTitle: 'Choose download sources',
  downloadDesc: 'Pick the lowest-latency sources; ping results are for reference only',
  downloadSource: 'Game file source',
  modSource: 'Mod source',
  autoSelect: 'Auto-select best',
  pinging: 'Pinging...',
  pingFailed: 'Ping failed',
  // Java
  javaTitle: 'Set up Java runtime',
  javaDesc: 'Java 8 / 17 / 21 are required. Missing versions can be downloaded online',
  javaScanning: 'Deep-scanning for Java runtimes...',
  javaScanAgain: 'Rescan',
  javaFound: 'Found',
  javaMissing: 'Missing',
  javaDownload: 'Download',
  javaDownloading: 'Downloading {progress}%',
  javaDownloaded: 'Downloaded',
  javaDownloadFailed: 'Download failed',
  javaVersion8: 'Java 8',
  javaVersion17: 'Java 17',
  javaVersion21: 'Java 21',
  javaReady: 'All required versions are ready',
  javaRequired: 'Continue once all required versions are ready',
  // Memory
  memoryTitle: 'Allocate memory',
  memoryDesc: 'Auto allocation is recommended',
  memoryAuto: 'Auto (recommended)',
  memoryAutoDesc: 'Calculated from available system memory',
  memoryCustom: 'Custom',
  memoryCustomDesc: 'Set the maximum memory manually',
  memoryMb: 'MB',
  // Done
  doneTitle: 'Setup complete',
  doneDesc: 'Your settings have been saved. Enjoy Qomicex!',
  doneSummary: 'Configured in this run:',
  finish: 'Get started',
  saving: 'Saving...',
  saveFailed: 'Save failed, please retry',
} as const
