// アカウント（ja-JP）
export default {
  loginErrors: {
    accessDenied: 'ブラウザで認証をキャンセルまたは拒否しました',
    expiredToken: '認証コードの有効期限が切れました。再ログインしてください',
    invalidGrant: '認証が無効です。再ログインしてください',
    loginFailed: 'ログインに失敗しました: {code}',
  },
  methodLabel: {
    offline: 'オフライン',
    thirdParty: 'サードパーティ',
    thirdPartyWith: 'サードパーティ/{server}',
    unified: '統一パスポート',
  },
  dataCorrupted: 'アカウントデータファイルが破損したか、マシンコードが変更されたため、ファイルは削除されました。アカウントを再追加してください。',
  microsoft: {
    gettingInfo: 'ログイン情報を取得中...',
    openingBrowser: 'ブラウザを開いています...',
    codeCopied: '認証コードをクリップボードにコピーしました。ブラウザで Microsoft アカウントにログインしてください\n認証コード: {code}',
    loginTimeout: 'ログインがタイムアウトしました。再ログインしてください',
    gettingAccount: 'アカウント情報を取得中...',
    loginSuccess: 'ログインに成功しました',
    noRole: '利用可能なロールを取得できませんでした',
    stepFetching: 'ログイン情報を取得',
    stepWaiting: '認証を待機',
    stepFetchingInfo: 'アカウント情報を取得',
    codeCopiedShort: '認証コードをコピーしました',
    browserOpened: 'ブラウザを自動的に開きました',
    relogin: '再ログイン',
  },
  deleteConfirm: 'このアカウントを削除しますか？',
  deleteTitle: 'アカウントを削除',
  batchDeleteConfirm: '選択した {count} 個のアカウントを削除しますか？',
  batchDeleteTitle: '一括削除',
  title: 'アカウント管理',
  refresh: '更新',
  addAccount: 'アカウントを追加',
  add: '追加',
  filterAll: 'すべて',
  filterName: '名前',
  filterLoginMethod: 'ログイン方法',
  filterServer: 'サーバー',
  searchPlaceholder: 'アカウントを検索...',
  noMatch: '一致するアカウントがありません',
  noAccounts: 'アカウントがありません',
  setDefault: '既定に設定',
  deleteSelected: '{count} 件削除',
  addTitle: 'アカウントを追加',
  tabOffline: 'オフライン',
  tabUnified: '統一パスポート',
  offline: {
    playerName: 'プレイヤー名',
    playerNamePlaceholder: 'オフラインモードのユーザー名を入力',
    uuid: 'UUID（任意。空の場合は自動生成）',
    uuidPlaceholder: '例: 069a79f4-44e9-4726-a5be-fca90e38aaf5',
    add: 'オフラインアカウントを追加',
  },
  ygg: {
    presetServer: 'プリセットサーバー',
    email: 'メールアドレス',
    password: 'パスワード',
    customServerAddr: 'カスタムサーバーアドレス',
    login: 'ログイン',
    loginLoading: 'ログイン中...',
    saving: '保存中...',
    chooseRole: 'ログインするロールを選択:',
    back: '戻る',
    confirmCount: '確認 ({count})',
    dndHint: 'または認証サーバーをウェブページからここにドラッグ＆ドロップ',
    dndTitle: '認証サーバーを追加',
    dndConfirm: 'この認証サーバーを追加しますか？\n{url}',
    resolvedTo: 'API アドレス: {url}',
    resolveFailed: 'このアドレスに接続できません。元のアドレスのまま試行します',
    httpWarning: '警告: この認証サーバーは平文 HTTP プロトコルを使用します。パスワードが平文で送信され、漏洩のリスクがあります',
  },
  unified: {
    desc: '統一パスポートは一部の Minecraft サーバーが使用する認証システムで、サーバー ID の入力が必要です。',
    serverId: 'サーバー ID',
    serverIdPlaceholder: '例: lilu',
    email: 'メールアドレス',
    password: 'パスワード',
    login: 'ログイン',
    loginLoading: 'ログイン中...',
    oauthLogin: 'Microsoft OAuth ログイン',
  },
} as const
