// 共通メッセージ（ja-JP）
export default {
  ok: '了解',
  cancel: 'キャンセル',
  close: '閉じる',
  save: '保存',
  create: '作成',
  delete: '削除',
  edit: '編集',
  confirm: '確認',
  loading: '読み込み中...',
  noData: 'データなし',
  comingSoon: '近日公開',
  retry: '再試行',
  refresh: '更新',
  copy: 'コピー',
  copied: 'コピー済み',
  search: '検索',
  select: '選択',
  back: '戻る',
  next: '次へ',
  prev: '前へ',
  unknown: '不明',
  all: 'すべて',
  none: 'なし',
  enabled: '有効',
  disabled: '無効',
  error: 'エラー',
  warning: '警告',
  success: '成功',
  failed: '失敗',
  info: '通知',
  input: '入力',
  inputPlaceholder: '入力してください...',
  batchSelected: '{count} 件選択中',
  selectAll: 'すべて選択',
  deselect: '選択解除',
  noMatch: '一致なし',
  pendingTasksCloseConfirm: '未完了のタスクがあります。閉じるとすべてのタスクが削除されます。\n\n本当に閉じますか？',
  language: '表示言語',
  theme: 'テーマ',
  dark: 'ダーク',
  light: 'ライト',
  externalLink: '外部リンク',
  seeMore: 'もっと見る',
  goto: '移動',
  name: '名前',
  version: 'バージョン',
  status: '状態',
  action: '操作',
  detail: '詳細',
  optional: '任意',
  javaRuntimeRequired: 'Minecraft を起動するには Java ランタイム環境が必要です。\n\n「設定 → Java → Java のダウンロード」から簡単にインストールできるほか、インストール済みの Java パスを手動で追加することもできます。',
  javaRuntimeRequiredTitle: 'Java ランタイムが検出されません',
} as const
