// マルチプレイ（ja-JP）
export default {
  hostBadge: 'ホスト',
  kick: 'キック',
  kickReviewTitle: 'プレイヤーが再参加を申請',
  kickReviewBody: 'プレイヤー "{name}" が部屋に再参加しようとしています。許可しますか？',
  kickReviewAllow: '許可',
  kickReviewReject: '拒否',
  kickReviewRejectSilent: '拒否して今後通知しない',
  kickedPlayersTitle: 'キック済みプレイヤー ({count})',
  unban: '禁止を解除',
  noPlayers: 'プレイヤーがいません',
  playerList: 'プレイヤーリスト ({count})',
  hostMods: 'ホストの Mods',
  matchInstances: '一致するインスタンス ({count})',
  scanningMatch: 'ローカルインスタンスとホストの mods を照合中...',
  noHostMods: 'ホストが mods リストを公開していません（またはスキャン中）',
  missingModsDesc: '「不足」と表示された mod は、インスタンス {instance}{countSuffix} に含まれていません（ホストの mods を最も多くカバーするローカルインスタンス）',
  missingModsCountSuffix: '、合計 {count} 個',
  noVersionInfo: 'ホストがバージョン情報を提供していないため、不足している mod を判定できません',
  missingTooltip: 'この mod は最適一致インスタンス（ホストの mods を最も多くカバーするもの）にありません',
  missing: '不足',
  scanningLocal: 'ローカルインスタンスをスキャン中...',
  noVersionForMatch: 'ホストがバージョン情報を提供していないため、ローカルインスタンスと一致させられません',
  noMatchingInstance: 'ホストのゲームバージョン/ローダーと同じローカルインスタンスがありません',
  matchedInstances: '一致インスタンス（{count}）',
  modsConsistent: 'mods 一致 ({count})',
  quickLaunch: 'クイック起動',
  unmatchedInstances: '不一致インスタンス（{count}）は差異を無視して起動できます',
  modsInconsistent: 'mods 不一致 ({count})',
  forceLaunchTitle: 'mod の差異を無視して、このローカルインスタンスで部屋に参加します',
  forceLaunch: '差異を無視して強制起動',
  noLocalInstance: '利用可能なローカルインスタンスがありません',
  gameCrashed: 'ゲームが異常終了しました',
  launchFailed: '起動に失敗しました',
  invalidPort: '有効なポート (1-65535) を入力してください',
  selectInstanceFirst: 'インスタンスを選択してください',
  enterRoomCode: 'ルームコードを入力してください',
  roomNotReady: 'ルームはまだ準備が整っていません',
  natCheckFailed: 'NAT タイプの検出に失敗しました',
  natTypes: {
    cone: { label: 'フルコーン', tooltip: 'UDP: 緩い  TCP: 中程度' },
    symmetric: { label: '対称型', tooltip: 'UDP: 厳しい  TCP: 厳しい' },
    blocked: { label: '貫通不可', tooltip: 'UDP: ブロック  TCP: ブロック' },
    unknown: { label: '不明', tooltip: 'NAT タイプが不明です' },
  },
  title: 'マルチプレイ',
  subtitle: 'マルチプレイのルームを作成または参加',
  natCheck: 'NAT 検出',
  easyTierDownloadFailed: 'EasyTier のダウンロードに失敗しました: {error}',
  retry: '再試行',
  easyTierStatus: {
    resolving: '最速のダウンロードソースを測定中…',
    extracting: 'EasyTier を解凍中…',
    downloading: 'EasyTier マルチプレイコンポーネントをダウンロード中…',
  },
  tabCreate: 'ルームを作成',
  tabJoin: 'ルームに参加',
  createTitle: 'インスタンスを起動してルームを作成',
  selectInstance: 'インスタンスを選択',
  pleaseSelect: '選択してください...',
  starting: '起動中…',
  startAndCreate: '起動してルームを作成',
  openLanHint: '起動後、ゲーム内で「LAN に公開」をクリックしてください。ポートは自動的に検出されます。',
  manualStarted: '手動でインスタンスを起動しましたか？ここをクリック',
  scanPortTitle: 'ローカルポートをスキャン',
  scanningPorts: 'Java プロセスのポートをスキャン中…',
  portDetected: 'ポートを検出しました',
  createRoom: 'ルームを作成',
  manualPort: 'またはポートを手動入力',
  joinTitle: 'ルームに参加',
  roomCode: 'ルームコード',
  joining: '参加中…',
  joinRoom: 'ルームに参加',
  gotIt: '了解',
  cancel: 'キャンセル',
  closeRoom: 'ルームを閉じる',
  serverAddress: 'サーバーアドレス',
  hostVersion: 'ホストバージョン: {version}',
  leaveRoom: 'ルームを退出',
} as const
