// 外部起動（qomicex-launcher:// ディープリンク、issue #127）のプロンプト文言
export default {
  launchNotFound: 'インスタンスが見つかりません：{target}',
  joinConfirmTitle: 'ルームに参加',
  joinConfirmDesc: 'ウェブページがルーム {code} への参加を要求しています。続行しますか？',
  joinFailed: 'ルームへの参加に失敗しました：{message}',
  installPluginConfirmTitle: 'プラグインをインストール',
  installPluginConfirmDesc: 'この要求は {host} からのもので、プラグイン {name} をインストールします。この提供元を信頼できる場合のみ続行してください。',
  installPluginSlugConfirmDesc: 'ウェブページがストアのプラグイン {slug} のインストールを要求しています。続行しますか？',
  installModpackConfirmTitle: 'Modパックをインストール',
  installModpackConfirmDesc: 'ウェブページが Modパック {name}（提供元：{source}）のインストールを要求しています。続行しますか？',
  installStarted: 'インストールを開始しました',
  installFailed: 'インストールに失敗しました：{message}',
  cancelled: '操作をキャンセルしました',
  registerTitle: '外部起動リンクの関連付け',
  registerDesc: 'qomicex-launcher:// リンクを開くアプリとしてランチャーを登録しますか？登録すると、ウェブページやショートカットから直接ランチャーを起動できます。',
  registerSuccess: '外部起動リンクを関連付けました',
  registerFailed: '関連付けに失敗しました。後で設定から再試行できます',
  registerDeclined: 'スキップしました。今後は自動で確認しません',
  launchAmbiguous: '{count} 個のインスタンスがすべて「{target}」という名前のため、どれを起動すべきか判断できません。代わりに ディレクトリ:インスタンス名 の形式で指定してください。例：{example}',
}
