// ダウンロードセンター（ja-JP）
export default {
  status: {
    queued: '待機中',
    downloading: 'ダウンロード中',
    paused: '一時停止',
    completed: '完了',
    failed: '失敗',
    cancelled: 'キャンセル済み',
  },
  stage: {
    queued: '待機中',
    'fetching-json': 'バージョンマニフェストを取得',
    'downloading-installer': 'ローダーインストーラーをダウンロード',
    downloading: 'ゲームファイルをダウンロード',
    'scanning-base': 'ゲームファイルをスキャン',
    'downloading-base': 'ゲームファイルをダウンロード',
    'scanning-loader-libs': 'ローダーライブラリをスキャン',
    'downloading-loader-libs': 'ローダーライブラリをダウンロード',
    'installing-optifine': 'OptiFine をインストール',
    'downloading-addons': '追加コンテンツをダウンロード',
    'downloading-additional-files': '追加ファイルをダウンロード',
    'installing-loader': 'ローダーをインストール',
    'verifying-jar': 'メイン jar を検証',
    finishing: '仕上げ',
    'downloading-json': 'バージョン JSON をダウンロード',
    'downloading-libraries': 'ライブラリをダウンロード',
    'downloading-assets': 'アセットをダウンロード',
    'downloading-mainjar': 'メインファイルをダウンロード',
    'downloading-loader': 'ローダーをダウンロード',
    'downloading-modpack': 'Modパックをダウンロード',
    'parsing-modpack': 'Modパックを解析',
    'modpack-files': 'Modパックファイルをダウンロード',
    'modpack-overrides': '上書きファイルを解凍',
  },
  steps: {
    fetchJson: 'バージョンマニフェストを取得',
    installer: 'ローダーインストーラーをダウンロード',
    gameFiles: 'ゲームファイルをダウンロード',
    loaderLibs: 'ローダーライブラリをダウンロード',
    installLoader: 'ローダーをインストール',
    installOptifine: 'OptiFine をインストール',
    downloadAddons: '追加コンテンツをダウンロード',
    finalize: '検証と仕上げ',
    downloadModpack: 'Modパックをダウンロード',
    parseModpack: 'Modパックを解析',
    installGame: 'ゲーム本体をインストール',
    downloadFiles: 'Modパックファイルをダウンロード',
    overrides: '上書きファイルを展開',
  },
  speedLabel: 'ダウンロード速度',
  stepsDone: '{done}/{total} ステップ完了',
  filter: {
    all: 'すべて',
    downloading: 'ダウンロード中',
    paused: '一時停止',
    completed: '完了',
    failed: '失敗',
  },
  title: 'ダウンロードセンター',
  subtitle: '{count} 個のタスク',
  clearFinished: '完了/失敗をクリア',
  taskCount: '{count} 個のタスク',
  empty: 'ダウンロードタスクがありません',
  emptyHint: '「インスタンス」ページでバージョンを選択してダウンロードを開始すると、ここに表示されます',
  goToInstances: 'インスタンスへ',
  addonsCount: '+ {count} 個の追加',
  createdAt: '作成日時 {date}',
  completedAt: '完了日時 {date}',
  resume: '再開',
  pause: '一時停止',
  cancel: 'キャンセル',
  retry: '再試行',
  remove: '削除',
  statusText: {
    done: 'ダウンロード完了',
    failedWith: '失敗: {error}',
    failed: 'ダウンロード失敗',
    pausedProgress: '{progress}% で一時停止',
    waiting: '待機中',
    downloading: 'ダウンロード中',
    connecting: '接続中…',
  },
  filesCount: '{done}/{total} ファイル',
  errors: {
    taskExpired: 'タスクの有効期限が切れました（バックエンドが再起動されました）',
    downloadFailed: 'ダウンロード失敗',
    cannotVerify: 'タスク状態を検証するためにバックエンドに接続できません',
    statusUnknown: 'タスク状態を確認できません（バックエンドがこのセッションを報告していません）',
    taskInvalid: 'タスクが無効です',
  },
} as const
