// バックエンドエラーメッセージ（フロントエンドのエラーコード表示用、ja-JP）
export default {
  notFound: '要求されたリソースが存在しません',
  forbidden: 'この操作を実行する権限がありません',
  badRequest: 'リクエストパラメータが不正です',
  internalError: 'サーバー内部エラー',
  upstreamError: '上流サービスへのリクエストに失敗しました',
  requestTimeout: 'リクエストがタイムアウトしました。後でもう一度お試しください',
  unknown: 'リクエストに失敗しました。後でもう一度お試しください',
  licenseNotFound: 'ライセンスが有効化されていません',
  licenseDecryptFailed: 'ライセンスの復号に失敗しました',
  licenseSignatureInvalid: 'ライセンスの署名が無効です',
  licensePublicKeyUnavailable: 'ライセンスの公開鍵を利用できません',
  licenseExpired: 'ライセンスの有効期限が切れています',
  licenseRemoteCheckFailed: 'ライセンスのリモート検証に失敗しました',
  licenseIoError: 'ライセンスファイルの読み取りに失敗しました',
  tokenExpired: 'ログイントークンの有効期限が切れました。再ログインしてください',
  networkError:
    'Microsoft認証サービスに接続できません。ネットワークを確認するか、オフラインモードで起動してください',
  mcApiError: 'Minecraft 公式 API へのリクエストに失敗しました',
  fsAuthRequired: 'ファイルシステムへのアクセスが許可されていません',
  pluginMissingDependency: 'プラグインに必要な前提依存がありません',
  connectorTimeout: 'マルチプレイ操作がタイムアウトしました。ネットワークを確認して再試行してください',
  exportDiagnosticsFailed: '診断レポートの出力に失敗しました',
  modpackParseFailed: 'Modパックの解析に失敗しました',
  skinUploadFailed: 'スキンのアップロードに失敗しました',
  skinSaveFailed: 'スキンの保存に失敗しました',
  skinResetFailed: 'スキンのリセットに失敗しました',
  pluginSignatureMissing: 'プラグインパッケージに署名がありません。開発者による再署名が必要です',
  pluginSignatureInvalid: 'プラグインパッケージの署名検証に失敗しました（改ざんの可能性）',
  pluginSignatureCertInvalid: 'プラグイン署名証明書が無効です（ルート鍵の検証失敗）',
  pluginSignatureHashMismatch: 'プラグインパッケージの署名ハッシュが一致しません（改ざんの可能性）',
  noRollbackSnapshot: 'ロールバック可能なバージョンスナップショットがありません',
} as const
