// インスタンス一覧（ja-JP）
export default {
  title: 'ゲームインスタンス',
  subtitle: '{count} 個のバージョン',
  type: {
    release: 'リリース版',
    snapshot: 'スナップショット',
    old_beta: '旧ベータ版',
    old_alpha: '旧アルファ版',
    april_fools: 'エイプリルフール版',
  },
  category: {
    all: 'すべて',
    release: 'リリース版',
    snapshot: 'スナップショット',
    april_fools: 'エイプリルフール版',
    old_beta: '旧ベータ版',
    old_alpha: '旧アルファ版',
  },
  sort: {
    recommended: 'おすすめ順',
    newest: '新しい順',
    oldest: '古い順',
    'name-asc': '名前 A-Z',
    'name-desc': '名前 Z-A',
  },
  loaderFilter: {
    all: 'すべて',
    modded: 'Mod',
    vanilla: 'バニラ',
    snapshot: 'スナップショット',
    april_fools: 'エイプリルフール',
    broken: 'エラー',
  },
  groups: 'カスタムグループ',
  manageGroups: 'グループを管理',
  groupNamePlaceholder: 'グループ名を入力...',
  noGroups: 'カスタムグループがありません',
  groupsHint: 'インスタンスは複数のカスタムグループに追加できます。クリックして切り替え',
  downloadTitle: '新しいバージョンをダウンロード',
  categoryLabel: 'カテゴリ',
  searchPlaceholder: 'バージョンを検索...',
  remoteCount: '計 {count} 個のリモートバージョン',
  filteredCount: 'フィルター後 {count} 個',
  noRemoteMatch: '一致するリモートバージョンがありません',
  noRemoteMatchHint: 'カテゴリ、並び順、検索キーワードを調整してみてください',
  releaseDate: '公開日 {date}',
  select: '選択',
  configTitle: 'ダウンロード設定',
  instanceName: 'インスタンス名',
  instanceNamePlaceholder: 'インスタンス名を入力...',
  gameVersion: 'ゲームバージョン',
  loader: 'Modローダー',
  loaderPlaceholder: 'ローダーを選択',
  noneVanilla: 'なし（純正バニラ）',
  versionPlaceholder: 'バージョンを選択',
  loadingVersions: '読み込み中...',
  noVersionData: 'バージョンデータがありません',
  latestRecommended: '最新版 {version} (推奨)',
  recommended: ' (推奨)',
  selectLoaderFirst: '先にローダーを選択してください',
  latestVersion: '最新版 {version}',
  addons: '追加コンテンツ',
  optional: '(任意)',
  fetchingAddons: '追加コンテンツを取得中...',
  onlyGameFiles: 'ゲームファイルのみをダウンロード。メモリや Java などの設定は作成後に調整できます',
  noLoaderAvailable: '利用可能なローダーバージョンがないためダウンロードできません',
  cancel: 'キャンセル',
  startDownload: 'ダウンロードを開始',
  repairName: '{name} を補完',
  pickGameDirTitle: 'ゲームディレクトリを選択',
  enterDirPath: 'ゲームディレクトリのパスを入力:',
  chooseDir: 'ディレクトリを選択',
  addDir: 'ディレクトリを追加',
  selectDirFirst: '先にゲームディレクトリを選択してからダウンロードを開始してください。',
  noLoaderVersions: '{loader} の利用可能なバージョン一覧を取得できませんでした。ネットワークを確認するか、後で再試行してください。',
  selectLoaderVersion: '{loader} の具体的なバージョンを選択してからダウンロードしてください。',
  createFailed: '作成に失敗しました: {error}',
  createInstanceFailed: 'インスタンスの作成に失敗しました: {error}',
  launchFailed: '起動に失敗しました: {error}',
  launchFailedDetail: '起動に失敗しました: {error}\n{detail}',
  refresh: '更新',
  dirManagerTitle: 'ディレクトリ管理',
  noDir: 'ディレクトリがありません',
  noDirHint: '下のボタンからゲームディレクトリを追加します',
  dirCount: '計 {count} 個のディレクトリ。チェックで現在使用中のディレクトリをマーク',
  openDir: 'ディレクトリを開く',
  remove: '削除',
  manualAdd: '手動で追加',
  browseAdd: '参照して追加',
  instanceSettings: 'インスタンス設定',
  basicInfo: '基本情報',
  repairFiles: 'ファイルを補完',
  versionName: 'バージョン名',
  gameDir: 'ゲームディレクトリ',
  notCreatedYet: 'このバージョンはまだランチャーで作成されていないため、ファイルを補完できません。',
  repairDesc: 'このインスタンスに不足している Minecraft ゲームファイル（libraries、assets、client.jar）をスキャンしてダウンロードします。',
  addedToDownload: 'ダウンロードタスクに追加しました',
  goToDownloadCenter: 'ダウンロードセンターで確認',
  repairCompleted: '補完が完了しました',
  repairFailed: '補完に失敗しました',
  retry: '再試行',
  startRepair: 'ファイルの補完を開始',
  selectGameDir: 'ゲームディレクトリを選択',
  savedDirs: '保存済みのディレクトリ',
  manage: '管理',
  noDirInManager: 'ディレクトリがありません。管理から追加できます',
  scanning: 'スキャン中...',
  import: 'インポート',
  openGameDir: 'ゲームディレクトリを開く',
  selectMcDir: 'Minecraft ゲームディレクトリを選択',
  selectMcDirHint: 'versions フォルダーを含む .minecraft ディレクトリを選択します',
  browseAndSelect: '参照して選択',
  noMatch: '一致するバージョンがありません',
  noVersionDetected: 'このディレクトリに Minecraft バージョンは検出されませんでした',
  needVersionsFolder: 'ディレクトリに versions/ フォルダーがあることを確認してください',
  available: '利用可能',
  unavailable: '利用不可',
  launch: '起動',
  settings: '設定',
  unpin: '固定を解除',
  pinToHome: 'ホームに固定',
  openFolder: 'フォルダーを開く',
} as const
