// インスタンス詳細（ja-JP）
export default {
  tabs: {
    overview: '概要',
    settings: '設定',
    gamesettings: 'ゲーム設定',
    saves: 'ワールド',
    screenshots: 'スクリーンショット',
    mods: 'Mod',
    resourcepacks: 'リソースパック',
    shaderpacks: 'シェーダーパック',
    datapacks: 'データパック',
    servers: 'サーバー',
    schematics: 'スケマティック',
  },
  confirm: {
    cancel: 'キャンセル',
    deleting: '削除中...',
    delete: '削除',
    confirm: '確定',
  },
  time: {
    minutes: '{count} 分',
    hours: '{count} 時間',
    hoursMinutes: '{hours} 時間 {minutes} 分',
    never: 'なし',
    justNow: 'たった今',
    minutesAgo: '{count} 分前',
    hoursAgo: '{count} 時間前',
  },
  openFolder: 'フォルダーを開く',
  loading: '読み込み中...',
  noMatch: '一致なし',
  empty: 'なし',
  deleteSelected: '{count} 件削除',
  batchDeleteTitle: '{type}を一括削除',
  batchDeleteConfirm: '選択した {count} 個の{type}を削除しますか？ゴミ箱に移動されます。',
  saves: {
    search: 'ワールドを検索...',
    noMatch: '一致するワールドがありません',
    empty: 'ワールドがありません',
    type: 'ワールド',
  },
  saveSettings: {
    title: 'ワールド設定',
    restoreFromOld: 'level.dat_old から復元',
    restoreFromOldConfirm: 'level.dat_old で現在の level.dat を上書きします（現在の内容は level.dat.qomicex.bak にバックアップされます）。復元しますか？',
    runningWarning: 'このインスタンスは実行中です。ゲームの保存時に変更が上書きされるため、先にゲームを終了してから編集することをおすすめします',
    sectionBasic: '基本情報',
    sectionWeather: '天候と時間',
    sectionSpawn: 'スポーン地点と村人',
    sectionBorder: 'ワールド境界',
    levelName: 'ワールド名',
    gameType: 'ゲームモード',
    gameTypeSurvival: 'サバイバル',
    gameTypeCreative: 'クリエイティブ',
    gameTypeAdventure: 'アドベンチャー',
    gameTypeSpectator: 'スペクテイター',
    difficulty: '難易度',
    difficultyPeaceful: 'ピースフル',
    difficultyEasy: 'イージー',
    difficultyNormal: 'ノーマル',
    difficultyHard: 'ハード',
    allowCommands: 'チートを許可',
    hardcore: 'ハードコア',
    difficultyLocked: '難易度をロック',
    time: '世界時間（Time）',
    dayTime: '昼夜時間（DayTime）',
    raining: '雨',
    thundering: '雷雨',
    clearWeatherTime: '晴れの残り時間',
    rainTime: '雨の残り時間',
    thunderTime: '雷雨の残り時間',
    spawnX: 'スポーン地点 X',
    spawnY: 'スポーン地点 Y',
    spawnZ: 'スポーン地点 Z',
    randomSeed: 'ワールドシード',
    wanderingTraderSpawnChance: '行商人の確率',
    wanderingTraderSpawnDelay: '行商人の遅延',
    borderCenterX: '境界中心 X',
    borderCenterZ: '境界中心 Z',
    borderSize: '境界の大きさ',
    borderSafeZone: '安全圏',
    borderDamagePerBlock: '境界外ダメージ/ブロック',
    borderWarningBlocks: '警告距離',
    borderWarningTime: '警告時間（秒）',
    gameRules: 'ゲームルール',
    ruleKeepInventory: '死亡時アイテムを保持（keepInventory）',
    ruleDoDaylightCycle: '昼夜サイクル（doDaylightCycle）',
    ruleDoFireTick: '延焼（doFireTick）',
    ruleMobGriefing: 'mobのブロック破壊（mobGriefing）',
    ruleDoMobSpawning: 'mobのスポーン（doMobSpawning）',
    ruleDoWeatherCycle: '天候サイクル（doWeatherCycle）',
    ruleDoMobLoot: 'mobのドロップ（doMobLoot）',
    ruleDoTileDrops: 'ブロックのドロップ（doTileDrops）',
    ruleDoEntityDrops: 'エンティティのドロップ（doEntityDrops）',
    ruleDoNaturalRegeneration: '自然回復（doNaturalRegeneration）',
    ruleDoImmediateRespawn: '即時リスポーン（doImmediateRespawn）',
    ruleDoInsomnia: 'ファントムのスポーン（doInsomnia）',
    ruleDoPatrolSpawning: '略奪者パトロール（doPatrolSpawning）',
    ruleDoTraderSpawning: '行商人のスポーン（doTraderSpawning）',
    ruleDrowningDamage: '溺れダメージ（drowningDamage）',
    ruleFallDamage: '落下ダメージ（fallDamage）',
    ruleFireDamage: '火ダメージ（fireDamage）',
    ruleFreezeDamage: '凍結ダメージ（freezeDamage）',
    ruleShowDeathMessages: '死亡メッセージ（showDeathMessages）',
    ruleAnnounceAdvancements: '進捗の告知（announceAdvancements）',
    ruleCommandBlockOutput: 'コマンドブロックの出力（commandBlockOutput）',
    ruleSendCommandFeedback: 'コマンドのフィードバック（sendCommandFeedback）',
    ruleReducedDebugInfo: 'デバッグ情報を簡略化（reducedDebugInfo）',
    ruleDisableElytraMovementCheck: 'エリトラの移動チェックを無効化（disableElytraMovementCheck）',
    ruleSpectatorsGenerateChunks: 'スペクテイターのチャンク生成（spectatorsGenerateChunks）',
    ruleDoLimitedCrafting: 'クラフトを制限（doLimitedCrafting）',
    ruleRandomTickSpeed: 'ランダムティックスピード',
    ruleSpawnRadius: 'スポーン半径',
    ruleMaxEntityCramming: 'エンティティの密集上限',
    save: '保存',
    saving: '保存中...',
    saved: 'ワールド設定を保存しました',
    loadFailed: 'ワールド設定の読み込みに失敗しました: {error}',
    saveFailed: 'ワールド設定の保存に失敗しました: {error}',
    restored: 'level.dat_old から復元しました',
    restoreFailed: '復元に失敗しました: {error}',
  },
  screenshots: {
    search: 'スクリーンショットを検索...',
    noMatch: '一致するスクリーンショットがありません',
    empty: 'スクリーンショットがありません',
    type: 'スクリーンショット',
  },
  resourcepacks: {
    search: 'リソースパックを検索...',
    noMatch: '一致するリソースパックがありません',
    empty: 'リソースパックがありません',
    type: 'リソースパック',
    install: 'リソースパックをインストール',
    loadFailed: 'リソースパックの読み込みに失敗しました: {error}',
  },
  shaderpacks: {
    search: 'シェーダーパックを検索...',
    noMatch: '一致するシェーダーパックがありません',
    empty: 'シェーダーパックがありません',
    type: 'シェーダーパック',
    install: 'シェーダーパックをインストール',
    loadFailed: 'シェーダーパックの読み込みに失敗しました: {error}',
  },
  datapacks: {
    search: 'データパックを検索...',
    noMatch: '一致するデータパックがありません',
    empty: 'データパックがありません',
    type: 'データパック',
    install: 'データパックをインストール',
  },
  schematics: {
    search: 'スケマティックを検索...',
    noMatch: '一致するスケマティックがありません',
    empty: 'スケマティックがありません（インポートするか schematics フォルダーに配置してください）',
    type: 'スケマティック',
    import: 'インポート',
    imported: '{name} をインポートしました',
    importFailed: 'インポートに失敗しました',
    deleteFailed: '削除に失敗しました',
    renamed: '{name} に名前を変更しました',
    renameFailed: '名前の変更に失敗しました',
    renameTitle: 'スケマティックの名前を変更',
    renamePlaceholder: '新しいファイル名',
    preview: 'プレビュー',
    rename: '名前を変更',
    delete: '削除',
    previewTitle: '{name} のプレビュー',
    parsing: 'スケマティックを解析中...',
    buildingPreview: '3D プレビューを構築中...',
    overCap: 'ブロック数が多すぎるため、素材リスト表示に切り替えました',
    overCapHint: 'ブロック数が多すぎて 3D 表示できません',
    largeSize: '大きいスケマティック（{count} ブロック）。描画に時間がかかる場合があります',
    totalBlocks: '{count} ブロック',
    byAuthor: '作者：{author}',
    materialsOnly: '素材リストのみ',
    missingBlocks: '{count} 個のブロックが素材なし（石で代替表示）',
    materials: '素材 ({count})',
    copy: '素材リストをコピー',
    minY: '最下層',
    maxY: '最上層',
    mouseSensitivity: 'マウス感度',
    moveSpeed: '移動速度',
    controlsHint: '左ドラッグ: パン · 中ドラッグ: 回転 · ホイール: ズーム · WASD: 移動',
  },
  mods: {
    management: 'Mod 管理',
    noModsHint: 'このインスタンスは Mod を使用できません。Forge、Fabric などのローダーが必要です',
    search: 'Mod を検索...',
    checkUpdates: '更新を確認',
    install: 'Mod をインストール',
    fetchingRemoteInfo: 'リモート情報を取得中（Modrinth/CurseForge の一致 id、アイコン、名前）...',
    readingMods: 'Mod 情報を読み取り中',
    loadFailed: 'Mod リストの読み込みに失敗しました：{error}',
    noMatch: '一致する Mod がありません',
    empty: 'Mod がありません',
    enable: '有効',
    disable: '無効',
    updateMods: 'Modを更新',
    filterAll: 'すべて',
    updatable: '更新可能',
    duplicate: '重複',
    sortNameAsc: '名前 A-Z',
    sortNameDesc: '名前 Z-A',
    sortTimeDesc: '新しい順',
    sortTimeAsc: '古い順',
    sortSizeDesc: '大きい順',
    sortSizeAsc: '小さい順',
    batchEnable: '一括有効',
    batchDisable: '一括無効',
    batchDelete: '一括削除',
    batchConfirm: '{action}{count} 個の Mod を操作しますか？',
    moveToRecycleBin: 'ゴミ箱に移動されます。',
    processing: '処理中...',
    checkingUpdates: 'Mod の更新を確認中…',
    foundUpdates: '{count} 個の Mod が更新可能です',
    addedToDownload: 'ダウンロードリストに {count} 個のタスクを追加しました',
    updatedCount: '{count} 個の Mod を更新しました',
    updateResult: '成功 {success} 個、失敗 {failed} 個{failures}',
    updateFailed: 'Mod の更新に失敗しました',
    loadFailedGeneric: '読み込みに失敗しました: {error}',
    unknownError: '不明なエラー',
  },
  servers: {
    search: 'サーバーを検索...',
    pingAll: 'すべてを測定',
    addServer: 'サーバーを追加',
    edit: '編集',
    ping: '測定',
    copyIp: 'IP をコピー',
    quickJoin: 'クイック参加',
    delete: '削除',
    online: 'オンライン',
    offline: 'オフライン',
    pinging: '測定中...',
    lanGames: 'LAN ゲーム ({count})',
    lanGame: 'LAN ゲーム',
    join: '参加',
    deleteConfirm: 'サーバー「{ip}」を削除しますか？',
    deleteTitle: 'サーバーを削除',
    addTitle: 'サーバーを追加',
    editTitle: 'サーバーを編集',
    name: 'サーバー名',
    address: 'サーバーアドレス',
    updating: '更新中...',
    adding: '追加中...',
    save: '保存',
    add: '追加',
    copiedIp: 'IP アドレスをコピーしました',
    copyFailed: 'コピーに失敗しました',
    pingDone: '測定完了: {ping}ms',
    addressOffline: '{address} はオフライン',
    pingFailed: '測定に失敗しました',
    deleted: 'サーバーを削除しました',
    deleteFailed: '削除に失敗しました',
    updated: '「{name}」を更新しました',
    added: '「{name}」を追加しました',
    opFailed: '操作に失敗しました',
    loadFailed: 'サーバーリストの読み込みに失敗しました',
  },
  overview: {
    launch: '起動',
    unpin: '固定を解除',
    pin: 'ホームに固定',
    gameVersion: 'ゲームバージョン',
    loader: 'ローダー',
    pureVanilla: '純正バニラ',
    lastPlayed: '最後のプレイ',
    totalPlayTime: '累計プレイ時間',
    modpackInfo: 'Modパック情報',
    modpackName: 'Modパック名',
    version: 'バージョン',
    author: '作者',
    summary: '概要',
    quickActions: 'クイック操作',
    defaultAccount: '既定アカウント',
    launchGame: 'ゲームを起動',
    instanceSettings: 'インスタンス設定',
    verifyIntegrity: 'リソースの整合性を確認',
    repairing: '{progress}% を補完中',
    openGameDir: 'ゲームディレクトリを開く',
    exportModpack: 'Modパックをエクスポート',
    deleteInstance: 'インスタンスを削除',
    refresh: '更新',
  },
  settingsTab: {
    instanceName: 'インスタンス名',
    instanceIcon: 'インスタンスアイコン',
    gameVersion: 'ゲームバージョン',
    javaRuntime: 'Java ランタイム',
    autoSelect: '自動選択',
    integrity: 'リソースの整合性',
    checkIntegrity: 'リソースの整合性を確認',
    repairing: '{progress}% を補完中',
    missingFiles: '{count} 個のファイルが不足',
    autoRepairing: '自動補完中...',
    integrityOk: 'リソースは整合しています',
    versionIsolation: 'バージョン分離',
    followGlobal: 'グローバル設定に従う',
    on: 'オン',
    off: 'オフ',
    isolationDesc: '各バージョンで独立した mods/config/saves ディレクトリを使用します',
    skipIntegrity: 'リソース整合性の確認をスキップ',
    skipIntegrityDesc: '起動時にファイル整合性の確認をスキップします。ファイル不足でゲームがクラッシュする場合があります',
    memoryAllocation: 'メモリ割り当て',
    auto: '自動',
    custom: 'カスタム',
    totalMem: '合計メモリ {size} GiB',
    usedMem: '使用中 {size} GiB',
    gameAlloc: 'ゲーム割り当て {size} GiB',
    remainingMem: '残り {size} GiB',
    jvmArgs: 'JVM 引数',
    linkedAccount: '関連アカウント',
    unlinked: '未関連',
    saving: '保存中...',
  },
  gamesettings: {
    search: '設定項目を検索...',
    noMatch: '一致する設定項目がありません',
    empty: 'ゲーム設定がありません',
    pressKey: 'キーを押してください...',
    add: '追加',
    addPlaceholder: '名前を入力…',
    remove: '削除',
    keys: {
      unbound: '未割り当て',
      space: 'スペース',
      enter: 'Enter',
      backspace: 'Backspace',
      leftShift: '左 Shift',
      rightShift: '右 Shift',
      leftControl: '左 Ctrl',
      rightControl: '右 Ctrl',
      leftAlt: '左 Alt',
      rightAlt: '右 Alt',
      leftSuper: '左 Win',
      rightSuper: '右 Win',
      menu: 'メニューキー',
      mouseLeft: 'マウス左ボタン',
      mouseRight: 'マウス右ボタン',
      mouseMiddle: 'マウス中ボタン',
      mouseButton: 'マウスボタン {n}',
      keypad: 'テンキー {n}',
      keypadAdd: 'テンキー +',
      keypadSubtract: 'テンキー -',
      keypadMultiply: 'テンキー *',
      keypadDivide: 'テンキー /',
      keypadDecimal: 'テンキー .',
      keypadEnter: 'テンキー Enter',
    },
  },
  launch: {
    launchFailed: '起動に失敗しました',
    instanceRunningConfirm: '現在このインスタンスは実行中です。新しいインスタンスを起動しますか？',
    instanceRunningTitle: 'インスタンス実行中',
    backToList: 'インスタンス一覧に戻る',
    instanceNotFound: 'インスタンスが存在しません',
    loadingInstance: 'インスタンスを読み込み中...',
    deleteInstanceConfirm: 'インスタンス「{name}」を削除しますか？バージョンフォルダーは完全に削除されます。',
  },
} as const
