// プラグイン（ja-JP）
export default {
  notFound: 'プラグインが見つかりません',
  notActivated: 'プラグインが有効になっていません',
  webviewPlaceholder: 'このプラグインは別ウィンドウで開かれています',
  webviewFocus: 'ウィンドウにフォーカス',
  installTitle: 'プラグインをインストール',
  permissionsRequest: 'このプラグインは以下の権限を要求します:',
  highRisk: '高リスク権限',
  caution: '注意が必要',
  normal: '通常',
  cancel: 'キャンセル',
  confirmInstall: 'インストールを確認',
  fileAuthRequest: 'プラグイン「{pluginId}」がパスへのアクセスを要求しています：\n{path}\n\n許可しますか？',
  fileAuthDenied: 'ユーザーがファイルアクセス権限を拒否しました',
  fileAuthFailed: '認可に失敗しました',
  permission: {
    instanceRead: 'インスタンスリストを読み取り',
    instanceWrite: 'インスタンスを作成/変更/削除',
    accountRead: 'アカウントリストを読み取り',
    licenseRead: 'ライセンス情報を読み取り',
    configRead: 'ランチャー設定を読み取り',
    configWrite: 'ランチャー設定を変更',
    cacheAccess: 'プラグインキャッシュを読み書き',
    endpointDiscover: 'バックエンド API エンドポイントを取得',
    pageList: 'ページリストを取得',
    networkFetch: 'HTTP リクエストを送信',
    networkCorsProxy: 'CORS プロキシリクエスト',
    networkWebsocket: 'WebSocket 接続',
    networkProxy: 'プロキシ設定を変更',
    uiInjectSidebar: 'サイドバーメニューを追加',
    uiInjectSettings: '設定ページを追加',
    uiPictureInPicture: 'ピクチャーインピクチャーウィンドウ',
    uiSubWindow: '独立したサブウィンドウ',
    uiContextMenu: '右クリックメニューを追加',
    uiToast: 'アプリ内通知',
    uiNavigate: 'ページ遷移',
    systemInfo: 'システムとランチャー情報を読み取り',
    systemNotification: 'システム通知を送信',
    clipboardRead: 'クリップボードを読み取り',
    clipboardWrite: 'クリップボードに書き込み',
    wasmExecute: 'WASM モジュールを実行',
    pluginInstall: 'プラグインをインストール/アンインストール/更新',
    pluginList: 'インストール済みプラグインリストを読み取り',
    resourceRead: 'ゲームリソースファイルを読み取り',
    resourceWrite: 'ゲームリソースファイルに書き込み',
    javaManage: 'Java ランタイムを管理',
    downloadManage: 'ダウンロードタスクを管理',
    gameProcess: 'ゲームプロセスを開始/停止',
    gameLog: 'ゲームログを検出',
    connectorHost: 'マルチプレイを開始/停止',
    connectorScan: 'LAN マルチプレイをスキャン',
    shellExecute: 'システムコマンドを実行',
    filesystemRead: 'ファイルシステムを読み取り',
    filesystemWrite: 'ファイルシステムに書き込み',
  },
} as const
