// リソースセンター（ja-JP）
export default {
  sources: {
    all: 'すべて',
  },
  categories: {
    mod: 'Mod',
    modpack: 'Modパック',
    shader: 'シェーダー',
    resourcepack: 'リソースパック',
    datapack: 'データパック',
    save: 'ワールド',
  },
  sort: {
    relevance: '関連度',
    downloads: 'ダウンロード数',
    updated: '更新日時',
    newest: '新しい順',
    name: '名前',
    recommended: 'おすすめ',
    installs: 'インストール数',
  },
  unknownAuthor: '作者不明',
  install: 'インストール',
  viewDetail: '詳細を見る',
  originalSite: 'オリジナルサイト',
  searchFailed: '検索に失敗しました',
  backendUnreachable: 'バックエンドサービスに接続できません。バックエンドが起動していることを確認してください',
  title: 'リソースセンター',
  sourceLabel: 'リソースソース',
  categoryLabel: 'リソースカテゴリ',
  searchPlaceholder: '{category}を検索...',
  search: '検索',
  gameVersionLabel: 'ゲームバージョン',
  allVersions: 'すべてのバージョン',
  loaderLabel: 'ローダー',
  allLoaders: 'すべてのローダー',
  categoryFilterLabel: 'カテゴリフィルター',
  clearFilter: 'フィルターをクリア',
  expandTags: 'すべて表示',
  collapseTags: '折りたたむ',
  notFound: '該当するリソースが見つかりません',
  notFoundHint: 'キーワード、リソースソース、カテゴリを変更してみてください',
  retry: '再試行',
  loading: '読み込み中...',
  loadMore: 'さらに読み込み（{current}/{total}）',
  allShown: 'すべての {count} 件の結果を表示しました',
  mode: {
    label: '閲覧モード',
    browse: 'リソース',
    searchPlaceholder: 'リソース、キーワードを検索...',
  },
  favorites: {
    viewSearch: '検索',
    viewLabel: 'お気に入り',
    viewLabelWithCount: 'お気に入り（{count}）',
    searchPlaceholder: 'お気に入りを検索...',
    add: 'お気に入りに追加',
    remove: 'お気に入りから削除',
    added: 'お気に入りに追加しました',
    removed: 'お気に入りから削除しました',
    failed: 'お気に入りの操作に失敗しました',
    loadFailed: 'お気に入りの読み込みに失敗しました',
    emptyTitle: 'お気に入りはまだありません',
    emptyHint: '検索結果またはリソース詳細ページで ♥ をクリックすると追加できます',
    filteredEmpty: '現在の絞り込み条件に一致するお気に入りはありません',
    filteredEmptyHint:
      '上部のリソースソース / カテゴリ、または左側のフォルダとタグの絞り込みを切り替えてください',
    allShown: 'お気に入り {count} 件',
    folders: {
      railTitle: 'フォルダ',
      all: 'すべて',
      unfiled: '未分類',
      loading: '読み込み中...',
      create: '新しいフォルダ',
      createPlaceholder: 'フォルダ名',
      rename: '名前を変更',
      renamePlaceholder: 'フォルダ名',
      emptyName: 'フォルダ名を入力してください',
      created: 'フォルダ「{name}」を作成しました',
      renamed: 'フォルダ名を変更しました',
      failed: 'フォルダの操作に失敗しました',
      delete: '削除',
      deleteTitle: 'フォルダを削除',
      deleteBodyWithItems:
        '「{name}」とその中の {count} 件のお気に入りが削除されます。この操作は元に戻せません。',
      deleteBodyEmpty: '「{name}」にお気に入りはありません。削除すると元に戻せません。',
      deleted: 'フォルダを削除しました（お気に入り {count} 件を含む）',
    },
    note: {
      label: 'メモ',
      placeholder: '用途やバージョン要件などを記録',
    },
    tags: {
      label: 'タグ',
      filterLabel: 'タグで絞り込み',
      placeholder: 'タグを入力して Enter',
      remove: 'タグ「{tag}」を削除',
      hint: 'Enter またはカンマで追加、最大 {max} 個',
      limitReached: '上限の {max} 個に達しました',
    },
    edit: {
      open: 'お気に入りを編集',
      title: 'お気に入りを編集',
      folderLabel: 'フォルダ',
      none: '未分類',
      cancel: 'キャンセル',
      save: '保存',
      saving: '保存中...',
      saved: '保存しました',
      failed: '保存に失敗しました',
    },
  },
} as const
