// リソース詳細（ja-JP）
export default {
  prereqMods: '前提Mod',
  basedOn: '{version} に基づいて解析',
  parsingPrereq: '前提Modを解析中...',
  noPrereq: 'このバージョンには前提Modがありません',
  addedToDownload: 'ダウンロードリストに追加しました',
  downloadFailed: 'ダウンロードに失敗しました',
  exportFailed: 'エクスポートに失敗しました',
  loadDetailFailed: 'リソース詳細の読み込みに失敗しました',
  loadVersionsTimeout: 'バージョン一覧の読み込みがタイムアウトしました',
  loadVersionsFailed: 'バージョン一覧の読み込みに失敗しました',
  title: 'リソース詳細',
  refresh: '更新',
  originalPage: 'オリジナルページ',
  loadFailed: '読み込みに失敗しました',
  notFound: 'リソースが存在しません',
  latest: '最新 {version}',
  noDescription: '概要がありません',
  translating: '翻訳中...',
  collapseTranslation: '翻訳をたたむ',
  translateDescription: '概要を翻訳',
  translatedMark: '訳',
  unknownAuthor: '作者不明',
  categoryTags: 'カテゴリタグ',
  detailedIntro: '詳細な紹介',
  showOriginal: '原文を表示',
  translateBody: '詳細を翻訳',
  expand: '展開',
  collapse: 'たたむ',
  noMoreContent: 'これ以上の紹介はありません',
  selectVersionInstall: 'バージョンを選択してインストール',
  gameVersion: 'ゲームバージョン',
  allVersions: 'すべてのバージョン',
  loader: 'ローダー',
  allLoaders: 'すべてのローダー',
  fetchingVersions: 'バージョン一覧を取得中',
  versionCount: '合計 {count} 個のバージョン',
  filteredCount: 'フィルター後 {count} 個',
  noVersionUnderFilter: '現在のフィルター条件では利用可能なバージョンがありません',
  install: 'インストール',
  saveAs: '名前を付けて保存',
  loading: '読み込み中...',
  getDownload: 'ダウンロードを取得',
  noDownload: 'ダウンロードがありません',
  loadMore: 'さらに読み込み ({count} 個)',
} as const
