// リソースセンター（ja-JP）
export default {
  sources: {
    all: 'すべて',
  },
  categories: {
    mod: 'Mod',
    modpack: 'Modパック',
    shader: 'シェーダー',
    resourcepack: 'リソースパック',
    datapack: 'データパック',
    save: 'ワールド',
  },
  sort: {
    relevance: '関連度',
    downloads: 'ダウンロード数',
    updated: '更新日時',
    newest: '新しい順',
    name: '名前',
    recommended: 'おすすめ',
    installs: 'インストール数',
  },
  unknownAuthor: '作者不明',
  install: 'インストール',
  viewDetail: '詳細を見る',
  originalSite: 'オリジナルサイト',
  searchFailed: '検索に失敗しました',
  backendUnreachable: 'バックエンドサービスに接続できません。バックエンドが起動していることを確認してください',
  title: 'リソースセンター',
  sourceLabel: 'リソースソース',
  categoryLabel: 'リソースカテゴリ',
  searchPlaceholder: '{category}を検索...',
  search: '検索',
  gameVersionLabel: 'ゲームバージョン',
  allVersions: 'すべてのバージョン',
  loaderLabel: 'ローダー',
  allLoaders: 'すべてのローダー',
  categoryFilterLabel: 'カテゴリフィルター',
  clearFilter: 'フィルターをクリア',
  expandTags: 'すべて表示',
  collapseTags: '折りたたむ',
  notFound: '該当するリソースが見つかりません',
  notFoundHint: 'キーワード、リソースソース、カテゴリを変更してみてください',
  retry: '再試行',
  loading: '読み込み中...',
  loadMore: 'さらに読み込み（{current}/{total}）',
  allShown: 'すべての {count} 件の結果を表示しました',
  favorites: {
    viewSearch: '検索',
    viewLabel: 'お気に入り',
    viewLabelWithCount: 'お気に入り（{count}）',
    filterHint: 'お気に入りは上部の「ソース / カテゴリ」で絞り込まれます',
    add: 'お気に入りに追加',
    remove: 'お気に入りから削除',
    added: 'お気に入りに追加しました',
    removed: 'お気に入りから削除しました',
    failed: 'お気に入りの操作に失敗しました',
    loadFailed: 'お気に入りの読み込みに失敗しました',
    emptyTitle: 'お気に入りはまだありません',
    emptyHint: '検索結果またはリソース詳細ページで ♥ をクリックすると追加できます',
    filteredEmpty: 'このソース / カテゴリにお気に入りはありません',
    filteredEmptyHint: '上部のソースまたはカテゴリを切り替えてください',
    allShown: 'お気に入り {count} 件',
  },
} as const
