// リソースセンター（ja-JP）
export default {
  categories: {
    mod: 'Mod',
    modpack: 'Modパック',
    shader: 'シェーダー',
    resourcepack: 'リソースパック',
    datapack: 'データパック',
    save: 'ワールド',
  },
  sources: {
    all: 'すべて',
  },
  sort: {
    relevance: '関連度',
    downloads: 'ダウンロード数',
    updated: '更新日時',
    newest: '新しい順',
    name: '名前',
    recommended: 'おすすめ',
    installs: 'インストール数',
  },
  unknownAuthor: '作者不明',
  install: 'インストール',
  viewDetail: '詳細を見る',
  originalSite: 'オリジナルサイト',
  searchFailed: '検索に失敗しました',
  backendUnreachable: 'バックエンドサービスに接続できません。バックエンドが起動していることを確認してください',
  title: 'リソースセンター',
  sourceLabel: 'リソースソース',
  categoryLabel: 'リソースカテゴリ',
  searchPlaceholder: '{category}を検索...',
  search: '検索',
  gameVersionLabel: 'ゲームバージョン',
  allVersions: 'すべてのバージョン',
  loaderLabel: 'ローダー',
  allLoaders: 'すべてのローダー',
  notFound: '該当するリソースが見つかりません',
  notFoundHint: 'キーワード、リソースソース、カテゴリを変更してみてください',
  retry: '再試行',
  loading: '読み込み中...',
  loadMore: 'さらに読み込み（{current}/{total}）',
  allShown: 'すべての {count} 件の結果を表示しました',
} as const
