// 実行／起動フロー（ja-JP）
export default {
  gameCrashed: 'ゲームがクラッシュしました',
  gameCrashTitle: 'ゲームクラッシュ',
  launchFailedTitle: '起動に失敗しました',
  gameExitedAbnormally: 'ゲームが異常終了しました (コード: {code})',
  launchError: '起動中にエラーが発生しました',
  analysisUnavailable: '解析サービスは現在利用できません',
  gameExited: 'ゲームを終了しました',
  gameStarted: 'ゲームを開始しました',
  preparingLaunch: '起動準備中...',
  javaIncompatibleTitle: 'Java バージョンが互換性がありません',
  javaIncompatible: '選択中の Java {current} は Minecraft {game} の要件（Java {required} が必要）を満たしていません。起動を続行しますか？',
  launchCancelled: '起動をキャンセルしました',
  gameStopped: 'ゲームを停止しました',
  timeSeconds: '{count}秒',
  timeMinutes: '{count}分{sec}秒',
  timeHours: '{hours}時間{mins}分',
  instancesRunning: '{count} 個のインスタンスが実行中',
  noRunningGame: '実行中のゲームはありません',
  goToInstances: 'インスタンス管理へ',
  title: '実行中のゲーム',
  runningFor: '実行時間 {time}',
} as const
