// 設定ページ（ja-JP；バッチ0 に category ナビ + appearance 外観の中核項目、その他は移行バッチで補充）
export default {
  category: {
    launcher: 'ランチャー',
    basic: '基本設定',
    launch: '起動設定',
    download: 'ダウンロード',
    storage: 'ストレージとキャッシュ',
    java: 'Java ランタイム',
    plugins: 'プラグイン',
    appearance: '外観',
    toolbox: 'ツールボックス',
    logs: 'ログ',
    about: 'バージョン情報',
    debug: 'デバッグ',
  },
  saved: '設定を保存しました',
  appearance: {
    title: '外観',
    language: '表示言語',
    followSystem: 'システムに合わせる',
    theme: 'テーマ',
    dark: 'ダーク',
    light: 'ライト',
    animations: 'ページアニメーション',
    animationsDesc: '有効にすると、ページ遷移やダイアログなどにトランジションアニメーションが付きます',
    animationSpeed: 'アニメーション速度',
    slow: '遅い',
    normal: '標準',
    fast: '速い',
    maxFrameRate: '最大フレームレート',
    maxFrameRateUnlimited: '無制限',
    maxFrameRateDesc: 'ランチャー画面の描画フレームレートを制限し、リソース消費を抑えます。無制限に設定するとディスプレイの本来のリフレッシュレートを使用します。',
    cornerRadius: '角丸',
    windowCorners: 'ウィンドウの角丸',
    windowCornersDesc: 'システムフレームを使用しない場合にのみ有効です',
    cornerSharp: '直角',
    cornerDefault: '標準（8px）',
    cornerLarge: '大きな角丸',
    font: 'フォント',
    fontFamily: 'UIフォント',
    fontDefault: '既定フォント',
    fontDesc: 'システムにインストール済みのフォントを選択します。UI全体にすぐ適用されます',
    fontPreviewTitle: 'フォントプレビュー',
    fontPreviewText: 'Qomicex ランチャー — 日本語サンプル 123 ABC',
    fontReset: '既定フォントに戻す',
    background: '背景',
    backgroundImage: '背景画像',
    noBackgrounds: '背景画像がありません',
    openFolder: 'フォルダーを開く',
    backgroundsHint: '画像を置くと上のリストに表示されます',
    backgroundRandom: '起動のたびにランダムに選択',
    backgroundRandomDesc: '背景フォルダーからランダムに1枚選択します',
    clearBackground: '背景をクリア',
    opacity: '不透明度',
    transparent: '透明',
    opaque: '不透明',
    blur: 'ぼかし',
    sharp: 'くっきり',
    watermark: 'ウォーターマーク',
    watermarkEnabled: 'ホーム画面にウォーターマーク文字を表示',
    watermarkEnabledDesc: 'ホーム画面の中央にカスタム可能な文字を表示します',
    watermarkText: 'ウォーターマークの内容',
    watermarkSubtext: 'サブタイトル',
    watermarkSubtextPlaceholder: 'ランチャー',
  },
  launcher: {
    title: 'ランチャー設定',
    dataDir: 'データディレクトリ',
    dataDirDesc: 'ランチャーのデータ保存場所。変更後はランチャーの再起動で反映されます',
    dataDirChanged: 'データディレクトリを変更しました。ランチャー再起動後に反映されます',
    saveFailed: '設定に失敗しました',
    downloadThreads: 'ダウンロードスレッド数',
    downloadThreadsDesc: '同時にダウンロードするファイル数（1-512）。数値が大きいほど速くなりますが、帯域を多く消費します',
    fileChunkThreads: '分割スレッド数',
    fileChunkThreadsDesc: '単一ファイルの並行分割数：オフ=分割せず直接、自動=エンジン既定、または手動 1-16',
    fileChunkThreadsOff: 'オフ',
    fileChunkThreadsAuto: '自動',
    versionIsolation: 'バージョン分離',
    versionIsolationDesc: '各バージョンで独立した mods/config/saves ディレクトリを使用します。有効のままを推奨します',
    closeAfterLaunch: 'ゲーム起動後にランチャーを閉じる',
    closeAfterLaunchDesc: 'ゲーム起動後にこのランチャーを自動的に閉じます',
    autoReportErrors: '重大なエラーログを自動的に報告',
    autoReportErrorsDesc: 'ランチャーがクラッシュするなどの重大なエラー時に、エラーログとデバイス情報（システム/ハードウェア）を自動アップロードして問題の特定に役立てます。通常の起動失敗やダウンロード/インストールエラーは報告されません',
    downloadSource: 'ダウンロードソース',
    downloadSourceName: { 0: '公式ソース', 1: 'BMCLAPI ミラー' },
    modSource: 'リソースダウンロードソース',
    modSourceName: { 0: 'Modrinth/CurseForge 公式', 1: 'MCIM ミラー' },
    refreshLatency: '遅延を更新',
    autoSelectDownloadSource: '最速のダウンロードソースを自動選択',
    autoSelectDownloadSourceDesc: '起動時およびインストール前に、最も遅延の低いダウンロードソースを自動検出して選択します',
    autoSelectModSource: '最速のリソースダウンロードソースを自動選択',
    autoSelectModSourceDesc: 'Modrinth/CurseForge API ミラーを自動検出し、最も遅延の低いものを選択します',
    translationProvider: '翻訳サービス',
    translationDefault: 'MyMemory (既定)',
    translationGoogle: 'Google Translate (VPN が必要)',
    translationProviderDesc: 'リソースの詳細・概要の翻訳に使用する翻訳サービスを選択します',
    bingApiKeyPlaceholder: 'Azure Translator API Key を入力',
    bingApiKeyDesc: 'Azure Portal で Translator リソースを作成して Key を取得してください。リージョンは global に設定する必要があります',
    downloadTimeout: 'ダウンロードタイムアウト (秒)',
    downloadTimeoutDesc: '単一ファイルのダウンロードがこの時間応答しない場合は自動的に再試行します（0=タイムアウトなし、1-120 秒）',
    enableHttp3: 'HTTP/3 ファイルダウンロードを有効化（実験的）',
    enableHttp3Desc: '有効にするとダウンロードは HTTP/3 を優先し、サーバーが対応していない場合は HTTP/2 へ自動的にフォールバックします。無効では HTTP/2 のみを使用します',
    logLevelLabel: 'ログレベル',
    logLevel: { error: 'エラー', warn: '警告', info: '情報', debug: 'デバッグ', trace: 'トレース' },
    logLevelDesc: 'コンソールとログファイルの出力詳細度を制御します。情報レベルが既定です',
    storageCache: 'ストレージとキャッシュ',
    versionListCache: 'バージョン一覧キャッシュ',
    versionListCacheDesc: 'Forge バージョン一覧の HTML キャッシュファイルをクリアします',
    clearCache: 'キャッシュをクリア',
    curseforgeConcurrency: 'CurseForge バージョン一覧の並列数',
    curseforgeConcurrencyDesc: '同時に取得するページ数（1-20）。数値が大きいほどバージョン一覧の読み込みが速くなります',
    curseforgeTtl: 'CurseForge バージョン一覧キャッシュの有効期間（秒）',
    curseforgeTtlDesc: '0 = 永続キャッシュ（再起動または手動クリアまで）、既定 300 秒（5 分）',
    curseforgeCache: 'CurseForge バージョンキャッシュ',
    curseforgeCacheDesc: 'CurseForge バージョン一覧のメモリキャッシュをクリアします',
    clearCurseforgeCache: 'CurseForge バージョンキャッシュをクリア',
    cacheCleared: 'キャッシュをクリアしました。{count} 個のファイルを削除しました',
    cacheClearFailed: 'キャッシュのクリアに失敗しました',
    curseforgeCacheCleared: 'CurseForge バージョンキャッシュをクリアしました',
    curseforgeCacheClearFailed: 'CurseForge キャッシュのクリアに失敗しました',
  },
  java: {
    title: 'Java ランタイム',
    ready: '準備完了',
    detected: '検出済み',
    available: '利用可能',
    quickScan: 'クイックスキャン',
    deepScan: 'ディープスキャン',
    manualAdd: '手動で追加',
    downloadJava: 'Java をダウンロード',
    refreshList: 'リストを更新',
    scanningQuick: 'クイックスキャン中...',
    scanningDeep: 'ディープスキャン中...',
    scanDoneFound: 'スキャンが完了し、{count} 個の新しいバージョンが見つかりました',
    scanDoneNone: 'スキャンが完了しました。新しいバージョンはありません',
    scanFailed: 'スキャンに失敗しました',
    refreshing: '更新中...',
    scanningRuntime: 'Java ランタイムをスキャン中...',
    noRuntimeDetected: 'Java ランタイムがまだ検出されていません',
    noRuntimeHint: '「クイックスキャン」でシステム内の Java を自動検出するか、手動で追加します',
    startScan: 'スキャンを開始',
    usable: '利用可能',
    unusable: '利用不可',
    openFolder: 'フォルダーを開く',
    availableCount: '{valid} / {total} 利用可能',
    defaultConfig: '既定の設定',
    defaultRuntime: '既定の Java ランタイム',
    autoSelect: '自動選択',
    defaultRuntimeDesc: '自動選択を推奨します。ランチャーが各ゲームバージョンに最適な Java ランタイムを自動的にマッチングします',
    memoryAllocation: 'メモリ割り当て',
    memoryAuto: '自動',
    memoryCustom: 'カスタム',
    totalMemory: '合計メモリ {value} GiB',
    usedMemory: '使用中 {value} GiB',
    gameMemory: 'ゲーム割り当て {value} GiB',
    remainingMemory: '残り {value} GiB',
    jvmArgs: '追加の JVM 引数',
    jvmArgsDesc: 'Minecraft 起動時に付加する JVM 引数',
    pickJavaExecutable: 'Java 実行ファイルを選択',
    unrecognizedPath: 'このパスの Java ランタイムを認識できません',
    added: '{name} {version} を追加しました',
    loadCatalogFailed: 'Java ダウンロードカタログの読み込みに失敗しました',
    addedToDownload: 'ダウンロードセンターに追加しました: {name}',
    downloadFailed: 'Java ダウンロードの開始に失敗しました',
    deleteConfirm: '「{name}」を削除しますか？',
    deleteTitle: 'Java を削除',
    deleted: '{name} を削除しました',
    deleteFailed: '削除に失敗しました',
    manualAddTitle: '手動で Java を追加',
    executablePath: 'Java 実行ファイルのパス',
    browse: '参照',
    executablePathDesc: 'Java 実行ファイルの完全なパスを選択または入力します',
    verifying: '検証中...',
    add: '追加',
    distribution: 'ディストリビューション',
    recommended: '(推奨)',
    mainVersion: 'Java メジャーバージョン',
    platform: 'プラットフォーム',
    architecture: 'アーキテクチャ',
    targetDir: '対象ディレクトリ',
    resolving: '解決中...',
    startDownload: 'ダウンロードを開始',
  },
  plugins: {
    title: 'プラグイン管理',
    installedCount: '{count} 個インストール済み',
    searchPlaceholder: 'プラグインを検索...',
    installing: 'インストール中...',
    install: 'プラグインをインストール',
    noneInstalled: 'プラグインはまだインストールされていません',
    noMatch: '一致するプラグインがありません',
    changesApplied: '変更を適用しました',
    saveFailed: '保存に失敗しました',
    uninstallConfirm: 'このプラグインをアンインストールしますか？',
    uninstalled: 'プラグインをアンインストールしました',
    uninstallFailed: 'アンインストールに失敗しました',
    installSuccess: 'プラグインをインストールしました',
    installFailed: 'インストールに失敗しました: {message}',
    permissions: '権限 ({count})',
    contributes: '拡張ポイント',
  },
  about: {
    aboutApp: '{name} について',
    beta: 'ベータ版',
    stable: '安定版',
    feedback: 'フィードバック',
    viewRepository: 'リポジトリを表示',
    versionInfo: 'バージョン情報',
    appVersion: 'アプリバージョン',
    versionHash: 'バージョンハッシュ',
    os: 'オペレーティングシステム',
    architecture: 'システムアーキテクチャ',
    memory: 'メモリ',
    license: 'ライセンス',
    licenseActivated: '有効',
    licenseNotActivated: '未アクティブ',
    licenseInvalid: '無効',
    channel: 'チャンネル',
    expiry: '有効期限',
    permanent: '永続有効',
    machineCode: 'マシンコード',
    changeLicense: 'ライセンスを変更',
    activateLicense: 'ライセンスを有効化',
    copyMachineCode: 'マシンコードをコピー',
    update: '更新',
    checking: '確認中...',
    checkUpdate: '更新を確認',
    upToDate: '最新バージョンです',
    checkUpdateFailed: '更新の確認に失敗しました',
    developers: '開発者',
    acknowledgements: '謝辞',
    referenceProjects: '参考プロジェクト',
    backendDependencies: 'バックエンド依存',
    frontendDependencies: 'フロントエンド依存',
    openSourceLicense: 'オープンソースライセンス',
    licenseNotice: '本プログラムは {name} オープンソースライセンスで公開されています',
    viewLicense: 'ライセンスを表示',
    copyrightPrivacy: '著作権とプライバシー',
    copyrightStatement: '著作権表示',
    copyrightStatementDesc: '本ソフトウェアの著作権帰属とオープンソースライセンス情報を表示します',
    userAgreement: '利用規約',
    privacyPolicy: 'プライバシーポリシー',
    appDescription: 'モダンな Minecraft ランチャー。マルチバージョン管理、modローダー互換、アカウント管理などをサポートします。',
    roleProjectLead: 'プロジェクト発起人 / 主要開発者',
    serviceModrinth: 'Mod とリソース検索 API',
    serviceModpack: 'Modパック API',
    serviceBmclapi: 'BMCLAPI ダウンロードミラーサービスを提供',
    serviceMcmod: '中国語 Mod データベース',
    serviceMinecraft: 'Minecraft 公式サイト、正規版をサポート！',
    serviceMinecraftName: 'Minecraft 公式サイト',
    refVersionCheck: 'バージョン検出の参考',
    refModloaderInstaller: 'ModLoader インストーラーの参考',
    refLaunchFlow: '起動フローの参考',
    depBackendRuntime: 'Rust バックエンドランタイム',
    depCoreLibraries: 'コアライブラリ',
    depCoreFramework: 'コアフレームワーク',
    depUiComponents: 'UI コンポーネント',
    depStylesTools: 'スタイルとツール',
    depAnimation: 'アニメーション',
    depRendering: 'レンダリングと表示',
    depInHouse: '自社開発',
  },
} as const
