// その他ツール／デバッグ／ログ／スプラッシュ（ja-JP）
export default {
  toolbox: {
    title: 'カスタムファイルダウンロード',
    description: '指定されたフォルダーに任意のファイルをダウンロードする',
    urlLabel: 'ダウンロード先 (URL)',
    savePathLabel: '保存パス',
    autoFillPlaceholder: 'フォルダーを選択すると自動入力されます',
    pickFolder: 'フォルダーを選択',
    submitting: '送信中...',
    startDownload: 'ダウンロードを開始',
    downloadFailed: 'ダウンロードに失敗しました',
  },
  logs: {
    title: 'ログ管理',
    loadFailed: 'ログ一覧の読み込みに失敗しました',
    exportedTo: '{dest} にエクスポートしました',
    downloadStarted: 'ダウンロードを開始しました',
    deleteConfirm: '「{name}」を削除しますか？',
    deleteTitle: 'ログを削除',
    deleted: '削除しました',
    deleteFailed: '削除に失敗しました',
    openDirFailed: 'ディレクトリを開けません',
    openFailed: 'ファイルを開けません',
    exportAll: 'すべてエクスポート',
    exportGz: 'エクスポート (.gz)',
    filesLabel: 'ログファイル',
    currentSession: '現在のセッション',
    none: 'ログがありません',
    emptyDescription: 'ランチャーとバックエンドの実行中にログファイルが生成されます',
    open: '開く',
    openContainingDir: '所在ディレクトリを開く',
    retentionHint: '直近のログを自動的に10件保持し、超過分は最も古いものから自動クリアされます',
    currentSessionSuffix: '{count} 件の現在のセッション',
    fileCountSuffix: '{count} 個のファイル',
    truncated: '切り詰めました（末尾 2MB のみ）',
    searchPlaceholder: 'ログを検索...',
    levelAll: 'すべてのレベル',
    levelError: 'エラー',
    levelWarn: '警告',
    levelInfo: '情報',
    noMatch: '一致するログ行がありません',
    debugLogsCount: 'デバッグログ ({count})',
  },
  debug: {
    liveLogs: 'リアルタイムログ',
    autoScroll: '自動スクロール',
    clear: 'クリア',
    exportLogs: 'ログをエクスポート',
    triggerDump: 'Dump を実行',
    noLogs: 'ログはまだありません...',
    diagnostics: 'ランチャー診断',
    systemInfo: 'システム情報',
    versionInfo: 'バージョン情報',
    connectivity: '接続状態',
    apiHealthCheck: 'API ヘルスチェック',
    pathInfo: 'パス情報',
    toggleDisableAnimations: 'アニメーションを無効化',
    toggleShowComponentBoundaries: 'コンポーネント境界を表示',
    toggleSimulateApiErrors: 'API エラーをシミュレート',
    toggleNetworkLogging: 'ネットワークリクエストログ',
    toggleDisableCaching: 'キャッシュを無効化',
    toggleLogOverlay: 'ログオーバーレイ（グローバル）',
    toggleShowFps: 'FPS 表示（右上）',
    togglesTitle: 'デバッグスイッチ（一時的、再起動でリセット）',
    clearTasksConfirm: 'すべてのダウンロードタスク一覧をクリアしますか？この操作は元に戻せません。',
    clearTasksTitle: 'ダウンロードタスクをクリア',
    tasksCleared: 'ダウンロードタスク一覧をクリアしました',
    dataManagement: 'データ管理',
    downloadTaskList: 'ダウンロードタスク一覧',
    clearTasksDescription: 'localStorage 内のダウンロードタスク記録をクリア',
    clearTasksButton: 'ダウンロードタスク一覧をクリア',
    dumpExported: 'ログを {path} にエクスポートしました',
  },
  splash: {
    preparing: '起動準備中...',
    almostReady: 'まもなく起動...',
  },
  analysis: {
    title: '解析結果',
    pageTitle: 'ログ解析',
    inputTitle: 'Minecraft ログを入力',
    pastePlaceholder: 'Minecraft ログの内容を貼り付け...',
    analyzeButton: 'ログを解析',
    analyzing: '解析中...',
    analyzeFailed: '解析に失敗しました',
    gameVersion: 'ゲームバージョン',
    modLoader: 'Modローダー',
    noIssues: '明らかな問題は見つかりませんでした',
    criticalCount: '{count} 深刻',
    errorCount: '{count} エラー',
    warningCount: '{count} 警告',
    suggestedSolutions: '推奨ソリューション',
    stackTrace: '例外スタックトレース',
    categoryMemory: 'メモリ',
    categoryModConflict: 'Mod 競合',
    categoryJavaRelated: 'Java 関連',
    categoryResource: 'リソース',
    categoryPerformance: 'パフォーマンス',
    categoryNetwork: 'ネットワーク',
  },
  errors: {
    pageRenderError: 'ページ描画エラー',
  },
  notifier: {
    downloadCompleted: '{name} のダウンロードが完了しました',
  },
} as const
