// 初回起動初期化ウィザード（ja-JP）
export default {
  title: 'Qomicex へようこそ',
  subtitle: '初回起動時に基本的な設定をいくつか行います',
  stepLabel: 'ステップ {current}/{total}',
  // ステップラベル
  stepMode: '設定方法',
  stepLanguage: '言語',
  stepTheme: 'テーマ',
  stepDirectories: 'ディレクトリ',
  stepDownloadSource: 'ダウンロードソース',
  stepJava: 'Java ランタイム',
  stepMemory: 'メモリ',
  stepDone: '完了',
  // モード選択
  modeTitle: '設定方法を選択',
  modeDesc: 'どちらのモードも言語、テーマ、Java、メモリの設定を含みます',
  quickTitle: 'クイック設定',
  quickDesc: '設定を自動でおすすめし、軽い確認だけで使い始められます',
  customTitle: 'カスタム設定',
  customDesc: '手順を追って設定。ダウンロードソース、データディレクトリ、ゲームディレクトリも設定できます',
  // 言語
  languageTitle: '表示言語を選択',
  languageDesc: '言語設定はすぐに反映されます。あとで設定からいつでも変更できます',
  // テーマ
  themeTitle: '外観テーマを選択',
  themeDesc: 'ダーク/ライトテーマは設定でいつでも切り替えられます',
  dark: 'ダーク',
  light: 'ライト',
  // ディレクトリ
  dirTitle: 'ディレクトリを選択',
  dirDesc: 'データディレクトリにはランチャー設定が、ゲームディレクトリには Minecraft ゲームファイルが格納されます',
  dataDir: 'データディレクトリ',
  dataDirDesc: 'ランチャー設定やキャッシュなどのデータの保存場所',
  gameDir: 'ゲームディレクトリ',
  gameDirDesc: 'Minecraft ゲームファイル（.minecraft）の場所',
  browse: '参照...',
  // ダウンロードソース
  downloadTitle: 'ダウンロードソースを選択',
  downloadDesc: '遅延が最も低いソースを推奨します。測定結果は参考用です',
  downloadSource: 'ゲームファイルのダウンロードソース',
  modSource: 'Mod ソース',
  autoSelect: '最適なものを自動選択',
  pinging: '測定中...',
  pingFailed: '測定に失敗しました',
  // Java
  javaTitle: 'Java ランタイムを設定',
  javaDesc: 'Java 8 / 17 / 21 の3つのランタイムが必要です。不足するバージョンはオンラインでダウンロードできます',
  javaScanning: 'Java ランタイムをディープスキャン中...',
  javaScanAgain: '再スキャン',
  javaFound: '見つかりました',
  javaMissing: '見つかりません',
  javaDownload: 'ダウンロード',
  javaDownloading: '{progress}% ダウンロード中',
  javaDownloaded: 'ダウンロード済み',
  javaDownloadFailed: 'ダウンロードに失敗しました',
  javaVersion8: 'Java 8',
  javaVersion17: 'Java 17',
  javaVersion21: 'Java 21',
  javaReady: '必要なすべてのバージョンが準備完了です',
  javaRequired: '必要なすべてのバージョンが準備できると続行できます',
  javaSkip: 'スキップ',
  javaSkipConfirmTitle: 'Java 設定をスキップ',
  javaSkipConfirm: 'Java 環境が不完全なため、一部のゲームバージョンが起動できない可能性があります。スキップしますか？',
  // メモリ
  memoryTitle: 'メモリを割り当て',
  memoryDesc: '自動割り当てを推奨します',
  memoryAuto: '自動割り当て（推奨）',
  memoryAutoDesc: 'システムの使用可能メモリに基づいて自動計算',
  memoryCustom: 'カスタム',
  memoryCustomDesc: '最大メモリを手動で指定',
  memoryMb: 'MB',
  // 完了
  doneTitle: '設定が完了しました',
  doneDesc: '初期化データを保存しました。Qomicex を使い始めましょう！',
  doneSummary: '今回完了した設定:',
  finish: '使い始める',
  saving: '保存中...',
  saveFailed: '保存に失敗しました。再試行してください',
  default: '既定',
} as const
